### ISSUE TITLE
Remote control down arrow should take you to video controls, not subtitle selection

### ISSUE THREAD

**Issue by micush** [jellyfin-archive/jellyfin-roku-legacy#1012]
Hi,

I find the client for Roku works okay for me. However, pressing the down arrow on the Roku remote control should bring up the player controls to be able to pause, fast forward, rewind, etc, and not a subtitle selection box. Please change this behavior. A little subtitle selection icon in the player controls to would be sufficient for subtitle selection.

Thanks for this great product. I prefer it to Plex with the exception of this single issue.

**Comment by jimdogx** [comment]
This is currently being worked on.

**Comment by micush** [comment]
Thanks much. I'll wait patiently. :)

**Comment by sevenrats** [comment]
for clarity, pressing down will not show the video controls in the upcoming feature set, it will show a set of buttons for stream info, cast info, program info, subtitles, and eventually audio tracks and favorite.
to show the video control bar, press right or left.  currently there is no intention to add play, pause, or seek buttons, as these are built into the remote.

**Comment by cewert** [comment]
>  currently there is no intention to add play, pause, or seek buttons, as these are built into the remote.

I think a play/pause button should be a part of the menu as well as being the default focus. It would solve some of the problems we ran into with #914 - you could have the okay button open the new menu and any further presses of okay would resume the video.

**Comment by tremby** [comment]
I really value having very quick access to switch and toggle subtitle tracks. I use it very frequently. It would be a shame if it were much harder/slower/more button presses to get to it.

**Comment by dathbe** [comment]
> I really value having very quick access to switch and toggle subtitle tracks. I use it very frequently. It would be a shame if it were much harder/slower/more button presses to get to it.

While I agree with this, I also miss being able to change the audio track while watching the movie.  As long as there is the option to go into the subtitles menu after pressing down, as most modern streaming services have, I'm ok with making the down button be a more complete controls menu and costing an extra button press when I want to change subtitles.

**Comment by 1hitsong** [comment]
Fixed by #1461

**Comment by tremby** [comment]
I don't understand -- that PR says it changes what happens when the user pauses the video. But this ticket was about what happens when the down arrow is pressed during playback.

**Comment by 1hitsong** [comment]
After the initial PR was submitted, the functionality expanded and it became a full OSD. It's not longer shown only on pause. It's shown by pressing up and down also. The subtitle selection and video playback info popups are now triggered from the OSD.
