### ISSUE TITLE
High Bitrate H264 Videos Transcode, Reason: The Video's Bitrate Not Supported

### ISSUE THREAD

**Issue by lakerssuperman** [jellyfin-archive/jellyfin-roku-legacy#1015]
I've discovered that some of my movies that are encoded in h264 and have a video bitrate that exceeds 10000kbps will result in transcoding.  The transcoding also knocks the 5.1 passthrough track down to AAC 2.0.  I can't say specifically which release these files last worked on, but they 100% used to direct play without issue. I'm doing a bit more investigating and will update with any further findings. 

![DTS](https://user-images.githubusercontent.com/18699905/216767589-57adcf33-c453-4bb5-bb50-eaa4f00a8860.png)

**Comment by jimdogx** [comment]
This will be addressed with #975

**Comment by lakerssuperman** [comment]
> This will be addressed with #975

Awesome!!! Thank you!
