### ISSUE TITLE
Show Trailers for Movies & TV Shows

### ISSUE THREAD

**Issue by Suzaru** [jellyfin-archive/jellyfin-roku-legacy#1021]
Hey there,

the Jellyfin App on other devices always has a beautiful "Trailer" button that opens up the youtube app and shows a trailer. I would love if this could come to Roku too. 

If I can help in anyway feel free to let me know. Thank you for your work, it's really appreciated <3

**Comment by 1hitsong** [comment]
We already showing trailers, but for local trailers only. See screenshot below.

I'm afraid Youtube's TOS prevents us from showing youtube content within the client. So legally we can't embed them. 

If we were to hotlink to the video and launch the youtube app on Roku, I don't believe we have any method to return users back into Jellyfin. So that's not really a usable solution either.

> If I can help in anyway feel free to let me know

If you know some way other than the 2 options above to make it work, we'd love to know!

![image](https://user-images.githubusercontent.com/3330318/217251422-2d2f4bf0-69b1-4d2d-b1b4-9ebe263f1d11.png)

**Comment by Suzaru** [comment]
Thank you for getting back to me! I massively appreciate the openess, rarely seen these days.
Sadly I do not have the ability to get local trailers. The Android version just gets you into the youtube app and it's only 2 clicks to get back. I know thats not perfect, but why not do that? User retention? It's better than having nothing in my mind. Sadly I am not tech savy enough to come up with another option I'm afraid :( Sorry!

**Comment by 1hitsong** [comment]
>  The Android version just gets you into the youtube app and it's only 2 clicks to get back.

The Android OS has specific code that allows for that, Roku doesn't.

**Comment by Suzaru** [comment]
> The Android OS has specific code that allows for that, Roku doesn't.

What exactly does hotlinking mean? Isn't it possible to open the youtube app with the fitting trailer when I hit "Play Trailer"? Even if the user just ends up in the youtube app, it's better than nothing in my mind.

**Comment by neilsb** [comment]
> Isn't it possible to open the youtube app with the fitting trailer when I hit "Play Trailer"? Even if the user just ends up in the youtube app, it's better than nothing in my mind.

Roku apps aren't allowed to send commands directly to other Roku Apps as per their certification criteria.  While it's technically possible to achieve, the app wouldn't pass the certification and not be approved for the store.  It may be possible to bounce the request off a server (i.e   The roku client could send a command to Jellyfin server, which would then send a command back to the Roku device to open the YouTube app and play a trailer) but that would be a lot of work, and require server changes for a single client.

**Comment by Suzaru** [comment]
Well then I thank you folks all for even entertaining the thought and I will have to live without it :) ! Still massively appreciate all the work you do, thank you!
