### ISSUE TITLE
Resume always continues ~5min after where movie is paused

### ISSUE THREAD

**Issue by brentl99** [jellyfin-archive/jellyfin-roku-legacy#1030]
**Software Versions**
Jellyfin Server Version:  10.8.0
Roku Client Version:  1.6.3 and prior

**Describe the bug**
When I stop watching a movie, or series, when I resume, the playback position is always approximately 5 minutes ahead of where I left off.   I see this was reported on reddit a few years ago: https://www.reddit.com/r/jellyfin/comments/iw1uvp/resume_on_roku_bug/
I have been running the Roku app for about 6 months and this has always been an issue.
If I am within the last 30 minutes of a movie and pause (quit the app) and then come back the app will have finished the movie.
If the same thing is done with a show series, it will start playing at the next episode.

**How To Reproduce**
1.  Start a show
2.  Play part way then Quit the app
3.  Or, play part way then pause and quit the app
4. Come back 12-24 hours later (not sure if 12-24hours is necessary, but that is how I use my Roku)
5. Resume the show
6. Note resumed position is ahead of where you left off

**Expected behavior**
I think it should resume at the prior pause location, or may be even a bit before?

**Logs**
I have not looked at any logs, but I can grab them if I knew what would be helpful.

**Screenshots**
I could take some photos of where I left off and where it is resuming, but I don't think that would help?

**Connection Information**
Server is on my LAN 

Is server connection http or https?   HTTP

**Additional context**
n/a

**Comment by sevenrats** [comment]
so, if you quit the app, we don't get to do anything, including tell the server that the playback state has changed to "stopped."  We have no control over this, Roku does not allow us to listen for the Home button or react to it in any way. The workaround, detecting the window closure that results from pressing the home button, reportedly does not work on modern Roku firmware.

The solution to this issue is to not close the app while the video is playing.  Press stop, and/or back out of the video before closing the app.

 https://developer.roku.com/docs/developer-program/getting-started/roku-dev-prog.md#DeveloperGuide-24Top-LevelMenu

**Comment by brentl99** [comment]
I do not use the home button.  It does not matter how I stop watching.  I can Pause, Stop, Back Button to the Jellyfin menu, or any combination of the above.  It doesn’t matter I see the same result.

**Comment by sevenrats** [comment]
in the absense of any better ideas, try updating to the latest stable version, 10.8.9

**Comment by cewert** [comment]
Definitely try updating your server.

v1.6.2 and later says in the release notes that 10.8.1 is the minimum required server version.

**Comment by brentl99** [comment]
Thank you for your feedback.    I have been taking pictures after I watch, and then when I restart, of Roku Jellyfin.  My plan was to post those images here.  Based on my testing I think there are two issues.  1)  The Roku Jellyfin app does not synchronize it's play stop with the server playback time.  This means the Roku app actually remembers the correct playback time, but it requests that resume point from the server but playback starts at a different point in the stream.  And 2)  The Roku Jellyfin app keeps playing the stream after you exit the app.  When you relaunch the app it requests a future playback time or sometimes will even have ended the movie, or skipped into the beginning of the next episode of a series.

Based on the comments here, I will look at upgrading my Jellyfin server before looking at this further.

Thank you for the feedback.
