### ISSUE TITLE
install: zip not found

### ISSUE THREAD

**Issue by 4jesse** [jellyfin-archive/jellyfin-roku-legacy#109]
**Describe the bug**
The make install script fails to complete properly.

**To Reproduce**
When running through the instructions I make it fine to the last step: make install and get down to the  >> creating application zip /home/.../apps/Jellyfin_Roku.zip and then 
/bin/sh: 4: zip: not found
/bin/sh: 5: zip: not found
...
there is no Jellyfin_Roku.zip file in the apps folder

**Expected behavior**
I expected the script to create and then upload the Jellyfin_Roku.zip file.

**Comment by bisby** [comment]
You dont have zip installed on your system. That is what "zip not found" means.

**Comment by 4jesse** [comment]
Thank you.
