### ISSUE TITLE
Button Color Defaults Clash with Background

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#11]
The button background color matches the background, so it is hard to differentiate the labels with buttons. Button background colors should be different from the main background. This issue might take care of itself after fixing #6 but a better default wouldn't hurt.

![image](https://user-images.githubusercontent.com/6452882/56857258-47ca3f80-6939-11e9-90b5-b9df2d7970bf.png)

**Comment by neilsb** [comment]
All button in the client now using a different background colour to the screen colour.
