### ISSUE TITLE
Music player loop button doesn't work

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#1107]
## Software Versions

- Jellyfin Server Version:  demo server
- Roku Client Version:  latest unstable

## Describe the bug
The loop button doesn't appear when playing individual songs, which I'm assuming is by design but is a bummer. The button appears when playing an album or "instant mix" but doesn't do anything. Checking the loop button makes the loop icon appear above the playbar but when the end of the song is reached, nothing gets looped and the loop icon disappears. See video below.

## How To Reproduce

1. load lates version of unstable
2. go to demo server
3. play an album or "instant mix"
4. select the loop button
5. observe

## Expected behavior
I would expect the button to loop an individual song or loop the whole playlist depending on what is being played althought that may not be the expected behavior

## Screenshots
https://user-images.githubusercontent.com/16514652/226203954-ac1e1e1d-55fd-449d-8591-fab23e552f6a.mp4

## Connection Information

- Is server local or remote? remote
- Is server connection HTTP or HTTPS? HTTPS

**Comment by 1hitsong** [comment]
I can't recreate this issue. I clicked loop and after the album ended, it restarted from track 1.

I clicked loop again to enable single track looping and it restarted the current track once it completed and once I turned it off, advanced to the next song.

**Comment by 1hitsong** [comment]
Based on your video, it looks like you were expecting a single song loop. Click the loop button again to change the loop mode to single track.

**Comment by cewert** [comment]
> I can't recreate this issue. I clicked loop and after the album ended, it restarted from track 1.

I was playing an "instant mix" and the playlist did not loop after the last track ended.

> Based on your video, it looks like you were expecting a single song loop. Click the loop button again to change the loop mode to single track.

Yes, I did expect the track to loop but only because the loop icon disappeared after the track finished playing. Is that the intended behavior? Shouldn't the loop button stay visible till the playlist finishes and loops?

If the loop button works for single tracks, why are we not showing the loop button when playing individual songs?

**Comment by 1hitsong** [comment]
I played an instant mix set to loop and after the last song it went back to track 1.

I played an instant mix set to single track loop and after the song it went back and played it again.

The expected behavior is the loop setting would stay engaged. I'm not sure why it turned off for you.

**Comment by 1hitsong** [comment]
>If the loop button works for single tracks, why are we not showing the loop button when playing individual songs?

It simply wasn't programmed to do that, but that sounds like a good feature.

**Comment by cewert** [comment]
So, after some more testing, the loop button appears to work as expected but ONLY if you toggle it on the last track of an album/playlist. If you toggle loop on any other track, the loop icon gets hidden and loop gets turned back off when the next track loads - like in my video.
