### ISSUE TITLE
Crashes After Intro

### ISSUE THREAD

**Issue by HopperMCS** [jellyfin-archive/jellyfin-roku-legacy#1128]
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version:  unstable

## Describe the bug

After intro plays, the main video starts. 5-10 seconds in and the client freezes, and the TV turns off and boot cycles. 

## How To Reproduce
1. Play media
2. Go past intro
3. Wait for crash

## Logs

Full debug output is here:
https://gist.github.com/HopperMCS/efb0a990ed28fa5e8f76c69898d499e8

## AV Info 
Video: 480p H264 SDR
Audio: Stereo, English, AAC, default

## Connection Information
Local over WLAN, port 8096 (http)

## Additional context
I plan to start working contributing, so I downloaded the unstable branch from GitHub to dogfood.

**Comment by HopperMCS** [comment]
Here's a video to show exactly what's going on

**Comment by HopperMCS** [comment]
It's been discovered that disabling Cinema Mode stops the crashes from happening

**Comment by HopperMCS** [comment]
It was requested that I post the settings of the Intros plugin to this thread, attached is a screenshot of it
![Screenshot_20230323_220200_Jellyfin](https://user-images.githubusercontent.com/13326489/227405430-9d6facc4-61e1-4e8a-8012-8178a21b0e10.jpg)

**Comment by HopperMCS** [comment]
![20230324_180924](https://user-images.githubusercontent.com/13326489/227652737-b48da236-7388-460c-8bc8-d0c86c0c81a3.jpg)

**Comment by HopperMCS** [comment]
Last known working commit:
id: a809f8aa319e7563083da57ed1a8ce8b905f31b9
message: Translated using Weblate (German)

Commit that broke Intros:
id: 45dc9e5fa0428ab8cb5dd8e76994440653cfe196
message: Merge branch 'unstable' into unstable

**Comment by 1hitsong** [comment]
The root cause has been a weird one to find. 

It seems like you have to catch the `fs.find()` in the file `components\captionTask.brs` before it completes or at least in an unexpected state.

The only way I've been able to cause the reboot is to hit play on an episode, then within the first second of the video, hit back, then play another episode.
