### ISSUE TITLE
Artwork Generated Home Screen Background Wallpaper Breaks With Server 10.8.9

### ISSUE THREAD

**Issue by lakerssuperman** [jellyfin-archive/jellyfin-roku-legacy#1130]
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version:  1.6.3

## Describe the bug
The user generated artwork background for the homescreen no longer works with server 10.8.9.  The old grey background is displayed.  I rolled back to server 10.8.8 and the artwork wallpaper returned.

## How To Reproduce

1. Use server 10.8.9 with the latest Roku client.
2. Background is grey
3. Roll back to 10.8.8
4. Artwork returns

## Expected behavior
Artwork generated wallpaper should be displayed when enabled.

## Connection Information

I was connected locally to test the different versions.

## Additional context
None at this time.

**Comment by 1hitsong** [comment]
@lakerssuperman 10.8.9 added this change: https://github.com/jellyfin/jellyfin/pull/9060 where the splash image is disabled by default and you need to enable it.

Try enabling it and see if it works again.

**Comment by lakerssuperman** [comment]
> @lakerssuperman 10.8.9 added this change: [jellyfin/jellyfin#9060](https://github.com/jellyfin/jellyfin/pull/9060) where the splash image is disabled by default and you need to enable it.
> 
> Try enabling it and see if it works again.

This fixes it!!
