### ISSUE TITLE
Expand "Quick Play"

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#1139]
## Is your feature request related to a problem? Please describe
- There are a lot of views that don't support hitting the play button such as TV library view, TV show detail view etc
- Quick Play could be quicker!

## Describe the solution you'd like
Make assumptions about what the user wants to do when using the play button while allowing the okay button to present more options to the user.

- When hovering a video file that is "resume-able":
  - Assume the user wants to resume it
- When hovering a Season of a TV Show :
  - Assume the user wants to watch the first un-watched episode
  - When all episodes are watched:
    - Assume the user wants to watch the whole season so start at the first episode
- When hovering a TV Show:
  - Assume the user wants to watch the first un-watched episode
  - When all episodes are watched:
    - Assume the user wants to shuffle all episodes
- When hovering an album:
  - Assume the user wants to start at the first track
- When hovering a music artist:
  - Assume the user wants to shuffle all songs by artist

## Describe alternatives you've considered
Keeping it the way it is now but that seems redundant to have two buttons on the remote have the same function. We could also have some sort of user setting for this but that seems like a slippery slope and I'm not sure how that would work exactly. I think sensible assumptions will work for most people

## Additional context

Neil had some good ideas about Quick Play in the original PR that introduced the feature https://github.com/jellyfin/jellyfin-roku/pull/332#issuecomment-743743230

**Comment by 1hitsong** [comment]
>  We could also have some sort of user setting for this but that seems like a slippery slope and I'm not sure how that would work exactly.

I'll brainstorm on this. 

Idea 1: We could have a setting for "Play button takes action" where if it's disabled, everything is as it is today, but if enabled, the play button performs whatever assumption action we come up with. OK button would remain unchanged.

Idea 2: We could create an settings menu where users can choose an alt action for the play button. This piggyback's off the idea of remapping keys a bit. Users could go to the setting and see a list of options for actions the play button could perform in the scenario, and choose one. For this idea we only assume the list of action options, but the user is in charge of selecting which one they want.

**Comment by cewert** [comment]
> Idea 1: We could have a setting for "Play button takes action" where if it's disabled, everything is as it is today, but if enabled, the play button performs whatever assumption action we come up with. OK button would remain unchanged.

~~I strongly dislike idea 1.~~ I believe the home screen and TV library view are the only views right now where the play button and okay button do something different. Meaning idea 1 is to have two buttons on the remote be redundant 95% of the time. If the buttons were right next to each other and were accidentally pushed then I think that would help the argument but they are not. There are 2 "rows" of buttons between them on the remote (at least on my 4k streaming stick remote there are). So it's a very safe assumption IMO that when a user hits play instead of okay that they actually want to play something or else why would they have hit the play button in the first place? The okay button is the main button for selecting things on the screen and navigation. Not just for our app but across all Roku apps.

Edit: I missed the fact you said this was behind a user setting the first time I read it, sorry. I would be fine with option 1 if Quick Play was enabled by default for reasons stated above about user intent.

> Idea 2: We could create an settings menu where users can choose an alt action for the play button. This piggyback's off the idea of remapping keys a bit. Users could go to the setting and see a list of options for actions the play button could perform in the scenario, and choose one. For this idea we only assume the list of action options, but the user is in charge of selecting which one they want.

This is more reasonable but has major issues IMO. As stated above, I strongly believe that the user hitting play instead of okay shows us their intent to play whatever they are hovering. And there's only so many "actions" that would make sense depending on what you are hovering. So if I'm hovering a resume-able video, there's only two possible choices for the play button, resume or start over. OK, easy. Now you have a setting for "resuming videos", but there's also music albums, music artists, TV shows, TV seasons, playlists, collections, TV channels, picture libraries etc. So now we need at least 9 user settings (and counting) so the user can customize the action based on what they are hovering. And that's assuming you do it by content being hovered and that's it. You could also have the user setting be aware of what view the user is on... so if I hover a video on the homescreen and hit play always resume but if I hover a video anywhere else then start over etc. etc. Where do you draw the line? That's what I meant by slippery slope. If you allow the user to customize his button presses how do you know when to stop?

**Comment by cewert** [comment]
When I first made Quick Play, it was a long time ago and we were always using the first video and audio track available with no way for the user to change them. I'm not sure if this would be necessary or maybe this would be part of Quick Play 2.0 but we may need to add logic so that video's are Quick Played with the user's default language, default subtitles etc. instead of just using the first one we find like how it used to be.

**Comment by 1hitsong** [comment]
Honestly I'm very much against idea 2. I start thinking of the maintenance and testing matrix needed to keep it working and begin to cry. I just put it out there so we at least considered it.

Option 1 feels like an acceptable solution, but I wonder if it's simply a solution looking for a problem. Perhaps we simply launch with the assumptions, and if people raise a stink about it, then we add the setting.

After all, I see nothing in your assumption list that is a show stopper. Really the only things I see to debate and discuss would be what the final assumption list would be.  Stuff like playing the first unplayed in the selected set VS starting from the first item in the selected set vs shuffling the items in the set. That sort of thing. I think we can make a table with each of the item types and screens we want to support and knock that out pretty quickly.

>  Quick Play 2.0 but we may need to add logic so that video's are Quick Played with the user's default language, default subtitles etc. instead of just using the first one we find like how it used to be.

I wonder if won't be such an issue once the video buttons are live. Then a user can swap between all the alternative options during playback without having to go back.

**Comment by cewert** [comment]
> Honestly I'm very much against idea 2. I start thinking of the maintenance and testing matrix needed to keep it working and begin to cry. I just put it out there so we at least considered it.

Agree. Testing things on the roku is the worst 😆 

> Option 1 feels like an acceptable solution, but I wonder if it's simply a solution looking for a problem. Perhaps we simply launch with the assumptions, and if people raise a stink about it, then we add the setting.

Totally agree. The way the feature is implemented right now isn't even consistent and makes the play button do nothing most of the time. Why would someone make a stink about removing a feature from a button so the button can do nothing again? The biggest one would be resume-able videos (because that has been displayed for the play button since it was introduced) but the same functionality can be achieved with the okay button and no extra clicks.

> Really the only things I see to debate and discuss would be what the final assumption list would be. Stuff like playing the first unplayed in the selected set VS starting from the first item in the selected set vs shuffling the items in the set.

I agree they should be debated to ensure we are choosing the option that satisfies the most users. Another point about these debated features is that they would be *new* features and not be replacing anything. Meaning we can't please 100% of users with whatever assumption we make but at least they won't be "losing" anything since the play button went from doing nothing to something they aren't a fan of.

> I wonder if won't be such an issue once the video buttons are live. Then a user can swap between all the alternative options during playback without having to go back.

Good point. I don't think we would need to add this functionality right now but I think it should be on the roadmap for Quick Play down the road. If I have to pause the movie, hit a few buttons, select things in a dropdown, then start the movie it's not very "quick" anymore and kind of removes the joy that comes from hitting the play button and your media starts playing. I might as well navigate to the movie detail screen at that point so I know I'm good before I start the movie.

It also gets kind of complicated too because do you take the defaults from roku settings or jellyfin-web settings? Probably be better to push the feature, deal with bugs and potential user complaints, and possibly make a couple settings if needed. Would make things easier to test and only introduce one new feature at a time.
