### ISSUE TITLE
HEVC won't direct play

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#1145]
Jellyfin server is at 10.8.9.
Jellyfin-roku is at 1.6 build 3, on a Roku Ultra 4800RW, at software version 11.5.0.

I'm unable to play HEVC files. I'm not sure if it's all or a subset. I checked the Jellyfin server logs just now.

For one file it's saying `TranscodeReason=AudioChannelsNotSupported`. That sounds understandable enough, and the file claims to have only a Dolby Digital+ 7.1 soundtrack. But I was under the impression this should still direct play, and the Roku hardware or my soundbar would handle any necessary audio transformation.

For another file it's saying `TranscodeReason=VideoRangeTypeNotSupported`. This file claims to be HDR, so maybe that's why? But the [codec support page](https://jellyfin.org/docs/general/clients/codec-support/#wikipedias-video-codec-tables) suggests that Roku supports h.265 10-bit. Maybe I'm confused but I assumed that's what HEVC HDR refers to.

I looked through the Jellyfin-roku settings, and "attempt direct play for HEVC media with unsupported profile levels before falling back to transcoding" is enabled.

**Comment by tremby** [comment]
Today I had a "VideoBitrateNotSupported" on an H264 video. FFmpeg reports this one as "h264 (High), yuv420p(tv, bt709, progressive)" and 10852 kb/s.

Is the hardware I have really this limited? Or is this a software issue, like capabilities not properly being advertised?

**Comment by dathbe** [comment]
10-bit encoding is not the same as HDR.  You can have a 10-bit encoded SDR video.  If your tv is not capable of HDR, it's possible the video needs to be transcoded...or that Jellyfin-Roku believes it must be transcoded.  I have an HDR tv, so I cannot check that.  But I can report that Jellyfin-Roku plays 8-bit, 10-bit, AVC, HEVC, SDR, and HDR videos for the most part without transcoding and without issue.  I suspect it is a problem with your setup.  I think you need to have a fairly beefy setup to stream 11mbps across your network.

**Comment by cewert** [comment]
> For one file it's saying TranscodeReason=AudioChannelsNotSupported. That sounds understandable enough, and the file claims to have only a Dolby Digital+ 7.1 soundtrack. But I was under the impression this should still direct play, and the Roku hardware or my soundbar would handle any necessary audio transformation.

I don't think our app has ever supported 8 channel audio files which would explain the `TranscodeReason=AudioChannelsNotSupported`. If you look at [some of the code ](https://github.com/jellyfin/jellyfin-roku/blob/unstable/source/utils/deviceCapabilities.brs#L36)responsible for building the device profile, it only checks if the device supports 6 channel audio and calls it a day. Then the `maxAudioChannels` var is used when building the device profile.

1. I'm working on a PR (#1299) that adds support for 8 channel audio. If you have time, please test the first file you mentioned to see if that PR solves your issue and report back.
2. As for your second file which says `TranscodeReason=VideoRangeTypeNotSupported`, `VideoRange` could be HDR, HDR 10, dolby vision, or HLG( see [here ](https://github.com/jellyfin/jellyfin-roku/blob/unstable/source/utils/deviceCapabilities.brs#L76)and [here](https://developer.roku.com/en-ca/docs/references/brightscript/interfaces/ifdeviceinfo.md#getdisplayproperties-as-object)). So yea, from my understanding that means your file had some sort of HDR but your TV didn't support it. 10 bit != HDR like the other guy mentioned.
4. To clarify, the "attempt direct play for HEVC media with unsupported profile levels before falling back to transcoding" user setting is referring to the `Level` row shown [here](https://developer.roku.com/en-ca/docs/specs/media/streaming-specifications.md#supported-video-codecs) i.e. `4.1`, `5.0`, and `5.1`
5. Does that answer all your questions from this issue? I'd love to close this if it does 😄

**Comment by tremby** [comment]
Thanks for the response.

1. Unfortunately I don't actually remember which file that was.
2. Sounds like a reasonable failure in this case then.
3. Understood.
4. Yes I think so. It sounds like my issues were nothing to do with it being HEVC exactly, and that if the 8-channel audio was stopping it from direct playing where it really should have, that's being fixed in the upcoming patch.
