### ISSUE TITLE
Roku channel listing needs updated

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#1169]
## Describe the bug
The listing for our app on the roku channel store needs updated:
- The description states our app needs a `v10.8+` Jellyfin server but our app requires `v10.8.1+`
- There is an incorrect warning message that states `CABLE OR SATELLITE SUBSCRIPTION REQUIRED`

## How To Reproduce

1. Go to https://channelstore.roku.com/details/cc5e559d08d9ec87c5f30dcebdeebc12/jellyfin
2. observe

**Comment by 1hitsong** [comment]
Your second point about the warning message "CABLE OR SATELLITE SUBSCRIPTION REQUIRED," I remember Anthony saying something about this. I believe he said Roku auto adds it for some reason based on our configuration.

We'll want to get his input on that one.

**Comment by cewert** [comment]
Interesting. I'm assuming there's a way to remove it - neither [emby](https://channelstore.roku.com/details/904d20cb3bd4aa340a35aa9c83c9a128/emby) nor [plex](https://channelstore.roku.com/en-ca/details/68e8d568fdd68a1197a2b9a5f69e16c0/plex-free-movies-and-tv) have that warning listed

**Comment by cewert** [comment]
I was able to fix both of these issues but they won't show up until our next release

**Comment by cewert** [comment]
> The description states our app needs a v10.8+ Jellyfin server but our app requires v10.8.1+

This was fixed in the latest release - v1.6.5. The other issue about the cable subscription warning can't be fixed at this time due to how our app is currently built.
