### ISSUE TITLE
Audio shuffle mode no longer works

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1172]
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version:  1.6.4

## Describe the bug
Shuffle songs during audio playback no longer works.

## How To Reproduce

1. Play an music album
2. Click the shuffle button to enable shuffle mode
3. Once the song ends, it will continue to the next track and shuffle will turn off by itself

## Expected behavior
Shuffle mode should remain on, and playback of songs should be shuffled.

## Additional context
I fixed a similar issue with the loop functionality. It's likely I hit a piece of code when fixing that issue and inadvertently caused this issue.

**Comment by JellyUserIn208** [comment]
I'm having this issue and i just installed and updated Jellyfin

**Comment by 1hitsong** [comment]
@JellyUserIn208 Please open a new bug ticket with details.
