### ISSUE TITLE
When choosing to play a song from an album, start playing the whole album from that point

### ISSUE THREAD

**Issue by kenneth-leblanc** [jellyfin-archive/jellyfin-roku-legacy#1216]
## Is your feature request related to a problem? Please describe
Whenever I go to listen to an album, I'm either forced to play the whole album from the start, play an instant mix, or choose a single song from the album. This prevents me from easily starting an album midway through and then listening to the rest of the album. This is frustrating for large albums that I would like to start in the middle on a certain song.

## Describe the solution you'd like
When going choose a song from an album, it shouldn't just play that song, it should start playing the whole album starting from the selected song and proceeding through the rest of the album. This would match the Jellyfin web interface, and I think most other music devices and interfaces.

**Comment by michaelcresswell** [comment]
Ideally it would queue the entire album and start playback at the selected track so I could start in the middle of an album and skip forward or back through all songs, as desired

**Comment by kenneth-leblanc** [comment]
Yes, that is perfect sounding.
