### ISSUE TITLE
Preparing for Store Release

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#122]
This issue is to track what is needed for a store release with Roku. This is separate from what features/functionality we will include in the first release.

Jellyfin now has a Roku Streaming Stick+ (Amarillo-2019 3810X) so we can test and package as needed, and a developer account has been created with Roku.

According to their documentation, there are [Certification Tests](https://developer.roku.com/docs/developer-program/certification/certification-testing.md) we must pass. From the certification tests, I'm only including the items that we need to review. Anything that is currently optional or does not apply has been omitted.

The article also contains the steps needed to execute each test.

---

**[Performance](https://developer.roku.com/docs/developer-program/certification/certification-testing.md#3-performance)** (Section 3)
_(Timing valid on RSS+ Amarillo-2019 3810X)_

- [x] The channel must launch and be response to user navigation, find, and playback of content at a reasonable speed _(§3.1)_
- [x] Launches to a **fully rendered** home screen within 20 seconds. _(§3.2)_
- [x] Screen-to-screen (scene-to-scene) transitions are within 5 seconds. _(§3.3)_
- [x] Responses to user requests that take longer than 3 seconds require the appropriate "in progress" notification. Responses cannot take longer than 10 seconds to complete. _(§3.4)_
- [x] The channel's response to a remote button press and tile-to-tile navigation is within 250 milliseconds. _(§3.5)_
- [x] Content starts playing within 10 seconds of initiation. _(§3.6)_

**[Channel operation](https://developer.roku.com/docs/developer-program/certification/certification-testing.md#4-channel-operation)** (Section 4)

- [x] Video and audio are in sync. Video is clear of visible defects... and audio is free of audible defects... _(§4.4)_
- [x] The video node must be in focus during full screen video playback when there are no active UI components over the video. _(§4.5)_
- [x] The channel may not prevent Roku's system screensaver from activating over UI. (_§4.6)_
- [x] The back button directly returns the user to the previous screen and/or state. On the channel's home page, the back button exits the channel and returns the user to the Roku home screen. _(§4.7)_
  - Issue created: https://github.com/jellyfin/jellyfin-roku/issues/136
- [x] VOD content longer that 15 minutes must include video bookmark functionality that allows the user to resume playback from the last-viewed location. _(§4.11)_

**[Deep linking](https://developer.roku.com/docs/developer-program/certification/certification-testing.md#5-deep-linking)** (Section 5)
- [ ] Channels support deep linking for all media types (including "series"), per [Roku's deep linking policy.](https://developer.roku.com/docs/developer-program/discovery/implementing-deep-linking.md) _(§5.1)_
- [ ] When the channel is already running, direct playback commands will [deep link](https://developer.roku.com/docs/developer-program/discovery/implementing-deep-linking.md) to content in the channel without requiring a channel launch delay by using [roInputEvent](https://developer.roku.com/docs/references/brightscript/events/roinputevent.md). To support this, channels must process roInputEvent the same way deep link parameters are passed through the main entry point on launch. _(§5.2)_
- [x] The channel does not deep link into other channels, or direct users to exit the channel to purchase content, goods or other services. _(§5.3)_

**[UI and graphics](https://developer.roku.com/docs/developer-program/certification/certification-testing.md#6-ui-and-graphics)** (Section 6)

- [x] All submitted channels must have a non-zero version number. This number must be incremented for each build submitted and updated in the [channel manifest](https://developer.roku.com/docs/developer-program/getting-started/architecture/channel-manifest.md). _(§6.1)_
  - Issue opened: #137
- [x] All Channel graphics are broadcast-safe, and RGB values do not exceed 235/235/235. Artwork must not be visually stretched, skewed or truncated. _(§6.5)_
- [x] File size of the channel is no larger than 4MB. _(§6.6)_

**Comment by cewert** [comment]
These tests will be run using the media available on the [demo server](https://demo.jellyfin.org/stable), correct?

I was able to login as the demo user on my roku and it ran really well. As is, I think we'd pass almost all of the performance and channel op. sections.

**Comment by anthonylavado** [comment]
@cewert Yes, the demo server is the preferred resource for this. We have specifically "groomed" all media for it to direct play whenever possible, on as many devices as possible.

For reference:
| Server Address                   | User Account | Password |
|----------------------------------|--------------|----------|
| https://demo.jellyfin.org/stable | demo         |          |

**Comment by anthonylavado** [comment]
Still reviewing these as I can. Making issues for items that need to be fixed, and making PRs where I can.

**Comment by cewert** [comment]
It looks like we'll have to add a line of code `myScene.signalBeacon(“AppLaunchComplete”)` to pass §3.2 - https://developer.roku.com/docs/references/brightscript/interfaces/ifsgnodefield.md#signalbeaconbeacon-as-string-as-integer

**Comment by anthonylavado** [comment]
Here's the results from Roku's static analysis:

Errors
---
- Your channel appears to be using ECP or roAppManager commands. Please ensure that this is not being done to launch other channels or suppress system screen savers. Path: [/components/TrackerTask.xml. Line: 1800](https://github.com/jellyfin/jellyfin-roku/blob/ddae9b5862b6c90df2615568cc2fd729af1ffd7a/components/TrackerTask.xml#L1800). [Cert Requirements: 2.8, 4.6, 5.3].

- Channels are now required to support roInput events. Please opt in to this support with the supports_input_launch=1 [manifest entry](https://github.com/jellyfin/jellyfin-roku/blob/master/manifest) and properly handle roInput events in your channel. [Cert Requirements: 5.2].

- Your channel must fire "AppLaunchComplete" beacon to pass certification. [Cert Requirements: 3.2].

Warnings
---

- "BookmarkPosition" content metadata attribute is deprecated. Use "PlayStart" instead. Path: [/source/utils/TranscodeSubtitles.brs. Line: 162](https://github.com/jellyfin/jellyfin-roku/blob/ddae9b5862b6c90df2615568cc2fd729af1ffd7a/source/utils/TranscodeSubtitles.brs#L162).

- "BookmarkPosition" content metadata attribute is deprecated. Use "PlayStart" instead. Path: [/source/utils/TranscodeSubtitles.brs. Line: 46](https://github.com/jellyfin/jellyfin-roku/blob/ddae9b5862b6c90df2615568cc2fd729af1ffd7a/source/utils/TranscodeSubtitles.brs#L46).

- "BookmarkPosition" content metadata attribute is deprecated. Use "PlayStart" instead. Path: [/source/VideoPlayer.brs. Line: 40](https://github.com/jellyfin/jellyfin-roku/blob/ddae9b5862b6c90df2615568cc2fd729af1ffd7a/source/VideoPlayer.brs#L40).

- "/images/channel-poster_sd.png" image used for "mm_icon_focus_sd" attribute has invalid resolution: "187x140". Valid resolution is "246x140". Path: /manifest. Line: 10. [Cert Requirements: 6.4].

- "/images/channel-poster_hd.png" image used for "mm_icon_focus_hd" attribute has invalid resolution: "280x210". Valid resolution is "336x210". Path: /manifest. Line: 9. [Cert Requirements: 6.4].

**Comment by neilsb** [comment]
So on the 1st error, regarding roAppManager commands.  The TrackerTask.xml file appears to be related to the RALE tool (Layout Editor) and I don't believe this TrackerTask.xml component should be included in the released builds.  I think it is only intended for local development and debugging.

The project certainly doesn't appear to be referencing the component  other than when it is added in the ConfigScene.brs and Home.brs init() functions.   No further references are made to it.

It looks like the BrightScript language plugin for VSCode can [automatically add this](https://github.com/rokucommunity/vscode-brightscript-language#rale-support) based on a config setting, so unless anyone has any other thoughts I would suggest we just remove the TrackerTask.xml file and references from the project?

**Comment by anthonylavado** [comment]
@neilsb I know that @cewert and I use the VSCode extension, but I’m not sure about anyone else’s workflows (like @bisby or @thomabx).

For this upload and test, I used the output of `make install`.

While we’re at it, I should probably split out what that command does as documentation, so we don’t have a dependency on `make` for manually building.

**Comment by anthonylavado** [comment]
I should note, as of the last beta update, the Static Analysis passed with no issues.

**Comment by anthonylavado** [comment]
@jellyfin/roku So I've checked off all the listed operations in sections 3 and 4 even with the current release from just over two weeks ago. Let me know when you want me to try an actual release.

**Comment by dkanada** [comment]
Right now sounds like an excellent time! 😆

**Comment by jcdick1** [comment]
> 
> 
> @jellyfin/roku So I've checked off all the listed operations in sections 3 and 4 even with the current release from just over two weeks ago. Let me know when you want me to try an actual release.

My opinion, as a server admin running Jellyfin alongside a "legacy" Plex instance just itching to get a public Roku client so I can finally shut it down, I'd prefer you wait for the DirectPlay support in #223 .  Push that build up and let it bake for a week or two in the private channel, so the initial public client supports all the various Roku models' hardware capabilities for DirectPlay right out of the gate.
