### ISSUE TITLE
Add support for music libraries

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#124]
Combining issues #22 #23 #24 #25 into one

**Comment by nikolowry** [comment]
Sorry for being "that guy", but is there any sort of ETA for this feature or is there a feature roadmap that outines when Music library support will be implemented?

I'm listening to more music than ever due to being forced to work from home, so I'm just antsy to not be dependent on Miracast for listening to my library via the TV (it's the best audio playback in my home).

Regardless, thanks for all the hardwork! It's impressive to see how far the client has come over this past year!

**Comment by anthonylavado** [comment]
No ETA, but I can give you a sort of progress report. Part of the work for this is in #223, where @neilsb has implemented the start of a playback profile. After the Movies and Live TV stuff, I think Collections and Music come next.

**Comment by nikolowry** [comment]
Thanks @anthonylavado -- appreciate the quick response!

**Comment by Protektor-Desura** [comment]
I'm looking forward to Live TV guide and music as well in the Roku client.

**Comment by ghost** [comment]
Thanks! Didn't see this

**Comment by nikolowry** [comment]
Is there anything end-users could do to help persuade maintainers this should be prioritized?

Regardless, I appreciate all the work!

**Comment by Protektor-Desura** [comment]
I'm looking forward to having collections and music supported.

**Comment by hardyoyo** [comment]
Still seeing an error on my Roku, says MusicAlbum is not supported.

**Comment by cewert** [comment]
@hardyoyo this PR was merged into master but there hasn't been a new release yet. You can side-load the app to get music support until a release is made.

**Comment by hardyoyo** [comment]
Is there a write-up on how to sideload the app on a Roku? EDIT: oh, there's this: https://www.howtogeek.com/290787/how-to-enable-developer-mode-and-sideload-roku-apps/

**Comment by TwitchBronBron** [comment]
We have instructions in our devguide too. The easiest way is to use the vscode instructions here: https://github.com/jellyfin/jellyfin-roku/blob/master/DEVGUIDE.md#method-1-visual-studio-code

**Comment by HuwSy** [comment]
When will the released package be updated for this?

**Comment by neilsb** [comment]
This should be in the 1.5 release of the client which is available in the store.

**Comment by HuwSy** [comment]
My mistake. It is here just Roku didn’t bother updating the apps automatically.
