### ISSUE TITLE
Community ratings don't show on movie detail pages.

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1241]
## Software Versions

- Jellyfin Server Version:  Latest
- Roku Client Version:  Latest

## Describe the bug
Community ratings don't show on movie detail pages.

## How To Reproduce

1. Go to the movie library
2. Click on a movie
3. The star "community rating" never shows
4. If you highlight the same movie in the library with Presentation view, you'll see we have the data for it.

## Expected behavior
Star rating shows

## Screenshots
Library View - showing 7.2 star rating
![image](https://user-images.githubusercontent.com/3330318/235303239-7ffa5b8b-6e50-4acb-af6a-cf190530cb8f.png)

Movie Detail view - missing star rating
![image](https://user-images.githubusercontent.com/3330318/235303255-58cb4b55-6b08-4489-8abe-1cbcf9e937c2.png)

**Comment by cewert** [comment]
Bug introduced in #844
