### ISSUE TITLE
Required firmware for app is incorrect

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#1263]
## Is your feature request related to a problem? Please describe
Currently, our app on the roku channel store says that we require a minimum firmware version of `v9.20 b1` but that is inaccurate.

## Describe the solution you'd like
Determine the minimum required firmware for our app and update for next release. I know it needs to be at least at v10.0 but I'm not sure the exact version we need.

## Additional context

Things we're using that require a higher firmware than `v9.20 b1`:
- StandardDialog node - v10.0
- StandardMessageDialog node - v10.0
- Tagging of [unused variables](https://github.com/jellyfin/jellyfin-roku/blob/unstable/components/JFScreen.brs#L6) - v11.0
- Try catch statements - v9.4

**Comment by cewert** [comment]
According to the docs [here](https://developer.roku.com/en-gb/docs/specs/hardware.md#legacy-models) the legacy models `Latest Roku OS version` go from `3.1` to `9.1` to `11` to `11.5`. The lowest version we can publish our app for is `9.2`. So if we can't or don't want to go down to `9.2` then the next logical choice would be `11`.

**Comment by sevenrats** [comment]
do we have any idea what our user base looks like?  the easiest thing to do would just be to say 11 is the minimum because I can say for a fact all our stuff works on it.  who knows what 9.2 is.

**Comment by cewert** [comment]
Minimum firmware required was updated in the v2.0.0 release. It is now set to `v11 b1`
