### ISSUE TITLE
Use of uninitialized variable in main.brs

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1274]
source\Main.brs

Around line 572, look for `if video.errorMsg = ""`

This line throws an error as video is uninitialized at this point in the code

I accessed this code by searching and playing a tv series special. When it completed, the error was thrown.

**Comment by cewert** [comment]
Introduced by #997. Looks like we just need to revert the [change from that PR](https://github.com/jellyfin/jellyfin-roku/pull/997/files#diff-20d93f2448cbd74f4e508446707eb15e3d299ab2765be87dc5a8873cc11b6fcb).
