### ISSUE TITLE
Crashing about 1/2 of the way through episode

### ISSUE THREAD

**Issue by naleo** [jellyfin-archive/jellyfin-roku-legacy#1285]
I am getting "An error was encountered while playing this item" about 1/2 of the way through an episode, and I am not exactly sure why.  Here is the server log and Transcoding log.

[System_Logs_Log_name=FFmpeg.DirectStream-2023-05-28_04-33-55_2cd3e84f63e0516ba655e52ec2391219_7b2ea0ae.log.txt](https://github.com/jellyfin/jellyfin-roku/files/11583848/System_Logs_Log_name.FFmpeg.DirectStream-2023-05-28_04-33-55_2cd3e84f63e0516ba655e52ec2391219_7b2ea0ae.log.txt)
[System_Logs_Log_name=log_20230528.log.txt](https://github.com/jellyfin/jellyfin-roku/files/11583849/System_Logs_Log_name.log_20230528.log.txt)

**Comment by cewert** [comment]
> Jellyfin version: "10.9.0"

It looks like you are using the unstable version of the Jellyfin server. Are you able to reproduce the issue using the latest stable release (10.8.10)?

**Comment by naleo** [comment]
I tried it on 10.8.10, and am still getting the same issue.  I had actually upgraded to unstable to see if that fixed the issue.
[System_Logs_Log_name=FFmpeg.DirectStream-2023-05-29_03-03-25_2cd3e84f63e0516ba655e52ec2391219_6422c72d.log.txt](https://github.com/jellyfin/jellyfin-roku/files/11587845/System_Logs_Log_name.FFmpeg.DirectStream-2023-05-29_03-03-25_2cd3e84f63e0516ba655e52ec2391219_6422c72d.log.txt)
[System_Logs_Log_name=log_20230529.log.txt](https://github.com/jellyfin/jellyfin-roku/files/11587846/System_Logs_Log_name.log_20230529.log.txt)

**Comment by 1hitsong** [comment]
If your error is still occurring using the latest Roku client, I would suggest posting to the new Troubleshooting forum. https://forum.jellyfin.org/f-troubleshooting

There are a ton of awesome people there offering support and are great at running down issues.
