### ISSUE TITLE
Ruko app does not display movie titles that start with special characters when filtering via #-Z menu in movies library

### ISSUE THREAD

**Issue by foolsh** [jellyfin-archive/jellyfin-roku-legacy#1296]
## Software Versions

- Jellyfin Server Version:  10.8.10 - on local network
- Roku Client Version:  Version 1.6 - build 6 - on local network

## Describe the bug
Ruko app does not display movie titles that start with special characters when filtering via #-Z menu in movies library

## How To Reproduce
1. Add sample/dummy movie file named "Æon Flux (2005)"
2. Scan library
3. Go to 'My Media -> {Movies library}'
4. Notice Æon Flux shows when unfiltered results are presented, at end of list
5. Filter movies by #-Z
6. Bug occurs - "Æon Flux" is not returned in any results

## Expected behavior
Movies with titles starting with special characters should show under the # filter

**Comment by michaelcresswell** [comment]
Music libraries have the same issue.

The Roku client matches other clients in this respect though, none have a way of filtering by any special character.

**Comment by 1hitsong** [comment]
This is due do to the restrictions provided by the server API. There is no "Starts with Special Character" property. We have 3 options:

1. Starts with Less Than - catches all letters "before" the passed letter. Numbers and some special characters are deemed before A
2. Starts with Letter - Direct match. "Title starts with the letter A."
3. Starts with or Greater - catches the passed letter and all letters or special characters deemed after it. The server deems "Æ" as being after Z.

So the method to fix this is not super straightforward, but doable.

We will need to make 2 API calls. 1 for less than A and 1 for  StartsWithOrGreater than Z. We will then iterate over the StartsWithOrGreater results and filter out any where the first char is Z. Combine these two results and return to the client.
