### ISSUE TITLE
Roku app does not check device maximum resolution

### ISSUE THREAD

**Issue by Nightseer769** [jellyfin-archive/jellyfin-roku-legacy#1307]
## Software Versions

- Jellyfin Server Version:  10.8.10
- Roku Client Version:  1.6.6

## Describe the bug
Jellyfin client app for Roku does not check for the maximum resolution of the client, which prevents files that are above that maximum resolution from playing. Example specifically regards any Roku devices not capable of 4K, such as the 3930X.

## How To Reproduce
1. On a non-4K-capable Roku device, attempt to play any 4K video.
2. Observe as the video will not transcode down to the appropriate resolution.
3. Video will not play. "An error was encountered while playing this item"

## Expected behavior
File should automatically be transcoded to the appropriate resolution for the device, 1080p in this instance, and the media should play.

## Connection Information
Server is on local network, wireless network over an HTTP connection.

## Additional context
I discussed this issue on the Jellyfin Discord server, where Sevenrats instructed me to create this bug report. I was also informed that a log would be unnecessary in the same way, hence the lack of one.

**Comment by RedSoxFan04** [comment]
Also, if a file of the appropriate resolution is already available, it should be chosen automatically. It can be very frustrating to always have to remember to switch to the 1080p version - even when resuming a movie.
