### ISSUE TITLE
**Playlists** not appearing on Home Screen

### ISSUE THREAD

**Issue by thehale** [jellyfin-archive/jellyfin-roku-legacy#1318]
## Software Versions

- Jellyfin Server Version:  10.8.10 (ubuntu apt)
- Roku Client Version:  1.6.6 (Roku Store)

## Describe the bug
The **Playlists** view is not appearing on the home screen as claimed by #986 which was released in version [1.6.4](https://github.com/jellyfin/jellyfin-roku/releases/tag/v1.6.4)

## How To Reproduce

1. Open the Jellyfin Roku App
2. Log in (either as an admin or a more restricted user)
3. Observe the absence of anything referencing **Playlists** on the home screen

## Expected behavior

I was hoping to see the option to choose one of my playlists.

## Logs

Where would I go to pull these for the Roku app? I'm not seeing any Roku errors in my main Jellyfin server logs.

## Screenshots

![image](https://github.com/jellyfin/jellyfin-roku/assets/47901316/7f1a73a8-0d74-487c-8a75-a9f2edd23dc0)

NOTE: Scrolling down doesn't show anything related to playlists either...

## Connection Information

- Is server local or remote? local
- Is server connection HTTP or HTTPS? http

## Additional context

I searched through all the settings to see if this was behind a sort of feature flag. I also explored the **Music** section to see if playlists were available there (that's the location for them on Android). All to no avail.

I'm hoping this is a "user error" issue, but I'm stuck on where to check next to enable this feature.

**Comment by cewert** [comment]
Are you talking about the Playlists library that shows up on the top row of the home page on the web client? Can you show me where in the web client that these playlists exist? Did the playlists library exist before you opened the roku app?

I went on the demo server and selected a couple movies and put them in a new playlist. This created a "Playlists" library on the home page. I then opened up the latest version of the unstable roku client and connected to the demo server. There was a "Playlists" library on the top row of the home screen with the playlist I created inside and everything opened and played as expected.

![PXL_20230624_232709672 MP](https://github.com/jellyfin/jellyfin-roku/assets/16514652/58105abd-3b76-476f-a0d5-b39db5ff128e)

**Comment by thehale** [comment]
Wow! Thanks for responding so quickly @cewert,

> Are you talking about the Playlists library that shows up on the top row of the home page on the web client?

Yes.

Fundamentally, what I'm trying to find is *some* way to access my playlists on the Roku so I can shuffle through subsets of my music library.

Based on the release notes, I had expected to see the web client's **Playlists** card also on the Roku Home screen, but I'd also be content with something buried in a menu. For example, in the Android client I can go **Home** Screen -> **Music** Card -> **Playlists** Tab which, while more taps, satisfies my hopes.

> Can you show me where in the web client that these playlists exist?

Web client screenshot incoming...

![image](https://github.com/jellyfin/jellyfin-roku/assets/47901316/8634d932-57c2-4be1-b199-688e49ee145e)

> Did the playlists library exist before you opened the roku app?

Before I opened the Roku app for the very first time ever? No. At that point I had barely finished setting up the Jellyfin server on my Raspberry Pi and only had one or two movies on the server while testing everything.

Since then, I've created a few playlists in Jellyfin, but mostly ensured all my old Windows Media Player playlists resolve file paths correctly in Jellyfin. Opening **Playlists** library in the web client shows a grid containing both types of playlists. Interestingly, if I remove all the Jellyfin-created playlists (leaving just my Windows Media Player ones), then the **Playlists** library disappears from the web client's home page. Either way, I'm not seeing the **Playlists** library on the Roku, even as the Roku shows each new movie, song, and/or show that I add to the Jellyfin server.

> I went on the demo server and selected a couple movies and put them in a new playlist.  ... everything opened and played as expected [on the Roku].

Fascinating. I was able to replicate this on my Roku too using the latest Roku Store version of the app (screenshot below).
![PXL_20230627_034201062](https://github.com/jellyfin/jellyfin-roku/assets/47901316/055b0138-25a6-4806-b40f-b6dea59d70b5)

**Comment by thehale** [comment]
Additional details that appear to be relevant...

I have configured a separate "roku" user on my Jellyfin server which I use to log in from my Roku. When using **Quick Connect** to sign back into that account after experimenting with the demo server, I noticed that the web client for my "roku" user does *not* show the **Playlists** library. When I instead sign into the Roku app with my admin account, the **Playlists** library does show up in the Roku app -- matching the screenshot I shared of my web client above (which was taken using my admin account).

This seems to suggest that the issue lies with something in the user permissions I have set for my "roku" user. However, I find this confusing, because my "roku" user has access to view all content of any rating from any library. There are restrictions prohibiting any content deletion and disallowing management of the server or other users, but temporarily enabling those settings still does not show the **Playlists** library on my Roku.

I also created a brand-new user account with default settings and access to all libraries, but "Playlists" did not show up for that user either.

---

### Viable Workaround
For now, I can use my admin account on the Roku as a workaround, but I would definitely prefer to figure out how to ensure a non-admin account can access my Playlists.

**Comment by cewert** [comment]
Weird. We may have stumbled on a server bug but let's try one more thing. Can you go to the web client and re-create your playlist using your roku user? Then log on to the roku with your roku user and see if you can see the playlist. I'm hoping this is some kind of permissions issue and that the only reason you can't see the playlist is because it was created by the admin account.

**Comment by thehale** [comment]
> Can you go to the web client and re-create your playlist using your roku user? Then log on to the roku with your roku user and see if you can see the playlist.

That does the trick! Creating a single playlist using my `roku` user grants visibility to all playlists on the server on both the web client and the Roku client -- both the ones read from my Windows Media Player playlist files in addition to the playlists created by the admin user.

Interestingly, if I delete the playlist created by the `roku` user, the Playlists library remains visible. If I delete all Jellyfin-created playlists (leaving only the Windows Media Player lists), then the Playlists library disappears again until I create a new playlist with the Jellyfin controls..

**Comment by cewert** [comment]
Glad you got it working!

That's really strange behavior - thank you very much for the detailed report!

**Comment by cewert** [comment]
Closing the issue since this is a server bug.

**Comment by thehale** [comment]
@cewert Are you reporting this sever bug, or shall I?

**Comment by cewert** [comment]
@thehale I brought it up to the team and the behavior we are seeing is a known bug but not the way we thought - see https://github.com/jellyfin/jellyfin/issues/2410

I didn't know this until today but playlists were designed to be user specific. So the fact that your roku user can see your admin user's playlists after making a playlist is the bug - not the other way around. This was fixed in master (https://github.com/jellyfin/jellyfin/pull/9746) but was never backported. I'm not sure if it's in that PR or another one but playlists were also updated to allow users to share playlists with other users - in master.

So once all these fixes drop, your roku user won't be able to see the admin's playlists until the admin user shares access to the roku user.

**Comment by thehale** [comment]
@cewert That makes sense and will work perfectly!

I'll be interested to see how these updates affect the Windows Media Player playlists that Jellyfin is automatically able to read since those were not created by any Jellyfin user, but I'll open separate issues on the server repository if any concerns arise on that front.

Thanks again for your help!

**Comment by Shadowghost** [comment]
Any playlists read directly from the file system will be accesible to all users, even if they haven't created any personal playlists.
