### ISSUE TITLE
Watch from/Start over dialog sometimes automatically continues after clicking an episode

### ISSUE THREAD

**Issue by lpukatch** [jellyfin-archive/jellyfin-roku-legacy#133]
**Describe the bug**
I can see the new box pop up to select if I want to continue watching from where I was or start over, but most of the time it is auto selecting

**To Reproduce**
1. Watch a few minutes of an episode
2. Go back to the Season list
3. Reselect the same episode
4. Get automatically moved into the episode at last watched time

**Expected behavior**
Dialog to take input

**Logs**
I'm not getting anything from the telnet

For context this is a 40~ minute tv show and I was stopping and going back in about 4 minutes in

**Comment by bisby** [comment]
To clarify. in this case you are going to the episode list, picking an episode. backing out to the episode list, and re-picking the same episode?

My suspicion in this case is that aren't reloading the episode list when you go back, and we aren't updating the episode you just watched, which is why you don't get the prompt.

I would have thought it would have resumed from the beginning though (if it didn't update to know there was a point to resume from), so that bit is interesting.

**Comment by lpukatch** [comment]
Yes, going to the episode, backing out and re-choosing the same episode. I can see the dialog popping up briefly, it just autoselects resume almost as if the ok press for the episode also hits the dialog.

**Comment by cewert** [comment]
I wasn't able to reproduce. The dialog box stays up for me.

**Comment by lpukatch** [comment]
I did some more digging and my current guess is this code 

` while m.scene.dialog <> invalid
  end while`
In the misc.brs file only works the first time. I got this from a print of the m.scene.dialog which seems that the dialog gets instanced the first time it starts but never cleared

`<Component: roSGNode:JFMessageDialog> =
{
    backExitsDialog: false
    backgroundUri: ""
    boldBullets: false
    bulletText: <Component: roArray>
    bulletTextColor: -1
    bulletTextFont: <Component: roInvalid>
    buttonFocused: 0
    buttonGroup: <Component: roSGNode:ButtonGroup>
    buttons: <Component: roArray>
    buttonSelected: 0
    close: false
    dividerUri: ""
    focusButton: 0
    graphicHeight: 0
    graphicUri: ""
    graphicWidth: 0
    iconUri: ""
    letteredBullets: false
    maxHeight: -1
    message: ""
    messageColor: -1
    messageFont: <Component: roInvalid>
    numberedBullets: false
    optionsDialog: false
    title: ""
    titleColor: -1
    titleFont: <Component: roInvalid>
    wasClosed: invalid
    width: 1050
    childRenderOrder: "last"
    clippingRect: <Component: roAssociativeArray>
    enableRenderTracking: false
    inheritParentOpacity: true
    inheritParentTransform: true
    muteAudioGuide: false
    opacity: 1
    renderPass: 0
    renderTracking: "disabled"
    rotation: 0
    scale: <Component: roArray>
    scaleRotateCenter: <Component: roArray>
    translation: <Component: roArray>
    visible: true
    change: <Component: roAssociativeArray>
    focusable: false
    focusedChild: <Component: roSGNode:ButtonGroup>
    id: ""
}
`
Edit: I think I was wrong before, but without selecting an option the buttonSelected is automatically returning a 0

**Comment by anthonylavado** [comment]
Thanks for reporting this. I was getting this too.

**Comment by cewert** [comment]
@lpukatch can you do a git pull and let us know if #140 fixed your issue?

**Comment by lpukatch** [comment]
@cewert I just had a second to check and yes it seems like #140 did fix the problem
