### ISSUE TITLE
Make it much easier to switch users

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#1373]
## Is your feature request related to a problem? Please describe

More than one person uses this TV, and we want to track our watched shows separately.
It is currently a lot of button presses to change user, and the process is unintuitive.

## Describe the solution you'd like
A much easier and faster way to switch between commonly-used, already-signed-in profiles.

Perhaps pressing back from the home screen could take us to a sign in screen, with signed-in profiles offered as "quick dial"-style options. I wouldn't mind this being the first screen when I choose the jellyfin app, or maybe whether to automatically sign in as the most recent user or to choose every time should be an option.

Or perhaps there could be a new entry in the menu, "change user" or "change profile" or "who's watching".

## Describe alternatives you've considered
- Use the existing "change server" function (but this doesn't currently work as far as I can tell; see #1372)
- Use the sign out function, then sign in as the other user. I don't want to do this since I don't want to remember the passwords, let alone type them on the on-screen keyboard.

**Comment by cewert** [comment]
Closing in favor of #310
