### ISSUE TITLE
loading spinner blocks the back button

### ISSUE THREAD

**Issue by sevenrats** [jellyfin-archive/jellyfin-roku-legacy#1381]
maybe this is how we want it to behave so that we don't have to deal with the complexity of task cancellation and what not.  maybe just killing the dialog and popping a scene will be enough, but my fear is that if a media loading task is underway that this task will not cancel.  So, either implement a simple listener to do close the dialog, or investigate what would be involved with making a more comprehensive solution (perhaps we could register the loaded task with the extended dialog object somehow, such that the task was killed on back press.)

**Comment by 1hitsong** [comment]
Resolved by #1515
