### ISSUE TITLE
Home Screen Section Preferences not respected

### ISSUE THREAD

**Issue by neilsb** [jellyfin-archive/jellyfin-roku-legacy#1385]
## Software Versions

- Jellyfin Server Version:  10.8.4
- Roku Client Version:  1.6.6

## Describe the bug
Users preferences of "Home" sections set on the Website are not being used to display appropriate Section in the appropriate order on the Roku Home Screen.  This certainly was working when implemented (#553)

## How To Reproduce
1. Go to User -> Home on the website
2. Change order and inclusion of items in the `Home Screen Section`s 
3. Save
4. Restart Roku Jellyfin app and log in as same user
5. Home screen not reflecting changes

Report from Forum:  https://forum.jellyfin.org/t-roku-ultra-home-screen

**Comment by cewert** [comment]
> This certainly was working when implemented (https://github.com/jellyfin/jellyfin-roku/pull/553)

We reverted that PR because it introduced so many bugs (https://github.com/jellyfin/jellyfin-roku/pull/700). He never resubmitted it.
