### ISSUE TITLE
AV1 Doesn't Direct Play (Transcoding Occurs) on Compatible Roku Models with AV1 Enabled in Settings.

### ISSUE THREAD

**Issue by lakerssuperman** [jellyfin-archive/jellyfin-roku-legacy#1392]
## Software Versions

- Jellyfin Server Version:  10.8.11
- Roku Client Version:  1.6.6 and Unstable give the same result.

## Describe the bug
I enable experimental AV1 playback in Roku Jellyfin app settings.  From everything I know about my Roku models they support AV1.  However, any AV1 clip I play results in the video being transcoded with the reason video codec not supported.  In my case, the clip gets transcoded to HEVC/AAC.  This occurs with version 1.6.6 and latest unstable as of this date (Sept. 25th, 2023).

## How To Reproduce

1) Enable AV1 playback in Jellyfin app settings with latest stable release or unstable.
2) Playback an AV1 clip.
3) Transcoding occurs.

## Expected behavior
AV1 should play back on my devices without any transcoding.

## Logs
"PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported"

Previous version of the app would result in playback of the AV1 clips, but I would get nothing but a black screen.  I could hear the audio and the server showed it was direct playing, but for some reason the video was black.  I hadn't tried AV1 in awhile and wanted to give it a go on the latest code and found that AV1 gets transcoded.

**Comment by cewert** [comment]
Can you post your device model and some information on the file you're trying to play? such as bitrate, profile, level etc. It's possible the file you are trying to play has an unsupported video profile or level etc. It would also be helpful to see a log file from unstable so I can verify your device profile is being built correctly after turning on the av1 user setting.

Also, you mention the file used to play sound but with no video, do you know what version that was? Did the video ever play video correctly? Was it the same file you are trying to play now?


![roku-codec-support](https://github.com/jellyfin/jellyfin-roku/assets/16514652/e39d2979-5817-4a02-b4b0-67469436d0b9)

**Comment by lakerssuperman** [comment]
> Can you post your device model and some information on the file you're trying to play? such as bitrate, profile, level etc. It's possible the file you are trying to play has an unsupported video profile or level etc. It would also be helpful to see a log file from unstable so I can verify your device profile is being built correctly after turning on the av1 user setting.
> 
> Also, you mention the file used to play sound but with no video, do you know what version that was? Did the video ever play video correctly? Was it the same file you are trying to play now?

The model Rokus are the 4800x (the 2020 Ultra) and the latest Roku Streaming Stick 4K.

The test clip I used is AV1 Profile Main Level 9 in Jellyfin, but MediaInfo reports it as main@L4.1. 1080p SDR.  60fps.  7744 kbps bitrate.

I got the clip from here: https://www.elecard.com/videos.  It's the City Hall Clip.

However, I tried a few other random AV1 files I have and they didn't work either.  I can try creating a fully Roku compatible clip later to see what happens.

I can't say what version used to play audio but no video, but it was somewhere in the last calendar year, not that that tells us much.

Here is the snippet of the log.  I believe this is when I played the clip on Unstable.  https://pastebin.com/H72Ky037

A little snippet on Roku and AV1 I found in the Roku fourms  Not sure it if is useful: https://community.roku.com/t5/Roku-Developer-Program/Is-Roku-Ultra-2022-Correctly-reporting-it-supports-AV1/m-p/853716#M51350

If you need more from the log I can post it.

Thank you!!

**Comment by cewert** [comment]
>  I can try creating a fully Roku compatible clip later to see what happens.

That's a great idea, thank you.

> Here is the snippet of the log. I believe this is when I played the clip on Unstable. [pastebin.com/H72Ky037](https://pastebin.com/H72Ky037)

Sorry for not being clear. Server logs are always good to see but I was wanting a roku log of the unstable app. Can grab them with vscode after deploying the dev app. I can help you get this setup if needed just give me a shout on the matrix channel.

> A little snippet on Roku and AV1 I found in the Roku fourms Not sure it if is useful: [community.roku.com/t5/Roku-Developer-Program/Is-Roku-Ultra-2022-Correctly-reporting-it-supports-AV1/m-p/853716#M51350](https://community.roku.com/t5/Roku-Developer-Program/Is-Roku-Ultra-2022-Correctly-reporting-it-supports-AV1/m-p/853716#M51350)

Interesting, thank you. What's the container of the file you're trying to play?

Also, what's the audio codec? Is it multichannel? Audio has nothing to do with this issue, just curious if you are losing multichannel audio during the transcode.

**Comment by lakerssuperman** [comment]
> > I can try creating a fully Roku compatible clip later to see what happens.
> 
> That's a great idea, thank you.
> 
> > Here is the snippet of the log. I believe this is when I played the clip on Unstable. [pastebin.com/H72Ky037](https://pastebin.com/H72Ky037)
> 
> Sorry for not being clear. Server logs are always good to see but I was wanting a roku log of the unstable app. Can grab them with vscode after deploying the dev app. I can help you get this setup if needed just give me a shout on the matrix channel.
> 
> > A little snippet on Roku and AV1 I found in the Roku fourms Not sure it if is useful: [community.roku.com/t5/Roku-Developer-Program/Is-Roku-Ultra-2022-Correctly-reporting-it-supports-AV1/m-p/853716#M51350](https://community.roku.com/t5/Roku-Developer-Program/Is-Roku-Ultra-2022-Correctly-reporting-it-supports-AV1/m-p/853716#M51350)
> 
> Interesting, thank you. What's the container of the file you're trying to play?
> 
> Also, what's the audio codec? Is it multichannel? Audio has nothing to do with this issue, just curious if you are losing multichannel audio during the transcode.

Ohhhh gotcha.  I'll see what I can do with the Roku log later.

The container for the City Hall clip is webm, but I've also tried mkv and gotten the same results.

The City Hall clip has no audio, but I've tried AV1 clips with Opus stereo and they transcode the audio to AAC.

**Comment by cewert** [comment]
> The container for the City Hall clip is webm, but I've also tried mkv and gotten the same results.

Can you try another container? Based on the roku forum post you linked, AV1 works with MKV but the roku device will report that AV1 support doesn't work within an MKV container: https://community.roku.com/t5/Roku-Developer-Program/Is-Roku-Ultra-2022-Correctly-reporting-it-supports-AV1/m-p/853959/highlight/true#M51362

**Comment by lakerssuperman** [comment]
@cewert Update:

I encoded some of my new Fright Night Bluray ( I know, I'm a man of taste and sophistication lol).  AV1, EAC3 in an MKV.  Using unstable the video still transcodes, but the audio (despite the Jellyfin dashboard claiming it was being transcoded to AAC) is passed through as EAC3.

I can see about another container, but Handbrake only gives me the options for MP4, MKV and webm so I'm not sure what container would work.

Also, I think this is the output you wanted from the Roku?  https://pastebin.com/xpxHFp5e

I Telnet'd into the Roku while I played back the AV1 clip and captured the output.  From looking at the output, it doesn't seem to be reporting AV1 in the video codecs array section, but that's just me and my laymen eyes talking.

I'm going to try local playback of the file off of a USB stick and see what happens as well.

**Comment by cewert** [comment]
Yep, that's the debug log I was looking for thank you. The top part showing your user settings is cut off, can you double check you have the av1 setting enabled? You said it was and I believe you lol I just want to double check before I start trying to change anything to fix this.

> I encoded some of my new Fright Night Bluray ( I know, I'm a man of taste and sophistication lol). AV1, EAC3 in an MKV. Using unstable the video still transcodes, but the audio (despite the Jellyfin dashboard claiming it was being transcoded to AAC) is passed through as EAC3.

Based on your device profile from the roku log, av1 isn't going to work for you no matter the container. Like you mentioned, av1 isn't listed in your debug log under `profile.DeviceProfile.DirectPlayProfiles` for any of the containers. That's awesome that eac3 is still working though.

At this point (assuming you did indeed have av1 setting enabled) I think it's safe to say that the `CanDecodeVideo()` isn't correctly reporting av1 compatibility (similar to mpeg4 and mpeg2.) Therefore, the only way to make this work is going to be hardcoding support for av1 in the device profile if the user settings is turned on (like we're doing with mpeg2 and mpeg4 right now).

If you'd like to test av1 in all possible containers, that would be best. Then we would only add av1 to the containers we know the roku can support. But if you can't do that or don't want to, then we can add av1 support to all the containers and remove them if necessary based on user feedback
