### ISSUE TITLE
Shuffle An Entire Library

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#1399]
## Is your feature request related to a problem? Please describe

This was created on behalf of a Reddit user comment: 
https://www.reddit.com/r/linux/comments/16xufak/comment/k352mtw/

## Describe the solution you'd like

Being able to select a library, and select "Shuffle" to play any media item inside at random. This would apply to the root of the library, whether movies or tv shows.

## Describe alternatives you've considered

Using TV Show shuffle, but it requires selecting a TV Show.

## Additional context

None really.

**Comment by cewert** [comment]
This is being implemented in my "Quick Play" PR https://github.com/jellyfin/jellyfin-roku/pull/1376. Pressing play on a movie or tv show collection from the home screen "My Media" row will shuffle play the items inside (mostly).

These are the library types supported and what the current logic looks like (copied from the PR):

- Add "collectionFolder" support
  - Supports `movies`, `tvshows`, `boxsets`, and `music` collection types
    - movies: shuffle play all movies found in collection
    - tvshows: shuffle play all watched episodes in collection
    - boxsets: pick a random boxset inside and play all the items inside
    - music: shuffle play all audio files in collection
  - Works from the "My Media" and favorite rows on the home page and also the main grid view

Edit: I also added support for Quick Playing Live TV and Music Video libraries
