### ISSUE TITLE
Movies/Shows playback - Change audio tracks on the fly

### ISSUE THREAD

**Issue by roast1880** [jellyfin-archive/jellyfin-roku-legacy#1412]
## Describe the feature you'd like
Can we create an option to change audio playback on the fly? If we start a show or movie but forget to change the audio track to our preferred language, can we have the option to change the track instead of fussing through the menu's?

## Additional context
Plex has this, if you long press OK you get a submenu where you can change playback options like audio.

**Comment by cewert** [comment]
Closing in favor of #1037
