### ISSUE TITLE
Show Extra Features on TV Show Season View

### ISSUE THREAD

**Issue by JarodTAerts** [jellyfin-archive/jellyfin-roku-legacy#1415]
## Is your feature request related to a problem? Please describe
Currently in the Roku app, TV Show special features and extras are not shown when viewing the episodes for a season. This is unlike the web view version of Jellyfin which does show the extra content. This means that in order to watch this extra content on the Roku app it is necessary to reorganize your media library to break the normal extras format described in Jellyfin docs: https://jellyfin.org/docs/general/server/media/shows/#show-extras. It would be best if the extras can be displayed in the Roku app just like in the other Jellyfin clients.

## Describe the solution you'd like
A button on the left side of the Season Episodes view which can be selected to switch between the Extras for the season and the Episodes. This would be hidden behind a user setting and the button would only show if the setting is enabled and the season has non-empty list of extra content. By default the TVEpisodes view would show the episodes and the button would show "Extras." If the button was selected, the TVEpisodes view would switch to showing the extras content and the button text would switch to "Episodes." At that point, selecting the "Episodes" button would toggle back to showing episodes and button would switch back to "Extras."

## Describe alternatives you've considered
1) More significant rework of the TVEpisodes and TVEpisodeRowWithOptions components to more closely match the web view equivalents. This would have an episode list and then a separate, but always visible extras section. In the end, I think this option is more work than necessary, since the existing TVEpisodes view is proven and works well. A more significant rework of the TVEpisodes component could still be a future work item for when I know more about BrightScript/Roku development 🙂

## Additional context
I recently started using Jellyfin to manage my media collection and have really enjoyed it. Further, I primarily use Roku as my streaming OS of choice. The Jellyfin Roku app did not have the ability to play extras on TV seasons which I have a lot of that I would like to watch on my TVs. I decided to dive into the code and do my best to improve the platform I am using. I have written the code for the above proposed solution and will test and improve it when I get back home where I have a Roku. I can open a PR once I have validated things work as expected.

**Comment by cewert** [comment]
Thanks for working on this!

Your proposed solution sounds good to me. Curious why you want to put this feature behind a user setting though? IMO it doesn't need one since the button will be displayed dynamically based on if the TV show extras are found. Basically, I don't understand why a person would have extras for their TV show but NOT want to see the button to display them.

**Comment by JarodTAerts** [comment]
Agreed, and thank you for the feedback! Initial instinct was to initially hide behind config in case any unintended consequences arose. But I think the presence of TV show extras is a good switch. I will run with that. Today I completed and tested the initial implementation, will clean up and link PR to this issue in next couple days for review.

**Comment by 1hitsong** [comment]
Resolved by #1416
