### ISSUE TITLE
App is missing from Roku channel store

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#1424]
At some point on 10/17/2023 our app in the [Roku channel store](https://channelstore.roku.com/) was changed, for a reason currently unknown to us, from a `public` to a `beta` release. Because of this, the app can no longer be found at the [URL in our readme](https://channelstore.roku.com/details/cc5e559d08d9ec87c5f30dcebdeebc12/jellyfin) or by searching the Roku channel store for "jellyfin".

As a workaround until this gets fixed, you can install the app using this link (you need to be logged in to your roku account): https://my.roku.com/account/add?channel=jellyfin

You will receive a warning that the app is "beta" and may have bugs etc. but that message can be ignored since it is the same code used for the `1.6.6` release.

**Comment by evanratt** [comment]
This is not working for me. I confirm the warning that the app is "not certified" and the warning goes away, but nothing else happens. If I click on "Add channel" again, and confirm the warning again, I get taken to a 404 page.

**Comment by matthewschroer** [comment]
I am having the same issue. According to the [Roku Dev docs](https://developer.roku.com/docs/developer-program/publishing/channel-publishing-guide.md), Beta Channels are limited to 20 users

**Comment by lachesis** [comment]
What needs to be done to convert this app back into a public release? I was able to install under the Beta but my friend was not.

**Comment by cewert** [comment]
We filed a ticket with roku support back on the 19th but they still haven't told us why this happened.

> What needs to be done to convert this app back into a public release?

That's the million dollar question that no one has the answer to right now. We have no idea why our channel was changed from `public` to `beta` which means we have no idea what we need to do to fix the problem 😢

**Comment by samnn** [comment]
> What needs to be done to convert this app back into a public release? I was able to install under the Beta but my friend was not.

As a stopgap you should be able to install the dev build with developer mode on your roku. There are steps for how to install it in the readme, just did it a few hours ago. Note, you'll need to be logged into github for the artifact to be downloadable.

**Comment by Alliyance** [comment]
Just contacted Roku via messenger and they are looking into why it was removed. Hopefully, we'll get an answer soon.

**Comment by Alliyance** [comment]
Saw that the Roku certification test was updated since October.They probably change something that didn't pass the test. 

https://developer.roku.com/en-ca/docs/developer-program/certification/cert-tests/authenticated-cert-testing.md

**Comment by 1hitsong** [comment]
Nope, we haven't pushed an update since April. We woke up one morning and it was just gone.

But, we just got word from Roku that the channel is back. They confirmed they were the ones who converted it to beta and that we had no method to change it back - it was 100% in their hands.

**Comment by richardklafter** [comment]
Confirmed it is back! Thanks!

**Comment by Alliyance** [comment]
That's fantastic!!!

**Comment by ragnarok22** [comment]
![Screenshot_20240125_145408_Chrome.jpg](https://github.com/jellyfin/jellyfin-roku/assets/8838803/78bef4a7-e46b-43cd-bc3b-826e6cc86f1b)

I tried to add from the website but the button is disabled. I installed others apps using the same method
