### ISSUE TITLE
Overhang is missing from the home view when returning from movie library.

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1427]
## Software Versions

- Jellyfin Server Version:  Latest
- Roku Client Version:  Unstable

## Describe the bug
Overhang is missing from the home view when returning from movie library.

## How To Reproduce

1. Go to home view
2. Click on Movie library
3. Press back button
4. Overhang is now hidden

## Expected behavior
Overhang should show.

**Comment by cewert** [comment]
I can't reproduce this. When I view my movie library, the overhang is still showing. Then hitting back shows the home page with overhang.

Do you have a setting enabled that hides the overhang on your movie library?

**Comment by 1hitsong** [comment]
What view are you using on your movie library? Try testing it with Presentation view.

**Comment by cewert** [comment]
Either I found a bug or my install got borked somehow. I can't get presentation mode to work - the user setting seems to be ignored. No matter what view I select, the overhang remains.

![PXL_20231024_230716980 MP](https://github.com/jellyfin/jellyfin-roku/assets/16514652/e121882d-4851-4ac7-b2bf-b39824316892)
