### ISSUE TITLE
Pressing the Back Button From the Lowest Level of the Settings Menu Returns to Jellyfin Home Screen

### ISSUE THREAD

**Issue by lakerssuperman** [jellyfin-archive/jellyfin-roku-legacy#1454]
## Software Versions

- Jellyfin Server Version:  10.8.11
- Roku Client Version:  Unstable

## Describe the bug
When at the lowest level of the settings tree (i.e. where you actually click on a preference) pressing the back arrow takes the user back to the Jellyfin home screen instead of the previous level of settings.

## How To Reproduce

1. Open settings
2. Navigate down to the lowest level of settings where a preference is selected.
3. Press the back arrow.
4. User is returned to the Jellyfin home screen instead of the previous level of the settings tree.
5. 
## Expected behavior
Back arrow should return user to the previous level of settings unless user is at the top level in which case returning to the home screen would be the correct behavior.

## Connection Information

Server and clients are on the same local network.

## Additional context
In the attached screenshot, user is at the codec section of video codec support.  MPEG-2 is selected.  Once enabled or disabled is chosen, pressing the back arrow should return the user up the tree (Video Codec Support, Playback, Settings) to allow for adjusting more settings, however,  pressing back from here returns the user to the main home Jellyfin screen instead.

![20231028_064203](https://github.com/jellyfin/jellyfin-roku/assets/18699905/20c14570-1ca4-4a37-9481-d725ace227b8)

**Comment by cewert** [comment]
Thanks, I forgot to make an issue for this. Fixed by #1390

**Comment by lakerssuperman** [comment]
> Thanks, I forgot to make an issue for this. Fixed by #1390

No problemo!!!
