### ISSUE TITLE
Roku not playing shows/movies

### ISSUE THREAD

**Issue by blankissue** [jellyfin-archive/jellyfin-roku-legacy#1457]
## Software Versions

- Jellyfin Server Version:  10.8.11 (updated after trying to fix the issue so a rollback wont fix it) 
- Roku Client Version:  1.6.6

## Describe the bug
start a show/movie and get a load screen (spinning circle) and it never plays the show then goes back to the play screen, server works on everything else but roku, even works remote, its every tv show/movie 
## How To Reproduce

1. go to a show/movie
2. Click on play

## Connection Information

- Is server local or remote?
- local
- Is server connection HTTP or HTTPS?
- https 

## Additional context
servers made through duckdns and caddy if it matters

it worked perfectly a few days beforehand even deleted and reinstalled the app, checked for updates for the app and the roku tv 
as mentioned above i updated the server to 10.8.11 i believe the server version before was from February of 2023

app works perfect besides not playing content, the settings menu works and the browsing works even has all the thumbnails for shows/movies

**Comment by Alliyance** [comment]
What kind of container are you using, codec, audio format? Roku is more picky when it comes to direct play and if you use a server (seedbox)it won't be fast enough to transcode.

**Comment by blankissue** [comment]
> What kind of container are you using, codec, audio format? Roku is more picky when it comes to direct play and if you use a server (seedbox)it won't be fast enough to transcode.

found the issue it was some sort of interference with a wifi extender, worked perfectly upstairs but downstairs the tv failed to load the content for some reason despite the extender being faster on everything else on the tv (extender worked for about a week downstairs which is why i assumed it was server/app related) 

ill just assume the issue was roku not liking the extender unless its right next to it 
thank you for the reply
