### ISSUE TITLE
Roku Subtitle Descriptions

### ISSUE THREAD

**Issue by tsuivo** [jellyfin-archive/jellyfin-roku-legacy#1465]
Hello,

Thank you all for having worked on the project, the Roku client specifically. It has been a great experience.

One question/enhancement request I have is how subtitles are displayed when trying to select them. 

On browser (and the other clients AFAIK), they will display as shown below
![subtitles](https://github.com/jellyfin/jellyfin-roku/assets/149628329/e599115e-dadf-41f8-a017-266d82b61ee6)

On Roku, they will display as shown below
![rokuoptions](https://github.com/jellyfin/jellyfin-roku/assets/149628329/8721234a-0dbf-4c3b-85c9-08cdbb220d3f)

This is troublesome because the subtitles, while the same language, can differ in content greatly depending on the medium. In my use case (anime), the official subtitles are often inferior products, so people fansub the shows in order to retain the original meaning of the content. As such, it is important to be able to differentiate between, and select which subtitle set one can use at the time of watching an episode.

It is worth noting that the order that they subtitles appear in the browser is not always the same as they appear in Roku.

In any case, is it possible to alter this behavior so the subtitle descriptions are fully displayed? It already functions this way with the audio options!

Thank you

**Comment by 1hitsong** [comment]
I believe the naming issue is resolved in the new video player that we're moving to for video playback.

Try this. Add this video to a playlist. Navigate to the playlist on Roku and play the video from there. Press down to open the subtitle popup. Does it have the full name in this popup?

Because playlist support is brand new, it was the first to get the new video player component, which is why it has some newer features the standard video player doesn't have yet.

**Comment by cewert** [comment]
Yea I think this is fixed on unstable even without a playlist. At least for movies. It uses the new popup style with the full name listed.

**Comment by tsuivo** [comment]
> I believe the naming issue is resolved in the new video player that we're moving to for video playback.
> 
> Try this. Add this video to a playlist. Navigate to the playlist on Roku and play the video from there. Press down to open the subtitle popup. Does it have the full name in this popup?
> 
> Because playlist support is brand new, it was the first to get the new video player component, which is why it has some newer features the standard video player doesn't have yet.

Yep! Works when added to a playlist! Although for whatever reason I can only get it to show up via my admin user (not a problem though, cool to see it working).

Thank you!

**Comment by tsuivo** [comment]
> Yea I think this is fixed on unstable even without a playlist. At least for movies. It uses the new popup style with the full name listed.

Awesome! Thanks for the hard work guys
