### ISSUE TITLE
If official rating is missing from content the homepage doesn't load

### ISSUE THREAD

**Issue by lpukatch** [jellyfin-archive/jellyfin-roku-legacy#148]
**Describe the bug**
If Official rating is invalid the home page does not load

**Logs**
Type Mismatch. (runtime error &h18) in pkg:/components/home/HomeItem.brs(39)
039:       itemTextExtra.text = StrI(itemData.json.ProductionYear).trim() + " - " + itemData.json.OfficialRating

**Additional context**
Line 39 of HomeItem.brs is the issue. I checked and it is the official rating that is invalid for me not the production year.

**Comment by cewert** [comment]
Can you do a git pull and see if it works now?
