### ISSUE TITLE
Live TV default view

### ISSUE THREAD

**Issue by Dleewee** [jellyfin-archive/jellyfin-roku-legacy#1480]
## Is your feature request related to a problem? Please describe

When selecting Live TV, I'm presented with a list of channel icons. This isn't helpful as I nearly always want to see guide details to know what is playing on each channel. 

## Describe the solution you'd like

When selecting Live TV, I want to automatically see the TV guide view. This could be set per user or system wide, as long as I can just make the guide view my default view. 

## Describe alternatives you've considered
At this time the alternative is every time I use the Live TV tile, I go to settings and switch the view to guide which takes about 5 button presses. I also cannot do this from a universal remote due to not having a star (settings) button mapped. This gets a bit frustrating over time.

**Comment by cewert** [comment]
You can already do this but it's not really documented anywhere.

We use your user's web client setting for "default screen" under User settings -> Home -> Live TV -> default screen dropdown

![livetv-default](https://github.com/jellyfin/jellyfin-roku/assets/16514652/994778e3-d887-4ce8-902e-19083f99e442)

**Comment by Dleewee** [comment]
Thank you so much! 👍

**Comment by cewert** [comment]
I'm going to close this since your issue has been resolved.

Feel free to reopen if you'd like to add a client side setting for this.
