### ISSUE TITLE
Return to Pause Menu After Pause Menu Pop-Ups

### ISSUE THREAD

**Issue by michaelcresswell** [jellyfin-archive/jellyfin-roku-legacy#1504]
Choosing either Playback Info or Select Subtitles within the new Pause Menu ([PR 1461](https://github.com/jellyfin/jellyfin-roku/pull/1461)) leads to a pop-up dialogue box.

After interacting with the dialogue (either pressing Ok or Back), the user is taken to the paused video without the Pause Menu showing.

It would be nice to return to the Pause Menu, since this is where the user was prior to the pop-up and it will more clearly communicate that the video needs to be unpaused by the user for playback to continue.

**Comment by cewert** [comment]
> After interacting with the dialogue (either pressing Ok or Back), the user is taken to the paused video without the Pause Menu showing.

I just want to point out that you can also open the pause menu with up/down/okay without actually pausing the video. We're calling it the "pause menu" so that part isn't very obvious 😊
