### ISSUE TITLE
No indication that specials are specials when shown within season

### ISSUE THREAD

**Issue by sevenrats** [jellyfin-archive/jellyfin-roku-legacy#1521]
If a library has "show specials in the order the were aired" or whatever its called enabled, specials have confusing numberings that do not indicate they are specials.  only by looking at the series from another client can you figure out whats going on.
affects all versions
to repro: enable the setting and browse to the TVListDetails of a season which has specials aired in it.

**Comment by cewert** [comment]
I don't think we've ever coded support for that feature. Changing this from a bug to a feature request.

Are you suggesting we do the same thing the web client does? How exactly do they handle it?

**Comment by photonconvergence** [comment]
Here's how it's handled in web:
![Screenshot_20240223_181410](https://github.com/jellyfin/jellyfin-roku/assets/116527579/03b9627d-9adc-49be-a523-3eaf796f4481)

Any special displayed in a season has the episode number replaced with "Special - ". When viewing the Specials season (Season 0), the same behavior occurs.

In my experience, special episode numbers rarely have any correlation to the show itself. They exist mostly for acquiring metadata. Some specials don't exist at the metadata providers, and don't have episode numbers at all.
