### ISSUE TITLE
Use the main web clients home screen failing.

### ISSUE THREAD

**Issue by p37307** [jellyfin-archive/jellyfin-roku-legacy#1578]
## Software Versions

- Jellyfin Server Version: 10.8.13
- Roku Client Version: 2.0.0
- Jellyfin user name "tv"
- Roku device 1: Hisense TV 40H4 (D000X)
- Roku device 2: Roku Express (3900X)
- Roku device 3: RCA TV RTRU6528-C-CA (G000X)

## Describe the bug

Changing the settings to use the main web clients home view arrangement is partially failing.

## How To Reproduce

1. Open Jellyfin Roku 2.0.0, press *, settings, user interface, general, use web clients home screen, enable.
2. Restart Jellyfin
3. Web clients home screen library folder order is respected in the top "My Media" but the order below in the "Latest Media" "next up/new" library folder arrangements are ignored.

## Expected behavior

Home screen library lineup should match Jellyfin's web clients in the My Media row, which it does, as well as the remaining Latest Media rows below. Favorites are delegated to the bottom, movies to the top.

## Logs

Log after removing roku from devices in the webclient, loggin in Jellyfin Roku, setting the web client view setting, exiting Jellyfin Roku opening Jellyfin Roku. Nothing really shows up that I can see.
`
2023-12-13 19:29:26.346 -05:00] [ERR] [7] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2023-12-13 19:29:26.383 -05:00] [INF] [7] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "tv" has been denied (IP: "192.168.0.182").
[2023-12-13 19:29:26.403 -05:00] [ERR] [7] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/AuthenticateByName".
[2023-12-13 19:29:39.973 -05:00] [INF] [7] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "tv" has succeeded.
[2023-12-13 19:29:39.976 -05:00] [INF] [7] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "tv": 0/0
[2023-12-13 19:29:39.991 -05:00] [INF] [7] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 2dbXXXXX-dxXXXb-4394-a231-48XXXXXXX2

`
## Screenshots

My Media, (libraries in the correct web client order) Continue Watching and Next Up rows are in the correct places. Then random library row loads, then Movies, regardless of where set in Web Client and the remaining libraries.

Image: Left, web client as the library order should and does appear. Right, Jellyfin Roku 2.0.0 order. Sometimes in Roku, between Next Up and Movies, a random library row is there.
![sidebyside](https://github.com/jellyfin/jellyfin-roku/assets/22573401/68e99cb9-a6ee-4831-bdc1-df4cb9c558fc)
## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? Http

## Additional context

This happens on three different Roku's, all of different Roku models.

**Comment by 1hitsong** [comment]
My first thought is we've created a race condition in the Latest In load tasks. The order the tasks are completing is the order the rows are being set.

**Comment by cewert** [comment]
In `1.6.6`, we were creating temporary "latest in" rows for each library once we had the "my media" data. Then later when we got data for each "latest in" row, we found the row by title and inserted the data. https://github.com/jellyfin/jellyfin-roku/blob/v1.6.6/components/home/HomeRows.brs#L96

I'm betting we stopped making temporary rows but I haven't looked into how we are doing things now.

**Comment by Alliyance** [comment]
Same issue with version 2.0.0 and 2.0.1 
Next up and Continuted watching are in the right position.
Latest movies and Latest series keeps changing. Sometimes, movies will be on top and some days series will be on top.

But thank you for fixing the subtitles with the new version 2.0.1 :):):)

**Comment by p37307** [comment]
> Same issue with version 2.0.0 and 2.0.1 Next up and Continuted watching are in the right position. Latest movies and Latest series keeps changing. Sometimes, movies will be on top and some days series will be on top.

Can confirm, still an issue after 2.0.1.

Will add, Favorites are on the bottom for both versions. Haven't sideloaded any testing versions lately.

**Comment by 1hitsong** [comment]
We haven't worked on a bug fix for this yet.

You can see the list of updates in the What's New popup on your Roku, or in the release notes: https://github.com/jellyfin/jellyfin-roku/releases/tag/v2.0.1

**Comment by Alliyance** [comment]
Sorry my fault, I haven't check the fix list. 🥴
