### ISSUE TITLE
ASS external subtitles do not display

### ISSUE THREAD

**Issue by sanqdinh** [jellyfin-archive/jellyfin-roku-legacy#1590]
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version:  2.0.0

## Describe the bug

After updating the Roku Client to 2.0.0, the client nó longer displays external .ass subtitles.
In the old client version, the server would transcode the subtitles when an .ass file is played. However, the new client does not display the .ass subtitles, and the server is no longer transcoding the subtitles (maybe the server does not receive the request?).

## How To Reproduce

4. Bug occurs

## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? HTTP

**Comment by 1hitsong** [comment]
If you can, please test and see if my code changes in this PR fixes this bug.

https://github.com/jellyfin/jellyfin-roku/pull/1608

**Comment by sanqdinh** [comment]
I have confirmed that your PR fixed the bug on my Roku client. Thank you so much and great work!
