### ISSUE TITLE
OK button doesn't play episode from season list

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1596]
## Software Versions

- Jellyfin Server Version:  Latest
- Roku Client Version:  Latest

## Describe the bug
When accessing the season episode list through the Go To Season popup option, the OK button doesn't play the episode

## How To Reproduce

1. From the home view, select a TV episode from Continue Watching
2. From the dialog choose Go To Season.
3. From this episode list view try selecting an episode using the OK button
4. The episode doesn't play

## Expected behavior
The selected episode plays.

**Comment by cewert** [comment]
This would also happen if the user has the `ui.tvshows.goStraightToEpisodeListing` setting enabled, has only one season, and selects the tv show.

**Comment by 1hitsong** [comment]
Fixed by #1597
