### ISSUE TITLE
Home Screen View Layout Update

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#16]
Currently just the libraries are selection options on the home screen after login.
 - The libraries need thumbnails
 - I can get focus going Down to a search field that is not visible
 - Missing Continue Watching category
 - Missing Latest Movies category
 - Missing Latest TV Shows category

**Comment by mcrowson** [comment]
RE: down leads to hidden search field.

My display is probably <=480p and is in SD. Its a second computer monitor. The search field is shown on HD views.

**Comment by mcrowson** [comment]
After loading it back up on a 1080p (Roku defines everything 780 and above as HD) the search field is not showing again. Might be a visibility setting or a black on black style thing

**Comment by cewert** [comment]
> I can get focus going Down to a search field that is not visible

this should have been fixed with #73
