### ISSUE TITLE
Automatically play next episode

### ISSUE THREAD

**Issue by amanaedk** [jellyfin-archive/jellyfin-roku-legacy#160]
**Automatically play next episode**
There should be an option to automatically play the next episode when an episode of a series finishes. 

**Additional context**
Currently the app kicks you back to the season or series level (seems random?) instead of playing the next episode. This feature was present in the very old version I just updated from and the web version, and it is sorely missed. If there is some option related to this in the app already, we have not been able to find it.

**Comment by devlin016** [comment]
I agree this could be a very good client for jellyfin just needs bugs worked out and features put in. Really need next episode autoplay and live tv playback.

**Comment by cron410** [comment]
The wife hates that this doesn't work. Back to Plex until it's sorted.

**Comment by oddnotions** [comment]
Agree that this is a key missing feature from the Roku app, in addition to a better OSD during playback. Both are much better executed in the web app at the moment.

I would prefer it if I could configure the maximum amount of time it will wait before moving to the next episode without input, along with a highlit-by-default button to manually advance to the next episode immediately similar to netflix.

**Comment by cron410** [comment]
Maybe something like this? https://github.com/rokudev/custom-playback-channel/issues/2

**Comment by Goddard** [comment]
Any update on this?

**Comment by devlin016** [comment]
the developer is trying lots of changes have been made since this posts starting date.. Live TV has been added with along other UI changes.... but still no autoplay

**Comment by Artiume** [comment]
autoplay missing is the bug i see most daily so don't think we don't see it. The reason it hasn't been implemented is the end of stream overlay which asks you if you want to watch the next episode or stop watching etc is a nightmare to implement on the roku. It is what it is, we're looking forward to fixing this so don't think we've forgotten about it!

**Comment by jceloria** [comment]
This must have recently been rolled out, because now all of my episodes default to autoplay. Despite having the box unchecked there appears to be no option to disable this functionality.

I frequently play media while lying in bed, I'd rather not blow through a series if I fall asleep. Is there a way to return to the previous default?

**Comment by cewert** [comment]
@jceloria Yes this was a part of the latest release. There's currently no way to change the behavior, it will always auto play, but I think you bring up a good point that we should be using the web client setting until we have our own client side setting to toggle.

Just to double check, when you talk about having the box unchecked you're referring to the Playback -> "Play next episode automatically" setting on the web client?

**Comment by jceloria** [comment]
Yes, my apologies if I wasn't specific about that setting. That is what I was referring to. I was desperately looking for anything that could potentially disable autoplay.

**Comment by jceloria** [comment]
Is there an easy way to return to the previous release?

**Comment by cewert** [comment]
Understood. I'll make an issue for this and hopefully we can get this done before the next release.

**Comment by anthonylavado** [comment]
Roku is in a holiday freeze until January 3rd (see [here](https://blog.roku.com/developer/channel-store-blackouts-2020)), so we are not able to update the release channel again before then.

I _might_ be able to update the beta channel, but I've never tried during the holiday shutdown. I believe it doesn't require review, so that might be worth a shot. Otherwise, I'll have to get a release build up and you'll have to enable developer mode to side load it.

**Edit:** I know there's another issue opened for the actual functionality, but I re-opened this as a note for me to try the beta stuff I mentioned in this comment.

**Comment by bachya** [comment]
I'm on 10.7.0-rc2 with the most recent Roku app and am noticing that one of my shows (`Seinfeld`) always seems to auto-play the same next episode (`1.4: Male Unbonding`). No matter what episode I select manually, this episode always comes next. I've also played this episode through to its ending, but even then, it starts to replay the same episode.

I've seen this same behavior with `The Office`: no matter what, the next episode to play is `1.2: Diversity Day`.

I've confirmed that this behavior doesn't happen in the web client: there, auto-play works as expected (the next episode starts after the current one ends).

New to the project and am not super familiar with the architecture, but let me know if I can provide more info (or if there is a different issue where this info should be placed). Thanks!

**Comment by hshl2** [comment]
> I've confirmed that this behavior doesn't happen in the web client: there, auto-play works as expected (the next episode starts after the current one ends).

I'd like to +1 this. I've noticed the exact same scenario. It happens on multiple (maybe all) series. I just tested this with the latest git build for Roku on 10.7 over the weekend.

**Comment by 1hitsong** [comment]
We believe this issue is resolved using a combination of the latest server and latest client releases. Please retest and if you still experience the issue, please open a new issue ticket.
