### ISSUE TITLE
Quick Connect crashes

### ISSUE THREAD

**Issue by lewisdiamond** [jellyfin-archive/jellyfin-roku-legacy#1601]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  Latest (will update once I find the version)

## Describe the bug
From a fresh install, go to quick connect, get the number and type it in the web based UI to allow.
The app crashes to home screen and is never logged in.

## How To Reproduce
From a fresh install, go to quick connect, get the number and type it in the web based UI to allow.
The app crashes to home screen and is never logged in.

## Expected behavior
Should not crash. Should log you in.

## Connection Information

- Is server local or remote?
Local, accessed via a reverse proxy over HTTPs with a local DNS server pointing to the local IP.
- Is server connection HTTP or HTTPS?
HTTPS

**Comment by 1hitsong** [comment]
We also need to know what Roku device you're using.

**Comment by cewert** [comment]
Fixed by #1651
