### ISSUE TITLE
Inconsistent Song Title, Track Number, & Audio Playback with Next Button

### ISSUE THREAD

**Issue by michaelcresswell** [jellyfin-archive/jellyfin-roku-legacy#1609]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0.0

## Describe the bug
Until album playback can be started at a chosen track (#1216), I sometimes start playback at the beginning of an album and skip ahead to the desired track. Occasionally, but not always, when I skip ahead many songs the song title, track number, and actual audio being played back do not match one another.

i.e. It may show the song title of track 6, say 5/12 for the track count, but actually be playing the audio of track 4.

## How To Reproduce
1. Go to a music library
2. Play an album with the Play Album button
3. Scroll to the next button ( i.e. >>| )
4. Click the next button several (5-10+) times, rapidly
5. Repeat if everything is correct

## Expected behavior
During music playback song title, track number, and audio playing should all be consistent.

## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? HTTP on Jellyfin, HTTPS via reverse proxy

## Additional context
The player seems to handle the invalid state smoothly.
i.e. The playback length not matching what is shown doesn’t cause issues, both when the actual playback is shorter or longer than the track length shown.

The next song played seems to be based on the track number, not the title or audio being played.

**Comment by 1hitsong** [comment]
Fixed by #1646
