### ISSUE TITLE
Cannot return to same item when returning to Home screen

### ISSUE THREAD

**Issue by thomabx** [jellyfin-archive/jellyfin-roku-legacy#162]
**Describe the bug**
Selected item does not launch when returning to the Home screen. Item is highlighted and Roku responds audibly to button press but does not launch next page.

**To Reproduce**
1. From home menu, select any item
2. Press back on remote
3. Press OK without selecting another item.

**Expected behavior**
Pressing OK should re-launch selected item.

**Comment by neilsb** [comment]
Reason for this is that it is watching for a change in the `SelectedItem`.  When you return to the home screen, the same item is selected so the event doesn't fire.   I tried added `alwaysNotify="true"`, but that didn't help.

I can think of a few ways round it, none of them particularly pretty though.

**Comment by neilsb** [comment]
Or alwaysNotify does work if I add it to the correct field...   Linked PR should solve it.
