### ISSUE TITLE
Playback pauses when turning off streamable subtitles (but not when turning them on!)

### ISSUE THREAD

**Issue by dathbe** [jellyfin-archive/jellyfin-roku-legacy#1628]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0.1 (2.0 build 1)

## Describe the bug

When watching a video and text (SRT) subtitles are turned on, the video playback continues uninterrupted.

But when the subtitles are then turned off again, the playback pauses for a second and then resumes--much like what happens when graphic subtitles are turned on/off and the server has to start or stop an transcode.

The app reports it is Direct Playing the video file when the subtitles are on and off.

## How To Reproduce

1. Play a movie with SRT subtitles
2. While watching the movie turn the subtitles on (using the up button options menu)
3. While still watching the movie, turn the subtitles off (same way)
4. Bug occurs

## Expected behavior

Playback should not be interrupted when turning on or off streamable subtitles

## Logs

N/A

## Screenshots

N/A

## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? HTTPS

## Additional context

This may be related to #1627 where the app seems to pick up SRT subtitles as graphical subtitles.

**Comment by ebits21** [comment]
I've noticed this as well.

**Comment by 1hitsong** [comment]
> This may be related to https://github.com/jellyfin/jellyfin-roku/issues/1627 where the app seems to pick up SRT subtitles as graphical subtitles.

It's def related. The stop/start occurs when we have to kick off a new content stream. We have code to only do that if the subtitles are not text.

Can you cut a 10 second sample of your file with the streams for me to test with? I've exhausted my subtitles test file and non exhibit this behavior.

**Comment by dathbe** [comment]
Sent you an invite to a private repository with a test file that is exhibiting the behavior on my setup.  File is called demo.mkv.

**Comment by 1hitsong** [comment]
File received. I'll check it out.

On a side note, I've seen this opening clip (and the rest of the movie) so many times I could recreate it frame by frame from memory. 😆

**Comment by 1hitsong** [comment]
I think I figured out the path to the bug.

**Comment by 1hitsong** [comment]
@dathbe If you can, please give this a try. It fixed the video stop/start when turning off text subtitles for me in my testing.

**Comment by dathbe** [comment]
Confirmed that PR #1632 fixes this issue for me.  I assume that neither 1632 nor 1633 incorporates the other because 1632 does not fix issue 1627 and 1633 does not fix this issue.  I imagine the next production release will include both, but I wanted to flag it in case not.

**Comment by 1hitsong** [comment]
Correct. PRs are self contained. These 2 bug fixes won't exist together until they get merged into the 2.0.x branch.

**Comment by 1hitsong** [comment]
Fixed by #1632
