### ISSUE TITLE
Home screen shows no media. Can only use search to find and play media

### ISSUE THREAD

**Issue by techninja025** [jellyfin-archive/jellyfin-roku-legacy#1631]
## Software Versions

- Jellyfin Server Version: 10.8.13 (Windows X64)
- Roku Client Version:  V2.0.1 (Roku Ultra 4800X) & V2.0.0 (43S515 7000X TCL TV)

## Describe the bug

Upon login (no matter the user permissions) no media shows on the home screen. The only way to play media is to press the "*"
 button and select search. You have to know what content you want to consume because you cant browse. I now use airplay from my iPod to listen to music more because this functionality has been broken for many months.

## How To Reproduce

1. Open the app
2. Login
3. Bug occurs

## Expected behavior

To see any UI with browsing options when logged in.

## Screenshots

![IMG_6372 731](https://github.com/jellyfin/jellyfin-roku/assets/95654573/7b334bc9-d4d0-4286-bc04-ac2d864994a1)

## Connection Information

- Is server local or remote? 
- Local
- Is server connection HTTP or HTTPS? 
- HTTP

**Comment by 1hitsong** [comment]
On the Roku, do you have the setting `User Interface / General / Use Web Client's Home Section Arrangement` enabled?

**Comment by techninja025** [comment]
I’ve tried both enabled and disabled with an app re-launch in between.
________________________________

**Comment by 1hitsong** [comment]
Can you post a pic of your Home Section settings on the server?

**Comment by techninja025** [comment]
Sorry for the delay. Dealing with snow removal. Here they are. Let me know if you'd like any more info!
![Screenshot 2024-01-11 171234](https://github.com/jellyfin/jellyfin-roku/assets/95654573/e924b3e3-47fb-48ae-b58b-6476d3e38ba4)
![Screenshot 2024-01-11 171354](https://github.com/jellyfin/jellyfin-roku/assets/95654573/a6348e3e-c2e5-4cac-93de-70806ab02f1b)
![Screenshot 2024-01-11 171411](https://github.com/jellyfin/jellyfin-roku/assets/95654573/ac7a0f7c-6f94-464a-a88d-add4b99b7570)

**Comment by cewert** [comment]
> "... this functionality has been broken for many months."

@techninja025 Did this work for you with version `1.6.6`? Did this ever work for you?

One thing you could try is reinstalling the app which will wipe all persistent data from the roku device. I don't expect this to fix your issue but it would rule a few things out.

**Comment by techninja025** [comment]
It worked before version 2.0.0. I deactivated my Jellyfin server when I was changing my network setup (power line networking went down when the A/C turned on summer 23’). I reinstalled the Roku app in December 2023 and it hasn’t worked since.

Cooper White
he/him/his
________________________________

**Comment by cewert** [comment]
So you uninstalled the roku app(v1.6.6), modified your network, reinstalled the roku app (v2.0.0), and the now the roku app is bugged. Do I have that right?

Can you sideload v1.6.6 to verify it still works correctly with your new setup? This would give you a way to use the app until the bug is fixed as well as help us narrow down the bug. There are instructions on our [readme under Beta Test](https://github.com/jellyfin/jellyfin-roku#beta-test) EDIT: use the [v1.6.6 zip](https://github.com/jellyfin/jellyfin-roku/releases/tag/v1.6.6) from the release page for step 2

**Comment by techninja025** [comment]
I didn’t explain that right. I’m still using power line networking to the server. The Roku has an Ethernet cable to the router. This setup worked and is the same from when the Jellyfin server was first deployed winter January of 23’. I just turned the Jellyfin off when only Wi-Fi worked on the server during the summer months. The only thing that ultimately changed is the Roku app version. The devices are all the same. I wish I could give you more info or logs but I don’t know how to find it. I may just stop using the Roku app because it’s a pain to use when the home screen is blank.

Cooper White
he/him/his
________________________________

**Comment by techninja025** [comment]
I’ve had no network connectivity problems between the server and the Roku. I’ve watched full movies no problem with continuous uninterrupted playback. When version 2.0.0 was installed back onto the Roku I only got a splash screen with the new features and fixes and it’s never shown a Home Screen since then.

Cooper White
he/him/his
________________________________

**Comment by Molecule5537** [comment]
I was also getting the same experience. Just realized that the users I created for each device didn't have access to the libraries.

**Comment by cewert** [comment]
> I was also getting the same experience. Just realized that the users I created for each device didn't have access to the libraries.

Seems like the most likely cause.

Please open a new issue if you are still experiencing this
