### ISSUE TITLE
roku crash log - HomeItem.brs(23)

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#1642]
```
'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/components/home/HomeItem.brs(23) 
```

Which points to this line of code https://github.com/jellyfin/jellyfin-roku/blob/master/components/home/HomeItem.bs#L25

This bug is happening a lot - 53 times so far just today.

**Comment by 1hitsong** [comment]
Fixed by #1645
