### ISSUE TITLE
Forced subtitles doesn't work.

### ISSUE THREAD

**Issue by Alliyance** [jellyfin-archive/jellyfin-roku-legacy#1648]
## Software Versions

- Jellyfin Server Version:
10.8.13  
- Roku Client Version:  
2.0.1
## Describe the bug

When Forced subtitles is present, the forced subtitles gets activated in the Jellyfin CC section but it doesn't appear on screen. By pressing Star on the remote, the closed captioning is turn to Off. 

## How To Reproduce

1. Play a movie with forced subtitles 
2. Press down arrow and up to CC, you'll see that Forced subtitles is on but doesn't work. 
3. Press star on remote, the Closed captioning should be On Always. 

## Logs

StreamBuilder.BuildVideoItem( Profile="Official Roku Client", Path="/home/alliyance/files/Movies/Killers.of.the.Flower.Moon.2023.mkv", AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/ae15ba1b-60b7-490a-afc8-ad5ef1e26eaa/stream.mkv?MediaSourceId=ae15ba1b60b7490aafc8ad5ef1e26eaa&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=e658c4bc8f90e2ca7b30c6e5a3a66f69"
[2024-01-13 14:26:01.665 +00:00] [INF] [191] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Roku" "2.0.1" playing "Killers of the Flower Moon". Stopped at "136000" ms
[2024-01-13 14:28:22.261 +00:00] [INF] [226] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:127.0.0.1" request
[2024-01-13 14:28:25.996 +00:00] [INF] [174] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was forbidden.

## Screenshots
None 
## Connection Information

- Is server local or remote?
- Is server connection HTTP or HTTPS?

**Comment by 1hitsong** [comment]
This is fixed by #1641 and will be fixed in 2.0.2. If after 2.0.2 the problem persists, please open a new ticket.

**Comment by Alliyance** [comment]
Made an error. I am using version 2.0.2 and this issue is still there.
