### ISSUE TITLE
Transcoding audio even though it is compatible.

### ISSUE THREAD

**Issue by rawkhopper** [jellyfin-archive/jellyfin-roku-legacy#1659]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0 build 2

## Describe the bug
I have a bunch of videos that have ac3 Dolby Digital 5.1.  They used to play fine with my system but now they are being reencoded and saying in AudioCodecNotSupported.

## How To Reproduce

1. Select movie with AC3 Dolby Digital
2. Choose 5.1 Audio if not default.
3. Play video.
4. Check Playback info and it says Transcoding Reason AudioCodecNotSupported

## Expected behavior
Direct Playing
The Source file is entirely compatible with this client and the session is receiving the file without modifications.

## Connection Information
Device is Roku Premiere+ 4630X

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? HTTP

**Comment by cewert** [comment]
Can you post the server and ffmpeg log so we can see the file information and what codec the file is being transcoded to?

**Comment by rawkhopper** [comment]
ffmpeg log:
[ffmpeg.txt](https://github.com/jellyfin/jellyfin-roku/files/13969801/ffmpeg.txt)

**Comment by rawkhopper** [comment]
server log:
[log.txt](https://github.com/jellyfin/jellyfin-roku/files/13969793/log.txt)

**Comment by rawkhopper** [comment]
Are the logs I added helpful?

**Comment by rawkhopper** [comment]
I am very confused.  I managed to go back to 1.6.6 and I am not able to get 5.1 audio working there either. I had it working a short time ago but am unable to figure out why it is not working now.  It does work with the AndroidTV app on my tv with the same setup.  If anyone has any ideas on what might be going on I would appreciate any advice.

**Comment by rawkhopper** [comment]
I found the problem!  My fault! Apparently my Roku was in “Levelling” mode which seems to tell the server that it does not support 5.1.
