### ISSUE TITLE
Recent update no longer supports certain codecs

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#1663]
## Software Versions

- Jellyfin Server Version: 10.8.13
- Roku Client Version:  2.0.2

## Describe the bug
Certain video codecs are no longer supported in the Roku Jellyfin Client. This seemed to happen in the transition from v1.6.6 to v2.0.2. The codec I am having trouble with is `V_MPEGH/ISO/HEVC` and the container is matrsoka (mkv). I have other mkv files that work fine but are using `V_MPEG2`, so I am leaning towards this being playback of this codec.

## How To Reproduce

1. Play any file with `V_MPEGH/ISO/HEVC` codec
2. Jellyfin exits playback immediately and returns to home screen

## Additional context
I sideloaded v1.6.6 and am able to playback the files so I can confirm this was previously working

**Comment by cewert** [comment]
Please provide server logs from the failed attempt with 2.0.2 and also of the file working with 1.6.6

**Comment by michaelcresswell** [comment]
I created a test file locally with `V_MPEGH/ISO/HEVC` encoding in a `Matroska` container and it direct played on both 1.6.6 and 2.0.2 so hopefully the server logs from each from @sanoti5896 will help identify the problem

**Comment by ghost** [comment]
@cewert is there a good way to look through the logs besides [this guide](https://github.com/jellyfin/jellyfin-roku/blob/master/docs/DEVGUIDE.md#bugcrash-reports)? I have the jellyfin server running in a Docker container

**Comment by cewert** [comment]
@sanoti5896 the easiest way is to use the web client. Login with an admin user, open the admin dashboard, then click Logs in the left menu. You will see an ffmpeg log for every transcode as well as at least one main "log". If you click on one it will open in a new tab.

The main log will show debugging info for the server as well as the API request sent from the roku client. The ffmpeg log will show the original file information as well as file info for the new transcoded file.

![webclient-logs](https://github.com/jellyfin/jellyfin-roku/assets/16514652/a9b76000-2c01-4882-b999-bba6d84bb86f)

**Comment by ghost** [comment]
@cewert thanks so much for the detailed instructions I didn't realize Jellyfin makes getting logs so easy! based on the errors I am now leaning towards the subtitle codec being the issue.

here is the log for when the video plays correctly on v1.6.6:
```log
[INF] [217] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="video.mkv", AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "video.mkv?MediaSourceId=123hash&Static=true&VideoCodec=hevc&AudioCodec=opus&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=456hash"
```

and here is the one for when it fails on v2.0.2 and includes the param `TranscodeReasons=SubtitleCodecNotSupported`
```log
[INF] [155] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Official Roku Client", Path="video.mkv", AudioStreamIndex=1, SubtitleStreamIndex=3 ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) "videohash123/master.m3u8?MediaSourceId=mediahash123&VideoCodec=hevc,h264,h264,hevc&AudioCodec=eac3,aac,mp3&AudioStreamIndex=1&SubtitleStreamIndex=3&VideoBitrate=40000000&AudioBitrate=640000&MaxFramerate=23.976025&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=8&RequireAvc=false&Tag=taghash123&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-rangetype=SDR,HDR10,HLG&TranscodeReasons=SubtitleCodecNotSupported"

[INF] [3] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -threads 1 -autorotate 0 -i file:\"video.mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:0 -codec:v:0 hevc_nvenc -tag:v:0 hvc1 -preset p1 -b:v 3471090 -maxrate 3471090 -bufsize 6942180 -profile:v:0 main -g:v:0 72 -keyint_min:v:0 72 -filter_complex \"alphasrc=s=1920x1080:r=10:start='0',format=yuva420p,subtitles=f='video.mkv':si=0:alpha=1:sub2video=1:fontsdir='/config/cache/attachments/mediahash123',hwupload=derive_device=cuda[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=format=yuv420p[main];[main][sub]overlay_cuda=eof_action=endall:shortest=1:repeatlast=0\" -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/config/data/transcodes/transcodehash123%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/config/data/transcodes/transcodehash123.m3u8\""

[ERR] [3] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[ERR] [220] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/videohash123/hls1/main/0.ts".

MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment...
```

here is what I get when I run `ffmpeg -i video.mkv` and look for the subtitle metadata:
```log
  Stream #0:3(eng): Subtitle: en (default)
    Metadata:
      title           : Subtitles
      BPS             : 698
      DURATION        : 00:23:36.790000000
      NUMBER_OF_FRAMES: 996
      NUMBER_OF_BYTES : 123756
      _STATISTICS_WRITING_APP: mkvpropedit 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-01 01:01:01
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

let me know if I can help debug in any other way! appreciate the quick responses

**Comment by cewert** [comment]
@sanoti5896 I agree the subtitles caused the transcode.

Can you post the subtitle info that's displayed in the web client when clicking the 3 dot menu and selecting "Media Info"? It will look something like this:

![subtitle-medie-info](https://github.com/jellyfin/jellyfin-roku/assets/16514652/00befae8-42ab-4f57-ac17-9fa4b9748991)

**Comment by ghost** [comment]
@cewert I promise I'm not trolling with this one, this is the actual metadata:
![subtitle](https://github.com/jellyfin/jellyfin-roku/assets/124461176/342669cd-3fea-406b-b3c7-1f08b40aa278)
I take it this codec is an acronym "All Signs & Songs". 

do you recommend I try to edit the mkv to try to get the subtitle to be `Default: No`? any recommendations on software/packages to do that?

**Comment by ghost** [comment]
Ok I think I figured out how to band-aid fix this for now. I downloaded [MKVToolNix](https://mkvtoolnix.download/downloads.html) which can also be installed via Homebrew (`brew install mkvtoolnix`). It provides `mkvinfo input.mkv` to check which subtitle tracks you need to edit. [Example #2](https://mkvtoolnix.download/doc/mkvpropedit.html#mkvpropedit.examples) in this list has the following command:

```shell
mkvpropedit input.mkv --edit track:s1 --set flag-default=0 --edit track:s2 --set flag-default=0
```

[This blog post](https://www.flynsarmy.com/2012/01/change-default-languge-subtitles-in-mkv-files/) describes how you can do that in bulk:

```shell
find . -name "*.mkv" -exec mkvpropedit {} --edit track:s1 --set flag-default=0 --edit track:s2 --set flag-default=0 \;
```

This was the subtitle codec information from `mkvinfo input.mkv` that caused issues:

```
| + Track
|  + Track number: 4 (track ID for mkvmerge & mkvextract: 3)
|  + Track type: subtitles
|  + "Lacing" flag: 0
|  + Codec ID: S_TEXT/ASS
|  + Codec's private data: size 1643
|  + Language (IETF BCP 47): en
|  + Name: Signs and Songs
```

Once I ran the above scripts re-running info on it gave me the flag `+ "Default track" flag: 0` which now runs on the latest version of Jellyfin. Thanks again for all your help on this issue and great stuff with this application.

**Comment by cewert** [comment]
Thank you for the update!

So your file has a default subtitle track with ASS subtitles and it plays on 1.6.6 but not on 2.0.2 is that correct? If so, does the file crash with 1.6.6 when you enable the ASS subtitles? And are you able to view the ASS subtitles on 2.0.2 after you removed the default flag from the subtitle track?

**Comment by ghost** [comment]
>file has a default subtitle track with ASS subtitles and it plays on 1.6.6 but not on 2.0.2

@cewert yes that is correct

>does the file crash with 1.6.6 when you enable the ASS subtitles

Nope, it seems like 1.6.6 was able to handle them for some reason

>are you able to view the ASS subtitles on 2.0.2 after you removed the default flag from the subtitle track

No, unfortunately it still crashes even when clicking CC -> Signs and Songs (English). This is with the Roku setting (*) [Captions Mode Off](https://support.roku.com/article/208756848). A weird side effect is when I change this setting to `On Always` it will try to display the signs with the Roku built-in black background/white text
