### ISSUE TITLE
Sign in screen broken 

### ISSUE THREAD

**Issue by lpukatch** [jellyfin-archive/jellyfin-roku-legacy#167]
**Describe the bug**
User variable in ShowScenes.brs uninitialized for me.

**Logs**
Use of uninitialized variable. (runtime error &he9) in pkg:/source/ShowScenes.brs(114)
114:   username_field.value = user
Backtrace:
#2  Function createsigningroup(user As Dynamic) As Dynamic
   file/line: pkg:/source/ShowScenes.brs(114)
#1  Function loginflow() As Boolean
   file/line: pkg:/source/Main.brs(407)
#0  Function main() As Void
   file/line: pkg:/source/Main.brs(22)
Local Variables:

**Comment by thomabx** [comment]
Did #165 fix your issue?

**Comment by lpukatch** [comment]
No it did not. I recently switched over servers so I was not connected when I pushed this new version that originally broke, so I might also be in a modified state.

It looks like line 407 in Main.brs is calling     passwordEntry = CreateSigninGroup(user) but in my case the user isn't initialized and when It goes into the function it doesn't turn it into the default "".

**Comment by thomabx** [comment]
It looks like the issue is with no publicly listed users. I hadn't tested this. I marked all my users hidden and was able to reproduce this. Does #168 fix this for you?
