### ISSUE TITLE
Movies/TV Show dont start (need to try 4-5 times to start)

### ISSUE THREAD

**Issue by PerkyZZ999** [jellyfin-archive/jellyfin-roku-legacy#1690]
## Software Versions

- Jellyfin Server Version:  latest
- Roku Client Version:  2.0.2 (latest)

## Describe the bug

When starting a movie or tv show i got black screen that freeze and client crashes after 10 secs.. After retry 4-5 times it finally start the movie and its all good. Wasnt doing this before roku client 2.0.2 (new year update).

## How To Reproduce

Start your Jellyfin app on your Roku TV.
Browse to your movie
Play your movie.

## Expected behavior
My movie/tvshow to start normally like before and not have to try 5 times to have it play lol.

## Logs
No logs error

## Screenshots
Dont have sorry

## Connection Information

- Is server local or remote? Local Server
- Is server connection HTTP or HTTPS? HTTP connection

**Comment by 1hitsong** [comment]
This reads more like a troubleshooting request than a bug ticket. I suggest posting this to the troubleshooting forum. You'll need to include more info than you did here. What Roku device? What are the video file details? etc.

https://forum.jellyfin.org/f-troubleshooting

**Comment by PerkyZZ999** [comment]
> This reads more like a troubleshooting request than a bug ticket. I suggest posting this to the troubleshooting forum. You'll need to include more info than you did here. What Roku device? What are the video file details? etc.
> 
> https://forum.jellyfin.org/f-troubleshooting

Its not a troubleshooting issue man , i didnt change anything and it was all working good before the build 2 of the client on roku ....

**Comment by PerkyZZ999** [comment]
I might try reinstalling everything tomorrow if I have the time but i didnt change anything on my jellyfin server nor my files ... The client got updated on my roku tv and after that the issue appeared... That should be a bug.. anyway ill troubleshoot myself and if i got it working fine ill comeback to say it was that but im pretty sure it isnt.. thanks!
