### ISSUE TITLE
Next episode timer appears when there isn't another episode

### ISSUE THREAD

**Issue by hdevine825** [jellyfin-archive/jellyfin-roku-legacy#1717]
## Software Versions

- Jellyfin Server Version:  10.8.8
- Roku Client Version:  2.0.4

## Describe the bug

When watching the last episode of a TV Show the next episode countdown appears even though there isn't a next episode. One the timer reaches zero playback ends and you are returned to the home screen of the Jellyfin app.

## How To Reproduce

1. Play the end of the final episode of a show 
2. Timer appears
3. Once expired you are returned to the home screen

## Expected behavior

No timer appears or a timer with a different message.

**Comment by 1hitsong** [comment]
I broke this logic in #1375

**Comment by 1hitsong** [comment]
Fixed by #1718
