### ISSUE TITLE
Use subtitle mode from user preferences to decide to play subtitles

### ISSUE THREAD

**Issue by thomabx** [jellyfin-archive/jellyfin-roku-legacy#172]
**Is your feature request related to a problem? Please describe.**
Currently, only Roku's closed caption settings are used to decide if subtitles are displayed.

**Describe the solution you'd like**
Get user's preference from server and use to determine setting at start of playback. Still allow selection of subtitle track during playback.

**Additional context**
User preferences from the server are:
- Default: Subtitles are loaded based on the default and forced flags in the embedded metadata. Language preferences are considered when multiple options are available.
- Smart: Subtitles matching the language preference will be loaded when the audio is in a foreign language.
- Only forced subtitles - Only subtitles marked as forced will be loaded.
- Always play subtitles - Subtitles matching the language preference will be loaded regardless of the audio language.
- No subtitles: Subtitles will not be loaded by default. They can still be turned on manually during playback.

The Roku has settings for "On mute", "On", and "Off" that are already coded. "On replay" is another setting that is not implemented. I am not sure how best to mix both of these settings when they are in conflict. I lean towards starting with the server's user preferences and then follow the Roku's settings. For example: if the user preference is set to always on, the Roku is set to "On Mute" and the Roku is not muted, we would not display subtitles.

**Comment by anthonylavado** [comment]
@thomabx I agree with that direction. The options on the user profile have to be specifically selected, but then the Roku will have different controls that are best suited for it's platform.
