### ISSUE TITLE
"Next Episode" Button Not Appearing

### ISSUE THREAD

**Issue by dathbe** [jellyfin-archive/jellyfin-roku-legacy#1722]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0 build 3

## Describe the bug
"Next Episode" button is not appearing at the end of tv shows, even though I have settings to have it displayed 60 seconds before the end of an episode.  I suspect this is user error and/or a settings issue on my end, but I can't figure out what is wrong.  

Is there another setting either in the app or on the server that I need to check/set to make this work?  I see issue #1099 where it mentions a "Play next episode automatically" setting on the server.  But I can't even find that setting, so I don't know if it still exists in the current version of the software.  (And, in any event, playing the next episode automatically and having a button pop up to ask if I want to play the next episode are two entirely different things; so I don't think the button should be hidden just because I don't want automatic play.)  

## How To Reproduce

1. Make sure "Settings>Playback>Next Episode Button Time" is set to a reasonable number
2. Play a tv show with multiple episodes
3. Nothing happens at the end

## Expected behavior

Button should pop up at the end of an episode to ask if I want to play the next episode.

## Logs

I'm not seeing anything relevant in my logs, but that may be because I don't know what I should be looking for.

## Screenshots

N/A

## Connection Information

- Is server local or remote? Both
- Is server connection HTTP or HTTPS? Both (https to proxy, http proxy to server)

## Additional context

N/A

**Comment by 1hitsong** [comment]
@dathbe Try testing against the 2.0.x patch branch. I just pushed a fix for the Next Episode button and it may have impact on what you're seeing.

ref: https://github.com/jellyfin/jellyfin-roku/pull/1718

**Comment by dathbe** [comment]
#1718 is actually the fix that I noticed in the 2.0.5 change log that reminded me this feature exists and that I don't see it on my setup.  I sideloaded the artifact here https://github.com/jellyfin/jellyfin-roku/actions/runs/7967104568, but it did not give me the button.  I don't recall ever seeing the button, so it's not something that has gone away with recent updates.

**Comment by 1hitsong** [comment]
On the server, click the avatar - top right.
Click Playback.
Scroll down, is `Play next episode automatically` checked?

![image](https://github.com/jellyfin/jellyfin-roku/assets/3330318/d18f9481-57ea-4552-9fcf-1c580189ffbe)

**Comment by dathbe** [comment]
That was it.  Seem incongruent to require "play next episode automatically" in order to display the "play next episode" button that takes a manual click.
