### ISSUE TITLE
Add Trailer Button for Movies

### ISSUE THREAD

**Issue by xthekrakenx** [jellyfin-archive/jellyfin-roku-legacy#1724]
## Is your feature request related to a problem? Please describe
No problem - the functionality looks like it already exists in the web version of Jellyfin.

## Describe the solution you'd like
I would like a "Trailer" button when viewing the details of a movie. I have provided a screenshot for an example of the trailer button in the web interface:

https://ibb.co/CPC2KGb

## Describe alternatives you've considered
Nothing native within the Jellyfin Roku app that I have been able to think of to date.

## Additional context
n/a

**Comment by 1hitsong** [comment]
The Roku client supports local trailers - see reference video below. You need to have them properly named according to the naming guidelines so the server picks it up. https://jellyfin.org/docs/general/server/media/movies/#extras-folders

If you're referring to external trailers from YouTube, we can't support it. It's against their terms of service for us to attempt to load YouTube content inside our client so the only method we would have to play them would be to close Jellyfin and open the trailer in the YouTube app - where there would be no method to quickly return back to Jellyfin.

https://github.com/jellyfin/jellyfin-roku/assets/3330318/3b9c852b-6ce7-4c64-9e5c-383098d71612

**Comment by xthekrakenx** [comment]
> The Roku client supports local trailers - see reference video below. You need to have them properly named according to the naming guidelines so the server picks it up. https://jellyfin.org/docs/general/server/media/movies/#extras-folders
> 
> If you're referring to external trailers from YouTube, we can't support it. It's against their terms of service for us to attempt to load YouTube content inside our client so the only method we would have to play them would be to close Jellyfin and open the trailer in the YouTube app - where there would be no method to quickly return back to Jellyfin.
> 
>  trailer.mp4

Gotcha - yes youtube is what I was referring to. Thank you very much for the info on the extras folders! :)
