### ISSUE TITLE
Clicking Set Watched button doesn't set resume point back to 0

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1750]
## Software Versions

- Jellyfin Server Version:  Latest
- Roku Client Version:  Latest

## Describe the bug
Selecting the Set Watched button doesn't set the resume point back to 0.

## How To Reproduce

1. Go to movie that is in a resumeable state
2. Click on Set Watched
3. Click play button
4. Resume popup will appear

## Expected behavior
Movie would start to play from the beginning

**Comment by cewert** [comment]
Fixed by #1826
