### ISSUE TITLE
unofficial roku app with intro skipper support 

### ISSUE THREAD

**Issue by the-math-god** [jellyfin-archive/jellyfin-roku-legacy#1752]
## Describe the feature you'd like

hi i know you guys don't want to code your official app to use 3rd party plugins
so could you make an unofficial app like 
https://github.com/asymworks/jellyfin-roku/tree/introskipper
or like the tizen app i made https://github.com/The-Math-God/jellyfin-tizen-builds-with-intro-skipper-support
but for the latest version so we can atleast have an unofficial solution 
## Additional context

hell why not add an unoffcial plugin setting like with the jellyfin media player for windows/linux

**Comment by the-math-god** [comment]
also why can't you use 3rd plugins with the official roku app

**Comment by 1hitsong** [comment]
This is the repo for the official client. If you want to create a 3rd party client with 3rd party plugin support, please feel free.

>also why can't you use 3rd plugins with the official roku app

We already told you in the chat, but I'll report here for others.

> Plugins are 100% out of our control. Their authors can change them however they please whenever they please. If we make our client dependent on their plugin for functionality, then we no longer have full control over our own client.The plugin author can break our app by making changes to the plugin and we wouldn't know until someone noticed. They can turn our app into a tracker by injecting unwanted calls and we wouldn't know until someone noticed.
> 
> Or as Cody showed, they could archive their plugin, and we're stuck with old/dead code in our client. So we must play catch up every time a plugin is deprecated. And what if there are multiple plugin options for a function? How do we program it to work with all of them since different users would want different plugins?
> It's just too much crap. Our client uses our API from our code from our server. Remove as many variables as possible.
> 
> 3rd party clients can do whatever they want.
