### ISSUE TITLE
Deep red color/tint on Roku Streaming Stick 4K for some H.265 videos

### ISSUE THREAD

**Issue by AArnott** [jellyfin-archive/jellyfin-roku-legacy#1754]
#569 was closed, so opening a new ticket.

It turns out this is still a problem. I still frequently see red tint on H.265 encoded videos, but only when played through the Roku.

_Originally posted by @AArnott in https://github.com/jellyfin/jellyfin-roku/issues/569#issuecomment-1957827228_

**Comment by Alliyance** [comment]
Reason why I still use H264.

**Comment by AArnott** [comment]
Sadly, I discovered this after encoding most of my videos with H.265 and deleting the raw rip files. :(
I'm interested in competing products (I'm thinking it's a Roku bug) that don't have this bug as I'd sooner switch to that than re-rip and re-encode all my movies.

**Comment by ChrisRosser** [comment]
Is this related to broken DoVi support? That can give purple/green tint to video.
