### ISSUE TITLE
Movie extras - allow "Play Trailer" to play a trailer from Youtube when no trailer file/folder is present.

### ISSUE THREAD

**Issue by Mr-Generic123** [jellyfin-archive/jellyfin-roku-legacy#1761]
## Is your feature request related to a problem? Please describe

When you have a folder/file for a trailer, I can see the trailer when I select "Play Trailer".  This works fine.
However, when there is no trailer folder/file, the "Play Trailer" option is not visible.  
When there is no trailer folder/file, the Jellyfin web client still displays a trailer button and, when clicked, plays a trailer from YouTube.

## Describe the solution you'd like

It would be nice to be able to play a trailer from Youtube, the same way the Jellyfin web client does.

**Comment by 1hitsong** [comment]
We have no method to do this. We can't embed YouTube videos directly in our client as that breaks their Terms of Service. The only way to do this would be to kick you out of Jellyfin and into the YouTube app where there would be no easy way to return to Jellyfin.

**Comment by Mr-Generic123** [comment]
> We have no method to do this. We can't embed YouTube videos directly in our client as that breaks their Terms of Service. The only way to do this would be to kick you out of Jellyfin and into the YouTube app where there would be no easy way to return to Jellyfin.

I understand.
Thanks for the reply.
