### ISSUE TITLE
Deselect Alpha Picker

### ISSUE THREAD

**Issue by InfamousStarFox** [jellyfin-archive/jellyfin-roku-legacy#1767]
## Is your feature request related to a problem? Please describe
Currently the alpha picker can be used to filter by a character, such as `A-Z`. However unlike web version, clicking the same letter a second time does not clear the selection.

## Describe the solution you'd like
It would be nice if, clicking the selected character in the alpha picker, would deselect the selection and allow for scrolling through the unfiltered library again

**Comment by cewert** [comment]
It still needs work but I implemented this feature in https://github.com/jellyfin/jellyfin-roku/pull/1539
