### ISSUE TITLE
Private Channel Release

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#177]
Hey team, looking at the state of the app on our test Roku Streaming Stick+, I think we should probably release it as a private channel for people to load and test with. This technically bypasses Roku certification, so we don’t have to worry about hitting all those markers in #122 just yet.

Any comments, thoughts?

**Comment by anthonylavado** [comment]
Tagging for feedback, @cewert @bisby

**Comment by PabloHuerfano** [comment]
I would just like to say that I support the use of the private channel. I would love to become part of the development of the Roku Channel and feel as though a private channel would make any bug report and updates more streamline.

**Comment by sumppump** [comment]
Any luck on getting live tv to work?

**Comment by cewert** [comment]
Sounds good to me.

@sumppump As far as I know, no one has ever attempted to get live tv working.

**Comment by sumppump** [comment]
@cewert I run a Server that uses Emby Currently and we Jellyfin on a test server, customers want to be able to run Jelly on roku which i have tested and played with. Only draw back is livetv is not working as you said, no attempt made to get it to work. 

I have investigated the older Roku Emby sourcecode that our live tv works on and i have yet to crack into implementing it into this code.

Link here - https://github.com/MediaBrowser/Emby.Roku

You Guys have done a Fantastic JOB! My partner and I would love to be able to ditch EMBY all together once us or someone gets livetv up and running.

**Comment by anthonylavado** [comment]
@sumppump I wouldn’t study the old one too closely. This app essentially had to be written from the ground up because the older code isn’t accepted by Roku anymore. That’s why the Roku Client has taken some time to develop.

**Comment by sumppump** [comment]
I am too green and do not have enough time to give a competent hand

**Comment by dkanada** [comment]
It actually might be useful, because the live TV code was likely not impacted that much from all the changes as mostly hidden logic.

**Comment by ghost** [comment]
> Hey team, looking at the state of the app on our test Roku Streaming Stick+, I think we should probably release it as a private channel for people to load and test with. This technically bypasses Roku certification, so we don’t have to worry about hitting all those markers in #122 just yet.
> 
> Any comments, thoughts?

I think this is a great idea. I also believe that by releasing to the private channel, this git will  see an influx of users, slowly, that will try to better shape future releases.

**Comment by Alcatraz077** [comment]
I agree, I think we should release it as a private channel.

**Comment by anthonylavado** [comment]
One of the problems with releasing it as a private channel, is that you wouldn’t get upgraded to the store release once it’s available.

Roku explicitly calls out avoiding building an audience with a private channel for this reason. It would really suck to get bug reports for people using outdated software once we ship it properly :-(

**Comment by bisby** [comment]
We could put it on the private channel branded as "Jellyfin Beta" and continue making "uncertain" releases to that channel even after we add a public channel. And then begin rejecting any issues or bug reports that dont list when channel they are on.

And I would imagine we could also use a build service to inject a "BETA" logo into the overhang in the app, to make it even more apparent.

**Comment by ghost** [comment]
> One of the problems with releasing it as a private channel, is that you wouldn’t get upgraded to the store release once it’s available.
> 
> Roku explicitly calls out avoiding building an audience with a private channel for this reason. It would really suck to get bug reports for people using outdated software once we ship it properly :-(

Is it possible to copy emby on that to bypass it? I believe if you create a "beta" version for private and keep an offical version you would be good to go. 

Edit: See Emby's sidebar? [https://emby.media/emby-for-roku.html](url)

**Comment by ddurdle** [comment]
You could still somehow manually update via a private channel, no?

**Comment by ddurdle** [comment]
I have lots of various roku devices I can test on (3 tvs, 3 sticks, 1 box)

**Comment by anthonylavado** [comment]
I like the beta idea.

Also, we have hardware to test with, so that’s not a worry. It’s just that for store publishing, Roku is gonna hold us to certain goals (speed, UI, etc).

This is just a way to try and get all the remaining “I need Roku” users over now.

I just want to avoid people staying on the beta and then never switching over to a proper release, but I realize that’s also a communication problem (my fault).

**Comment by neilsb** [comment]
We can easily have an (obnoxious?) "This is the beta version" message displayed above the library list on the home page or something, to encourage normal users to switch.

Could even let them turn the message off in the settings, but it comes back with each update to the channel or something.

**Comment by cewert** [comment]
> I just want to avoid people staying on the beta and then never switching over to a proper release, but I realize that’s also a communication problem (my fault).

@anthonylavado Couldn't we just force an update to the private(beta) channel disabling all functionality with a message that says "To continue using Jellyfin search for the "jellyfin" channel on your Roku or go to this URL"?

**Comment by anthonylavado** [comment]
> @anthonylavado Couldn't we just force an update to the private(beta) channel disabling all functionality with a message that says "To continue using Jellyfin search for the "jellyfin" channel on your Roku or go to this URL"?

@Cewert This is also true. Will make plans for the private channel then.

**Comment by anthonylavado** [comment]
I've gone ahead and done this without the artwork for now.


https://my.roku.com/add/jellyfinbeta

Enjoy.

Please check back eventually so you can get on the actual release when it's available. We can't switch you over like on other platforms.
