### ISSUE TITLE
distorted/stretched profile pictures when non native format

### ISSUE THREAD

**Issue by BotBlake** [jellyfin-archive/jellyfin-roku-legacy#1780]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0.5 (Feb 21, 2024)

## Describe the bug

When using a non natively fitting format for the Profile picture, Jellyfin Roku stretches them to fit.
Since Jellyfin Web Crops the Image excess instead of stretching it, this is unexpected behaviour.
The pictures then look "correct" on almost every client, but "wrong" on the Roku.

_I am not sure if it might be a good option to let the Server handle the image cropping in the first place though.
Then the user could decide which part should be cropped.
But I will leave this open, as I have no Idea._

## How To Reproduce

1. Set a Profile Picture that doesnt fit natively into the square profile pictures (e.g. 16:9 - 1920:1080)
2. Make sure that Profile is visible on the Login Screen
3. Open the Login Screen on Roku
4. You now notice that the Picture is stretched  <-- "bug"

## Expected behavior

Since Jellyfin Web cuts off the excess of the image, it is expected that Jellyfin Roku also does so.
By not doing that it looks "unexpected", when using a non-native Picture format.

## Logs

Since my Roku is not in Dev Mode, I did not include Logs.
If you do need logs feel free to ask me and And I will do what is necessary to attach the logs.

## Screenshots

This here is Jellyfin Web, dealing with different formats of pictures ("Test 2" being 16:9 - 1920:1080)
![Jellyfin Web Login](https://github.com/jellyfin/jellyfin-roku/assets/94436780/d4e5908a-9b06-4a0a-b367-b641592b941b)
And this is Jellyfin Roku Behaviour:
![Jellyfin Roku Login](https://github.com/jellyfin/jellyfin-roku/assets/94436780/f9f4eba6-beb6-44ad-ab1e-e98b25df5acb)

## Connection Information

- Is server local or remote? : Doesnt matter for this to orccur. I tried both Local and Remotely
- Is server connection HTTP or HTTPS? : Also doesnt matter. I tried local http and remote https.

**Comment by cewert** [comment]
Fixed by #1782
