### ISSUE TITLE
Allow sorting movies by more than just name

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#1781]
I really want to be able to sort my movies by Date Added. I can do this on Web, Fire Stick, etc. But not Roku. I am on latest self-hosted Jellyfin (Debian / Raspberry Pi) and an up-to-date Roku Ultra.

**Comment by ghost** [comment]
I should mention also that no filters are available for me.

**Comment by cewert** [comment]
This is already possible. It sounds like your server may be bugged.

![jfroku-movie-sort-options](https://github.com/jellyfin/jellyfin-roku/assets/16514652/30f13707-624a-46e9-8997-32ad5d230492)

**Comment by cewert** [comment]
Were you able to get this working? Please reopen if you still need help
