### ISSUE TITLE
Dev Client unresponsive when Closing an Actor Card

### ISSUE THREAD

**Issue by BotBlake** [jellyfin-archive/jellyfin-roku-legacy#1786]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  Manual Build of [2.0.z Branch](https://github.com/jellyfin/jellyfin-roku/tree/2.0.z)

## Describe the bug

Opening the "Cast & Crew" section works fine. Opening Person Details - so the Actor Card - it also works.
As soon as you press the "back" button on the remote (I use the Roku App as Remote - maybe that makes a difference idk) the client freezes and will not respond.
The only option is to press the home button and reopen the client.

## How To Reproduce

1. Build & Write 2.0.z on the roku - (I have done via VSCode Extension)
2. Open a Movies "Cast&Crew" section
3. Click on an Actor/Crewmember 
4. Press the Back button
4. Client is now unresponsive <- Bug

## Expected behavior

The client should continue working properly after closing the Actor Card.

## Logs

```
PostTask Started - Posting array to /Sessions/Capabilities/Full
event.Mode =    Instant replay
event.Mute =    false
04-26 22:01:23.569 [beacon.signal] |AppLaunchComplete ---------> Pending Render Pass
04-26 22:01:23.598 [beacon.signal] |AppLaunchComplete ---------> Duration(8230 ms), DialogTime(4032 ms)
PostTask Finished.  Response = 204
WARN /c:/Users/Simon/Documents/Software_Development/Testi/jellyfin-roku/components/home/HomeItem.bs(313) Unhandled Home Item Type AudioBook       
BrightScript Micro Debugger.
Enter any BrightScript statement, debug commands, or HELP.
Suspending threads...
Thread selected:  1*   ...ents/manager/QueueManager.brs(242)      m.queue[0].startingPoint = positionTicks
Current Function:
241:  sub setTopStartingPoint(positionTicks)
242:*     m.queue[0].startingPoint = positionTicks
243:  end sub
Source Digest(s): 
pkg:    dev 2.0.6 77892b4f Jellyfin
pkg: 632126 1.0.2 ff28787e libplayready
Invalid value for left-side of expression. (runtime error &he4) in pkg:/components/manager/QueueManager.brs(242)
Backtrace:
#0  Function settopstartingpoint(positionticks As Dynamic) As Void
   file/line: pkg:/components/manager/QueueManager.brs(243)
Local Variables:
positionticks    roInt refcnt=2 val:0 (&h0)
global           Interface:ifGlobal
m                roAssociativeArray refcnt=2 count:10
Threads:
ID    Location                                Source Code
 0[u] pkg:/source/Main.brs(1)                 subMain(args as dynamic) as void
 1*   ...ents/manager/QueueManager.brs(242)      m.queue[0].startingPoint = positionTicks
  *selected   [u]unattached(not debuggable)
Brightscript Debugger> 
Can't continue
```

## Connection Information

- Is server local or remote? remote
- Is server connection HTTP or HTTPS? https

## Additional context

Does only occur on the Dev branch, not on the stable one.

**Comment by cewert** [comment]
Fixed by #1787
