### ISSUE TITLE
Beta Artwork and Text

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#179]
As part of #177, we should create artwork for the channel that has a “Beta” label/banner, so that we can create a private channel release.

At the same time, if there is any opportunity to add a label on screen, we should do that as well.

**Comment by cewert** [comment]
These are the images we need to replace:

images/logo.png
images/channel-poster_fhd.png
images/channel-poster_hd.png
images/channel-poster_sd.png
images/splash-screen_fhd.jpg
images/splash-screen_hd.jpg
images/splash-screen_sd.jpg

@bisby image script should take care of the last 6 so we'd only need to recreate the logo

**Comment by ghost** [comment]
Could you do something like: https://imgur.com/a/8kSSYSZ

You have to download the image to see the text since it's black. I think I new logo might distinguish it from the release schedule...thoughts?

**Comment by Alcatraz077** [comment]
I think it looks good, personally.
