### ISSUE TITLE
Critical audio / language support completely missing from TV shows

### ISSUE THREAD

**Issue by Ferynix** [jellyfin-archive/jellyfin-roku-legacy#1797]
## Software Versions

- Jellyfin Server Version:  10.8.10
- Roku Client Version: 20.0.7

## Describe the bug
The normal audio selector / dropdown is completely inaccessible on TV shows... Meaning all animes and non-english shows are unwatchable without subs. In the player itself, there is a button to select captions but no way to change the audio? This seems like a very core feature thats completely missing / broken for some reason. 

Ive had to resort to using airplay to watch animes on my TV, and its super glitchy / buggy / barely functions most of the time... So it would be nice if it behaved normally on the app itself

## How To Reproduce
Click a TV show in the menu, notice the selectors for audio and subtitles are completely missing. (yet are visible on movie preview pages)

Also play a TV show, notice that the subtitle button shows up, but theres no button for audio selection.

## Expected behavior
There should be an audio selector inside the player itself, but at the very least, copy the audio selector from the movie preview over... because otherwise theres literally no way to change the audio language

**Comment by cewert** [comment]
Hit star on an episode in the episode list view

**Comment by Ferynix** [comment]
goddamn Ive been struggling to watch shows and its been that simple this whole time? man wtf... that aint right

**Comment by jimdogx** [comment]
Yeah I added this back in 2022 (https://github.com/jellyfin/jellyfin-roku/pull/575) ... unfortunately at the time I couldn't think of a clever way to make it obvious you had to hit "\*".... but since "\*" is used elsewhere in the app for "options" I hoped it would be semi-intuitive.

I'm assuming this issue can now be closed.

**Comment by Ferynix** [comment]
> Yeah I added this back in 2022 (https://github.com/jellyfin/jellyfin-roku/pull/575) ... unfortunately at the time I couldn't think of a clever way to make it obvious you had to hit "\*".... but since "\*" is used elsewhere in the app for "options" I hoped it would be semi-intuitive.
> 
> 
> 
> I'm assuming this issue can now be closed.

Well, it's not really about intuitive / not intuitive, the star selector only worked if you manually went all the way to the show, selected the season, and scrolled down, and selected star for every single episode as you watch them

It wasn't intuitive and it couldn't be accessed unless you manually selected each episode, which means that it couldn't be used for "continue watching", "up next", or if you were just inside an episode and wanted to change the language

**Comment by jimdogx** [comment]
Agreed.  With all of the following changes:

* Hit "\*" while on the show list
* The new OSD on v2.1.x that allows you to change audio while playing
* Respecting the user's audio preference (as set via the web client)

I believe it's a lot better now.

**Comment by Ferynix** [comment]
> Agreed. With all of the following changes:
> 
>     * Hit "*" while on the show list
> 
>     * The new OSD on v2.1.x that allows you to change audio while playing
> 
>     * Respecting the user's audio preference (as set via the web client)
> 
> 
> I believe it's a lot better now.

Ive since gotten the update and audio changing during runtime seems to work. Glad it's been improved
