### ISSUE TITLE
curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.

### ISSUE THREAD

**Issue by nicxvan** [jellyfin-archive/jellyfin-roku-legacy#181]
I'm working on testing the latest version.
I ran git pull
Set the ip address and dev password
I ran make install

It seems to have succeeded, but the above message was returned.

**Comment by bisby** [comment]
This sounds like you, or your package provided built curl in a weird way. This sounds a bit like a curl problem.

**Comment by cewert** [comment]
Yea this definitely looks like a curl problem:

"CURLE_NOT_BUILT_IN (4)

A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. This means that a feature or option was not enabled or explicitly disabled when libcurl was built and in order to get it to function you have to get a rebuilt libcurl."

Source: https://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by nlighteneddesign** [comment]
It is related to curl, but this is the first release that this error message has cropped up and I was not sure if something had changed with how you were using curl.

It did not seem to actually affect installing the dev channel.

**Comment by cewert** [comment]
Nothing has been changed with the build process in a long time so it shouldn't be that.

The error says your curl is missing a feature or two so as long as curl installs the dev app successfully then you should be fine.

**Comment by whaduu** [comment]
For anyone finding this thread in 2023 related to installing RUST on MacOs... the version of curl that is installed by homebrew does not support the -tls option (just remove it from the default rust install command line)

**Comment by SaidkomilMS** [comment]
> For anyone finding this thread in 2023 related to installing RUST on MacOs... the version of curl that is installed by homebrew does not support the -tls option (just remove it from the default rust install command line)

Thanks bro, Extra thanks from lazy me (lazy to read in English so much unhelpful text).

This really helps!!

**Comment by davis-mwangi** [comment]
@whaduu  thanks

**Comment by shlkhosla** [comment]
> For anyone finding this thread in 2023 related to installing RUST on MacOs... the version of curl that is installed by homebrew does not support the -tls option (just remove it from the default rust install command line)

Thanks, worked for me too :)
