### ISSUE TITLE
Cannot See Roku TV Client from "Play On" List

### ISSUE THREAD

**Issue by Co1lin** [jellyfin-archive/jellyfin-roku-legacy#1815]
## Software Versions

- Jellyfin Server Version:  10.9.7
- Roku Client Version:  latest one

## Describe the bug

After logging in to the same account from the client app on Roku TV, I cannot see it in the "Play On" list from a client on browser.

## How To Reproduce
1. Log in to the same account from the client app on Roku TV.
2. Open Jellyfin from a browser, like Chrome on macOS.
3. Click "Play On" list at the right upper corner.
4. Cannot see the Roku TV client.

## Expected behavior

The client on Roku TV should show up on the list. Just like after logging into the account from the client on an iPad, it shows up. Then I can play a video on the iPad by operating the client in the browser on a macOS.
Also, for macOS and iPad, I can play videos in a synchronized way by joining the same group. The client on Roku TV cannot join a group.

**Comment by jimdogx** [comment]
This is a little more involved.  See issue https://github.com/jellyfin/jellyfin-roku/issues/42
