### ISSUE TITLE
ASS Subtitles Aren't Displayed Correctly

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#183]
**Describe the bug**
As reported on [Reddit](https://www.reddit.com/r/jellyfin/comments/g9vowy/jellyfin_now_on_roku_beta/fox12ie/).
Advanced SubStation Alpha format subtitles are being extracted and treated like regular SRT subtitles. This means that they are not animated or displayed correctly.

**To Reproduce**
_Looking in to demo content for testing..._

**Expected behavior**
Display the subtitles correctly.

**Logs**
N/A

**Screenshots**

**Additional context**
It seems the Emby app tells the server to burn-in the subtitles during playback. Thus avoiding having to implement this on the client side for Roku. This needs to be verified though.

**Comment by neilsb** [comment]
Roku does not support ASS, so we either need to show them as text, or burn them in.  At present, we show them as text if the `IsTextSubtitleStream` is true (i.e. the subtitles are text) which is true for ASS subtitles.

The server does not send us the actual subtitle type so we can't easily identify if it's ASS or SRT format, so at the present time we're not able to automatically choose to burn in ASS subtitles without also burning in all text based subtitles.

We could provide the option (when selecting a text subtitle track) of whether to display as text or burn in?

**Comment by anthonylavado** [comment]
Hrm... for ASS I think we should probably lean towards always burning-in. It's typically used because of the custom text placement/colours/fonts, so it would be better to respect it. I wonder what other apps do here.

**Comment by neilsb** [comment]
Should be fixed by #476. ASS subtitles will now be class as not supported and result in transcoding to burn them in.

**Comment by msawatzky75** [comment]
Not to reopen this or anything, but i've noticed that if there is more than 1 image being displayed (top subtitle and bottom subtitle) it only renders one of them (the top one in my cases).

**Comment by neilsb** [comment]
Since ASS/SSA subtitles are not supported natively Roku they should be getting burned in by the server, so if that's happening then this sounds like a server issue rather than the Roku client.

I'll try and test this locally and let you know.
