### ISSUE TITLE
Unresponsive after pressing * (option button) after a search results is listed. 

### ISSUE THREAD

**Issue by Catsrules** [jellyfin-archive/jellyfin-roku-legacy#185]
**Describe the bug**
When looking at a search result page, if I press the * button a blank option menu comes out. When I press * or back button to close it It does close but I loose control, The application becomes unresponsive, There is no selector anymore nothing happens if when pressing back button, navigation buttons or * button. The only thing that works is the home button, that closes Jellyfin and I can open it again.

**To Reproduce**
1.Go to Search
2. Search for something
3. When viewing the Search results press the * button (options)
4. Press the * button again or back button
5. Application becomes unresponsive. (Try navigating or pressing the back buttons)
6. Press Home button to get out of application

**Comment by Catsrules** [comment]
This actually sounds very similar to Issue #147  

However on that issue, when I reproduce it I can regain control by pressing the down arrow and then the up arrow.

**Comment by neilsb** [comment]
The options need looked at across the app, so for the meantime it probably makes sense to disable the options on the search results.  Currently there are no options to show on this page anyway.
