### ISSUE TITLE
Roku Streaming Stick 4K Transcode Both Video (AV1) and Audio When Only Audio is Not Supported

### ISSUE THREAD

**Issue by lakerssuperman** [jellyfin-archive/jellyfin-roku-legacy#1851]
## Software Versions

- Jellyfin Server Version:  10.9.8
- Roku Client Version:  2.1.1

## Describe the bug
Playing back an mkv file with AV1 video and DD+ 5.1 audio on a Roku 4k Streaming set to stereo causes a full transcode to occur instead of just Direct Streaming.   A similar mkv file with HEVC and DD+ correctly triggers Direct Streaming and not a full transcode so the issue seems to be related to AV1.

This does not occur with my Roku Ultra 4800x when set to forced stereo output, however my Roku Dashboard(seemingly) incorrectly reports that the file is direct playing even though it probably should report Direct Streaming is occurring.

## How To Reproduce

1. Play back an mkv file with AV1 video and audio that is incompatible with the source and requires transcoding.
2. Only audio should be transcoded and Direct Streaming should occur, but this triggers a full transcode of audio AND video.

## Expected behavior
AV1 video is supported on the Roku streaming stick and should not be transcoded because the audio is not compatible.  Direct Streaming should occur in this case.

## Logs
I didn't immediately see any errors in the log that would help, but I will test more and add any log errors I find.

DEVICE PROFILE INFORMATION - https://pastebin.com/FhE4Gedb

## Connection Information

Server is local.

## Additional context
Both my Roku 4k Streaming sticks transcode video because the audio codec isn't supported when the video is AV1.  The same situation with HEVC video doesn't cause this issue and the issue doesn't seem to happen on my Roku Ultra 4800x.  The 4K stick and the Ultra have enough difference in the audio configuration options that I could see the bug/issue not hitting both, but I will test as many things as I can think of to be sure.  I tested this on two different 4K sticks, one plugged into a receiver running in stereo mode and another plugged directly into a TV.  Both exhibited the same behavior.  I will be happy to update this post with any info I can that helps.

Hope everyone is doing well!

**Comment by cewert** [comment]
Do you know if this file ever played correctly using our app? and if so what version?

A debug log from the dev client showing the device profile output would be helpful to see as well as any and all information about the file in question.

**Comment by lakerssuperman** [comment]
> Do you know if this file ever played correctly using our app? and if so what version?
> 
> A debug log from the dev client showing the device profile output would be helpful to see as well as any and all information about the file in question.

I don't know if it ever did play on Roku, as I've only recently begun to switch over to using AV1 for my Bluray collection.

I will work on getting the device profile output for you ASAP, but the files in question use mkv containers with AV1 video of the mostly 1080p SDR variety (Main@L4.0) and Dolby Digital+ audio of either 5.1 or 2.0 channels depending on the particular Bluray's channel layout.

I would also add that I tried playing back and H.264 video with incompatible audio and, like the HEVC video files, Direct Streamed like it was supposed to.

**Comment by dthreee** [comment]
I see a similar issue when playing AV1 videos with 7.1 audio on a 5.1 system via Roku Ultra 4802X. It transcodes video when it should just direct stream. Playing HEVC or h264 video with 7.1 works correctly, transcoding only audio. Playing AV1 with 5.1 direct plays as expected.

**Comment by cewert** [comment]
What are the transcode reasons given by the server in the server log when these files are incorrectly being transcoded?

**Comment by dthreee** [comment]
I don't know if I see any reason for transcoding, but here is the log. In the same file is a 5.1 AAC stream, if I switch to that, it direct plays. If I play a HEVC/7.1 file, it direct streams, only transcoding the audio.

[transcode log 241017.txt](https://github.com/user-attachments/files/17436203/transcode.log.241017.txt)

**Comment by lakerssuperman** [comment]
https://pastebin.com/3rvLRmXA - Transcoding Log
https://pastebin.com/NpZvZULf - Log showing transcoding is triggered.

@cewert These are the same logs I messaged you on Matrix over the summer when I filed the bug, but I figured I'd put them here for completeness sake.

Thanks for taking a look at this!

**Comment by lakerssuperman** [comment]
So after doing a bit more testing, it seems this issue isn't fully resolved.  Playing Hevc/EAC3 or H264/EAC3 files correctly direct streams on my two channel system.  However, AV1/EAC3 files have no audio.

I checked on one of my other systems and was able to reproduce the issue.

https://pastebin.com/0UCeFdDq
https://pastebin.com/1rgL9AxA

These are my logs.  There are many like them, but these ones are mine.

Thanks!

**Comment by cewert** [comment]
Does the server give you a TranscodeReason? Can you paste the debugging output from the dev client after it starts? The `profile.DeviceProfile.DirectPlayProfiles =` section is what I'm interested in

**Comment by lakerssuperman** [comment]
> Does the server give you a TranscodeReason? Can you paste the debugging output from the dev client after it starts? The `profile.DeviceProfile.DirectPlayProfiles =` section is what I'm interested in

I will have to remember my debug-fu, but I'll try to get you the info ASAP!!

**Comment by lakerssuperman** [comment]
> Does the server give you a TranscodeReason? Can you paste the debugging output from the dev client after it starts? The 
```
profile.DeviceProfile.DirectPlayProfiles =` section is what I'm interested in

profile.DeviceProfile.ContainerProfiles =       <Component: roArray> =
[
]
profile.DeviceProfile.DirectPlayProfiles =
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3,mp2,pcm,lpcm,flac,aac,mpg123"
    Container: "ts"
    Type: "Video"
    VideoCodec: "h264,mpeg4 avc,hevc,h265,mpeg4,av1"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3,mp2,pcm,lpcm,flac,alac,aac,opus,vorbis,mpg123"
    Container: "mkv,webm"
    Type: "Video"
    VideoCodec: "h264,mpeg4 avc,vp8,vp9,hevc,h265,mpeg4,av1"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "aac"
    Container: "ism"
    Type: "Video"
    VideoCodec: "h264,mpeg4 avc,hevc,h265,mpeg4,av1"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3,mp2,alac,aac,mpg123"
    Container: "mp4,mov,m4v"
    Type: "Video"
    VideoCodec: "h264,mpeg4 avc,hevc,h265,mpeg4,av1"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3,mp2,aac,mpg123"
    Container: "hls"
    Type: "Video"
    VideoCodec: "h264,mpeg4 avc,hevc,h265,mpeg4,av1"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3,mp2,alac,aac,mpg123"
    Container: "dash"
    Type: "Video"
    VideoCodec: "h264,mpeg4 avc,hevc,h265,mpeg4,av1"
}
<Component: roAssociativeArray> =
{
    Container: "aac,mp3,mp2,pcm,lpcm,flac,alac,aac,vorbis,mpg123"
    Type: "Audio"
}
profile.DeviceProfile.SubtitleProfiles =
<Component: roAssociativeArray> =
{
    Format: "vtt"
    Method: "External"
}
<Component: roAssociativeArray> =
{
    Format: "srt"
    Method: "External"
}
<Component: roAssociativeArray> =
{
    Format: "ttml"
    Method: "External"
}
<Component: roAssociativeArray> =
{
    Format: "sub"
    Method: "External"
}
profile.DeviceProfile.TranscodingProfiles =
<Component: roAssociativeArray> =
{
    AudioCodec: "aac"
    Container: "aac"
    Context: "Streaming"
    MaxAudioChannels: "2"
    Protocol: "http"
    Type: "Audio"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "aac"
    Container: "aac"
    Context: "Static"
    MaxAudioChannels: "2"
    Protocol: "http"
    Type: "Audio"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3"
    Container: "mp3"
    Context: "Streaming"
    MaxAudioChannels: "2"
    Protocol: "http"
    Type: "Audio"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "mp3"
    Container: "mp3"
    Context: "Static"
    MaxAudioChannels: "2"
    Protocol: "http"
    Type: "Audio"
}



<Component: roAssociativeArray> =
{
    Condition: "LessThanEqual"
    IsRequired: true
    Property: "Height"
    Value: "720"
}
<Component: roAssociativeArray> =
{
    Condition: "LessThanEqual"
    IsRequired: true
    Property: "Width"
    Value: "1280"
}
<Component: roAssociativeArray> =
{
    AudioCodec: "aac,mp3,alac"
    BreakOnNonKeyFrames: false
    conditions: <Component: roArray>
    Container: "mp4"
    Context: "Streaming"
    MaxAudioChannels: "2"
    MinSegments: 1
    Protocol: "hls"
    Type: "Video"
    VideoCodec: "hevc,h265,h264,h264,mpeg4 avc,av1"
}
<Component: roAssociativeArray> =
{
    Condition: "LessThanEqual"
    IsRequired: true
    Property: "Height"
    Value: "720"
}
<Component: roAssociativeArray> =
{
    Condition: "LessThanEqual"
    IsRequired: true
    Property: "Width"
    Value: "1280"
}
profile.PlayableMediaTypes =    <Component: roArray> =
[
    "Audio"
    "Video"
    "Photo"
]
profile.SupportedCommands =     <Component: roArray> =
[
]
```

Is it possible this block is the issue? As my system is set to explicit 2 channel stereo, which I believe is PCM output, and I don't see AV1 listed in the VideoCodec line.  

```
<Component: roAssociativeArray> =
{
    AudioCodec: "aac,mp3,flac,pcm"
    BreakOnNonKeyFrames: false
    conditions: <Component: roArray>
    Container: "ts"
    Context: "Streaming"
    MaxAudioChannels: "2"
    MinSegments: 1
    Protocol: "hls"
    Type: "Video"
    VideoCodec: "hevc,h265,h264,h264,mpeg4 avc"
}
```

And the AV1 files Direct Streams and reports as such in the Dashboard, there's just no audio on playback.

![Image](https://github.com/user-attachments/assets/34c3c187-b40b-4ed8-b56d-a3fed22375af)

**Comment by dthreee** [comment]
Seeing a similar result to the OP, but when playing 7.1 files on a 5.1 system so it has to downmix, triggering the full transcode like the OP. Not sure the version but, at one point the files would just refuse to play, crashing back to the JF library. After the update, it plays back with no audio. This is with AAC, FLAC, or OPUS audio.
