### ISSUE TITLE
AAC audio not working

### ISSUE THREAD

**Issue by AveryTimm** [jellyfin-archive/jellyfin-roku-legacy#1855]
## Software Versions

- 10.9.8 (in TrueNAS which is up to date):  
- 2.1.1 

## Describe the bug
AAC music will not play. When starting a track the progress bar quickly advances and it goes to the next track which does the same thing. The stereo audio was ripped from CD's by iTunes/Music. This music did work in the past on the Roku app but hasn't in at least the last several updates. The music does play in the web interface.

MP3 and FLAC does work. Audio in videos works.

I have tried forcing channels to 2, and adjusting the bitrate.

## How To Reproduce

1. Go to Music library
2. Select an album
3. Select a track and play it
4. Bug occurs

## Expected behavior
The audio track should play

## Logs
In the activity window in the web interface it lists each track a few seconds apart and says "AudioPlaybackStopped". It doesn't say "AudioPlayback".

**7/23/2024 3:15:21 PM**
Information
jellyfin has finished playing Vince Guaraldi Trio - Happiness Is on 55S531 (A000X)
AudioPlaybackStopped
**7/23/2024 3:15:19 PM**
Information
jellyfin has finished playing Vince Guaraldi Trio - Oh Good Grief on 55S531 (A000X)
AudioPlaybackStopped
**7/23/2024 3:15:14 PM**
Information
jellyfin has finished playing Michael Hedges - Hot Type on 55S531 (A000X)
AudioPlaybackStopped
**7/23/2024 3:15:11 PM**
Information
jellyfin has finished playing Michael Hedges - Rickover's Dream on 55S531 (A000X)
AudioPlaybackStopped
**7/23/2024 3:15:09 PM**
Information
jellyfin has finished playing Michael Hedges - Aerial Boundaries on 55S531 (A000X)
AudioPlaybackStopped

## Screenshots
Media Info for one of the files that will not play from the web interface...
<img width="645" alt="roku-jellyfin" src="https://github.com/user-attachments/assets/dfda1a19-545f-4688-a2b9-02d9bd922ccc">

## Connection Information

- Is server local or remote?
       **local**
- Is server connection HTTP or HTTPS?
       **http**

**Comment by AveryTimm** [comment]
The problem persists with the last and current update.

Is anyone else having a similar problem?

**Comment by cewert** [comment]
Can you upload a sample file? That would be the quickest way for me to look into it

**Comment by AveryTimm** [comment]
Sorry… I reinstalled Jellyfin in TrueNAS because I was having some other issues. After that it seems to be working. I don’t know what went wrong. Sorry for the confusion.
