### ISSUE TITLE
Possible to sponsor maintainers?

### ISSUE THREAD

**Issue by mtlynch** [jellyfin-archive/jellyfin-roku-legacy#1856]
## Describe the feature you'd like

Given Jellyfin's announcement that they no longer need financial contributions, is it possible to redirect my donation to the maintainers here? Is there a way of sponsoring @neilsb directly?

## Additional context

https://forum.jellyfin.org/t-we-re-good-seriously

**Comment by neilsb** [comment]
Thanks very much for considering this.  Personally, I have less time to dedicate to this project than I did initially, and I prefer to keep my involvement as a hobby without the added pressure of financial expectations.

So your query is very much appreciated, and there are many other regular contributors in core, and the roku & other clients who are happy to accept contributions, but at the current time I don't have that setup.
