### ISSUE TITLE
Crash when certain videos appear in the search results

### ISSUE THREAD

**Issue by Catsrules** [jellyfin-archive/jellyfin-roku-legacy#186]
**Describe the bug**
I can get the the application to crash (close and go back to the home scree) depending on the search results. It crashes when particular videos appear in the results.

I believe I have multiple offending videos in my library but for testing I have narrowed down one of the offending videos. It is a CGP gray video I downloaded off YouTube. Whenever it appears in the search it crashes. 

For testing I added the video in question to the TV Show library (It was in the Mixed Content Library before). It still crashes when the video appears in the search result. However it doesn't crash when browsing the video under the TV Show library. It appears to only be related to search.

I still haven't figured out what characteristics are causing the crash. Maybe a special character or something as the description I have is a mess. (it was the YouTube video description so it has links and all sorts of stuff.) If anyone is interested I posted link to the raw video and meta data files in question. Just throw it in your TV Shows directory and let Jellyfin scan it. 

**To Reproduce**
1. Download my raw video files here
https://files.soxscloud.com/index.php/s/Dn8aHS3YsJHzopQ
2. Unzip and copy the files into the root of the TV Show directory
3. Refresh Jellyfin library 
4. On the Roku application search for part of all of the video title. (Video should be title 8 Animal Misconceptions Rundown)
5.Application should crash when video is listed in the search results.

**Comment by neilsb** [comment]
This is due to it being classes as a Episode of a Series.  We assume there is an Index Number and try to display that  (e.g.   3. Animal House).

We should be checking an index number is set for each entry.
