### ISSUE TITLE
Allow selection of audio track

### ISSUE THREAD

**Issue by scottAnselmo** [jellyfin-archive/jellyfin-roku-legacy#188]
**Describe the feature you'd like**

Currently as far as I can tell, the audio track defaults to track 1 for Movies. There is no way to change this at will in the client from either the title meta card, or during mid-play. Only subtitles can be changed midplay. Easiest fix would probably be to update the subtitle selection popup to also have audio track selection.

**Additional context**

Reasons for implementing this are plentiful. For example, being able to listen to cast commentary tracks, or a non-track 1 language.

**Comment by boydthomson** [comment]
this would be great to be able to select original language or dubbed languages depending on who is watching and what they can understand
