### ISSUE TITLE
Movies with FLAC 5.1 audio won't play

### ISSUE THREAD

**Issue by scottAnselmo** [jellyfin-archive/jellyfin-roku-legacy#189]
**Describe the bug**

Certain movies when accessed will have the retrieving bar get stuck halfway. Have left alone for 10+ minutes and the progress status remains the same:
![IMG_20200429_003106](https://user-images.githubusercontent.com/3056597/80573818-3e623000-89f0-11ea-9a53-e8da9652418f.jpg)

**To Reproduce**

1. Load a movie w/ FLAC 5.1 (Japanese)
2. See movie fails to retrieve in a timely fashion

**Expected behavior**

Movies loads w/o issue.

**Logs**

Can't find a way to retrieve logs for a beta app. Please point me to any documentation if it's possible

**Screenshots**

See above

**Additional context**

I've found two movies that have this issue on Roku that share the audio codec being FLAC 5.1, so I believe this is the likely root cause. It's worth noting these movies load near instantaneously on Jellyfin for Android, and PLEX for Roku, so it's not an issue with the Jellyfin server, networking, or Roku HW limitations. I'll write a script to easily find more movies I've ripped w/ FLAC 5.1 to confirm my hypothesis and update the ticket this weekend.

**Comment by neilsb** [comment]
Interesting.  I just re-encoded a video with FLAC 7.1 and FLAC 5.1 to test, and FLAC 7.1 worked fine but I get the same hanging as you with FLAC 5.1.

**Comment by neilsb** [comment]
For the Roku Stick I'm testing on, the call to `CanDecodeAudio()` reports that it thinks it **can** decode a 6 channel FLAC stream.  However for the 8 channel (7.1) steam is reports it cannot decode it and so it is being transcoded by the server (which is why it works).

**Comment by neilsb** [comment]
After some more testing, my test FLAC 5.1 does work on the Android app and on the Plex Android App.

However, on the Plex Roku app it _hangs_ in a similar way while retrieving the video, then after about 30 seconds or so a message appears "This video isn't supported for Direct Play".

@sanecito Can you just double check that when viewing your FLAC 5.1 encoded videos via Plex Roku (or any other Roku player) that they are streaming with Direct Play and not being transcoded?    If you **are** seeing the  same error in Plex then it's likely a Roku issue, but if it is playing correctly then it's more likely there is an issue with the video I am testing with which I need to resolve before looking at this in more detail :)

**Comment by scottAnselmo** [comment]
Excellent find! I get the same end error message. One movie loaded to 51% and then the 30 seconds to throw the error, another instantaneously

For any one else wishing to replicate the issue for PLEX, this is what I did, but you may very well only need to modify client side:

1. On Plex Server Settings > Transcoder make sure 'Disable video stream transcoding' is selected
2. On Plex client Video settings set local/remote video settings to 'Original'
3. On Plex client Video settings set Direct Play to 'Forced', don't allow direct stream

And for what it's worth this is on a Roku Ultra lest there be a new model that supports FLAC 5.1

**Comment by neilsb** [comment]
The annoying thing is that each Roku Device reports what codecs and channels it can decode, and the app use that to determine whether it needs to request transcoding from the server.  In this case it is reporting that is can decode a 6 channel FLAC stream, but plainly it cannot.

I wonder if there are any FLAC 5.1 videos that Roku can handle and there is something special about the ones we're looking at.  It certainly wouldn't be ideal to force transcoding (downmixing to 2 channel) if not a problem across the board.   We'd just need to come up with some some smarter logic....

**Comment by neilsb** [comment]
After more testing, thing don't become any clearer:

- With a different video with FLAC 5.1 audio, it Direct Plays fine without transcoding
- With a different video with FLAC 7.1 audio, detects that it cannot play it, and requests transcoding.  If I set it to request a transcode to FLAC 5.1, then it transcodes and plays fine

So from these results, it appears that the Roku device _is_ able to handle FLAC 5.1 audio, but there is something specific about the other videos we tested with.

**Comment by scottAnselmo** [comment]
This may have already been done, but it may be worthwhile for you or another contributor to ping Roku dev support and see if they can better explain what the Roku firmware supports rather than spending too much time making educated guesses: https://developer.roku.com/contact

**Comment by neilsb** [comment]
Interestingly the same FLAC 5.1 video that was causing problems on the Roku Streaming Stick 4k works fine on a 2013 Roku LT. So it suggests it's a problem with how some of the newer devices are decoding the FLAC 5.1 in specific videos.  

@sanecito I think I will drop Roku Support a note about this, although I think the devices are reporting what they should support correctly.  It looks like we've maybe just stumbled on a specific decoding bug in the newer models.

**Comment by cewert** [comment]
@neilsb right now we are only sending codec and channel count to [CanDecodeAudio()](https://developer.roku.com/en-ca/docs/references/brightscript/interfaces/ifdeviceinfo.md#candecodeaudioaudio_format-as-object-as-object), maybe if we sent all the parameters it would correctly play the files?

**Comment by neilsb** [comment]
I think that's certainly an improvment that should be investigated, but I don;t think it would help in this particular case.  Both my test files have exactly the same Audio Codec, Channels, Sample Rate and Bits per sample according to VLC.  And while both play fine on the Roku LT, one of them is consistently hanging on the newer devices.

**Comment by neilsb** [comment]
A query has been sent to Roku Support.

**Comment by neilsb** [comment]
Roku support unfortunately just told us to use the Community support, so I've [posted there](https://community.roku.com/t5/Roku-Developer-Program/Video-retrieval-problem-on-4k-players/m-p/565947).  Will see what response we get.

In the meantime, I'll submit a PR that has a timer to monitor the Buffering status, and if it hangs while loading gives a poup message, and returns you to the previous screen.

**Comment by scottAnselmo** [comment]
What if instead it attempts to transcode rather than exit? Are there any other known cases where the app will hang at buffering which would make this not ideal? If no other cases, opting to transcode would allow users to at least watch and listen to their media, even if it's at a lesser quality.

**Comment by neilsb** [comment]
This is the only occurrence of the _hang_ that I've heard about.   I wouldn't be overly happy about  automatically transcoding if this happens, as if the Roku says it can handle the current codec/bitrate then "randomly" choosing another one that the device says it supports could result in the same thing.  I'd just much rather we got a definitive error from Roku (or better yet, it worked)

Providing an offer to transcode in the dialog (rather than forcing it on the user) would be a little better.  And just force it down to one of the most commonly supported audio and video.  It would mean that the server was transcoding both Audio and Video though, when only one may be required - but I'm just not sure that this _hang_ wouldn't happen in other situations, so would be wary of assuming if there was a hang, it was due to this particular issue.

**Comment by neilsb** [comment]
Just re-resting this, and I am no longer able to reproduce this problem locally.   There has been an minor Roku OS Update since this was originally tested I believe, but potentially something else has changed.

@sanecito - Are you able to confirm if you are still getting this problem?

**Comment by scottAnselmo** [comment]
@neilsb Can confirm videos with FLAC 5.1 play. However audio itself is effectively mute (other non-FLAC 5.1 plays audio just fine). I route my audio just to my TV as I don't have a fancy sound system which might be why I'm not getting sound through TV for FLAC 5.1?

**Comment by neilsb** [comment]
@sanecito  Version 1.3 Build 5 has just been approved on the store.  There was a issue with knowing what Audio could be decoded which was fixed in this release (that I don't believe was in the beta version).

When you get a moment could you check if the error is resolved with this latest version, and let us know?  If it hasn't I'll dig into it again, and may be in touch about exact audio/video formats and possibly a sample  :)

**Comment by scottAnselmo** [comment]
@neilsb Thanks to you and whoever worked on this! Can confirm the issues I was experiencing w/ 5.1 FLAC movies no longer occur; closing.
