### ISSUE TITLE
Queue Entire Playlist Starting From the Chosen Song

### ISSUE THREAD

**Issue by michaelcresswell** [jellyfin-archive/jellyfin-roku-legacy#1894]
## Is your feature request related to a problem? Please describe
Being limited to a single song when selecting within a playlist is poor UX and no longer necessary.

## Describe the solution you'd like
When a song is selected from a playlist, queue the entire playlist and start at the selected song. This would allow the remaining portion of the playlist to be played automatically and also allow the forward and back buttons to step through the entire playlist.

## Describe alternatives you've considered
Using Play All and skipping ahead to desired song but this is untenable with large playlists.

## Additional context
This is analagous to https://github.com/jellyfin/jellyfin-roku/issues/1216 but for playlists.

**Comment by cewert** [comment]
Fixed by #1895
