### ISSUE TITLE
Show loading icon or other feedback mechanism when connecting to server for the first time

### ISSUE THREAD

**Issue by Jacob-Lasky** [jellyfin-archive/jellyfin-roku-legacy#191]
When trying to connect to my server for the first time, I type in the server name, click "Ok", click "Submit," and then nothing else happens. I incorrectly typed the server address the first time and it took about 30 seconds for the "Server not found" message to appear under the "Submit" button.

I would love to see a "Loading" or "Please wait" animation or popup, maybe even with the current step in the connection process that it is on.

An alternative to that would be to grey-out the submit button after pressing it until the Jellyfin is done searching.

I'm on a TCL Roku TV. Model number 49S405. Software version 9.2.0, build 4502.

**Comment by jystadj** [comment]
Just a note for later reference that this would better comply with the Roku Best Practices target in #30 .

**Comment by neilsb** [comment]
Closed by #409
