### ISSUE TITLE
Clicking "Add User" returns to "Connect to Server" page

### ISSUE THREAD

**Issue by Jacob-Lasky** [jellyfin-archive/jellyfin-roku-legacy#192]
**Describe the bug**
Clicking "Add User" from the settings menu returns me to the "Connect to Server" page. The behavior is exactly the same as if I were to click "Change server" from the settings menu.

**To Reproduce**
1. Press "*" (settings) on the remote
2. Click "Add User"

**Expected behavior**
I'm honestly not sure what I expected from this. I expected to be able to add a user, but I don't know what would come after clicking "Add User."

**Comment by cewert** [comment]
I believe the intended use was to allow the client to save login credentials for multiple users - so you could switch between users without having to enter your password every time. But, it hasn't worked since I've started working with the code so I'm not sure.

I'm thinking we just remove that link from the menu for now until someone comes along to code the feature (if we still even want the feature?)

**Comment by neilsb** [comment]
I had been looking at an updated login screen (before the recent update was made) that allowed selecting a server and user from the one screen.   However, work on it has stalled.  :)

This would have involved saving known servers, so would provide a quick way to switch user accounts, and allow logging in via a PIN pad had the user enabled the short password option.

However, it raised a number of questions on how things should work, including whether multiple user accounts were needed, and whether the user stays logged in by default, etc etc.  Happy to resurrect.

**Comment by PabloHuerfano** [comment]
I think multiple user accounts would be amazing. It would help different watched/resume status between multiple users sharing one roku.

**Comment by cewert** [comment]
@neilsb Yea go for it. We can always work things out in the PR or on matrix. There's definitely people that want this - I know the emby client has most or all of those features

**Comment by macman85602** [comment]
I have just started using this and having the Multiple Users feature would be great with having kids. Having the pin option works good because typing in usernames and passwords all the time is cumbersome.

**Comment by neilsb** [comment]
@macman85602 The multiple user thing already mostly works.  If you ensure that **Hide this user from login screens** option is not set (on the User Profile Tab - it's set by default), after selecting a server these users will show up on the login screen a little like they do on plex and Netflix, etc.

If the user has an **Easy Pin Code** set they can use this or their password to log in (need to also ensure _Enable in-network sign in with my easy pin code_ is selected.  It doesn't show a PIN pad, but you can use the number pad at the right hand side of the keyboard.

At the moment "Sign Out" is the same as other services would call "Switch User".  Maybe it should be renamed that?

Updating the server setup and login process are on the list of things to do, but currently functionality missing from the client has a higher priority.   I'll get the "Add User" menu option removed to stop any confusion.
