### ISSUE TITLE
Item Titles on Roku Does Not Update  

### ISSUE THREAD

**Issue by andrewteg** [jellyfin-archive/jellyfin-roku-legacy#1926]
## Software Versions

- Jellyfin Server Version:  10.9.11
- Roku Client Version:  Current

## Describe the bug
Titles do not show on Roku when "Always Show" is selected in Roku Settings.

## How To Reproduce

1. Settings => User Interface => Libraries => General => Grid View Settings
2. Select Item Title
3. Select Always Show
4. View a Library
5. Titles still only Show on Hover

## Expected behavior

In step 5 above, Titles will be on all Library Items all the time.

## Connection Information
- Is server local or remote? Local
- Is server connection HTTP or HTTPS? NA/Roku

## Additional context
Started as question at https://forum.jellyfin.org/t-titles-on-roku with screenshots and confirmation from Moderator there if needed.

Thanks :)

**Comment by thedreaddpirate** [comment]
I was able to replicate this issue on my 4800X.

**Comment by cewert** [comment]
Different library types use different code. What library types did you see this behavior with? Movies? Tv shows? music? etc.

**Comment by thedreaddpirate** [comment]
I tested on a Movies library.  When I get home I can test on a Shows library.

**Comment by andrewteg** [comment]
I had tried it on a Mixed Content and Movies, and also have a 4800X FWIW.

**Comment by cewert** [comment]
No need for anymore testing I figured out - it was affecting all libraries. Thanks for the bug report
