### ISSUE TITLE
Display legibility improvement for truncated item titles.

### ISSUE THREAD

**Issue by jystadj** [jellyfin-archive/jellyfin-roku-legacy#196]
Movie titles only have so much width to display in the Movies view and truncate with a ellipsis for longer titles, this sometimes results in a minimally distinguishable title.

I would like a way to see the full title when highlighting items that have been truncated. The Plex Roku channel scrolls the titles in place a second or two after you highlight it, so we at least know that approach is possible on the Roku though I am not sure it is the best approach.

**Comment by jystadj** [comment]
Thought about this a bit more and realized that I'd be happy with the title area for each row growing enough vertically to allow the largest title in each row to wrap and display fully, with a maximum character or line count to keep it from getting out of hand.

But I suspect that the resulting unevenness of the row heights might drive some people up the wall. :)

**Comment by neilsb** [comment]
PR #206 updates the Layout to reduce the number of items on screen, so when that is merged things will be even more readable.

PR #214 enables scrolling for the titles

**Comment by jystadj** [comment]
Oh wow, yeah I agree that fixes it **completely**.

This looks much better, and it helps deal with the Roku Safe Zones at the same time. Nice work impacting a bunch of stuff with the same fixes, very cool!
