### ISSUE TITLE
Collections do not show their contents.

### ISSUE THREAD

**Issue by jystadj** [jellyfin-archive/jellyfin-roku-legacy#197]
**Describe the bug**
Clicking into any collection from the Collections section displays the correct name of the collection in the header, but shows the contents of the Movies topParent instead of the Item Details of the selected collection.

**To Reproduce**
1. Go to Collections
2. Click on any collection
3. Land on the main Movies page.

**Expected behavior**
User should be sent to the Item Details screen for the selected collection.

**Additional context**
I currently only have 3-5 collections and they consist entirely of movies. I have no other media types in collections and no collections contain mixed media types.

**Comment by cewert** [comment]
Just tested and wow are collections broken. Thanks for reporting this!

I think they were working after bisby's single scene rewrite so we must have broke them sometime after that

**Comment by jystadj** [comment]
Glad to help, I only tested it because I just started playing with collections myself so they were in front of my brain. :)

**Comment by bisby** [comment]
Last I knew collections were working, but only for Movies.

**Comment by jystadj** [comment]
@bisby Dang, I should have spoke to that above, my current collections are only movies. I try to be more complete then that. Thanks, I'll go add that to the issue ticket.

**Comment by cewert** [comment]
https://github.com/jellyfin/jellyfin-roku/commit/9570f51dc96865baf572bae42e40bebc90e70533#diff-9107e03a79b22cc1b1e893e7a44961b1R76

Removing that line fixed the layout of the collections page. still digging into the links not working

**Comment by neilsb** [comment]
It seems that from 10.5.0 the server is losing the MetaData when adding Movies to Collections, and instead adding them as Videos.  (jellyfin/jellyfin#2565 & jellyfin/jellyfin#2826).  

Will get the Collections updated to handle Video's in the meantime, and also add TV Shows and Episode support.   Music needs added too, but the client doesn't yet support playing Albums.

**Comment by Artiume** [comment]
This has been fixed and is slated for 10.6, resolving ticket

**Comment by Artiume** [comment]
Wrong issue
