### ISSUE TITLE
Playback errors with v2.1.6

### ISSUE THREAD

**Issue by skunk-ink** [jellyfin-archive/jellyfin-roku-legacy#1975]
## Software Versions

- Jellyfin Server Version:  10.9.11
- Roku Client Version:  2.1.6

## Describe the bug
After the recent update to 2.1.6, I am now receiving a pop-up saying, "There was an error retrieving the data for this item from the server." I am able to play these videos from both the WebUI and Jellyfin Client on all my other devices, so it is not an issue with the file and is specific to my Roku TV. This file was playing just fine last night before the update as well.

## How To Reproduce
Play any HVEC video

## Expected behavior
The video should play

## Logs
```
jellyfin  | [16:04:07] [INF] [57] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for skunk. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
jellyfin  | [16:04:08] [INF] [20] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Roku 2.1.6 playing The Intruder. Stopped at 0 ms
```

## Connection Information

- Is server local or remote? Remote
- Is server connection HTTP or HTTPS? HTTP

## Additional context
None.

**Comment by cewert** [comment]
Should be fixed by #1974. 2.1.7 coming thursday


Here is the production build zip for 2.1.7 [Jellyfin-Roku-v2.1.7.zip](https://github.com/user-attachments/files/17296298/Jellyfin-Roku-v2.1.7.zip)

You can use the [Beta Test instructions](https://github.com/jellyfin/jellyfin-roku#beta-test) on the readme to sideload the zip onto your roku as a workaround or to test.

If this is still an issue for you after tetsting with 2.1.7 please let us know!

**Comment by skunk-ink** [comment]
Awesome, thanks for such a quick response!

Edit: I just tested the 2.1.7, and everything seems to be working well

**Comment by TreySpooner65** [comment]
I also updated to 2.1.7 and it fixed the issue. 

I had a similar issue on the JellyFin android app at the same time. Hoping a fix for that comes but Roku is the main issue and it's fixed now.

**Comment by CorpHackRyan** [comment]
Just wanted to comment - I ran into the same issue last night. The previous night, I was playing a movie, worked fine. Got the auto update yesterday. Went to play the same movie, got kicked back to the main screen on my Roku. I tried several movies with the same issue. I'll just wait for the new push hotfix today and report back here with my results.

**Comment by cewert** [comment]
@CorpHackRyan v2.1.7 hit devices today as of midnight PT. 

To manually update the app:
- home screen
- select the Jellyfin app
- hit star(*)
- update app.
