### ISSUE TITLE
Add shuffle option

### ISSUE THREAD

**Issue by hshl2** [jellyfin-archive/jellyfin-roku-legacy#198]
**Describe the feature you'd like**
On TV series, add a shuffle option to randomly play episodes as seen on web interface. 

**Additional context**
Would be a nice feature to have long term once music is supported as well.

**Comment by FreeSoftwareServers** [comment]
This is a make or break daily use feature for me. Back to Emby until this is resolved :(

**Comment by bryce-hoehn** [comment]
It seems like the TV Season Select menu doesn't have a * menu. Perhaps a small menu could be created and bound to that button to add options such as shuffle and add to playlist? I'm not sure how to go about distinguishing from shuffle series vs. shuffle season though.

**Comment by bryce-hoehn** [comment]
![shuffle_preview](https://user-images.githubusercontent.com/1351017/121267067-23c4e080-c8ab-11eb-85b4-4963b6a9a89c.jpg)

Something like this could work. I've been poking at the code trying to get something like this working but I'm pretty new to coding in general let alone Roku's language.

**Comment by Artutos** [comment]
> ![shuffle_preview](https://user-images.githubusercontent.com/1351017/121267067-23c4e080-c8ab-11eb-85b4-4963b6a9a89c.jpg)
> 
> Something like this could work. I've been poking at the code trying to get something like this working but I'm pretty new to coding in general let alone Roku's language.

How did it go?

**Comment by johnmmcgee** [comment]
I would love to see this option!

**Comment by FreeSoftwareServers** [comment]
> ![shuffle_preview](https://user-images.githubusercontent.com/1351017/121267067-23c4e080-c8ab-11eb-85b4-4963b6a9a89c.jpg)
> 
> Something like this could work. I've been poking at the code trying to get something like this working but I'm pretty new to coding in general let alone Roku's language.

Can you share your code edits? I looked at the code and was supprised to see how close it resembles VBA which im great with. Id love to see what you did to get me pointed in the right direction

**Comment by levia7han** [comment]
This is a feature I would love to see. Is this on the road map at all?

**Comment by 1hitsong** [comment]
If we started by adding a shuffle play button to the top of the episode selection screen (after clicking on a season) would that be a good enough start?

**Comment by levia7han** [comment]
Personally, the use case is to pick a show and have it random play from all the episodes available. I will often do this at night when I sleep. Or if I just want something on in the background.

**Comment by FreeSoftwareServers** [comment]
> If we started by adding a shuffle play button to the top of the episode selection screen (after clicking on a season) would that be a good enough start?

That sounds bang on! I've personally been following this waiting to switch to Jellyfin!

I can say my GF loves shuffle, I guess its not on most major streaming services but I use it almost every time. Kodi and Emby both have it.

**Comment by cskaryd** [comment]
I'd love to see a way to turn that off or on by library.  Currently, it's a bit of a screen real estate hog.  Putting it above or below the episode list might make more sense than to the left or right of the episode list.

**Comment by 1hitsong** [comment]
> That sounds bang on! I've personally been following this waiting to switch to Jellyfin!

This is live now. Just click on a TV season and you'll see it on the left under the season poster.

Edit: Let me clarify. We added a "Play Random" button that plays a random episode from the season. To shuffle, we need to make many more edits to allow it to work properly. This is still in process. Baby steps 😄

**Comment by FreeSoftwareServers** [comment]
Very cool! I'll spin up a VM amd test soon and let you know feedback 😁

**Comment by pforpond** [comment]
I'd love to see the shuffle feature come to the music too! I'm a big fan of having my library on shuffle.

**Comment by FreeSoftwareServers** [comment]
@1hitsong I tried Jellyfin again and I was a bit disappointed, I think I read to fast last time around. I'm super happy to see "Play Random" on episodes, but think of this as an example (very close to @levia7han ). I want to put on the simpons in the background, I don't want to pick first one of ~25+ seasons, I just want any simpsons. I do in fact enjoy sometimes when it goes from early stuff to more modern and such.

I was thinking maybe I'd look over the code to see how the "Play Random" button was implemented, but I think you mentioned that a "shuffle" will be a lot harder? Anyway, maybe in the winter :P.
![Emby-Series](https://user-images.githubusercontent.com/16218200/190879177-05383d02-4485-439d-b271-e5a1c91f51c2.jpg)
![Jellyfin-Season](https://user-images.githubusercontent.com/16218200/190879179-92a17390-1ebd-4bc4-a4b6-bd19935a7d9b.jpg)
![Jellyfin-Series](https://user-images.githubusercontent.com/16218200/190879181-8e3184e9-9285-4aa4-8e7d-3efe5c429733.jpg)
![Emby-Season](https://user-images.githubusercontent.com/16218200/190879183-0f06326e-cbcc-48f1-a8d2-62af26d1a4ee.jpg)

I've attached some screenshots of a comparison w/ Emby. The seasons have the same functionality, but not the series just yet.

**Comment by 1hitsong** [comment]
@FreeSoftwareServers We'll get there eventually, but there is a lot of foundation work that must be done first. At its core the Roku app was built to play through shows sequentially. So we not only need to start from scratch to support shuffle, we must take several steps backwards before we can built it back and **_then_** start working on shuffle.

**Comment by JamesSwift** [comment]
Thanks for your work so far on this feature. I thought it might help to explain our use case. We are currently using Plex to accomplish this on our Roku.

I've got lots of different shows for my 3 tear old. Sometimes he wants a specific show so we shuffle the whole show (not just a season). but sometimes we just want "random kids TV", so for that we shuffle the whole parent "kids" library. 

It would be really helpful to be able to this with jellyfin.
