### ISSUE TITLE
Problema la aplicación me saca al menú principal del roku

### ISSUE THREAD

**Issue by EDWAR-R** [jellyfin-archive/jellyfin-roku-legacy#1985]
Hola buenos días tengo el siguiente problema con jellyfin con mi dispositivo roku al momento de ingresar a jellyfin y al buscar los canales que tengo cargados en la aplicación le doy reproducir al canal y la aplicación me saca al menú principal del roku.
Pero el error se genero después dela actualización.

**Comment by cewert** [comment]
Lo sentimos, no hablamos español.

Hopefully this is a duplicate of #1975 which will hit devices on Thursday. Please reopen if 2.1.7 doesn't fix your issue!

Here is the production build zip for 2.1.7 [Jellyfin-Roku-v2.1.7.zip](https://github.com/user-attachments/files/17296298/Jellyfin-Roku-v2.1.7.zip)

You can use the [Beta Test instructions](https://github.com/jellyfin/jellyfin-roku#beta-test) on the readme to sideload the zip onto your roku as a workaround or to test.

**Comment by jimdogx** [comment]
> Lo sentimos, no hablamos español.

Yo si hablo Espanol :smile:

**Comment by cewert** [comment]
🤦   ¿cuáles son las probabilidades?
