### ISSUE TITLE
"Next Up" duplicates "Continue Watching"

### ISSUE THREAD

**Issue by dathbe** [jellyfin-archive/jellyfin-roku-legacy#1986]
## Software Versions

- Jellyfin Server Version:  10.9.11
- Roku Client Version:  2.1.7

## Describe the bug
Since one of the recent releases (the first 2.1 build?), shows that appear as partially watched in "Continue Watching" also appear in "Next Up."  I don't believe this used to happen, and it does not seem to be ideal behavior.  

I think this is a bug, but if anyone thinks this should be converted to a feature request, let me know.

## How To Reproduce

1. Start a show, watch long enough to have it save progress
2. Go to the home menu
3. Bug appears

## Expected behavior
A show should either be in progress ("Continue Watching") or something to watch next ("Next Up"). Not both.

## Logs
N/A

## Screenshots
Happy to provide if they will help, but I think this is fairly self explanatory.

## Connection Information

- Is server local or remote? both
- Is server connection HTTP or HTTPS? HTTPS

## Additional context
Happy to provide any additional details that anyone needs.

**Comment by cewert** [comment]
Looks like the web client removes the Next Up link when there is a Continue Watching episode. I agree, it would make sense for us to do the same.
