### ISSUE TITLE
Skip-ahead should increase step size

### ISSUE THREAD

**Issue by dnno** [jellyfin-archive/jellyfin-roku-legacy#2010]
## Is your feature request related to a problem? Please describe
When I skip through a movie, the Roku Jellyfin client uses 10 second steps. If I want to skip further into a movie (more than a few minutes), it takes a long time.

## Describe the solution you'd like
I've been using Kodi for a long time. It increases the step sizes if you repeatedly step forward. Starting with 10 second steps is fine. But to skip further into a movie, increasing step sizes to 30 seconds or even a minute or 5 minutes would help a lot. The increased step size should be reset when you stop skipping.

Example step sizes in seconds for 10 repeated skips:

10s - 10s - 10s - 30s - 30s - 30s - 60s - 60s - 60s - 300s ...

Ideally this could be configured by the user. But I think even without a configuration option, this would add a lot of value.

## Describe alternatives you've considered
Making the step size configurable could also be an option, but it wouldn't be optimal, because if you increase the default step size you can't do finer grained skipping anymore.

**Comment by roidy** [comment]
The Roku already has a 3 step FF/RW button on the remote that will skip in 10/30/60 second increments. If you need to move around faster then just use chapter forward/back, if your media doesn't have chapters then the server can be set up to generate dummy chapters at any interval you want.

**Comment by dnno** [comment]
Apologies. I'm using a Roku Express box with my Samsung Samrt-ZV and I wasn't using the Roku remote but my TV's remote to scroll. With the roku remote it works as you say. my tv remote is too dumb, it seems. I'm closing this. Thanks a lot for your advise though!
