### ISSUE TITLE
Live TV Does Not Remember "TV Guide" View Preference in Jellyfin Roku Client

### ISSUE THREAD

**Issue by johnpc** [jellyfin-archive/jellyfin-roku-legacy#2022]
## Software Versions

- Jellyfin Server Version:  10.10.0
- Roku Client Version:  2.2.1

## Describe the bug

The Jellyfin Roku client is not retaining the user's preference for the "TV Guide" view in the Live TV section. Despite selecting "TV Guide" as the preferred view, the app defaults back to the "Channels" view every time the Live TV section is accessed.

## How To Reproduce

1. Open the Jellyfin Roku client
2. Navigate to the Live TV section
3. Change the view preference to "TV Guide" (Choose *, then "View", then "TV Guide")
4. Exit the app (e.g., go back to the Roku home screen)
5. Re-enter the Jellyfin app and Live TV section. See "Channels" view instead of "TV Guide"

## Expected behavior

I expect the app to remember my preference for "TV Guide"

## Logs

N/A

## Screenshots

N/A

## Connection Information

- Is server local or remote? *Local*
- Is server connection HTTP or HTTPS? *https*

## Additional context

N/A

**Comment by jimdogx** [comment]
The Roku client uses your Web Client preferences for some items.  Including this one 😄
