### ISSUE TITLE
Finishing a video crashes the app

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#203]
**Describe the bug**
Allowing an episode or video to play till the end, causes an error and crashes the app

**To Reproduce**
1. Play an episode
2. Allow it to play till the end
3. observe

**Expected behavior**
I'm returned to the screen i came from (home in this case)

**Logs**
```
Suspending threads...
Thread selected:  0*   pkg:/source/VideoPlayer.brs(235)        m.device.EnableAppFocusEvent(False)

Current Function:
232:  function StopPlayback()
233:    video = m.scene.focusedchild
234:    video.control = "stop"
235:*   m.device.EnableAppFocusEvent(False)
236:    video.findNode("playbackTimer").control = "stop"
237:    video.visible = "false"
238:  STOP
239:    if video.status = "finished" then MarkItemWatched(video.id)
Interface not a member of BrightScript Component (runtime error &hf3) in pkg:/source/VideoPlayer.brs(235)
```

EDIT: This is using the latest version of master

**Comment by neilsb** [comment]
I am currently getting that errror message when exiting a video using the back button during playback as well.

**Comment by cewert** [comment]
m.device is invalid so all calls to it in VideoPlayer will error out. Looks like an easy fix but this used to work so trying to figure out what happened
