### ISSUE TITLE
Improve github issue templates

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#204]
Now that we are pushing to the beta channel, we have multiple versions of the software and are seeing more issues created. Ask the user to provide all necessary info for troubleshooting bugs 

Adding jellyfin server and client version to bug template
Whether server is local or remote
http vs https

**Comment by neilsb** [comment]
Would be useful to capture the **Model** and **Software Version** information from the  _Settings -> System -> About_ menu.

**Comment by cewert** [comment]
@anthonylavado are you still working on this?
