### ISSUE TITLE
Preview "About this Item" episode page

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#21]
Add a detail page for a TV episode

**Comment by jimdogx** [comment]
Are there additional TV episode details currently not shown with the latest client?  Just looking at old issues that could be worked on (or closed) and this one is really light on details (pun not intended).

**Comment by neilsb** [comment]
Closing this due to lack of feedback.  If this is still required please re-open this issue or raise a new one.
