### ISSUE TITLE
Unable to access servers using Self Signed Certificate

### ISSUE THREAD

**Issue by neilsb** [jellyfin-archive/jellyfin-roku-legacy#218]
When attempting to use a Jellyfin server using a Self Signed certificate (or invalid in any other way) the client shows the generic "Server not found" message.

**Expected behaviour**
The ability to ignore _Invalid Certificate_ errors, or at the very least a more helpful error message detailing the problem is an invalid certifcate.

**Comment by neilsb** [comment]
It seems an invalid certificate can be ignored when performing a manual call to a URI, but not when setting the URI of an image or media stream.   As the app could allow the user to log in and browse the media on a server with a Self Signed (or invalid) cert, but would not display any images or play any media.

**Comment by thornbill** [comment]
Just saw this issue. I don’t think any of our apps currently support self signed certs. Android might be possible to add at a system level, but we don’t explicitly support them.

**Comment by duckinator** [comment]
I ran into this issue last night. If it can't be properly supported, it'd be nice to at least get a more-accurate error ("invalid certificate" or something instead of "server not found").

**Comment by neilsb** [comment]
So a little more information on Self Signed Certificates.

When using SSL, the certificate must be valid with respect to the issue and expiry dates.  Any certificate that is not yet valid or expired will just plain not work.

When making calls to an API (etc), there is the option to tell Roku to ignore the hostname match and issuer check, which _would_ allow the use of Self Signed certificates to communicate with the Jellyfin server.  However when getting any media off the server (e.g. Images, Video or audio streams, etc) then there is no option to disable these checks, meaning 2 things:

1. The server host name the client is connecting to must be a valid host name in the certificate being used
2. The certificate must be issued by a trusted Certificate Authority

There is no option to install a new trusted CA at a device level, but it _can_ be done at a channel level.  This is intended to allow Content Companies to include their self signed certificate within the channel distribution files, and then use that when making requests for Media.

Since there's very little non-volatile storage available for channels, it is not really possible to have the Jellyfin channel to download the CA certificated used for a self signed certificate and store that for all future calls.  The only option would be to modify Jellyfin server to allow clients to download the CA certificate from it, and then use that.   With added the complication of the volatility of the storage we have access to, meaning it may have to be re-downloaded frequently.

Give the prevalence of free, trusted SSL certificates these days (from the likes of LetsEncrypt, etc) I don't think it's worth the additional effort at this point to try and put something together to allow self signed certificates to be used.  If there is enough demand then this can be revisited and discussed with the server team.

For now PR #409 will add better feedback when connecting to the server, so the reason for a failure (e.g. invalid or self signed certificate) will be displayed to the user.
