### ISSUE TITLE
Alphanumeric navigation

### ISSUE THREAD

**Issue by jcdick1** [jellyfin-archive/jellyfin-roku-legacy#224]
Match the alphanumeric navigation along the right side of the library screens to quickly jump to that alphabetically listed section of titles in the library.

**Comment by candry7731** [comment]
This is Currently being worked on. #564 adds alpha filter to the options screen under filter tab
 #563 Will add alpha to the grid screens for jump to letter

**Comment by neilsb** [comment]
Closed via #540

**Comment by jcdick1** [comment]
I have to say, with the flurry of activity lately, I'm really looking forward to the next version release.
