### ISSUE TITLE
HDR Support

### ISSUE THREAD

**Issue by cgibson33** [jellyfin-archive/jellyfin-roku-legacy#225]
On TCL 615 Roku TV,
When testing video file with HDR content, on EMBY app, HDR video is displayed, but this is not the case when testing with the Beta Jellyfin app.
Using latest stable release of Jellyfin 10.5.5 on windows.

**Comment by neilsb** [comment]
Just to confirm, you are able to play the HRD video on the Jellyfin app, but the output is not in HDR?

If so, could you check the server while it is being played, and see if the output is being transcoded?  I suspect this is to do with the Device Profile that we are using for the client right now, and the issue may be resolved in the linked livetv PR where we have added a basic Device Profile.  But this still needs refining.

**Comment by cgibson33** [comment]
Yes it plays fine.
However, when I play it using the Emby app, the TV OS confirms that it is playing an HDR file by showing the “HDR” logo, which is not the case for the Jellyfin app.  So probably a device profile issue if the jellyfin app just uses the native file player on the Roku TV OS.  I have a ryzen 2200G processor, so no doubt it is capable of transcoding a 4k HDR stream.

To confirm that the video stream is being transcoded, what is the easiest way to check?

**Comment by cgibson33** [comment]
I found that I could just determine transcoding vs direct streaming by just checking the dashboard.
Confirmed that the server is transcoding when using the Jellyfin Beta app, and direct streaming when using the Emby app.
