### ISSUE TITLE
Ability to turn on/off subtitles and select audio track

### ISSUE THREAD

**Issue by dathbe** [jellyfin-archive/jellyfin-roku-legacy#232]
**Describe the feature you'd like**

There does not appear to be a way, when selecting a media file, to tell the player whether you want subtitles or which audio track you would like to use.

**Additional context**

**Comment by neilsb** [comment]
For now, you can set the Subtitles to use by pressing the down arrow when the content is playing.

**Comment by dathbe** [comment]
Confirmed.  Thanks.  I never would have thought to try that.  Is there a similar way to select alternative audio tracks?

**Comment by neilsb** [comment]
Not yet.  Subtitle and audio track selection will be available soon from the screen before starting the video, as well as a more polished way while the movie is playing.

Stay tuned 😊

**Comment by subchromat** [comment]
Has any progress been made towards this?

**Comment by jimdogx** [comment]
Audio tracks can now be selected for Movies and TV shows (where more than one audio track is available).  I believe this issue can be closed.
