### ISSUE TITLE
Nested folders no longer working in 1.3.0

### ISSUE THREAD

**Issue by lravelo** [jellyfin-archive/jellyfin-roku-legacy#233]
**Describe the bug**
Movies in nested folders no longer showing up (I.e., James Bond collection folder and all movies inside. James Bomd collection exists in the movies folder)

**To Reproduce**
Selected the library containing my movies and inside were only the movies not nested. This is not an issue on Jellyfin web or iOS client.
**Expected behavior**
I expect to the these movies in nested folders just like the web and iOS clients

**Comment by anthonylavado** [comment]
When you say "no longer working", was it working before?

**Comment by lravelo** [comment]
> When you say "no longer working", was it working before?

Yes this was working in 1.2.0

**Comment by neilsb** [comment]
I think I can see the problem.

@lravelo - Can I just check that in the Library Settings (_Dashboard -> Libraries -> Display_) you have the **Group movies into collections** option selected?

**Comment by lravelo** [comment]
> I think I can see the problem.
> 
> @lravelo - Can I just check that in the Library Settings (_Dashboard -> Libraries -> Display_) you have the **Group movies into collections** option selected?

Yes I do have that checked but I don't have any collections set up in Jellyfin. I just have the physical folder structure for it (I.e., /mnt/media/movies/James Bond Collection/...)

**Comment by HahUK** [comment]
Hi, I just wanted to add that I also have this issue on 1.3, Movies in nested folders do not show up. I do not have the Group movies into collections option selected and toggling it doesn't make any difference. I did have one or two manual collections created. Removing those did nothing to change the behaviour either.

I can test the referenced PR if that would be useful to you?

Thanks

**Comment by neilsb** [comment]
If people are happy to try out any of the PRs and give us feedback that would be brilliant.

We can do our best to replicate issues and do fixes, but feedback from people who genuinely face the problems is invaluable.  Whether in the PRs (although we know that takes a fair bit of effort from users, so really appreciate that), the beta versions or even the live releases.

The more feedback we get, and the earlier we get it, the better.  😊

**Comment by nodux7** [comment]
I just noticed I had this problem as well. I use top level folders for organizational purposes and am now missing over half my library in the app.

If I'm understanding correctly, the API call for loading "items" is now set in `components/ItemGrid2/LoadItemsTask2.brs` and no longer being called with "recursive: true" ?

**Comment by neilsb** [comment]
> I just noticed I had this problem as well. I use top level folders for organizational purposes and am now missing over half my library in the app.

Apologies if this is a stupid question, but I'm a former Plex user rather than an Emby user, so bear with me. :) 

When you say "top level folders" is that the physical disk folder view, which is enabled from the _Dashboard_ -> _Libraries_ -> _Display_ -> _Display a folder view to show plain media folders_ option?
 
> If I'm understanding correctly, the API call for loading "items" is now set in `components/ItemGrid2/LoadItemsTask2.brs` and no longer being called with "recursive: true" ?

That is correct.  The _recursive_ option doesn't actually seem to do anything.  I'm checking what's happening in the backend with this option, but on all my testing so far the same results are returned irrespective of the recursive flag.

The is definitely a problem that the new item grid was displaying "folders" (or collections).  So any movies grouped into a collection would just not be displayed.  This has been resolved by #234 which is just waiting for some testing and merging.

**Comment by nodux7** [comment]
> When you say "top level folders" is that the physical disk folder view, which is enabled from the _Dashboard_ -> _Libraries_ -> _Display_ -> _Display a folder view to show plain media folders_ option?

Yes. I do not actually use this folder view in Jellyfin though.

> That is correct. The _recursive_ option doesn't actually seem to do anything. I'm checking what's happening in the backend with this option, but on all my testing so far the same results are returned irrespective of the recursive flag.

My brief testing showed "Folder" items returned for directories not containing a unique item.
```
[...]
"IsFolder": "true",
"Type": "Folder",
[...]
```
The _recursive_ option was necessary to include the items contained under them.

It seems like you're conflating "Folders" (filesystem structure) and "Collections" (purely metadata?)

**Comment by neilsb** [comment]
Sorry, yes - I get it now and can see what you mean when doing the API call.  I misunderstood what you were saying, thinking you were seeing a "Folder" item within Jellyfin, and I was struggling to replicate that.

So yes, the recursive parameter is required, and I'll get it added to the PR.

**Comment by lravelo** [comment]
> If people are happy to try out any of the PRs and give us feedback that would be brilliant.
> 
> We can do our best to replicate issues and do fixes, but feedback from people who genuinely face the problems is invaluable. Whether in the PRs (although we know that takes a fair bit of effort from users, so really appreciate that), the beta versions or even the live releases.
> 
> The more feedback we get, and the earlier we get it, the better. 😊

Forgive my ignorance. What are PR's and how can I test them? Would love to be able to contribute in any way that I can to make this app better.
