### ISSUE TITLE
Missing Audio on H.265

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#235]
**Describe the bug**

[_From Reddit:_](https://www.reddit.com/r/jellyfin/comments/g9vowy/jellyfin_now_on_roku_beta/fvmobma/) 
> Uninstalled, reinstalled, same issue. Appears H.265 encoded videos no longer have audio just video. H.264 seem ok so far in testing. They all used to work fine when I first installed Jellyfin beta. Current Jellyfin Beta 1.3 Build 0
>
>System: Roku 4630X Premiere+ Software 9.3.0 Build 4170-29

**To Reproduce**
Playback H.265 media with FLAC audio.

**Expected behavior**
The audio plays.

**Additional Information**
Note that the user said it worked prior to the latest version.
Here is media info from the user:

>They are flac stereo audio, 16 or 24bit. I'm willing to do some testing if you have a new build to try out.
>Here are two examples.

**Video**
**Title** 480P HEVC
**Codec** HEVC
**Profile** Main 10
**Level** 90
**Resolution** 710x480
**Aspect ratio** 4:3
**Interlaced** No
**Framerate** 29.97003
**Bitrate** 1823 kbps
**Pixel format** yuv420p10le
**Ref frames** 1

**Audio**
**Title** Eng FLAC stereo
**Default Language** eng
**Codec** FLAC
**Layout** stereo
**Channels** 2 ch
**Sample rate** 48000 Hz
**Bit depth** 16 bit
**Default** Yes

---

**Video**
**Title** 1080P HEVC
**Codec** HEVC
**Profile** Main
**Level** 120
**Resolution** 1920x1080
**Aspect ratio** 16:9
**Interlaced** No
**Framerate** 23.976025
**Bitrate** 7836 kbps
**Pixel format** yuv420p
**Ref frames** 1

**Audio**
**Title** Eng FLAC stereo
**Default Language** eng
**Codec** FLAC
**Layout** stereo
**Channels** 2 ch
**Sample rate** 48000 Hz
**Bit depth** 24 bit
**Default** Yes

**Comment by RazeLighter777** [comment]
This problem isn't exclusive to FLAC, OPUS does not work either from my testing.

**Comment by MaxPelly** [comment]
I can confirm OPUS doesn't work via the ROKU app but seems to work fine if you stream through the ROKU media player
