### ISSUE TITLE
SubRip MKV Subtitle Not Displaying

### ISSUE THREAD

**Issue by Cmdrd** [jellyfin-archive/jellyfin-roku-legacy#242]
**Describe the bug**
Playing MKV files with embedded SubRip subtitles are not displaying at all, even when selected from hitting the down button.

**To Reproduce**
Play any MKV file with embedded SubRip subtitles.

**Expected behavior**
Subtitles to be shown when playing content. 

**Additional context**
Have tried disabling and enabling "Allow subtitle extraction on the fly" on the server as per [this](https://www.reddit.com/r/jellyfin/comments/g9vowy/jellyfin_now_on_roku_beta/fox90bh/) suggestion as well as pausing media for a while to allow extraction to catch up as per suggestions in [this](https://www.reddit.com/r/jellyfin/comments/g6gl4a/embedded_subtitles_not_working/) thread.

Subtitles work properly in the web client so this does appear to be an issue specifically with the Roku player.

**Comment by neilsb** [comment]
Just had a look, and presently selecting an Subtitle Track does not change the Roku setting for whether subtitles should be shown.

Could you, after selecting a subtitle track, press the * button and set _Close Captioning_ to _On Always_ and just confirm that the subtitles are shown?

We need to manage that setting from within the Jellyfin app, but it would be good to confirm there is nothing fundamentally wrong with the way we retrieve the subtitles.

**Comment by Cmdrd** [comment]
That seems to be doing the trick, thank you! Didn't know about that option while playing content. Only downside is that skipping around appears to put things out of sync but I will keep doing some testing.

**Comment by anthonylavado** [comment]
@neilsb Looks like design decisions from #172 and #173 coming back to get us then

**Comment by neilsb** [comment]
It is not a great system IMHO, and apps seem to be all over the place on how they implement it.

Some [guidelines from roku](https://developer.roku.com/en-gb/docs/developer-program/media-playback/closed-caption.md#custom-control-settings) would suggest that you just set the global settings when displaying them.

**Comment by neilsb** [comment]
So looking through #172, I don't think much needs changed.  How about:

- When starting Playback if either our logic or Roku's setting say we should show subtitles, the global setting is set to On
- When a subtitle track is selected with the client, the global setting is turned on
- When subtitle track is set to None the global setting is turned off  (Same as when user changes the Roku Setting to Off)

And if the user selects Instant Replay (or only when muted) from the Roku settings, then the subtitles will be showing during the appropriate period only if a Subtitle track is already selected (from our rules or the user manually having selected one).

**Comment by anthonylavado** [comment]
@neilsb That makes perfect sense IMO. 💯
