### ISSUE TITLE
"Form key or value length limit 2048 exceeded." error with Roku *Movies* library

### ISSUE THREAD

**Issue by captainzonks** [jellyfin-archive/jellyfin-roku-legacy#251]
**Describe the bug**

When selecting the _Movies_ category from My Media on the Jellyfin Roku app's home page the library fails to load (appears empty) and the controller cannot navigate out of the failed screen (the standard "failed" sound effect is played); all buttons on the remote emit the same error sound, except for the system Home button which is the only way to escape the failed library. Upon re-entering the Jellyfin app it restores at the home page. The _TV Shows_ media library functions properly and loads. The _Movies_ library also loads just fine when accessed via a browser on a desktop.

Movies are accessible through the Up Next selection, or if placed in a Collections. For example, currently all the Star Wars films are in my Movies library. If I place them all into a Collection, I can access them there successfully.

**To Reproduce**

1. Go to 'Jellyfin' app on Roku
2. Click on 'Movies' under My Media
3. See error as described

**Expected behavior**

Expecting the _Movies_ library to display selections and options like the _TV Shows_ library does.
_Movies_ library loads as expected on PC browser.

**Logs**

```
[14:54:35] [ERR] Error processing request
System.IO.InvalidDataException: Form key or value length limit 2048 exceeded.
   at Microsoft.AspNetCore.WebUtilities.FormReader.ReadChar(Char separator, Int32 limit, String& word)
   at Microsoft.AspNetCore.WebUtilities.FormReader.TryReadNextPair()
   at Microsoft.AspNetCore.WebUtilities.FormReader.ReadNextPairAsyncImpl(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FormReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Emby.Server.Implementations.Services.ServiceHandler.GetFlattenedRequestParams(HttpRequest request)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by captainzonks** [comment]
The error appears to be with the default key/value length limit in FormReader, as described here,
https://stackoverflow.com/questions/43305220/form-key-or-value-length-limit-2048-exceeded

the defaults can be seen here:
https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.WebUtilities/FormReader.cs/

**Comment by neilsb** [comment]
We came across a problem with the form key length in relation to the Device Profile, and have switched switched from forms in PR #239, which will be in the next release of the client.

Interesting that you're getting this when browsing a movie collection though, as the request for the contents of a library should be comparatively small.  I'll look into this before closing this issue, but if you're able to install the dev version and test it that would be great.  If not, don't worry about it.  We should get a new release out shortly with a number of fixes.

**Comment by captainzonks** [comment]
> We came across a problem with the form key length in relation to the Device Profile, and have switched switched from forms in PR #239, which will be in the next release of the client.
> 
> Interesting that you're getting this when browsing a movie collection though, as the request for the contents of a library should be comparatively small. I'll look into this before closing this issue, but if you're able to install the dev version and test it that would be great. If not, don't worry about it. We should get a new release out shortly with a number of fixes.

I got the dev build on my Roku and I can confirm that this issue is not present. No changes made to the library, exact same server. Dev build accesses the _Movies_ library just fine.

**Comment by anthonylavado** [comment]
Okay. I might push it to both Beta and Release at the same time then.

**Comment by ZoomStop** [comment]
So no need to install the Beta channel to get this patch earlier? This bug is the only one I really have, but have been able to replicate it across three different Roku devices.

**Comment by neilsb** [comment]
> So no need to install the Beta channel to get this patch earlier? 

Unfortunatly this fix isn't in the beta version yet.  We hope to get a release to the main channel out shortly to address this.

**Comment by captainzonks** [comment]
I wouldn't celebrate just yet, either. I tried to play Star Trek (2009) last night, 4k H.265 10bit with Atmos 7.1, and it failed to play on the Roku Ultra. No sound at all, and the 10bit HEVC failed completely with green globular pixelated junk all over the screen. Only way to get it to play was by enabling conversion settings on the server, but this made the 10bit color compressed into total garbage (colors were squashed badly, reds were nasty and flat, brightness was odd and dimmed down, whites weren't white; I'm assuming HDR color just can't be squished to SDR properly?). Not watchable.

Different bug entirely, though, from the library failing to load.

**Comment by neilsb** [comment]
@captainzonks Can I just confirm that this was using the dev version, and that there wasn't any reference to Form Key length in any errors your may have seen?    Happy to get this into another ticket though. :)

**Comment by captainzonks** [comment]
Yes, I've got the dev version on my Roku Ultra currently. The "Form Key Length" bug as I initially reported is non-existent in the dev build. I can load the _Movies_ library just fine now.

**Comment by neilsb** [comment]
@captainzonks  Version 1.3 Build 5 has just been approved on the store.  There was a issue with knowing what Audio could be decoded which was fixed in this release (that I don't believe was in the beta version).

Since the issue specifically affected Audio, when you get a moment could you check if the error is resolved with this latest version, and let us know?  If it hasn't we'll track it in another bug since it isn't due to the form length issue. :)

**Comment by captainzonks** [comment]
Wanted to followup. I have the new dev build on my Roku Ultra and I just watched _A Fistful of Dollars_ last night. Things seem to be working. I haven't had any fails yet. If I encounter anything I'll make a post again!

Thanks!
