### ISSUE TITLE
Select files crash out after retieving bar reaches the end

### ISSUE THREAD

**Issue by nlMeminger** [jellyfin-archive/jellyfin-roku-legacy#252]
**Describe the bug**
When playing select movies or shows the "retrieving" page comes up and after it reaches the end it crashes back down to the movie/show info page.  This only seems to affect certain files and only on the Roku app as the affected files can be played on browser/phone app

**To Reproduce**
1. go to 'any movie'
2. click play

**Expected behavior**
file plays

**server logs**
```
$ cat /var/log/jellyfin/jellyfin20200716.log | grep 22:40
[2020-07-16 22:40:01.087 -04:00] [WRN] HTTP Response 200 to "172.16.1.32". Time (slow): 0:00:03.118441. "http://172.16.1.11:8096/Videos/8398886d3f9c15dab1fc27bf02dcf56b/hls1/main/2.ts?AudioCodec=aac&BreakOnNonKeyFrames=True&h264-profile=high%2Cmain%2Cbaseline%2Cconstrainedbaseline&MaxAudioChannels=6&MediaSourceId=8398886d3f9c15dab1fc27bf02dcf56b&MinSegments=1&PlaySessionId=75e522b0c05f43d1a1ae6f82725be284&RequireAvc=false&SegmentContainer=ts&SubtitleStreamIndex=2&VideoCodec=h264"
[2020-07-16 22:40:01.435 -04:00] [ERR] Error processing request. URL: "http://172.16.1.11:8096/Sessions/Playing/Progress"
[2020-07-16 22:40:01.726 -04:00] [ERR] Error processing request. URL: "http://172.16.1.11:8096/Sessions/Playing/Stopped"
[2020-07-16 22:40:04.164 -04:00] [ERR] Error processing request: "A task was canceled". URL: "http://172.16.1.11:8096/Videos/8398886d3f9c15dab1fc27bf02dcf56b/hls1/main/3.ts?AudioCodec=aac&BreakOnNonKeyFrames=True&h264-profile=high%2Cmain%2Cbaseline%2Cconstrainedbaseline&MaxAudioChannels=6&MediaSourceId=8398886d3f9c15dab1fc27bf02dcf56b&MinSegments=1&PlaySessionId=75e522b0c05f43d1a1ae6f82725be284&RequireAvc=false&SegmentContainer=ts&SubtitleStreamIndex=2&VideoCodec=h264"
[2020-07-16 22:40:04.166 -04:00] [WRN] HTTP Response 500 to "172.16.1.32". Time (slow): 0:00:02.9591157. "http://172.16.1.11:8096/Videos/8398886d3f9c15dab1fc27bf02dcf56b/hls1/main/3.ts?AudioCodec=aac&BreakOnNonKeyFrames=True&h264-profile=high%2Cmain%2Cbaseline%2Cconstrainedbaseline&MaxAudioChannels=6&MediaSourceId=8398886d3f9c15dab1fc27bf02dcf56b&MinSegments=1&PlaySessionId=75e522b0c05f43d1a1ae6f82725be284&RequireAvc=false&SegmentContainer=ts&SubtitleStreamIndex=2&VideoCodec=h264"
```

**Comment by anthonylavado** [comment]
Could you provide us with the Media Info from one of the affected movies?
You should be able to get it from the "three dot" menu in the web interface. Thanks!

**Comment by nlMeminger** [comment]
I've included 4 movies that I know are affected [here](https://pastebin.com/YbBjdfEG)

**Comment by neilsb** [comment]
@nlMeminger Version 1.3 Build 5 has just been approved on the store.  There was a issue with knowing what Audio could be decoded which was fixed in this release (that I don't believe was in the beta version).

When you get a moment, could you check if the error is resolved with this latest version, and let us know either way?  Thanks.

**Comment by SoftoLibre** [comment]
I'm on 1.3 build 5 and still having playback issues with certain files that work fine from the web browser. The "Retrieving" bar doesn't even finish before it pops up the error message "Error During Playback: An error was encountered while playing this item."

Here is the mediainfo from one of the files:
General
Unique ID                                : 196278985129064632927199014602036230639 (0x93A9F51E280A4AF688E78948099839EF)
Complete name                            : Removed.For.Privacy.Reasons.mkv
Format                                   : Matroska
Format version                           : Version 1
File size                                : 233 MiB
Duration                                 : 21 min 56 s
Overall bit rate                         : 1 483 kb/s
Encoded date                             : UTC 2007-12-08 14:02:34
Writing application                      : mkvmerge v2.0.2 ('You're My Flame') built on Feb 21 2007 23:40:55
Writing library                          : libebml v0.7.7 + libmatroska v0.8.1

Video
ID                                       : 5
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 11 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 11 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 21 min 56 s
Nominal bit rate                         : 1 349 kb/s
Width                                    : 704 pixels
Height                                   : 528 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.145
Writing library                          : x264 core 56 svn-680
Encoding settings                        : cabac=1 / ref=8 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=umh / subme=7 / brdo=1 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=2 / deadzone=21,11 / chroma_qp_offset=0 / threads=6 / nr=0 / decimate=0 / mbaff=0 / bframes=5 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=3 / wpredb=1 / bime=1 / keyint=250 / keyint_min=25 / scenecut=40(pre) / rc=2pass / bitrate=1349 / ratetol=1.0 / rceq='blurCplx^(1-qComp)' / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / pb_ratio=1.30
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 6
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 21 min 56 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Title                                    : AAC 128 Kbps
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 1
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Norsk
Language                                 : Norwegian
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 2
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Svensk
Language                                 : Swedish
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Dansk
Language                                 : Danish
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Engelsk
Language                                 : English
Default                                  : No
Forced                                   : No

**Comment by 1hitsong** [comment]
Please try again using the latest server and Roku client versions. If it's still not working, please open a new issue and we'll investigate.
