### ISSUE TITLE
Moving People Off The Beta

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#253]
I think we should try to move as many people _off_ the beta as possible. If there's an easy way to add in a message pop up or similar, I think we should do it.

I'll look into ways that I could maybe "pull" the beta temporarily, and then re-instate it later.

**Comment by neilsb** [comment]
Certainly should be easy enough to do.  Multiple ways of cutting it depending on how _annoying_ it should be.

Can easily add a standard Dialog message box with an OK button for a short message.  Or could redirect to a completely new screen if we want to provide a longer message (and changes in the current beta etc).

Easy enough to show it every time, the 1st time for a new version, or give them a checkbox to now show it again (until the next release maybe).

It looks like you can launch another app from within your app.  So with a small amount of work we could potentially have a beta version that launches the main channel if there are no new beta features at the time.  (i.e.  Release 1.4.0 to both at the one time, then any time the beta is opened all it does it loads live 1.4 - Then release 1.5 beta when we're ready and it will start working as "normal").  Think you can check that another channel is installed too, to provide a friendly message that the live one needs installed if it is not currently.

**Comment by anthonylavado** [comment]
Short message, first time only sounds good to me! 👌

**Comment by anthonylavado** [comment]
This is kind of done since the beta is staying closer in line with production, etc.
