### ISSUE TITLE
Films media group doesn't work

### ISSUE THREAD

**Issue by abudden** [jellyfin-archive/jellyfin-roku-legacy#255]
**Describe the bug**

On my Jellyfin server, I have three Libraries.  One is called "TV Shows" of type "TV Shows".  One is called "Films" of type "Movies" and one is called "Collections" of type "Mixed Content".  If I open either "TV Shows" or "Collections" in the Roku app, I get the list of things to watch.  If I open "Films", I get a blank screen and the app becomes unresponsive.

I can open the films collection in the web browser: it works fine there.  If I add a film to a collection I can open it from the "Collections" library in the Roku app and watch it.  If a film isn't in a collection, then I can't watch it on the Roku app.

**To Reproduce**

1. Go to Jellyfin Roku app
2. Click on "Films"
3. Blank screen (with "Films" title at the top) appears and app becomes unresponsive until I press home button

**Expected behaviour**

I expected to see the list of films.

**Logs**

I don't know how to do this.

**Screenshots**

**Additional context**

I don't know if this is relevant, but at some point the "loading" time when starting a tv show or film increased dramatically.  It was taking a few seconds to buffer but now takes up to 2 minutes.  This change occurred after I had initially installed the beta and I assume it happened when the beta was upgraded automatically.  I've since switched to the production release but exactly the same happens.  I only mention this as it might be related to latency in the connection to the server (although they're connected with ethernet cables so it should be a very good link).

I still really appreciate the release of Jellyfin for Roku by the way: I used to use emby and it would crash the Roku (and cause it to reboot) halfway through most TV shows.

Sorry if the details are a bit vague: I can add any more information you need (logs etc) if you can tell me how to get it.

**Comment by neilsb** [comment]
I think this is the same issue as we see in #251, which we believe we have resolved in PR #239.   It should be fixed in the next release (either beta or live) which I hope we can get out very soon.

**Comment by abudden** [comment]
Great news, thank you!
