### ISSUE TITLE
Live TV and PVR Functionality

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#26]
Add functionality for TV/PVR

**Comment by Artiume** [comment]
What's missing for this?

**Comment by anthonylavado** [comment]
Literally the implementation. I don't think we have any reference to go off of.

@jellyfin/roku - If you need help with a Live TV source, we have a feed you can add to your server for testing.

**Comment by sumppump** [comment]
> Literally the implementation. I don't think we have any reference to go off of.
> 
> @jellyfin/roku - If you need help with a Live TV source, we have a feed you can add to your server for testing.

Is there any potential to have LiveTv added soon to the release? We migrated from emby and some customers are itching to get this function on their Roku's.

**Comment by anthonylavado** [comment]
@sumppump Roku is a unique platform that uses its own scripting/programming language. We are grateful to have these few volunteers that created this app from the ground up. We'll always keep improving it, but this is one where we can't really set a timeline just yet. If you know any other BrightScript programmers, send them our way!

**Comment by azagon63** [comment]
I've made some changes to very basically support livetv on [this fork](https://github.com/Musi13/jellyfin-roku/tree/livetv-support), but I don't intend to make a PR for a few reasons:
* I haven't done any proper testing with normal tuners (I'm using a [plugin](https://github.com/Musi13/jellyfin-plugin-streamlink) I wrote to stream from twitch.tv)
* I don't really know BrightScript well (this is the first thing I've done)
* I'm rather new to Jellyfin development, so I dont know much of the codebase or logic flow

Anyway, it lets you browse and watch channels, but it doesn't do anything with recording/tv guide/etc. I thought I'd post it in case some of the jellyfin-roku devs want to use it as a reference.

**Comment by anthonylavado** [comment]
@Musi13 Thank you for this! @neilsb has been investigating behind the scenes so anything helps :-)

**Comment by neilsb** [comment]
@Musi13 That's great.  The branch doesn't appear to work against the standard LiveTV in Jellyfin, but I suspect it will just be a few small changes to sort that.  I'll look at getting your plugin installed locally to ensure that it's working with any comitted changes.

Thanks!

**Comment by azagon63** [comment]
@neilsb Thanks for picking this up; I wouldn't worry about making sure the plugin works, since it might handle streams differently  (I had to write a new stream wrapper to handle subprocess output). If you can get the roku part working with the standard tuners, I can go back in the plugin and fix the compatibility issues

**Comment by Artiume** [comment]
can you test the `Force LiveTV Transcoding` option in user profiles? It should work out of the box hopefully

**Comment by azagon63** [comment]
It seems to work fine, streams still play, and I can see transcoding logs in the jellyfin (server) output where before it was directly playing. I didn't look at how its implemented though, maybe `POST Items/{id}/PlaybackInfo` returns something different

**Comment by neilsb** [comment]
Sorry, yes - seems to work.  Had a problem with my setup.

**Comment by Protektor-Desura** [comment]
Live TV is working well for me. Just would like to see the guide in the Roku client now.

**Comment by Protektor-Desura** [comment]
If you need something to feed IPTV then check out my script to pull in Pluto TV via M3U and XMLTV. 
https://github.com/Protektor-Desura/PlutoIPTV

**Comment by anthonylavado** [comment]
@Protektor-Desura Thanks for linking that! I was going to ask about it. I have some feeds already from my antenna/TVHeadend setup, and I believe @neilsb has something, but this is good for anyone else who needs to test it.

**Comment by starbearnine** [comment]
I see that the Live TV guide is working in Jellyfin on the Roku. Is it possible in the Roku Jellyfin app to set the tv guide as the default mode when live tv is opened? Right now when I close the app and open it again it defaults back to channel icons instead of the tv guide.

**Comment by neilsb** [comment]
> Is it possible in the Roku Jellyfin app to set the tv guide as the default mode when live tv is opened?

It should use the setting defined in your profile on Web.  So if you go into your settings, select home, then for the Live TV section, set the default page to _Guide_.
