### ISSUE TITLE
IPTV Streams Not available on jellyfin-roku

### ISSUE THREAD

**Issue by kershs01-home** [jellyfin-archive/jellyfin-roku-legacy#262]
I have a number of http ip live streams that I can playback in the web browser that was setup using the IPTV Streams plugin in jellyfin. This feature also works in the jellyfin android app.

When I try to access the iptv streams on roku it displays a box saying "This library type is not yet implemented"

I understand that this app is still in its early stages but could this feature please be added to a future release?

**Comment by neilsb** [comment]
I've got a PR to fix this ready to submit, but just need PR #278 to be merged first.
