### ISSUE TITLE
Include Audio and Video File Details on Movie/Episode page

### ISSUE THREAD

**Issue by SoftoLibre** [jellyfin-archive/jellyfin-roku-legacy#264]
**Is your feature request related to a problem? Please describe.**

When displaying the page for a specific movie or episode, it would be great to see details about the file. A competing closed-source app displays this information for each file on its movie/episode page, and it helps a great deal with home theater configuration.

**Describe the solution you'd like**

Most important file details (to me) are the video/audio codec (Eg. DTS 5.1, x265, etc.) because I have to change settings on my A/V receiver to resolve lipsync issues depending on the audio and video codecs being used.

**Describe alternatives you've considered**

**Additional context**

**Comment by jimdogx** [comment]
Was going to look in to this issue, however, this appears to already be fixed / working in the latest release.  Unless I'm missing something, I suggest we close this issue.  @SoftoLibre ?

**Comment by SoftoLibre** [comment]
I just checked on my Roku TV, and the codec info does display for movies, but not for TV episodes, so we are not quite there yet IMO.

**Comment by jimdogx** [comment]
> I just checked on my Roku TV, and the codec info does display for movies, but not for TV episodes, so we are not quite there yet IMO.

Ah! I must have just looked at Movies.  My bad.

I'll take a stab at adding these to TV episodes this weekend.
