### ISSUE TITLE
App crashes when updating poster to designate as watched.

### ISSUE THREAD

**Issue by aniformafax** [jellyfin-archive/jellyfin-roku-legacy#266]
The Roku app crashes when updating posters after watch. This behavior happens less frequently when it updates the poster after watching something, but can be far more frequent when you manually select the material as "watched". Happened to me at least 3/5 times attempting it.

1. Select a show or movie
2. Select "Watched" button
3. As the poster updates to include the check mark designating it as watched, app crashes.

**Comment by neilsb** [comment]
Can I just check this is on the latest Roku client?   As presently there's not a way of marking a show as watched and also the posters don't show the watched status on them right now.

**Comment by aniformafax** [comment]
This was on Roku, but shortly after placing a ticket, the feature disappeared from the app altogether. I had assumed it was addressed when it vanished.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by neilsb** [comment]
OK - thanks for replying.   A new "Movie", "Episode" and "Show" page will be coming along _soon_, and the logic will have code for manging the poster and status will change significantly for this.   So for now I'll just close the issue.
