### ISSUE TITLE
Update menu layout based on User menu settings configuration

### ISSUE THREAD

**Issue by scottAnselmo** [jellyfin-archive/jellyfin-roku-legacy#270]
**Is your feature request related to a problem? Please describe.**

When updating the menu layout to my needs (Settings -> Menu) for my user profile by doing things like removing sections like "Recently Added", it's reflected in Android and Web apps, but not Roku despite power cycling. It seems like Roku is stuck on the default layout

**Describe the solution you'd like**

When loading the menu layout for a User, poll the server for the layout configuration and render accordingly

**Describe alternatives you've considered**

Have tried power cycling the Roku just to be sure it wasn't some sort of caching bug

**Additional context**

N/A

**Comment by neilsb** [comment]
Think this is a duplicate of #158?

**Comment by scottAnselmo** [comment]
Closing as is duplicate; find similar issues feature didn't catch, apologies
