### ISSUE TITLE
Ability to sort movies/shows/etc

### ISSUE THREAD

**Issue by duckinator** [jellyfin-archive/jellyfin-roku-legacy#276]
**Describe the feature you'd like**

I'd like to be able to sort movies/shows/etc based on at least:

- name
- run length
- release date

**Additional context**

There is a way to get a sort menu by hitting the `*`/options button on the Roku remote when viewing a list of movies/shows/etc, but it doesn't appear to actually work.

**Comment by bisby** [comment]
This has actually been updated to work, but hasn't been deployed to the store yet.

**Comment by duckinator** [comment]
Awesome, in that case I'll go ahead and close this. :+1:
