### ISSUE TITLE
Ability to Select Version of movie

### ISSUE THREAD

**Issue by benshroyer** [jellyfin-archive/jellyfin-roku-legacy#280]
In the Roku Version 1.3 build 5, the option to select different versions is not available like on the Web or the Android versions of the app. 

I have followed the naming procedure as outlined in the [official documentation](https://jellyfin.org/docs/general/server/media/movies.html) and it does work in Chrome 86.0.4240.75, FF 81.0.2, and Android 2.0.1

**Comment by neilsb** [comment]
Currently the client does not allow selecting of a Version or Audio Stream (although Audio Stream Selection is now in PR #275).

As a work around, do different versions of the same movie not currently appear as different Posters when browsing the Movie Grid?  I know it's not ideal in that on the grid page it doesn't show which version it is you're selecting, but it may work as a short term fix until we get this implemented.

**Comment by benshroyer** [comment]
Some show multiple posters, some do not.

**Comment by Artiume** [comment]
If you `Group Versions`, they'll show as a single poster and when you select the movie, it'll show the option. If you've `Group`ed them, it's impossible to select a version via roku. Grouping can be done by multi-selecting or by using the ` - name` system.

![test](https://user-images.githubusercontent.com/20715731/100456489-73218d00-308e-11eb-9d88-eb4a432bac85.png)

**Comment by itsb** [comment]
Related to this issue - and covered in the same official documentation - [movie extras](https://jellyfin.org/docs/general/server/media/movies.html#movie-extras) are also not visible in the roku app.

**Comment by jimdogx** [comment]
This was actually fixed recently with PR #533  @neilsb please close at your convenience. 👍
