### ISSUE TITLE
[Feature] Attempt https

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#283]
When entering domain name, it will attempt http:// and 8096. it should also attempt https:// and 443

**Comment by jcdick1** [comment]
I would say that even with a port specified, it should probably start with an HTTPS attempt before dropping back to HTTP, by default.

**Comment by Fyb3roptik** [comment]
http is default because the server is http by default. You cannot force https as default when someone hasnt set it up at all, that is bad design. I am however making a PR to fix this, so that way if it SHOULD be https it will remap it automatically
