### ISSUE TITLE
Mixed Content type isn't supported

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#284]
Mixed Content library is unselectable, however content can be played via its Latest Media section

**Comment by neilsb** [comment]
Should be fixed by #282, which will be in the next release.   Can wait to confirm before closing this.

**Comment by Artiume** [comment]
cool,  one bug down. let me find more 🥰

**Comment by neilsb** [comment]
Mixed content collections now browsable in v1.4.5, currently in the Roku channel store
