### ISSUE TITLE
Add support for series

### ISSUE THREAD

**Issue by mushkevych** [jellyfin-archive/jellyfin-roku-legacy#286]
**Describe the feature you'd like**
I want to be able to select an episode; currently I can only play the first one;

**Additional context**
Web application provides a convenient drop-down list, which would be a great feature for the TV App
![github-roku-issue-1](https://user-images.githubusercontent.com/1039233/98487298-03c72480-21d7-11eb-9dbf-aff014628f35.jpg)

**Comment by neilsb** [comment]
If you choose a TV Show, and then select a Season you should get a list of Episodes to choose from.

Selecting an episode from the "Continue", "Next up" or "Latest In" groups, will play the episode shown.  But it you browse to the "TV Shows" collection and select a Show from the Grid, you will have the option of choosing a season and then an episode.

The Design for the TV Show and Episode List will be changing in the near future.
