### ISSUE TITLE
"Releases" on Github page not updating to current

### ISSUE THREAD

**Issue by jcdick1** [jellyfin-archive/jellyfin-roku-legacy#301]
The current latest release on Github is shown as 1.3.0, while the latest in the Roku store is 1.4 (Build 5).  Just thinking it might be a good idea to update that for people who might need to sideload a particular version due to regressions or other issues, or just want to know the current version and what the changelog is.

**Comment by neilsb** [comment]
Yup - sorry about that.  Release info for 1.4.5 added now.
