### ISSUE TITLE
Loop episode list - up arrow from first to get to last last and reverse

### ISSUE THREAD

**Issue by cskaryd** [jellyfin-archive/jellyfin-roku-legacy#304]
For TV shows with dozens of episodes per season, it would be nice to be able to loop from the top to the bottom quickly.  Clicking up once from the first episode to get to the last or clicking down from the last episode to jump back up to the first.

Deep Space 9 Season 6 had 26 episodes.  That a lot of clicks to get to episode 25.

Daily Show Season 25 had 160 episodes.  

Other Roku apps seem to allow for this endless looping when hitting either end of the list, so it should be possible

**Comment by neilsb** [comment]
There's plans to revamp the TV Show pages, but this should be considered as part of that work.
