### ISSUE TITLE
Jellyfin Logo offset

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#308]
The upper left logo sits too low and is almost touching the bottom border.

![20201121_065115](https://user-images.githubusercontent.com/20715731/99876660-2dfce700-2bc6-11eb-9159-8daf5dc5dda9.jpg)

**Comment by neilsb** [comment]
The top left of the logo is as close to the top corner as [roku recommend](https://developer.roku.com/en-gb/docs/specs/graphics.md#safe-zones).

So I guess the Overhand bar should be taller or the logo smaller.   I kind of like the ideal of removing the background to the bar altogether.....

**Comment by Artiume** [comment]
removing the bar itself might be the better choice

**Comment by cewert** [comment]
The background of the overhang is meant to provide contrast for when the screen background switches from the default dark grey to a full screen backdrop image. Some backdrop images are white and would make it near impossible to read any text from the overhang.

**Comment by cewert** [comment]
It looks a different strategy is being used in `ItemGrid2` with an opacity filter on the whole background image. I was thinking more load the background as is and then add filters behind the text as needed when I made the overhang.

So yea if that's the plan with the full screen images then I vote to get rid of the overhang background too. Would be an easy way to make things look nicer and we might even gain some room by not needing padding by the divider.
