### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by benshroyer** [jellyfin-archive/jellyfin-roku-legacy#309]
An option similar to other streaming platforms that logs out the active user after retuning to the Roku menu so that when relaunched the select user screen is presented. This timeout could be relatively short, but not instant to prevent frustration from accidentally hitting the menu button and having to navigate back to your media you were watching.

**Comment by loganmarchione** [comment]
Also looking for something like this. Right now, I'm using two users (myself and wife) without passwords. However, because it doesn't sign out between watch sessions, one of us might end up watching something on the other's profile...
