### ISSUE TITLE
Play Count and Played Checkbox Slightly Offset

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#312]
The check mark and numbering is slightly off center.

![20201124_224600](https://user-images.githubusercontent.com/20715731/100181048-760e5900-2ea7-11eb-812f-24c0a4bc48b5.jpg)

**Comment by neilsb** [comment]
This is technically a server problem, as that is part of the image returned by the server when the Roku client requests the poster to show the played status/count.

That said, the desire is to have the Roku Client show the status and unplayed count itself, to save having to reload the poster images so frequently  (Currently played status is not shown at all on the new library grid view).

Additionally, there are plans for a new "TV Series Detail" page which will also take into account #21.  So this should work itself out when these are addressed.

**Comment by dkanada** [comment]
I wonder what other clients are using this, it shouldn't exist in my opinion.

**Comment by Artiume** [comment]
![20201127_100951_7622764791902394121_20201127101544](https://user-images.githubusercontent.com/20715731/100463309-a1589a00-3099-11eb-8f58-3f4e28354d31.jpg)

I'm down with removing the backend functionality. it appears to be buggy anyways.

**Comment by cewert** [comment]
I made an issue for this last year on the main jellyfin repo but nothing ever came of it

https://github.com/jellyfin/jellyfin/issues/1888

**Comment by anthonylavado** [comment]
So we used to use this in the server for Android TV, but don't anymore. There's only one third party client that uses it (to my knowledge). It's lower on the priority scale at the server side.

That said, if it helps to fix it up for now, I'll see about getting it fixed. If it's easy enough to re-implement or re-imagine on the Roku side, that might be the way to go.

**Comment by cewert** [comment]
So this was fixed server side apparently but is still happening for me? and it also seems like someone implemented a custom checkmark/unplayed count but yet we are still using both methods?

![PXL_20230319_150906564 MP](https://user-images.githubusercontent.com/16514652/226197436-2ee1d4c6-6c93-4bf7-88bb-d408db22f8a1.jpg)

**Comment by 1hitsong** [comment]
Fixed by #1547
