### ISSUE TITLE
Login flow doesn't follow HTTP->HTTPS redirects

### ISSUE THREAD

**Issue by strugee** [jellyfin-archive/jellyfin-roku-legacy#316]
**Describe the bug**

If the user accidentally enters an HTTP URL but the server is HTTPS (and redirects port 80 HTTP to port 443 HTTPS), Jellyfin thinks things are ok but at login time, presents an error. Note that this is easy to run into if you hit #283 and simply delete the port but don't touch the scheme.

**To Reproduce**

1. Install the app
2. Make sure `https://jf.example.org` works
3. Use the "Change server" option and log in with `http://jf.example.org` instead
4. Hit "Submit"
5. Try to login with your credentials
6. Notice the error that pops up about the login not working

**Expected behavior**

Jellyfin follows the server's redirect and logs me in over HTTPS.

**Logs**

I don't see an easy way to extract logs from the Roku?

**Screenshots**

N/A

**Additional context**

N/A

**Comment by Fyb3roptik** [comment]
Working on a PR for this now
