### ISSUE TITLE
Resuming episodes from dialog screen causing loss of focus

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#323]
Resuming TV episodes from the home screen causes loss of focus when returning back to the home screen.
Same thing when resuming an episode from the season episode list - loss of focus when returning.

I believe I've tracked this down to the `lastFocus `change done in #311 - the issue starts to appear with commit 6bab4b719eb658d9c67862f820ff151e6044c79f  which means there could be more bugs lurking wherever else the lastFocus was changed

**To Reproduce**

1. continue watching an episode from the homescreen
2. hit back
3. observe

**Expected behavior**
Previous focus is restored

**Logs**
N/A

**Screenshots**
N/A

**Comment by neilsb** [comment]
Setting focus when a screen is displayed is currently done from the main function.  I feel it would be better if every screen that was shown (or re-shown) handled it's own focus.  Possible ensuring each screen had a `SetFocus()` function that could be called when it was displayed, and it could then choose what item to set focus to.   It could then be responsible for managing the last thing focused if it wanted to set the focus to that again, or just pick a starting item to focus on.

This is obviously a bigger change for the future.

**Comment by cewert** [comment]
Makes sense to me. As long as it doesn't break anything :smile: Should make #290 easy to do (I think)
