### ISSUE TITLE
1.0 Release Scope

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#33]
We should set the scope for a 1.0 release. I imagine this could be tracked as a GH project, but would help us prioritize and focus.

**Comment by fabianvf** [comment]
This would definitely be great, I generally like to make an issue with a roadmap on it and then create a GitHub project based on that, I find just using projects too hard to organize in my head.

**Comment by RealOrangeOne** [comment]
Before opening a dedicated issue for it, I presume this is what's blocking pushing to the roku app channel store?

Although, IMO, it's better to get something up there sooner rather than later. No way i'm getting my family to do the manual install process!

**Comment by anthonylavado** [comment]
@RealOrangeOne The app requires more work than is currently listed before it would:
- be considered fully functional
- pass any testing that Roku would likely perform

We should define this scope though...
In the meanwhile, we still welcome any contributor to this platform who wishes to help 🙂
