### ISSUE TITLE
Error playing video, works from Jellyfin web interface

### ISSUE THREAD

**Issue by Mr-Chimp** [jellyfin-archive/jellyfin-roku-legacy#341]
**Describe the bug**
I go to play a video in the Roku app and it gives an 'Error during playback' error stating an error was encountered, yet whilst viewing videos in the JellyFin web interface I can watch without issue. I have tried removing the Jellyfin channel from Roku and added it again but the error still persists. This may be related to https as that is the only thing I have changed recently on the server, I updated the Roku app to connect using the new https URL (as opposed to IP address) and can log-in without issue just have the problem with playback. The SSL certificate is done by LetsEncrypt and the URL points to a Nginx reverse proxy if that is useful.

**To Reproduce**
Just try to play any video file

**Expected behavior**
The video plays without issue

**Logs**
Logs from Jellyfin server related to this: https://pastebin.com/72g2DQyn

**Additional Context**
I tried using the Beta app to see if this issue is fixed but that just wouldn't even let me play a video, I could browse them but pressing ok on a video just made the Roku "beep" noise and did nothing, no error or anything. 

Thank you

**Comment by neilsb** [comment]
Are you connecting to the server from a local network, or over the internet?  Was the IP address beforehand a local IP address too?    

My guess it is to do with the Reverse Proxy, but not exactly sure what yet.

**Comment by Mr-Chimp** [comment]
I am connected over the local network but using a web accessible URL that points to my static IP (for the https bits). Beforehand it was connecting using the local IP Address. 

Here is the reverse proxy config: https://pastebin.com/JqZed7rG with the domain name redacted, something I did think was weird in the web interface it mentions the https port being 8920 but in the proxy file (which I got from the JellyFin help pages) it just uses 8096, could that be the cause?

**Comment by Artiume** [comment]
8920 is if you want https without a reverse proxy. in a sane configuration, jellyfin connects to a local reverse proxy via 8096 then the proxy reterminates it with https as configured.

**Comment by Mr-Chimp** [comment]
@Artiume Thanks for that clarification.

I have made some new discoveries and it appears that only avi files that don't play, mkv files play without issue. I have not been able to check any other file types yet.

Below is the media info (from Jellyfin web app) from one of the avi files that wouldn't play in case that gives any useful info:
```
Container avi
Size 153 MB

Video
Title SD MPEG4 SDR
Codec MPEG4
Codec tag DX50
Level-99
Resolution 352x240
Aspect ratio 22:15
Interlaced No
Framerate 29.97
Bitrate 912 kbps
Video range SDR
Pixel format yuv420p
Ref frames 1

Audio
Title MP3 - Stereo
Codec MP3
Layout stereo
Channels 2 ch
Bitrate 63 kbps
Sample rate 22050 Hz
Default No
```

**Comment by Finnspiration05** [comment]
I have the same problem

**Comment by yoonst** [comment]
Experiencing same issue with SD MPEG4 SDR video.
```
TitleSD MPEG4 SDR
CodecMPEG4
Codec tagxvid
```

**Comment by 1hitsong** [comment]
We've made several improvements to video support. We've about to push further updates in the 1.6.2 update. Please retest once it's released and if it's not working for you, open a new ticket.
