### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#342]
When performing a search, the roku app is 2x to 3x times slower than web at rendering results from the server.

**Comment by joshstubble** [comment]
This x1000. Jelly roku search feature is unusable on every client I've tried

**Comment by neilsb** [comment]
Search has been improved in latest client release (1.4.12).  Search will likely get a complete overhaul at some point, but should hopefully be usable for now.  If you're still having issues, let us know.
