### ISSUE TITLE
CPU usage through the roof on Roku Client Stream

### ISSUE THREAD

**Issue by joshstubble** [jellyfin-archive/jellyfin-roku-legacy#345]
**Describe the bug**
I'm noticing huge spikes in my VM's cpu usage when someone fires up a roku stream watching Live TV. Seems to be fine for downloaded movies and tv shows. 

Just one client on roku pushes my cpu usage pass 60%. 

I've had 3 clients mix of iOS and web streaming tv the without seeing that big of a spike. 

Running through docker on Ubuntu.

**Comment by Artiume** [comment]
we'll need more details such as is the stream being transcoded on each client.

**Comment by neilsb** [comment]
Suspected transcoding when not required.  Due to lack of additional information or response, closing issue.
