### ISSUE TITLE
No acepta ningún servidor 

### ISSUE THREAD

**Issue by Negro735** [jellyfin-archive/jellyfin-roku-legacy#347]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Remplazando algunos archivos como son el de servidor la aplicación funcionaria al 100 %

**Comment by ferferga** [comment]
@Negro735 ¡Hola! ¿Qué problema tienes exactamente? 

No entiendo muy bien tampoco a qué te refieres con lo de reemplazar el archivo del servidor.

**Comment by Negro735** [comment]
Mira compré una pantalla hisense de rocu y la app no me acepta ningungun
servidor disculpa la molestia no se mucho de el tema de ustedes pero si se
cambiar una aplicación por otro soy policía pero me gusta realizar mis
actividades como te comento no se demaciado de ese tema se un poco de
electrónica pero casi nada de sistemas  descargue la aplicación en mi
celular y es lo mismo no agarra ningún servidor ya ví 100 videos y no puedo
solucionar dicho problema PERO SI ESO ES UN PROBLEMA DISCULPAME NO FUI MI
INTENCIPN MOLESTAR

**Comment by ferferga** [comment]
@Negro735 Tienes problemas solo con Roku? Puedes acceder desde el navegador correctamente?

Recuerda que la dirección por defecto es http://IP_DEL_SERVIDOR:8096/jellyfin

Puedes comprobar la IP de tu servidor usando el comando ipconfig en Windows o ifconfig en Mac/Linux

Por favor, sé más concreto en cuál es el problema exactamente si esto no te ayuda a resolver el problema: que has hecho hasta ahora para resolver el problema, que has intentando, que ha salido bien, que no...

Con la información que das es imposible entender exactamente qué es lo que ocurre.

**Comment by Negro735** [comment]
Ya  le intruje un servidor pero me pide un usuario y una contraseña

**Comment by Negro735** [comment]
Pero me rechaza las q le he metido

**Comment by jimdogx** [comment]
@Negro735 Haz podido usar el Roku?  Este issue es del 2020.  Si ya no necesitas ayuda, me gustaría cerrar este issue.

**Comment by jimdogx** [comment]
Closing as I asked for feedback over a month ago.  I have to assume this is no longer an issue.
