### ISSUE TITLE
movies appear in web view but not roku

### ISSUE THREAD

**Issue by cpankonien** [jellyfin-archive/jellyfin-roku-legacy#348]
A number of movies (13) appear in the web view, but do not appear in the Roku movies menu. 

Go to "movies'" in jellyfin.
Movies that appear in the web interface are not listed in the Roku movies menu.

Both views should match.

No errors noted in logs.

I have been unable to determine any commonality between those that show up in one view and not the other, seems random.

**Comment by neilsb** [comment]
Is it always the same movies that do not appear?  If you change the Sort Order for the Movies Library on the Roku is it different movies that are missing?  (Wondering if it's to do with way we load "pages" from the server - maybe we're off by one or something)

**Comment by cpankonien** [comment]
Roku seems to show the first 29 movies shown in web view in A-Z sort, then shows the last 25 shown in web view in Z-A sort. 

Roku Z-A sort,  last 25 movies. Roku A-Z sort, first 29 movies. Web view A-Z, 42 movies, web view Z-A sort, 42 movies. 

Hope that makes sense!

**Comment by jimdogx** [comment]
@cpankonien is this still an issue?

**Comment by cpankonien** [comment]
No idea, I haven't used jellyfin in along time, sorry.

------- Original Message -------

**Comment by jimdogx** [comment]
No worries.  Going to go ahead and close this issue.  If anyone else experiences this in the latest build, we can open a new issue.
