### ISSUE TITLE
Videos won't play when TV connected to AVR via HDMI ARC

### ISSUE THREAD

**Issue by christianlegge** [jellyfin-archive/jellyfin-roku-legacy#353]
**Describe the bug**
Videos will not play on my Roku TV Jellyfin channel while it's connected to my receiver with HDMI ARC. I get the loading bar, then within 1-2 seconds it backs out to the menu, as if the media has finished. If it's a series it will jump straight to the next episode instead where the same thing happens. Sometimes the first frame or two of the media will play before abruptly ending, but it's hard to tell as most things I'm trying to play open with a silent black fade-in.

I have a HiSense 55' Roku Smart TV which I'm using the Roku Channel on, and a Yamaha RX-V385 receiver which is connected via HDMI ARC and an optical cable. If I unplug the HDMI cable the issue fixes itself. The issue is present whenever the HDMI cable is connected, whether or not the optical cable is.

Previously I was able to work around the issue by pressing the pause button while the loading bar was on screen and waiting a few seconds before playing, but in the last couple days this has stopped working and I've been forced to unplug the HDMI cable.

**To Reproduce**
1. Connect a receiver to the TV with an HDMI cable with an ARC channel.
2. Go to the Jellyfin channel and try to play any media.

**Expected behavior**
The media loads and then plays from the beginning.

**Logs**
Not sure if there's any way to get log files from the Roku TV. I had a look around the server dashboard and don't see any relevant errors. Nothing at all is produced in the server log file.

**Additional context**
This issue was discussed in [this Reddit thread.](https://old.reddit.com/r/jellyfin/comments/klf4ld/cant_play_anything_on_roku_channel/)

**Comment by jimmygle** [comment]
Having the same issue with my HiSense 55" and Yamaha RX-V479.

**Comment by christianlegge** [comment]
Alright, I know why this bug is happening, but I don't know why the why is happening.

When a video node exists in Roku it has a `position` field that tells Roku how far along it is in the playback. This is (of course) set to 0 at the beginning of playback normally. However, for some reason, when the observer event for the `state` field fires at the beginning of playback - when its state changes to `playing` (line 440 of Main.brs) - the position field has been set to 0xFFFFFFFFFFFFFFFF (or very close to it - I couldn't figure out how to print its true value and it truncates a few digits early). I cannot for the life of me figure out why this happens, and I'm not entirely sure it's happening as a result of anything Jellyfin is doing. As a result, it updates the playback state, thinks the playhead is far beyond the end of the video, and ends playback.

As a workaround, if I give it a second to begin playing before updating that playback state, it will set the position correctly and work fine. This can be accomplished by adding a `sleep` call right before that happens, and I've done so [in a branch on my fork](https://github.com/scatter-dev/jellyfin-roku/blob/wont_play_fix/source/Main.brs#L441). The sleep is entirely invisible to the user, as playback starts immediately, this is just waiting to update the internal playback state. This is what I'll be using until I can get some more insight as to what's going on here.
