### ISSUE TITLE
Respect Audio Preference Setting

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#356]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Roku should respect the Audio preference from a user's settings. Noticed the issue with media that has English as the secondary (also not the default) audio track.

![Screenshot_20210118-043547_Jellyfin](https://user-images.githubusercontent.com/20715731/104900510-2188d680-594a-11eb-8291-9db815a05031.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by eprouty** [comment]
Adding a vote for this as well. Would be nice to have audio track selection but this at the least would solve the problem for Roku users.

**Comment by BrushieStroke** [comment]
I'd really like this too. Currently it seems that Roku has its own internal settings for selecting what it deems to be the best track, but I'd **really** like a way to change the audio track manually during playback, without going into any kind of deeper settings on roku itself that might affect stuff outside of Jellyfin. This would be a **huge** quality of life improvement for me.

**Comment by jimdogx** [comment]
This should be fixed with #1252
