### ISSUE TITLE
Search doesn't release focus

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#359]
**Describe the bug**

If you use the search feature, you are unable to navigate the app after pressing back. 

**To Reproduce**

Actually searching isn't required, merely going to the search page will cause the homepage to be unusable After watching a movie via the search function, the home page will still be unusable. Forcing me to exit to the Roku Home and reenter the app to restore functionality.

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by neilsb** [comment]
Are you seeing this consistently?  I've tried the following, and every time when I get back to the home screen it works fine:

All starting from Home Screen

1. Options -> Search -> Back (Close Keyboard) -> Back (To Home Screen)
1. Options -> Search -> Enter Text -> Search -> Back (To Home Screen)
1. Options -> Search -> Enter Text -> Search -> Into Movie Details -> Back (To Search Results) -> Back (To Home Screen)
1. Options -> Search -> Enter Text -> Search -> Into Movie Details -> Play Movie -> Back (To movie Details) -> Back (To Search Results) -> Back (To Home Screen)
1. Options -> Search -> Enter Text -> Search -> Into Movie Details -> Play Movie -> Let movie finish and return to Movie Details -> Back (To Search Results) -> Back (To Home Screen)
