### ISSUE TITLE
Change app icon for beta version

### ISSUE THREAD

**Issue by Germs2004** [jellyfin-archive/jellyfin-roku-legacy#367]
**Describe the feature you'd like**
I installed the release version and the beta version of Jellyfin on Roku side by side, and they both have the same graphical icon on the Roku's home page.  I suggest changing the graphical icon of the beta version to include the word "beta" to differentiate the two icons.

**Comment by anthonylavado** [comment]
They do as of future betas - we haven't run one in a long time so this has not been rolled out to users. I'll see if we can change it or not. We have thought about a mechanism to "reset" the beta by removing everyone from it, or advising when the release is outdated.

**Comment by Germs2004** [comment]
Maybe the beta version could update to the release version if the release version is newer than the beta.  That way, a person could install only the beta app, and they would always have the latest version (beta or release), so they don't have to keep both apps (beta and release) installed on their Roku and switch between them.

**Comment by anthonylavado** [comment]
We're planning on pushing something out to beta shortly, so it will largely match up.
