### ISSUE TITLE
Static Analysis/Certification Test Issues

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#372]
A new release has been created for the beta channel based off of PR #370.

There are some Static Analysis warnings (as usual), but most importantly, there was a failure in Certification Testing.

## Static Analysis Results
Number | Message                                                                                                                                                               | Severity | Category        | Certification requirements
-------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|-----------------|---------------------------
1      | "PlayDuration" is only supported when used with the TimeGrid component. All other uses have been deprecated. Path: /components/data/ScheduleProgramData.brs. Line: 11 | Warning  | DeprecatedAPIs  |
2      | "PlayDuration" is only supported when used with the TimeGrid component. All other uses have been deprecated. Path: /components/liveTv/ProgramDetails.brs. Line: 107.  | Warning  | Deprecated APIs |

## Certification Testing

Certification Tests:

Number | Test title                       | Status | Severity | Category     | Certification requirements | More information
-------|----------------------------------|--------|----------|--------------|----------------------------|-------------------------------------------
1      | Channel Launch Performance       | Fail   | Error    | Performance  | 3.2                        | Launch time exceeds 20s.
2      | Channel Deep Linking Basic       | Skip   | Error    | Deep Linking | 5.1                        | No valid deep linking parameters.
3      | Channel Content Play Performance | Skip   | Error    | Performance  | 3.6                        | Skipped due to no deep linking parameters.

As always, all Certification Requirements can be viewed here:
https://developer.roku.com/en-ca/docs/developer-program/certification/certification.md

### Notes
The deep linking stuff can probably be safely ignored for now. It hasn't affected us yet during submission.

**Comment by neilsb** [comment]
PlayDuration is only used in the TimeGrid.  We reference it in the Program Details screen in the TimeGrid as well, but that should be fine.  Think both of those can be ignored.

It appears that the Channel Loaded Beacon is not set in some cases when the user removed the display of the "Latest In" via the web interface.  Will update so that the Channel Launch beacon is fired after we show the standard rows on the home screen (Libraries and Continue Watching).

**Comment by FullHDSG** [comment]
I'm having similar issues
Error    Deep Linking    5.1
Error    Performance    3.6
Warning    Automation    4.4
Warning    Automation    4.5
