### ISSUE TITLE
Adding TV Show (group) to a collection adds TV show (group) to collections folder. 

### ISSUE THREAD

**Issue by pinovecs** [jellyfin-archive/jellyfin-roku-legacy#375]
**Describe the bug**
When adding a TV Show group (example Agents of Shield) to an overall collection (Marvel MCU) the TV show appears in the collection correctly, but it also appears in the base Collections view as well.

**To Reproduce**

1. Create a Collection containing Movies and TV Shows
2. Add a TV Show (group of seasons) to the Collection
3. TV Show will appear in the collection, but also in the root collections folder.

**Expected behavior**
I feel the TV Show group should NOT appear in the root folder

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by neilsb** [comment]
Just to check that I'm seeing the same thing as you.   If I start with no collection, and select a TV show and add it to a new collection, then on the home page a get a new Library called "Collections"

When I go into this library on the Roku, I see the new collection I created, plus another "Collections" folder.  If I go into that Collections folder, I see the new collection I created again.   If I create another new collection I see that in the root of the "Collections" library, as well as in teh "collections" folder in that Library.

Is that what you are describing too?

If so, it sounds like the fix is that the when you select the "Collections" Library from the home screen, the "Collections" folder in that should not be displayed.

**Comment by pinovecs** [comment]
I think we are talking the same thing, but I'll try to re-describe it.  I'll be honest I didn't have an empty collections folder to start, but this is what I did specifically.

I have three sections in my view.  "Movies" "Collections" and "TV Shows - Series" (this contains groups of episodes) compared to movies which are single instances.

If in the root of collections I create a new item.  In this case I created "Marvel".  I then went to my movies and added "Iron Man".  In the "Marvel" collection I see "Iron Man" appearing correctly and only in the collection.   Now I go to the TV Series section and find "Agents of Shield" and add that to the same "Marvel" collection.  If I go to the "Marvel" collections folder now I see "Agents of Shield" appearing correctly in that Collection. 

Here is the problem, if I go back to the "root" of the collections section I see two entries one for "Marvel" which is correct and one for "Agents of Shield".   Personally I don't think that should be there, but I will admit I'm still learning JellyFin.

I will add on the Web Interface I only see "Marvel" in collections.  I do not see Agents of Shield so the web interface is operating the way I felt the Roku should operate.

I hope I'm helping to explain it, but let me know.  Thanks for getting back to me.

**Comment by neilsb** [comment]
> If in the root of collections I create a new item. In this case I created "Marvel". I then went to my movies and added "Iron Man". In the "Marvel" collection I see "Iron Man" appearing correctly and only in the collection.

Can I check how you're doing this?   Are you working with folders, or is this though the Web UI?  I can't recall a way of making a collection first and then adding something to it.  Generally you'll select a movie, choose "Add to Collection", then from the collection dropdown select "New" and give it a title.

When I add a movie and TV show to a new collection, it displays the same as on the website, with the exception of an additional _Collections_ folder when I go into the Collections library

![image](https://user-images.githubusercontent.com/5013482/109335564-1f276f80-785a-11eb-8d6d-b6d3949c12cf.png)

**Comment by neilsb** [comment]
I believe the collection `folder` is no longer shown in the latest client release (1.6.1).  If this has not resolved your problem please re-open this issue.
