### ISSUE TITLE
Subtitles force default Audio track

### ISSUE THREAD

**Issue by ceejjay** [jellyfin-archive/jellyfin-roku-legacy#376]
Enabling subtitles seems to forcibly set the audio track to default. 

I use mkv files with multiple audio streams and subtitle tracks. (Multi lingual family) We’d like to change the audio to track to and be able to use subs from different languages. 

I can change audio tracks without issue, as long as I leave the subs off. 

But selecting a subtitle track will force the audio back to its default audio track. I think it’s trying to bake the subs on the fly, and just doesn’t care about audio track while doing so? I’m not sure. 

repro steps:
1) Load a file with multiple audio and subtitle tracks. 
2) Use the Roku menu to change audio tracks
— observe language has changed 
3) press down and select a subtitle track. 
— video plays default audio track with selected subs
4) open Roku menu (*) observe audio track setting
— Audio is set to default and cannot be changed. 

Disabling subtitles will allow you to change audio tracks again.

**Comment by turosian** [comment]
I have a similar problem with my dual-language files, except when I switch to the english subtitles, it plays default audio, but does not enable subtitles.

**Comment by neilsb** [comment]
I've not been able to replicate this locally.

Could you let me know if the video you are using is being transcoded by the server?  If you select the Audio track via Jellyfin, before playing the video (assuming this is a Movie) then can you change subtitle tracks without the track switching back to the default?

**Comment by neilsb** [comment]
Closing due to no response and being unable to replicate.  If this is still an issue please re-open.
