### ISSUE TITLE
Embedded Subtitles Not Displaying

### ISSUE THREAD

**Issue by Queuecumbr** [jellyfin-archive/jellyfin-roku-legacy#386]
**Describe the bug**

Embedded subtitles are not displaying when selecting a subtitle language in the menu.

**To Reproduce**

1. Play a video through other means such as through the web app or through DLNA that is not through the Roku.
2. Verify subtitles are working for that method.
3. Play the same video using the Roku Jellyfin app.
4. Select the desired subtitle language by pressing down during playback.
5. Ensure closed captions are enabled through the Roku settings.
6. Embedded subtitles are not displayed.

**Expected behavior**

Embedded subtitles should be displayed. When testing with the latest build on master, external .sbr subtitles work, but embedded ones do not when playing on a Roku, even though subtitles are displayed properly when playing using different clients. This seems to be a similar issue to the current release with external subtitles not being displayed that was fixed by #385. 

**Logs**

[https://pastebin.com/Ev7r5Qdj](https://pastebin.com/Ev7r5Qdj)

Most notable error in the output seems to be 

`[2021-03-19 03:09:51.690 -06:00] [INF] Not eligible for DirectPlay due to unsupported subtitles`
`[2021-03-19 03:09:51.690 -06:00] [INF] Not eligible for DirectStream due to unsupported subtitles`

**Additional context**

Specific Roku model is the Roku Ultra. I am also available to sideload and test any potential builds. Let me know if you need more information from me or if there is somewhere I can be of use.

**Comment by christianlegge** [comment]
Do external srt subtitles work for you? I haven't tried sbr but neither external srt nor embedded mkv (which look to be provided in srt format by the Jellyfin server) work for me.

**Comment by neilsb** [comment]
Note Server v10.7.2 has now been released, that should resolve the text subtitle issue with the current live client.  We are still waiting for approval for the Roku Channel Store the the updated client.
