### ISSUE TITLE
Particular HEVC video won't play properly 

### ISSUE THREAD

**Issue by christianlegge** [jellyfin-archive/jellyfin-roku-legacy#387]
**Describe the bug**
When playing a particular HEVC video, it flashes green colors at the beginning, and stutters and freezes a few seconds later. The problem persists even when seeking through the video. If left to play, the video will unfreeze and display the correct image will show, but only for a second or two before the problem repeats. While frozen, it looks like the screenshot below. Note that other HEVC files play perfectly, this is not a problem I've found with any others.

**To Reproduce**
This issue does reproduce consistently, with hardware decoding on or off. It is specific to the Roku app; the same video file plays normally through through Chromecast to the same TV, and the web client. If I find a way to reproduce this with a file I'm able to share, I'll share it; this is a feature film so I can't just upload and link it. 

**Expected behavior**
The video to play normally.

**Logs**
- [ffmpeg directstream log file](https://gist.github.com/scatter-dev/e88146b08bf68425c98866bfee6ed2bc)
- [mediainfo for the video being played](https://gist.github.com/scatter-dev/adb4b3dd191961f3e2c30ab1eaa59d01)

**Screenshots**

![](https://cdn.discordapp.com/attachments/279864711107969046/822981020948103168/PXL_20210320_234904592.jpg)

**Additional context**
55" HiSense Roku TV, RX-V385 AVR connected via HDMI ARC.

**Comment by anthonylavado** [comment]
I just want to say - thank you for including the media info. That's a huge help.

**Comment by conorm125** [comment]
I am also having a similar issue with one of my movies where my screen looks similar to the image above when  I play it on my TV via the Roku Streaming stick plus. The error does not happen when I play it on my PC with the desktop application. My PC does not support HDR my TV does, I have other H256 HDR movies that play fine.
Here is an extract off my FFmpeg Direct Stream log:
...
Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2076 [SAR 1:1 DAR 320:173], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS             : 29805237
      BPS-eng         : 29805237
...
    Stream #0:1: Audio: dts (DTS-HD HRA), 48000 Hz, 7.1, fltp (default)
    Metadata:
      title           : French DTS HR MA 7.1
      BPS             : 2045999
      BPS-eng         : 2045999
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (dts (dca) -> aac (native))
...

**Comment by pinovecs** [comment]
I think I'm experiencing a similar issue, but it occurs on only ONE of my Roku Ultra devices.  I have a 2019 Roku Ultra and a 2020 Ultra.  I can always produce the problem with the older 2019 Roku and have never had it on the 2020.

I know I'm not helping much, but I wanted to provide the data point.

**Comment by neilsb** [comment]
Would be possible to test this on the latest client release please 1.4.12?    Thanks.

**Comment by christianlegge** [comment]
@neilsb Roku reports the version as 1.4 build 12 which I assume is the same thing. The bug persists.

**Comment by neilsb** [comment]
@scatter-dev Yeah, that's the same version.  Thanks for confirming, I'll take a look at it.

**Comment by 1hitsong** [comment]
@christianlegge We pushed several new user settings that adjust how HEVC videos are handled on Roku. Does this video now work using the latest Roku client after adjust the HEVC playback settings?

**Comment by christianlegge** [comment]
@1hitsong Yes, it does work now! I'll go ahead and close. Thanks!
