### ISSUE TITLE
Add Episode Count or Completed indicator to TV Series and clean up the watched/count icons.

### ISSUE THREAD

**Issue by aaronmartin1651** [jellyfin-archive/jellyfin-roku-legacy#388]
I would like to see how many episodes (or percentage) of a TV Series I have watched or whether I have completed a series.  You can see this on the Seasons of the TV Series but not on the Series screens.  Also, the light blue bubble that is semi-transparent is difficult to see an several of the images.  Could it be enhanced in some way to make it more visible regardless of the background it is against?  When a series is completely watched personally I would prefer no icon whatsoever to a checkmark.  I only need notifications if there are episodes I haven't watched.

**Comment by neilsb** [comment]
Closing in favour of #402, which encompasses this and also includes request for watched status for Movies
