### ISSUE TITLE
Add Extended Detail to Items

### ISSUE THREAD

**Issue by aaronmartin1651** [jellyfin-archive/jellyfin-roku-legacy#389]
The web ui shows you the full description for an episode as well as the cast and crew.  Would like the web ui ability to also be present in the roku app so that I can see what else the actor is in and perhaps jump to that content.

**Comment by anthonylavado** [comment]
To recap for later use:
- Detail view should add Cast and Crew
- Detail view needs "More Like This" items
- Should apply to Movie and TV Shows library types

**Comment by johnmmcgee** [comment]
Air date would be pretty cool as well, for TV Shows.  The ability to see an extended detail of the show summary.  It currently is cut off.

**Comment by jimdogx** [comment]
I believe this was recently fixed via PR #520 .  @neilsb if you agree, please close at your convenience 👍
