### ISSUE TITLE
Play/Watched/Favorite buttons do nothing on Movie

### ISSUE THREAD

**Issue by christianlegge** [jellyfin-archive/jellyfin-roku-legacy#394]
**Describe the bug**
When I go into a movie and press OK on the Play, Watched, or Favorite buttons, nothing happens. The roku "button clicked" sound plays, but nothing else. I'm still able to play movies from the main screen (under "Latest Movies"), but also cannot press play on the movie ItemGrid menu.

My testing shows this was a regression introduced with #382, specifically commit [9e77bc9](https://github.com/jellyfin/jellyfin-roku/pull/382/commits/9e77bc9a60715b0f9cf9a2837fc429c223fa9747). @neilsb Your help would be valuable here. 

Hisense 55" Roku TV.

**Comment by neilsb** [comment]
Yup - that's a pretty bad one. :(
