### ISSUE TITLE
Fast forward and rewind are non-functional

### ISSUE THREAD

**Issue by Qiangong2** [jellyfin-archive/jellyfin-roku-legacy#396]
**Describe the bug**
Whenever you try to fast forward in the ROKU app, it will act likr it's fast forwarding. However, when you click play, it will automatically jump back to the beginning.

**To Reproduce**

1. Open video
2. Fast forward
3. Play
4. Video startd from the beginning

**Expected behavior**
You can fast forward

**Comment by neilsb** [comment]
I'm unable to reproduce this currently.  

- What version of the app are you seeing this behaviour on?
- What Roku device are you using?
- Is this the case on all videos, or just some?
- When hitting fast forward or rewind, the blue "Progress" bar appears, and you can navigate on it.  But when pressing play (or OK?) the video starts from the beginning?
- If you are in the middle of a video when you try and FF or rewind, does it always take you back to the very start of the video?  Or does it continue playing from where you were?
- When you press OK or Play while FF/Rewind, do you get a "Loading" bar appear, or does it resume playback immediately?

**Comment by Qiangong2** [comment]
1. Whichever one is the latest on the roku store.
2. 2018 roku streaming stick
3. All videos
4. Yes
5. Continue playing from where we started originally.
6. Resumes playback immediately

**Comment by DanMossa** [comment]
I am currently having this issue as well.

My tv is the tcl 55p605 if that helps.

I've only experienced this on one file

**Comment by JohnCrafton** [comment]
also having this issue, but only on the TVs (not android/win clients).  will update the comment with the TV model and app version shortly.

**Comment by 1hitsong** [comment]
We've made several updates to the video playback functionality. Please retest using the current version and if the issue is still present, please open a new ticket.
