### ISSUE TITLE
App no longer connects after upgrading to Jellyfin Server 10.7.1

### ISSUE THREAD

**Issue by copperheadclgp** [jellyfin-archive/jellyfin-roku-legacy#400]
**Describe the bug**
Ever since upgrading my Jellyfin instance on Ubuntu 20.04.2 LTS from version 10.6.4 to 10.7.1, the Roku app version 1.4.6 is unable to connect to the server.

**To Reproduce**
1. Launch Roku app
2. Enter in the server address as http://IP ADDRESS:8096
3. Submit server address
4. See error "Server is not found; is it online?"

**Expected behavior**
Connection should establish to server as before. 

**Additional context**
The Jellyfin server is on the same local network as my Roku device. Communication between the two devices has been verified; there are no firewall rules in place which would prevent the Roku from reaching the server. Additionally, the Jellyfin web UI has been verified as working from other devices (desktop PC, smartphone) and plays media as expected. No connection attempts are shown in log files. 

I have also tried connecting to the server using the beta app, but the same issue occurs.

**Comment by neilsb** [comment]
For the server address, can I check the "http" is lowercase (as I've just spotted that it doesn't work if it's not lowercase … need to sort that) , and when you hit **submit** the URL in the server box doesn't change?

Could you also try just entering the IP address on it's own, with no protocol or port (e.g.  "1.2.3.4").  It should use http and default to port 8096 if not specified?

All the Roku client does at this stage is make a call to _[ServerURL]_/System/Info/Public, so for some reason it's not getting the data expected when making that call, however just about every client uses that URL as standard, and has not changed in 10.7.  And the Roku client has not had a store update since December.

Could you also try the demo server from your Roku and see if that works.  Bit of a painful Server Url to enter on the Roku though, as the port is required in and it has a path:

- https://demo.jellyfin.org:443/stable

**Comment by copperheadclgp** [comment]
Confirming that "http" is in lowercase. Hitting "submit" leaves the URL unchanged. 

Nothing changed when just the IP address was entered. 

The demo server works perfectly without any issues. Clearly something is going on with my specific instance. I am going to perform a backup, purge the packages, and install a fresh copy to see if that has any effect.

**Comment by cewert** [comment]
@copperheadclgp could you try reinstalling the roku app? This will reset all persistent data for the app (anything the roku app remembers after a restart). My theory is that your config is messed up. Reinstalling the app is the only way to start fresh.

**Comment by copperheadclgp** [comment]
@cewert, I snapshotted my server before reverting back to 10.6.4 so I was able to roll that back. I just ran through the following:

- Verified that entering in the IP address only resulted in the full url (http://192.168.x.xx:8096) populated in the server field automatically
- Verified that navigating to http://192.168.x.xx:8096/System/Info/Public on a desktop computer resolved properly. It instantly redirected to https://192.168.x.xx:8920/System/Info/Public, and displayed the following: 
`{"LocalAddress":"https://192.168.x.xx:8920","ServerName":"jellyfin","Version":"10.7.1","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"longstringoflettersandnumbers","StartupWizardCompleted":true}`
 - Uninstalled the Roku app, rebooted the Roku, reinstalled, and tried again. No difference in behavior.
 - Tried changing the server info to https://192.168.x.xx:8920/. No difference in behavior.

**Comment by neilsb** [comment]
When you rolled back server to 10.6.4 was the Roku app able to connect again?

Also, have you got a redirect in place to redirect to SSL?  Not sure the roku app follows redirects currently (think there is an issue open for that)

Also, currently the Roku app won't work with self signed or invalid (IIRC) certificates, so if you're using SSL and an IP then that won't work currently I think.

So the question is, if it's working in 10.6.4 then I guess the it allows connections over http?

**Comment by copperheadclgp** [comment]
@neilsb - you hit the nail on the head. The settings I had in 10.6.4 were all https and redirect from http. Turned all of that off and it works fine now. The big question I have now is why it worked fine with the same settings as before...

Thanks for the help everyone!

**Comment by jmcparland** [comment]
Would like to amplify this concern a bit. 

Conditions: My first install of jellyfin server was last night via docker. I have a laptop with firefox, a roku device with jellyfin app installed today, and the jellyfin server all on the same network segment. The laptop and roku device are connected to the same wireless access point. Using the laptop & firefox, I am able to connect to http://numeric-ipv4-addr:8096 without issue; however, the the roku w/app are not able to do the same. 

Any potential firewall restrictions were removed for testing. tcpdump on the server confirms traffic from the laptop but no traffic from the roku.

The roku (and laptop) are each able to connect to the demo server without issue.

I did also check that entering my server's local numeric-ipaddr did result in auto-prefix with http:// and suffix with :8096, but did not result in a change in outcome.

**Comment by neilsb** [comment]
> The big question I have now is why it worked fine with the same settings as before...

I've just re-installed 10.6.4 and done some testing.  It _looks_ like even with `Require HTTPS` checked on 10.6.4 that you can still connect over HTTP, and you're not getting the redirection responses that we're seeing in 10.7.  So it appears that this may well have been a bug that existed in 10.6.4 that has now been fixed.

Issue #316 covered the HTTP -> HTTPS redirect issue.  I can capture the redirection request here within the client, so I'll see if I can get that issue resolved this weekend.

As for the certificate issue (see #218) this is more or a problem.  I'll add some more details to that ticket, but in effect it's not really feasible to support self-signed certificates in the Roku client.  If using SSL, it will need to be a valid, certificate from a known issuer.

**Comment by copperheadclgp** [comment]
This is what I was thinking as well, since I do use self-signed certificates within my internal network, and knew that there wasn't a good / easy way to load the CA onto the Roku. But since it just "worked" without any issues previously, it fell off my radar.
