### ISSUE TITLE
H265 HDR video not playing

### ISSUE THREAD

**Issue by conorm125** [jellyfin-archive/jellyfin-roku-legacy#401]
**Describe the bug**
When trying to play a 4K H265 HDR video the first couple of seconds play and then the loading bar appears indefinitely and the server's admin dashboard no longer says the video is playing.
I have tested this on both the stable and beta releases and get the same behaviour.

**Expected behaviour**
The video to direct play and audio to transcode fine (since AC3 is not supported on the Roku).

**Logs**
FFmpeg Direct Stream log from Jellyfin server
```
Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc
    Metadata:
      BPS-eng         : 73199888
...
    Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 448000
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (ac3 (native) -> aac (native))
```

**Additional context**
The server is being run on a Raspberry Pi 3 running Jellyfin 10.7.1.
Video transcoding is disabled for the user account being used.
Audio transcoding is enabled for the user account being used.
The video plays fine on Windows with the Desktop application.
Roku streaming stick plus being used.

**Comment by conorm125** [comment]
Here is another extract of a log for a video that plays:

 Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc
    Metadata:
      BPS-eng         : 73199888
...
    Stream #0:1(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit) (default)
    Metadata:
      title           : Surround 7.1
      BPS-eng         : 4213261
... 
 Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (truehd (native) -> aac (native))

**Comment by trekkie690** [comment]
Curious, cause i have had a similar issue. Video will direct play but audio needs trans-coding. When i check the steam if either needs trans-coding then the video is trans-coded (its whats in the code right now). For the 4K videos i play it takes like 2-5min to load when this type of event occurs (can direct stream video but has to trans-code audio). Fast forwarding isn't really a thing to do when it does the tans-coding

1) Have you tied other videos with the same issue occurring?
2) Do you have a video that both audio and video can direct stream, and does it produce the same issue?
3) what does the web interface show when you watch the video (in the Jellyfin web GUI)?

**Comment by conorm125** [comment]
1.  Have you tied other videos with the same issue occurring? - movie 4
2. Do you have a video that both audio and video can direct stream, and does it produce the same issue? - movie 3.

Note: I have content that can direct play (its in .mp4 rather than .mkv) and the audio and video are codecs that require no transcoding. These play fine and are reported correctly as direct play.


Movie 2 says direct stream on the web GUI and keeps stopping to buffer, this video played smoothly before updating the server to 10.7.1 (previously 10.6.?).
The FFmpeg Direct Stream log says audio is being transcoded.
...
Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS-eng         : 17862627
...
    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : DDP 5.1 Atmos
      BPS-eng         : 768000
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
...

Movies 3 says direct streaming but is transcoding eac3 audio to aac according to the FFmpeg Direct stream log. This plays smoothly.
...
Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1920, SAR 1:1 DAR 2:1, 24 fps, 24 tbr, 1k tbn, 24 tbc (default)
    Metadata:
      BPS-eng         : 12996291
...
    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1, fltp
    Metadata:
      BPS-eng         : 768000
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
...

Movie 4 has the same issues as movie 1 listed in the initial issue, where it shows the loading bar/page indefinitely. The web GUI states it is direct streaming and the FFmpeg direct stream log says that is transcoding the audio:
...
Stream #0:0[0x1011]: Video: hevc (Main 10) (HDMV / 0x564D4448), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 23.98 tbc
...
    Stream #0:2[0x1100]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, 7.1, s32 (24 bit)
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (truehd (native) -> aac (native))
...

**Comment by conorm125** [comment]
@trekkie690 When you are transcoding audio but direct streaming video, do your ffmpeg logs look similar?
