### ISSUE TITLE
Libaries not showing watched tick or unwatched episodes count

### ISSUE THREAD

**Issue by conorm125** [jellyfin-archive/jellyfin-roku-legacy#402]
**Describe the bug**
Both Movies and Tv Shows are not showing the blue watched tick as the web application does. Blue ticks are only shown for Tv Epsidoes and seasons. In addition, the number of unwatched episodes is not displayed on the Tv show and is only shown on the seasons.

**Expected behaviour**
- Movies should show the blue tick on the poster if watched
- Tv Show should show the blue tick if all of the episodes have been watched, else the number of unwatched episodes should be displayed in the blue circle.

**Additional context**
Tested on both the beta and stable releases.

**Comment by TommyNorthAL** [comment]
This appears to be low priority, since it's still true 18 months later (version 1.5), but it does seem rather basic functionality is missing.

**Comment by 1hitsong** [comment]
Fixed by #1547
