### ISSUE TITLE
Buffering when trying to play nearly everything

### ISSUE THREAD

**Issue by christianlegge** [jellyfin-archive/jellyfin-roku-legacy#403]
**Describe the bug**
When playing nearly everything on my Roku TV, it will end up buffering about a half hour in (with the Loading bar in the center of the screen). Once it starts buffering it will continue to do so about once a second until playback is stopped, and if playback is resumed, the buffering resumes almost immediately. Playing the same thing through the Chromecast app has no issue. Doesn't matter whether it's 1080p, 4k, transcoded or direct play. 

**Expected behavior**
Smooth, buffer-free playback.

**Logs**
[FFmpeg.Transcode.log](https://gist.github.com/scatter-dev/07c0640fbbc0f27e1962b4acba2ff0d4) (Not entirely sure where this log is coming from since the file in question is being direct played. Subtitles maybe? But there is an error in here. I have not seen similar errors with this problem before.)
[FFmpeg.DirectStream.log](https://gist.github.com/scatter-dev/b566f7be6046ec664e188b61b29e7e92)

**Additional context**
I use a Roku HiSense 55" TV, connected to a Yamaha RX-V385 AVR. My server is hardware transcoding with a GTX 960, although I see no difference when I switch to software. Both the server and the TV are connected to the same router via an ethernet cable and bandwidth far exceeds bitrates these videos would be playing at.

When I first encountered this problem I determined that it was caused by the file or folder it was in being read by Windows, causing Jellyfin to be unable to open it. Seeding torrents, having an Explorer window open, etc. This solution does not seem to be working anymore and it would not explain why the file could play in other clients besides Roku.

I regularly use this client and server to watch 20-minute, 720p episodes of Jeopardy (5 times a week for months now) and have never once seen this issue.

**Comment by fsteveb** [comment]
I am seeing this issue with Roku play on certain large files. I don't have the problem with almost every other file. The file type is MKV and the file is 3.5GB. Here is the log from the Transcode.
{
  "Protocol": 0,
  "Id": "bb4e9b2bc93b911b97a5e96afd358fdd",
  "Path": "Y:\\Shared Videos\\TV\\Doctor Who\\Season 06 [2011]\\S06E03 The Curse Of The Blackspot.mkv",
  "EncoderPath": null,
  "EncoderProtocol": null,
  "Type": 0,
  "Container": "mkv,webm",
  "Size": 3518590976,
  "Name": "S06E03 The Curse Of The Blackspot",
  "IsRemote": false,
  "ETag": "85fee63ca0d4e4585255ce532f3c6afc",
  "RunTimeTicks": 26939600896,
  "ReadAtNativeFramerate": false,
  "IgnoreDts": false,
  "IgnoreIndex": false,
  "GenPtsInput": false,
  "SupportsTranscoding": true,
  "SupportsDirectStream": true,
  "SupportsDirectPlay": true,
  "IsInfiniteStream": false,
  "RequiresOpening": false,
  "OpenToken": null,
  "RequiresClosing": false,
  "LiveStreamId": null,
  "BufferMs": null,
  "RequiresLooping": false,
  "SupportsProbing": true,
  "VideoType": 0,
  "IsoType": null,
  "Video3DFormat": null,
  "MediaStreams": [
    {
      "Codec": "h264",
      "CodecTag": null,
      "Language": "eng",
      "ColorRange": null,
      "ColorSpace": null,
      "ColorTransfer": null,
      "ColorPrimaries": null,
      "DvVersionMajor": null,
      "DvVersionMinor": null,
      "DvProfile": null,
      "DvLevel": null,
      "RpuPresentFlag": null,
      "ElPresentFlag": null,
      "BlPresentFlag": null,
      "DvBlSignalCompatibilityId": null,
      "Comment": null,
      "TimeBase": "1/1000",
      "CodecTimeBase": null,
      "Title": null,
      "VideoRange": "SDR",
      "VideoRangeType": "SDR",
      "VideoDoViTitle": null,
      "LocalizedUndefined": null,
      "LocalizedDefault": null,
      "LocalizedForced": null,
      "LocalizedExternal": null,
      "DisplayTitle": "1080p H264 SDR",
      "NalLengthSize": "4",
      "IsInterlaced": false,
      "IsAVC": true,
      "ChannelLayout": null,
      "BitRate": 10448828,
      "BitDepth": 8,
      "RefFrames": 1,
      "PacketLength": null,
      "Channels": null,
      "SampleRate": null,
      "IsDefault": true,
      "IsForced": false,
      "Height": 1080,
      "Width": 1920,
      "AverageFrameRate": 25,
      "RealFrameRate": 25,
      "Profile": "High",
      "Type": 1,
      "AspectRatio": "16:9",
      "Index": 0,
      "Score": null,
      "IsExternal": false,
      "DeliveryMethod": null,
      "DeliveryUrl": null,
      "IsExternalUrl": null,
      "IsTextSubtitleStream": false,
      "SupportsExternalStream": false,
      "Path": null,
      "PixelFormat": "yuv420p",
      "Level": 41,
      "IsAnamorphic": null
    },
    {
      "Codec": "dts",
      "CodecTag": null,
      "Language": "eng",
      "ColorRange": null,
      "ColorSpace": null,
      "ColorTransfer": null,
      "ColorPrimaries": null,
      "DvVersionMajor": null,
      "DvVersionMinor": null,
      "DvProfile": null,
      "DvLevel": null,
      "RpuPresentFlag": null,
      "ElPresentFlag": null,
      "BlPresentFlag": null,
      "DvBlSignalCompatibilityId": null,
      "Comment": null,
      "TimeBase": "1/1000",
      "CodecTimeBase": null,
      "Title": null,
      "VideoRange": null,
      "VideoRangeType": null,
      "VideoDoViTitle": null,
      "LocalizedUndefined": null,
      "LocalizedDefault": null,
      "LocalizedForced": null,
      "LocalizedExternal": null,
      "DisplayTitle": "English - DTS - 5.1 - Default",
      "NalLengthSize": null,
      "IsInterlaced": false,
      "IsAVC": null,
      "ChannelLayout": "5.1",
      "BitRate": 1536000,
      "BitDepth": null,
      "RefFrames": null,
      "PacketLength": null,
      "Channels": 6,
      "SampleRate": 48000,
      "IsDefault": true,
      "IsForced": false,
      "Height": null,
      "Width": null,
      "AverageFrameRate": null,
      "RealFrameRate": null,
      "Profile": "DTS",
      "Type": 0,
      "AspectRatio": null,
      "Index": 1,
      "Score": null,
      "IsExternal": false,
      "DeliveryMethod": null,
      "DeliveryUrl": null,
      "IsExternalUrl": null,
      "IsTextSubtitleStream": false,
      "SupportsExternalStream": false,
      "Path": null,
      "PixelFormat": null,
      "Level": 0,
      "IsAnamorphic": null
    }
  ],
  "MediaAttachments": [],
  "Formats": [],
  "Bitrate": 11984828,
  "Timestamp": null,
  "RequiredHttpHeaders": {},
  "TranscodingUrl": null,
  "TranscodingSubProtocol": null,
  "TranscodingContainer": null,
  "AnalyzeDurationMs": null,
  "DefaultAudioStreamIndex": null,
  "DefaultSubtitleStreamIndex": null
}

The logfile has this over and over.
[2023-02-25 00:00:51.715 -05:00] [ERR] [73] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "192.168.128.1" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at Emby.Server.Implementations.Net.UdpSocket.<>c__DisplayClass21_0.<SendToAsync>b__0(IAsyncResult callbackResult)
--- End of stack trace from previous location ---
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2023-02-25 00:00:51.839 -05:00] [ERR] [140] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "192.168.128.1" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at Emby.Server.Implementations.Net.UdpSocket.<>c__DisplayClass21_0.<SendToAsync>b__0(IAsyncResult callbackResult)
--- End of stack trace from previous location ---
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)

If I can provide any other info let me know.
The episodes from this entire season do this. It plays for about 10 mins and then loads more over and over.

**Comment by mptpro** [comment]
I am having the same problem. The video plays fine on Jellyfin on my phone and in the browser. And, for what it's worth, it plays fine using Emby on Rokul

**Comment by 1hitsong** [comment]
If you're still experiencing this issue using the latest Roku client release, please post to the troubleshooting forum. There are tons of great people help who can help dive into issues like this.

https://forum.jellyfin.org/f-troubleshooting
