### ISSUE TITLE
Add ability to record Live TV

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#404]
**Is your feature request related to a problem? Please describe.**
While it is possible to view Live TV and use a guide (ref #26), it isn't possible yet to set a show for recording.

**Describe the solution you'd like**
Add the record/record series buttons, as in the TV show detail UI from the web interface.

**Describe alternatives you've considered**
Setting the recording from the web interface or app.

**Additional context**
When working on this, we should be careful to present the options in an intuitive way (e.g. default to web settings, maybe some help text with "for more recording settings, log in to Jellyfin on the web"). We should also see what the Android TV app uses for reference.

**Comment by jimdogx** [comment]
Currently working on this.

**Comment by neilsb** [comment]
Fixed in #515
