### ISSUE TITLE
Testing and CI

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#406]
The first in a series of [[Architecture]](https://github.com/jellyfin/jellyfin-roku/labels/architecture) issues.

Thanks to #363, there have been some improvements by adding CI and checks for the channel.

Still to do items:
- Tests, in general (as mentioned by #35)
- The fixing or removal of Rooibos (issues as seen in #68)

For adding tests in to the CI checks, just flagging this commit that shows what would be needed: https://github.com/jellyfin/jellyfin-roku/pull/363/commits/ed2e6d6327c703689331a3ede2a62fe30b27d765

**Comment by 1hitsong** [comment]
Rooibos has been removed.
