### ISSUE TITLE
Not reporting playback to 10.7.1 server

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin-archive/jellyfin-roku-legacy#411]
**Describe the bug**
Video is playing correctly, but server is not displaying that roku client is playing video. Video is not marked as watched.

**To Reproduce**

1. Play video
2. View server dashboard
3. Notice no active roku clients

**Expected behavior**

Playback status should be reported and visible. Videos should be marked as watched.

**Logs**

**Screenshots**

**Additional context**

Roku version 1.3.5
10.7.1 LSIO docker image

**Comment by neilsb** [comment]
I suspect this may be related to #344. Fix for that is in the beta version, and will be in the next store release which should be any day now.

**Comment by neilsb** [comment]
Could you check if this is happening in the latest Release on the Roku Store (1.4.7) please?

**Comment by SenorSmartyPants** [comment]
Playback status is now visible on JF 10.7.2 using Roku app version 1.4.7.

I consider this closed

**Comment by michaelkrieger** [comment]
Is this broken again?  Roku 1.4.11 to 10.7.7 I’m seeing the same behaviour. It disappears as an active client shortly after it starts playing but meanwhile is still watching and logs show it streaming still.
