### ISSUE TITLE
Show channel version

### ISSUE THREAD

**Issue by crass** [jellyfin-archive/jellyfin-roku-legacy#412]
**Is your feature request related to a problem? Please describe.**
I'd like to know when the channel gets updated so I can see if the new version fixes my issue. To do this, I need to know that I am in fact testing on the new channel version. As far as I know the only way to get the version of the channel is to query the roku via `http://[rokuip]:8060/query/apps`, but that's a bit of a pain.

**Describe the solution you'd like**
It would be nice if the channel displayed the channel version somewhere, perhaps when pressing the `*` button.

**Describe alternatives you've considered**
It could be displayed next to the logo at the top.

**Comment by anthonylavado** [comment]
You can press the `*` on the icon from the home screen, and it tells you the version there 🙂

(this is built in to the Roku OS, we didn't have to do anything special)

As it stands, we are prioritizing both the beta and "release" versions soon, so beta will always have the latest features and be at the latest stable release of nothing else comes up. We also set it up so both can be installed side by side with no impact on each other.

**Comment by neilsb** [comment]
Showing the version number in the client was something I was thing about the other day too actually. 

@anthonylavado I know the version number is in the manifest file, but it also entered when uploading the package. Do these have to match, or does one overwrite the other? 

Pretty sure we can't get the version from Roku in code, and can't easily read the manifest, but we could update our build script to read it and insert it into an appropriate variable

**Comment by neilsb** [comment]
Never mind. You can get it from the Roku OS.

**Comment by crass** [comment]
@anthonylavado Hah, so it is. Apparently my googlefu was weak today. At least this issue maybe useful for others in a similar situation in the future. Thanks guys!
