### ISSUE TITLE
VP9 video with OPUS audio does not play audio on Roku 

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#417]
**Describe the bug**
Videos with VP9 video and OPUS audio have no audio playback on Jellyfin-Roku.
Video is transcoded, but audio is copied, and the playback has no sound.
However, if the video is H264 and the audio is OPUS, playback is fine.
If the video is VP9 and audio is AAC, the playback is fine.

**Expected Result**
There should be audio playback

**Additional Context**
Hardware is a Roku Streaming Stick+ 3810X.
The result is the same with hardware acceleration (VAAPI) and without hardware acceleration.

VP9/OPUS works fine on the web client and also the iOS client.

**Comment by Artiume** [comment]
I imagine it might be the Opus audio inside the mpegts stream while Direct Streaming. Can you test the file locally from within the transcode cache folder with Vlc to make sure the file works properly

**Comment by ghost** [comment]
@Artiume I will try this to test. 
@neilsb suggested a workaround -

I added:
```
if meta.json.MediaStreams[audio_stream_idx]["Codec"] = "opus" return false
```
to source/VideoPlayer.brs after line 271 and this fixes the issue.

**Comment by neilsb** [comment]
That will certainly force any OPUS audio streams to be transcoded. I suspect that there is something funny with OPUS (looking at #267 too) on Roku as @Artiume mentioned in the comments of these tickets. 

Until it's understood what's happening, or at least if it affects everyone on all devices I think that forcing transcoding for all is not the right thing to do. 

One of the things currently being worked on is user settings on Roku, and if this is a common problem then when the options are in place I think it would make sense to add an user choice to always transcode OPUS tracks.

**Comment by ghost** [comment]
@Artiume I was able to test using ffplay (moved the transcodes from the server to a different client). ffprobe confirms that the files are h264 video and opus audio. The transcoded files play fine, audio working as expected. I was not able to get them to play using VLC, but I think that this might be my own ignorance than an issue with the file.

**Comment by Artiume** [comment]
weird that vlc couldn't play them, it should've worked like normal. one way to live test the stream is to start the video playback, copy the url from the ffmpeg log and give the url to vlc.

**Comment by kamanwu** [comment]
Roku TV could play VP9/OPUS directly.  Why need transcoding here?

BTW: I was want to report the bug:   Roku media player could play VP9/OPUS directly, but the jellyfin roku client cannot which make the server do transcoding.

**Comment by neilsb** [comment]
> Roku TV could play VP9/OPUS directly. Why need transcoding here?

There is something odd going on when asking Roku if it can decode a container of type "webm".  It reports that it needs transcoding.

We are changing the way that we determine whether a file needs transcoding, which hopefully resolve most of these issues, along with some subtitles issues that we still have.

**Comment by neilsb** [comment]
@jd1123 The files that you are testing with, is the Opus Audio stereo, or if 5.1 does your Roku support 5.1  (i.e. should you expect to be able to play the Audio without transcoding)?

If so, would you mind performing another test if you have the time?  Could you change the first line of the function `directPlaySupported(meta as object)` in source/VideoPlayer.brs to just `return true`.  This will force all videos to direct play and not transcode, so not something you can leave in I suspect.  But I'd be interested to see if this allows the VP9/Opus video(s) that you had problems with play correctly.

_Edit:_ As I can reproduce the no sound then OPUS is transcoded to H264 in a sample video, but direct plays fine when I make the change above.

**Comment by Artiume** [comment]
> Roku TV could play VP9/OPUS directly. Why need transcoding here?
> 
> BTW: I was want to report the bug: Roku media player could play VP9/OPUS directly, but the jellyfin roku client cannot which make the server do transcoding.

we want to fix the direct play issue if that's the issue,  but what about those who might need to transcode due to the bitrate being too high over the network or something. While it might seem like there's only one issue here, there's at least two,  maybe three if you include the buggy opus audio ticket

**Comment by neilsb** [comment]
Fixing the direct play will still respect any other needs to transcode (e.g. Audio has too many channels, bitrate exceeds max supported/configured, etc etc).

In this case, I suspect if it transcodes to h264/mkv we'll still have this problem - although that remains to be tested.  It would also be interesting to know if any other players are affected if media with OPUS audio is transcoded to h264/mkv (i.e. whether it's a problem with Roku or ffmpeg).   

I'll need to spend some more time looking at the DeviceProfile for Roku, as I suspect we can tell the server to prefer transcoding to vp9 (or vp8?) rather than h264, but I believe that would result in a significant overhead on the server, so we would only want to do that for videos where Opus audio is being used.  I'm not sure if that can be done solely via the Device Profile.

**Comment by ghost** [comment]
@neilsb - I am testing this on files encoded in OPUS stereo. My Roku player does support 5.1 but the output I am testing with are the stereo speakers built into the television.

I did the test you suggested and these files do indeed play normally.

**Comment by kamanwu-oicr** [comment]
> > Roku TV could play VP9/OPUS directly. Why need transcoding here?
> 
> There is something odd going on when asking Roku if it can decode a container of type "webm". It reports that it needs transcoding.
> 
> We are changing the way that we determine whether a file needs transcoding, which hopefully resolve most of these issues, along with some subtitles issues that we still have.



> > Roku TV could play VP9/OPUS directly. Why need transcoding here?
> 
> There is something odd going on when asking Roku if it can decode a container of type "webm". It reports that it needs transcoding.
> 
> We are changing the way that we determine whether a file needs transcoding, which hopefully resolve most of these issues, along with some subtitles issues that we still have.

I can confirm that after I change the container from webm to mkv (still VP9/OPUS codec), I can play it by Jellyfin Roku client without transcoding.
You mentioned that you are changing the way to determine if a file need transcoding or not.  This changing hasn't been release yet, right?

**Comment by neilsb** [comment]
> You mentioned that you are changing the way to determine if a file need transcoding or not. This changing hasn't been release yet, right?

That is correct.  I expect it to be released to the beta app at the start of May, and then to main channel store a week or so later.

**Comment by kamanwu** [comment]
I just saw the new release, and did a quick test.  The result is even worse.
Before, I can play "webm" container (VP9/OPUS codec).  Just the server need do transcoding.
Now, the server still do transcoding, but the audio disappeared.

**Comment by neilsb** [comment]
The release done there was to address two issues (playback on Roku OS 10 and a regression preventing viewing box sets). 

The release mentioned above to help with Opus issues will hopefully be in beta next week or so. This issue will be updated when the work is done.
