### ISSUE TITLE
Show "Additional parts" as in web UI when movie is split into multiple parts

### ISSUE THREAD

**Issue by crass** [jellyfin-archive/jellyfin-roku-legacy#420]
**Describe the feature you'd like**
I have files `movie-cd1.avi` and `movie-cd2.avi`. On the web UI in the movie details there is a section "Additional parts" which shows the second file so it can be easily played after the first file finishes. This feature request is to add a similar section to the roku. Even better would be if the roku would automatically queue and play the additional parts.

**Comment by mathmaniac43** [comment]
I think this might be considered a bug, or at least a deficiency. I was unable to watch a multi-part film and could not access the second part!

**Comment by jimdogx** [comment]
Going to close this issue as a duplicate of #830 only because it has a little bit more info and I started investigating the issue under that report.

**Comment by jimdogx** [comment]
p.s. if either of you are comfortable with testing developer branches, please see jimdogx:feature/jf-830-movie-additonal-parts and let me know if it works for you 👍
