### ISSUE TITLE
Static Analysis Errors for 1.4.7

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#422]
Here are the latest failures. The ones listed with "Error" will prevent publishing until they are resolved. "Warning" can be ignored for now.

  | Message | Severity | Category | Certification requirements
-- | -- | -- | -- | --
1 | "PlayDuration" is only supported when used with the TimeGrid component. All other uses have been deprecated. Path: /components/data/ScheduleProgramData.brs. Line: 11. | Error | DeprecatedAPIs |  
2 | "PlayDuration" is only supported when used with the TimeGrid component. All other uses have been deprecated. Path: /components/liveTv/ProgramDetails.brs. Line: 107. | Error | DeprecatedAPIs |  
3 | Channels are now required to support roInput events. Please opt in to this support with the supports_input_launch=1 manifest entry and properly handle roInput events in your channel. | Error | DeepLinking | 5.2
4 | The GetVersion() API has been deprecated. Use the roDeviceInfo.GetOsVersion() function instead, which was introduced in Roku 9.2 OS, to get the major, minor, revision, and build numbers of the Roku OS running on a device. Path: /source/api/baserequest.brs. Line: 135. | Warning | DeprecatedAPIs |  
5 | Channel Name contains the brand name "Roku" which is prohibited. | Warning | ChannelStore

**Comment by neilsb** [comment]
Not sure what is requested for the deep link URLs when submitting, but just let me know if you want some samples.

For items 1 & 2, it seems the change implemented by Roku means it's not possible to have a working TimeGrid within an application and have it pass Static Analysis tests.  Need to wait for Roku to resolve this issue, or disable the TimeGrid functionality to push a new client.

**Comment by anthonylavado** [comment]
Here's what the dashboard asks for when preparing to publish:

![2021-04-14 11_23_07-Roku — Mozilla Firefox](https://user-images.githubusercontent.com/596194/114736469-1d374400-9d14-11eb-97db-a46896800848.png)

Regarding the other thing, as we have found, it appears to be a bug, so we're going to have to watch for Roku to fix it.

**Comment by anthonylavado** [comment]
Here's the guidelines for section 5.2 on deep linking: https://developer.roku.com/en-ca/docs/developer-program/certification/certification.md#5-deep-linking

**Comment by anthonylavado** [comment]
The first two issues regarding PlayDuration have been fixed by Roku releasing an update to their Static Channel Analysis tools.

**Comment by anthonylavado** [comment]
These are all resolved at this time.
