### ISSUE TITLE
Loads for extremely long time when skipping forward or resuming 

### ISSUE THREAD

**Issue by barbecued** [jellyfin-archive/jellyfin-roku-legacy#424]
When playing videos from the beginning, roku plays just fine. If you skip forward (10 minutes for example) or resume part way through a video, the video loads / retrieves for a very long time. I do not see any errors in the logs and I do not see any transcoding logs for the video. The further you skip, the longer it takes. If I skip 15 minutes or longer, the video never loads. It is stuck on retrieving. No issues skipping when watching on browser or android app.

**Comment by 1hitsong** [comment]
If you're still experiencing this issue using the latest Roku client release, please post to the troubleshooting forum. There are tons of great people help who can help dive into issues like this.

https://forum.jellyfin.org/f-troubleshooting
