### ISSUE TITLE
Unable to Open Collections/Boxsets

### ISSUE THREAD

**Issue by jsea76** [jellyfin-archive/jellyfin-roku-legacy#427]
**Describe the bug**
When attempting to open a collection in jellyfin-roku (v1.4.7) a message is displayed "This type is not yet supported: Boxset.". This worked in previous versions. Still able to open and play collections and individual items in collections on jellyfin-web and android app.

**To Reproduce**
1. Create a collection in Jellyfin.
2. Attempt to open said collection in jellyfin-roku.

**Expected behavior**
Collection should open, displaying items contained within said collection to be played. Same or similar to previous version of jellyfin-roku or current version of jellyfin-web

**Logs**

**Screenshots**

**Additional context**
Jellyfin server/web version: 10.7.2 Linux ARM
jellyfin-roku version: 1.4.7

**Comment by pinovecs** [comment]
When is there a new release coming or is there a way to rollback?

**Comment by neilsb** [comment]
The beta release currently has this fix in it. I imagine a store release will happen in the next week or so
