### ISSUE TITLE
This type is not yet supported: Boxset

### ISSUE THREAD

**Issue by pinovecs** [jellyfin-archive/jellyfin-roku-legacy#429]
**Describe the bug**

Roku version - 4800X (software 10.0.0 build 4177-C2
Jellyfin version - Version 1.4 build 7

When attempting to open any movie "Collection" (custom groups that I had setup) the error "The type is not yet supported: Boxset" appears on the screen.

**To Reproduce**

1. Go to Collections
2. Click on any Collection and the error will appear.

**Expected behavior**

When opening the Collection movies that have been assigned to the group appear.

**Additional context**

Testing from a Web Client on a laptop functions correctly
Testing the Emby Client on the Roku connecting to the Jellyfin server functions correctly

**Comment by neilsb** [comment]
This was a regression introduced in 1.4.7.  Another user raised this in issue #427, and a fix has been merged for it.  It will be working again in the next release.
