### ISSUE TITLE
Blu-Ray Subtitles Not Inserted into Roku Streams in 10.7.*

### ISSUE THREAD

**Issue by CptNonsense** [jellyfin-archive/jellyfin-roku-legacy#440]
**Describe the bug**
Subtitles are not inserted into display stream when selected while streaming to Roku devices for blu-ray titles (stored in MKV with extracted subtitles)

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: N/A
 - Clients: Roku
 - Browser: N/A
 - Jellyfin Version: 10.7.* (2 and 5 verified specifically)
 - Playback: Direct Stream/Transcode 
 - Installed Plugins: AudioDB, TVMmaze, TheTVDb, OMDb, Open Subtitles, Trakt, TMDbBox Sets
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Load any blu-ray ripped video with extracted subtitles on a Roku device
2. Set subtitle to selection other than "None"
3. See no subtitles appear

**Expected behavior**
Stream inserts selected subtitles on playback

**Logs**
No error reported in log

**Screenshots**
None

**Additional context**
Only applicable to Roku (multiple systems).  Behaves properly in browser and on Android.  Behavior worked as expected in previously installed version, 10.6.2.  Behavior works for me for ripped DVD files in MKV format with extracted subtitles. Open Subtitles plugin is not being used.

**Comment by CptNonsense** [comment]
Verified this issue is host version specific, not simply Roku client specific.  This problem is not present in 10.6.4 while it is present in 10.7.* with the same Roku client version and with the same media file.

**Comment by neilsb** [comment]
They're working fine on the current dev version I have which is reworking a pile of transcoding and subtitle stuff. So there may well have been a server change but it hasn't fundamentally broken anything.
