### ISSUE TITLE
Completed episode checkmark is off-center and inconsistently sized

### ISSUE THREAD

**Issue by tydog98** [jellyfin-archive/jellyfin-roku-legacy#441]
**Describe the bug**
The check for completed episodes does not appear in the center of the circle, and also is sometimes differently sized.

**To Reproduce**
1. Go to a completed episode
2. Look at the checkmark

**Expected behavior**
The check should appear in the center of the circle and be sized consistently.

**Screenshots**
![IMG_20210509_233500](https://user-images.githubusercontent.com/45440255/117603127-dd605280-b141-11eb-8ea3-2ceee4da60c1.jpg)

**Comment by neilsb** [comment]
This has already been reported in #312.  Closing this in favour of #312.
