### ISSUE TITLE
Remember Live TV View Selecton

### ISSUE THREAD

**Issue by bryce-hoehn** [jellyfin-archive/jellyfin-roku-legacy#444]
**Is your feature request related to a problem? Please describe.**

I prefer the guide view over the channel list but I have to manually switch to it every time I open the app because it defaults to the channel view.

**Describe the solution you'd like**

I would like the Roku app to remember my selection when I change the Live TV Channel View and automatically apply it every time I go to the Live TV portion of the app.

**Describe alternatives you've considered**

An alternative would be to simply change the default to guide view but then anyone who prefers the channel sort view would have the same issue.

**Additional context**

Applies to the Roku app both Stable and Beta.

**Comment by anthonylavado** [comment]
So, it actually uses the defaults in your Web settings.

To change the behaviour, do this:
- Log in to the web interface
- Click on your user profile at the top right
- Click on Home, then scroll down to Live TV
- Change it from Channels to Guide
- Save

Then it will load that in the Roku app by default.

**Comment by anthonylavado** [comment]
@neilsb I guess discoverability is an issue here because we keep seeing this come up 😆

How about we take a two-pronged approach here?
Could we add an option that reads "Web Profile Settings", and keep separate entries for the Channels view and the Guide view?

Since we're in the process of reworking documentation, we can add a note on this to the new client pages for Web and Roku. I'll probably also add a quick FAQ on the readme here.

**Comment by bryce-hoehn** [comment]
I just followed your instructions and it's going straight to guide view now, thanks!

I think it would be less of an issue if the user profile settings were somehow accessible from within the Roku app.

**Comment by anthonylavado** [comment]
@17hoehbr It's a tricky balance to strike. The web profile defaults are used by a few things. For native apps - Roku, Android TV - it's a selective implementation of some features. For other apps - smart tv, iOS, Android - we load the actual web interface.

It would be weird if changing a setting on the Roku then affected all the others. Hence my new suggestion that maybe we have an extra option wherever this comes up. Over time, we plan to make more things have a "unified" appearance, but still allow customization per device.

**Comment by neilsb** [comment]
The question, I guess, is whether the setting on one Roku (or any client I guess) device should be applied to all devices of that type.  Maybe some people will have a specific TV they use for watching movies, and would always want the movie libraries listed first, but on all other TVs it would be TV shows first. 

I guess this would be per client to implement and choose how this is managed. (E.g. let the choose if it's a 'local' setting or for all Roku devices)

Think there was talk of server supporting key/values pairs to allow clients to store and share settings, but not sure if this has been done yet. 

Implementing settings is high of my todo list, as it is becoming necessary, and would allow us to close off a pile of issues 🙂

**Comment by neilsb** [comment]
Closed by #492
