### ISSUE TITLE
Add support for skipping to the next or previous chapter in a video

### ISSUE THREAD

**Issue by asmartin** [jellyfin-archive/jellyfin-roku-legacy#445]
**Describe the feature you'd like**

I have video files which have chapters, but I can't see an OSD button or key combination on the Roku remote for skipping from chapter to chapter. If I hover over the timeline in the web player, I can see the chapter names, so I know Jellyfin is reading them, but there doesn't appear to be a way to navigate between them in the Roku app. One idea would be to make a long-press of the forward/back buttons on the Roku remote trigger skipping to the next/previous chapter, while a short press of those buttons has the existing functionality of fast-forwarding/rewinding.

Adding this functionality would greatly improve the user experience of the Roku app with videos that have chapters.

**Additional context**

Thank you for considering this feature request!

**Comment by asmartin** [comment]
It looks like this functionality is now being implemented in the web player in [this PR](https://github.com/jellyfin/jellyfin-web/pull/2670), so hopefully that will make it easier to incorporate into the Roku app as well

**Comment by jeromatron** [comment]
It would be great to have this as an option in the Roku app.  Would the code be similar to what is done with the web client as @asmartin mentions?

**Comment by sam-later** [comment]
Yes, please add this feature to the Roku app!
