### ISSUE TITLE
Search TV Guide and Jellyfin Library From Roku Search Page

### ISSUE THREAD

**Issue by asmartin** [jellyfin-archive/jellyfin-roku-legacy#446]
**Describe the feature you'd like**

From the home screen of the Roku, you can select the Search menu item and search for a particular TV show; once you select the show you are interested in, it shows which Roku channels offer the show. Currently, the results of the TV Guide and Jellyfin Library are not included in this list; it would be great if the Jellyfin Roku app could hook into this global search so that results for the show that are in the TV Guide or in your library show up.

A use case for this would be you use the Roku search to look for a particular TV show. If it is airing tomorrow, you would then see the Jellyfin app listed in the search results and you could select it to be taken to the TV Guide so you can note the time or choose to record it.

**Additional context**

This would provide better integration of the Jellyfin search functionality with the rest of the Roku system. Thank you for considering this feature request!

**Comment by neilsb** [comment]
Unfortunately this is not possible with the way the Roku search works. The search is performed on the Roku servers, not the local device. 

Each Channel can configure a list of content that it serves, and Roku will include that in the content it searches. So even if we provided a list of content to Roku for the Jellyfin channel, the that would be used for all installs of the channel. 

Unless Roku changes their search process significantly, you will need to search for content within the Jellyfin app
