### ISSUE TITLE
Plugin intros not requested

### ISSUE THREAD

**Issue by snowe2010** [jellyfin-archive/jellyfin-roku-legacy#448]
**Describe the bug**

Installed https://github.com/dkanada/jellyfin-plugin-intros and expect intros to play on the Jellyfin Roku App. 
Per [this issue](https://github.com/dkanada/jellyfin-plugin-intros/issues/30) it appears that this is something the client has to request. 

I'm not sure if this is a bug or enhancement, so filing as a bug. 

**To Reproduce**
1. Install https://github.com/dkanada/jellyfin-plugin-intros
2. Set up plugin intro (any works)
3. Go to web client and start a video
4. Intro plays
5. Go to roku app and start a video
6. Intro does not play

**Expected behavior**
I expect the video to play

**Logs**
If logs are necessary I can provide them. 

**Screenshots**
N/A/

**Additional context**
N/A

**Comment by anthonylavado** [comment]
I changed the label to enhancement. Though it is something that is supported by the web interface, the Roku channel has never had it.

**Comment by snowe2010** [comment]
Thank you!
