### ISSUE TITLE
Subtitles don't work

### ISSUE THREAD

**Issue by CubeyGlyph** [jellyfin-archive/jellyfin-roku-legacy#451]
**Describe the bug**
I cannot get subtitles to work at all

**To Reproduce**
turn on subtitles, nothing happens

**Expected behavior**
I'd like to be able to see what people 

**Logs**
I don't see logs related to subtitles but maybe I don't know what to look for.

**Comment by neilsb** [comment]
There is currently work happening to improve subtitle display.

At the moment, you'll need to ensure the Roku Setting (From the * menu while playing something) has subtitles set to "Always Displayed".  Then if you use the down arrow while playing you can select the track to be displayed.

If that doesn't work, can you let us know the format of the subtitles that are not working (srt, ass, etc etc)?
