### ISSUE TITLE
Default audio track not respected for series

### ISSUE THREAD

**Issue by tydog98** [jellyfin-archive/jellyfin-roku-legacy#460]
I have a series with an English and Japanese audio track, with the Japanese audio track as default. When I play episodes from the series on the Roku client it only plays in English. When I press the * button and try to change the audio track from there it's says that's it's playing the default audio track and won't let me change it. When using the web client or VLC media player the audio will automatically be in Japanese, so it's not an issue with the files.

**Comment by cewert** [comment]
Is this still happening to you on the latest version of the app?

**Comment by tydog98** [comment]
I haven't used the Roku player in awhile now and I don't have that specific piece of media anymore. Now that different audio tracks can be selected for series I would imagine this problem isn't that big of a deal anymore.

**Comment by jimdogx** [comment]
Closing this issue since the reporter is no longer using the Roku client and believes it is potentially fixed with the ability to select audio tracks.  PR #1252 , should also help in this area.
