### ISSUE TITLE
Fix proposed: App crash on when attempting to playback from Emby server

### ISSUE THREAD

**Issue by chaosloth** [jellyfin-archive/jellyfin-roku-legacy#467]
Application hangs when playing any media from Emby server due to server responding with NoCompatibleStream . There are two bugs that need to be fixed (see below)

### Steps to Reproduce
1. Load JellyFin client on Roku box, in my case Telstra TV
2. Connect to server
3. Choose any media file to play
4. Once Play button is clicked, application hangs
5. Roku debug output shows crash with pkg:/source/VideoPlayer.brs

### Resolution for crash
The issue is caused by uncaught error in AddVideoContent(), in response to a `POST {server}/Items/{0}/PlaybackInfo` the server returns `{"MediaSources":[],"ErrorCode":"NoCompatibleStream"}` The fix to stop the app crash is to add a check on the returned error code and to bail out of the function.

After VideoPlayer.brs:61 
`playbackInfo = ItemPostPlaybackInfo(video.id, mediaSourceId, audio_stream_idx, subtitle_idx, playbackPosition)`

Add something like this
```
  if playbackinfo.ErrorCode = "NoCompatibleStream"
    video.content = invalid
    return
  end if
```

### Resolution for root cause
The underlying cause to the NoCompatibleStream is due to `mediasourceid` being passed with an invalid value. The value being passed is the `video.id`, where as it should either be blank or the actual media source id. A simple fix is to simply force it to be null.

Simply replace, near line VideoPlayer.brs:59 with comment: ' Call PlayInfo from server
`mediaSourceId = video.id`

with
`mediaSourceId = ""`

-Enjoy. Conno

**Comment by jimdogx** [comment]
Thank you!  This fixed my inability to play anything on my new TCL Roku TV (jellyfin worked just fine with a previous TV and a Roku USB stick).

**Comment by neilsb** [comment]
> Thank you! This fixed my inability to play anything on my new TCL Roku TV (jellyfin worked just fine with a previous TV and a Roku USB stick).

Can I just check if you were having problems playing from a Jellyfin server, or were you using an Emby server?

**Comment by crobibero** [comment]
> > Thank you! This fixed my inability to play anything on my new TCL Roku TV (jellyfin worked just fine with a previous TV and a Roku USB stick).
> 
> Can I just check if you were having problems playing from a Jellyfin server, or were you using an Emby server?

It’s (my) Jellyfin server, currently running 10.8-alpha2

**Comment by jimdogx** [comment]
> Can I just check if you were having problems playing from a Jellyfin server, or were you using an Emby server?

Sorry, I should have been more clear, this is connecting to a Jellyfin server.  I know this issue is specific to the Emby server, but after debugging the latest master branch I found it was crashing for the same reason (NoCompatibleStream error).  Also note that the latest jellyfin-roku from the Roku store was working fine with an old Roku USB stick.  This only started happening when I upgraded to a TCL Roku TV.

**Comment by neilsb** [comment]
OK - thanks - that's great.  I see your comment on #397 too.  I'll look check exactly what's happening and get that fix in place as long as it doesn't look like it will affect anything else.

**Comment by neilsb** [comment]
There were 2 lines (in one place) that was setting the MediaSourceId to the video id.  All other references in the app appear to be setting to the correct MediaSourceId (or empty string).

Updated the 2 lines that were setting it incorrectly to use the correct MediaSourceId.

**Comment by jimdogx** [comment]
FYI, @neilsb I just pulled down your branch (https://github.com/neilsb/jellyfin-roku/tree/set-mediasourceid-correctly) and it still crashes when trying to read subtitles because playbackInfo is "NoCompatibleStream".  Log dump:
```

12-03 17:29:38.346 [beacon.signal] |AppLaunchInitiate ---------> TimeBase(0 ms)

12-03 17:29:38.346 [beacon.signal] |AppCompileInitiate --------> TimeBase(1 ms)
Note: Translation file loaded: pkg:/locale/en_US/translations.ts: 85 items.
12-03 17:29:38.351 [scrpt.cmpl] Compiling 'Jellyfin', id 'dev'
12-03 17:29:38.361 [scrpt.load.mkup] Loading markup dev 'Jellyfin'
12-03 17:29:38.370 [scrpt.unload.mkup] Unloading markup dev 'Jellyfin'
12-03 17:29:38.438 [scrpt.parse.mkup.time] Parsed markup dev 'Jellyfin' in 77 milliseconds

------ Compiling dev 'Jellyfin' ------

12-03 17:29:38.778 [scrpt.ctx.cmpl.time] Compiled 'Jellyfin', id 'dev' in 338 milliseconds

12-03 17:29:38.781 [scrpt.proc.mkup.time] Processed markup dev 'Jellyfin' in 0 milliseconds

------ Compiling dev 'Jellyfin' ------
12-03 17:29:38.828 [scrpt.ctx.cmpl.time] Compiled 'Jellyfin', id 'dev' in 46 milliseconds
12-03 17:29:38.840 [beacon.signal] |AppCompileComplete --------> Duration(494 ms)
12-03 17:29:38.854 [ui.frm.plugin.running.enter] Entering PLUGIN_RUNNING for dev
12-03 17:29:38.854 [beacon.signal] |AppLaunchInitiate ---------> TimeBase(0 ms)

12-03 17:29:39.201 [beacon.signal] |AppSplashInitiate ---------> TimeBase(347 ms)

12-03 17:29:40.131 [beacon.signal] |AppSplashComplete ---------> Duration(930 ms)

12-03 17:29:40.536 [scrpt.ctx.run.enter] UI: Entering 'Jellyfin', id 'dev'

------ Running dev 'Jellyfin' main ------

Get server details

12-03 17:29:42.989 [beacon.signal] |AppDialogInitiate ---------> TimeBase(4135 ms)

invalid         invalid         invalid

onKeyEvent      OK              true

onKeyEvent      OK              false

onKeyEvent      down            true

onKeyEvent      down            false

roSGNodeEvent   <Component: roSGNodeEvent>

12-03 17:30:19.922 [beacon.signal] |AppDialogComplete ---------> Duration(36933 ms)

12-03 17:30:19.923 [beacon.signal] |AppDialogInitiate ---------> TimeBase(41069 ms)

12-03 17:30:53.559 [beacon.signal] |AppDialogComplete ---------> Duration(33635 ms)

Unhandled roDeviceInfoEvent:

<Component: roAssociativeArray> =
{
    Mode: "Instant replay"
    Mute: false
}

12-03 17:30:57.281 [beacon.signal] |AppLaunchComplete ---------> Pending Render Pass

12-03 17:30:57.303 [beacon.signal] |AppLaunchComplete ---------> Duration(78449 ms), DialogTime(70568 ms)
Unhandled Item Type: Trailer
Unhandled Item Type: Trailer
Unhandled Item Type: Trailer
Unhandled Item Type: Trailer

BrightScript Micro Debugger.
Enter any BrightScript statement, debug commands, or HELP.

Suspending threads...
Thread selected:  0*   pkg:/source/VideoPlayer.brs(82)         subtitles = sortSubtitles(meta.id, playbackInfo.MediaSources

Current Function:
074:
075:      if meta.live
076:          video.content.live = true
077:          video.content.StreamFormat = "hls"
078:      end if
079:
080:      video.container = getContainerType(meta)
081:
082:*     subtitles = sortSubtitles(meta.id, playbackInfo.MediaSources[0].MediaStreams)
083:      video.Subtitles = subtitles["all"]
084:
085:      if meta.live
086:          video.transcodeParams = {
Source Digest(s):
pkg: dev 1.4.9 8780d0d5bb431a2f345ea9ef6b6c7994 Jellyfin

Syntax Error. (runtime error &h02) in pkg:/source/VideoPlayer.brs(82)
Backtrace:
#3  Function addvideocontent(video As Dynamic, audio_stream_idx As Dynamic, subtitle_idx As Dynamic) As Dynamic
   file/line: pkg:/source/VideoPlayer.brs(82)
#2  Function videoplayer(id As Dynamic, audio_stream_idx As Dynamic) As Dynamic
   file/line: pkg:/source/VideoPlayer.brs(6)
#1  Function createvideoplayergroup(video_id As Dynamic, audio_stream_idx As Dynamic) As Dynamic
   file/line: pkg:/source/ShowScenes.brs(308)
#0  Function main(args As Dynamic) As Void
   file/line: pkg:/source/Main.brs(201)
Local Variables:
video            roSGNode:JFVideo refcnt=2
audio_stream_idx roInt refcnt=4 val:1 (&h1)
subtitle_idx     Integer val:-1 (&hFFFFFFFF)
playbackposition roInt refcnt=1 val:0 (&h0)
global           Interface:ifGlobal
m                roAssociativeArray refcnt=5 count:8
meta             roSGNode:MovieData refcnt=1
dialogresult     <uninitialized>
group            <uninitialized>
mediasourceid    roString refcnt=1 val:"2784027"
playbackinfo     roAssociativeArray refcnt=1 count:2
params           roAssociativeArray refcnt=1 count:0
subtitles        <uninitialized>
Threads:
ID    Location                                Source Code
 0*   pkg:/source/VideoPlayer.brs(82)         subtitles = sortSubtitles(meta.id, playbackInfo.MediaSources
  *selected
```

**Comment by jimdogx** [comment]
FYI @neilsb, I pulled down your branch with the fix and it worked on my TCL Roku TV. 👍
