### ISSUE TITLE
Images will not show for a migrated library.

### ISSUE THREAD

**Issue by CubeyGlyph** [jellyfin-archive/jellyfin-roku-legacy#470]
**Describe the bug**
Images will not show for TV shows or their seasons.

**To Reproduce**
I migrated my library to different physical drives.  Initially I took the existing library and pointed it at the new location and the images no longer displayed.  I deleted the old library and created a new one and scanned that new location.  It still has no images.  I have migrated other libraries and did not get this issue.  

**Expected behavior**
Images should be available

**Screenshots**
![Screen Shot 2021-07-13 at 10 09 43 AM](https://user-images.githubusercontent.com/82244912/125469273-132a46ef-209a-43bc-9cd1-fcadc140f938.png)
![Screen Shot 2021-07-13 at 10 10 01 AM](https://user-images.githubusercontent.com/82244912/125469280-a06583c0-03e7-4008-be95-2e686bb8fc70.png)

**Comment by neilsb** [comment]
Are all the images displaying correctly via the web browser, or any other client you can try?

**Comment by CubeyGlyph** [comment]
> Are all the images displaying correctly via the web browser, or any other client you can try?

No, the images are not visible in the browser or the Roku app.

**Comment by neilsb** [comment]
This points to a problem with the images on your library missing, rather than an issue with the Roku client.  Would be worth checking that you have a MetaData set up correctly for the server.   

If you need more assistance, there are multiple places you can visit for troubleshooting, advice and support.  You can see the full list at our website, https://jellyfin.org/contact/

**Comment by CubeyGlyph** [comment]
> This points to a problem with the images on your library missing, rather than an issue with the Roku client. Would be worth checking that you have a MetaData set up correctly for the server.
> 
> If you need more assistance, there are multiple places you can visit for troubleshooting, advice and support. You can see the full list at our website, https://jellyfin.org/contact/

Oh hell, I posted into the wrong one. My apologies, I never meant to raise it as a Roku app issue, I simply was spinning too many plates.

**Comment by neilsb** [comment]
No problem.  :)
