### ISSUE TITLE
Flashing cover images in menus

### ISSUE THREAD

**Issue by tlc** [jellyfin-archive/jellyfin-roku-legacy#473]
**Describe the bug**
After entering "Movies" or "Shows" I am presented with 2 rows of 6 DVD cover type images.
The images are flashing on and off at independent rates. 
The background image is also flashing on and off.
*Sometimes* they stop flashing after a long time.  But if I scroll down, the ones below will be flashing.

**To Reproduce**

1. Select the Jellyfin app on Roku.
2. Select Movies.
3. Get a headache from flashing images.

**Expected behavior**
Non flashing images.

**Additional context**
I am new to Jellyfin.  This is loading directories of files that work in Plex.

Also, it seems that when an image is not found for a movie, a blue rectangle is shown with the title in it.  These flash too.

But sometimes, I don't get the blue rectangle.  I get nothing and only know the movie in that position by navigating to the empty spot so the title is written below where the cover image or rectangle should be.

When I select a Movie, I get the screen with the DVD cover and "Play", "Audio", ...
Sometimes the DVD cover image on this page is initially blank and shows up a few seconds later.

FWIW, *playing* video worked fine for me.  It's just the menus.

**Comment by anthonylavado** [comment]
What model Roku are you using?

**Comment by tlc** [comment]
It happens on my Roku Streaming Stick+ and on my TCL TV, 55R617, also labeled "Roku TV 7120X".

**Comment by neilsb** [comment]
Would you be able to change server on one of your devices and try pointing at our test server please?   The Address for the server is `https://demo.jellyfin.org/stable/`.  Need to enter all that I'm afraid.

This just sounds very odd, and first thing I'd like to check out is that it's definitely not related to your local server.

**Comment by tlc** [comment]
Well, I entered all that, but dont have a username and password...

**Comment by tlc** [comment]
I used your server with my Streaming Stick+ and it does not happen.  
OTOH, it does not happen with my server and a web browser either, which led me to guess it was the Roku client.

My server is a docker image:

> $ docker image ls |grep jellyfin
> jellyfin/jellyfin              latest    b888247d3095   5 weeks ago    717MB

I see that the image has been updated on the docker hub.  I'll try that this weekend.

**Comment by tlc** [comment]
The new jellyfin/jellyfin docker image did it too.  

But it stopped when I switched to the linuxserver/jellyfin image.

**Comment by neilsb** [comment]
That is really odd, but glad you found a solution.  I can't think what could be causing that, but I'll ask the rest of the team if they have any ideas.
