### ISSUE TITLE
Add audio track selection option 

### ISSUE THREAD

**Issue by PatrickA94** [jellyfin-archive/jellyfin-roku-legacy#478]
Unable to choose audio track for media which has multiple audio tracks for different languages.

**Comment by neilsb** [comment]
For movies, in the movie details screen there is an "Audio" option which allows you to select the audio track to play.  Unless you are meaning something else?

**Comment by tydog98** [comment]
I think they mean for TV series.

**Comment by PatrickA94** [comment]
Yes this is related to tv shows

**Comment by valespisl** [comment]
Yes please, add audio track selection for TV

**Comment by SpencerHHayes** [comment]
I came across this today. Most of the TV shows in my library have multiple tracks in different languages, would really be useful to have the same functionality movies already have.

**Comment by Omripresent** [comment]
Also adding selection for default audio track to use similar to the web client or using the setting already selected for the running profile since that seems to sync.

**Comment by eprouty** [comment]
Are there any updates on this issue?

**Comment by jimdogx** [comment]
I have this working currently.  Just need to clean up the UI.
