### ISSUE TITLE
/bin/sh: 4: zip: not found

### ISSUE THREAD

**Issue by junkmasters21** [jellyfin-archive/jellyfin-roku-legacy#479]
Hello,

Hope someone can help me with this. I'm trying to get this on to our Roku device and encountered an error -

jorge@ubuntuserver:~/jellyfin-roku$ sudo make dev
[sudo] password for jorge:
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
make BUILD='dev' package
make[1]: Entering directory '/home/jorge/jellyfin-roku'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
*** Preparing Staging Area ***
  >> removing old application zip /home/jorge/jellyfin-roku/out/apps/Jellyfin_Roku.zip
  >> creating destination directory /home/jorge/jellyfin-roku/out/apps
  >> setting directory permissions for /home/jorge/jellyfin-roku/out/apps
  >> creating destination directory /home/jorge/jellyfin-roku/out/staging
echo "  >> moving application to /home/jorge/jellyfin-roku/out/staging"
  >> moving application to /home/jorge/jellyfin-roku/out/staging
cp /home/jorge/jellyfin-roku/manifest /home/jorge/jellyfin-roku/out/staging/manifest
cp -r /home/jorge/jellyfin-roku/source /home/jorge/jellyfin-roku/out/staging
cp -r /home/jorge/jellyfin-roku/components /home/jorge/jellyfin-roku/out/staging
cp -r /home/jorge/jellyfin-roku/images /home/jorge/jellyfin-roku/out/staging
# Copy only supported languages over to staging
mkdir /home/jorge/jellyfin-roku/out/staging/locale
cp -r /home/jorge/jellyfin-roku/locale/en_US /home/jorge/jellyfin-roku/locale/en_GB /home/jorge/jellyfin-roku/locale/fr_CA /home/jorge/jellyfin-roku/locale/es_ES /home/jorge/jellyfin-roku/locale/de_DE /home/jorge/jellyfin-roku/locale/it_IT /home/jorge/jellyfin-roku/locale/pt_BR /home/jorge/jellyfin-roku/out/staging/locale
*** Creating Jellyfin_Roku.zip ***
  >> copying imports
  >> generating build info file
mkdir -p /home/jorge/jellyfin-roku/out/staging/source
echo "  >> generating build info file";\
echo "Function BuildDate()" >> /home/jorge/jellyfin-roku/out/staging/source/buildinfo.brs
  >> generating build info file
echo "  return \"20 Aug AM 2021\"" >> /home/jorge/jellyfin-roku/out/staging/source/buildinfo.brs
echo "End Function" >> /home/jorge/jellyfin-roku/out/staging/source/buildinfo.brs
echo "Function BuildCommit()" >> /home/jorge/jellyfin-roku/out/staging/source/buildinfo.brs
echo "  return \"ee8301f\"" >> /home/jorge/jellyfin-roku/out/staging/source/buildinfo.brs
echo "End Function" >> /home/jorge/jellyfin-roku/out/staging/source/buildinfo.brs
# zip .png files without compression
# do not zip up any files ending with '~'
  >> creating application zip /home/jorge/jellyfin-roku/out/staging/../apps/Jellyfin_Roku-dev.zip
/bin/sh: 4: zip: not found
/bin/sh: 5: zip: not found
*** packaging Jellyfin_Roku-dev complete ***
make[1]: Leaving directory '/home/jorge/jellyfin-roku'
jorge@ubuntuserver:~/jellyfin-roku$

same error I got when doing make install

I'm fairly new to this so I hope this get's some attention.

Thanks for your help!

**Comment by neilsb** [comment]
Look like you're simply missing `zip` on your development box.   If you try installing zip using ` sudo apt-get install zip` and then give it another shot

**Comment by junkmasters21** [comment]
> Look like you're simply missing `zip` on your development box. If you try installing zip using ` sudo apt-get install zip` and then give it another shot

it felt like something was missing so there it is. now i got this

Install Failure: Error parsing XML component ServerDiscoveryTask

Thanks for the help!
