### ISSUE TITLE
Streaming gets stuck at "Loading" status on Roku when Transcoding is needed

### ISSUE THREAD

**Issue by danbezerra** [jellyfin-archive/jellyfin-roku-legacy#490]
This is happening with any movies that requires transcoding (either only audio or audio + video): The streaming starts OK, but after ~1 min or so it gets stuck in the "Loading " status with no progress. in the server side, the transcoding continues as usual and I couldn't see any issues in the log. The interruption always happens at the same spot.

Anyone else facing the same issue? Could it be that my Roku model is too old?

Here are some details:

- Jellyfin Server: 10.7.7 running on a Ubuntu Server VM.

- Roku: Roku 3 model 4200X. Tried with both wireless and wired networks

- Jellyfin Roku client: Tried with both the current version 8 published to the store and the latest Beta.

Here is the transcoding log: https://pastebin.com/WUF9Ngvy

**Comment by neilsb** [comment]
What version of Roku OS is your device running?

**Comment by danbezerra** [comment]
Version 10.0.0 Build 4209-04. 

I believe Roku just announced 10.5, but it's not yet available for my device (just checked via Check for Updates menu option)

**Comment by neilsb** [comment]
Could you check this on the just-released Jellyfin Roku app version if you have time. A change has been made to the transcoding logic.
