### ISSUE TITLE
1.4.9 Transcoding issues 7.1

### ISSUE THREAD

**Issue by faptaincrunch** [jellyfin-archive/jellyfin-roku-legacy#491]
**1.4.9 Transcoding issues**
< Just updated to newest version and any file with 7.1 audio no longer transcodes. Reverting back to 1.4.7 fixes issue>

**To Reproduce**

1. Update to newest version'
2. Play file with 7.1 audio
3. Video plays but no sound is heard

**Expected behavior**
<Jellyfin remxxes or transcodes 7.1 audio to stereo so its compatible with my devices>

**Logs**
<https://pastebin.com/iEbkE3BN>

**Additional context**
<1.4.7 and 1.4.8 work perfectly and allow 7.1 audio to be converted to stereo but build 1.4.9 fails to transcode. 5.1 and below audio work fine on all versions>

**Comment by anthonylavado** [comment]
Just to confirm, you _do_ want it mixed down to stereo, or just passed through?

**Comment by faptaincrunch** [comment]
Sorry, i don't know the verbiage exactly. I dont have a 7.1 setup at home but the server used to play all aac and ac3 7.1 files after transcoding when audio transcoding was selected on the server. If i disabled audio transcoding, it would  remux the files and still play. Now on the new update 7.1 files dont play. I guess i dont need passthrough but down mixing? All settings on tv are pcm-stereo

Oct 7, 2021 6:08:15 PM Anthony Lavado ***@***.***>:

**Comment by tgiokdi** [comment]
I'm seeing the same issue on my Roku 4k, can provide logs if necessary.

**Comment by michaelharmonart** [comment]
Having the same issue with the newest release to the jellyfin server and roku. not sure if it's fixed

**Comment by sunnybreaux** [comment]
Same issue here on latest Roku Jellyfin app 2.0.2.

Jellyfin is not transcoding 7.1.

User limit set to stero/5.1 makes no difference.
