### ISSUE TITLE
Audio only playing in stereo

### ISSUE THREAD

**Issue by tydog98** [jellyfin-archive/jellyfin-roku-legacy#495]
**Describe the bug**
Despite trying to play many different 5.1 audio tracks, they only come out in stereo (confirmed by my AVR only getting 2.0 input)

**To Reproduce**
Play movie

**Expected behavior**
Audio should be given on more than 2 channels for devices that support it.

**Comment by anthonylavado** [comment]
A lot of this depends on what the Roku detects. Could you go in to your Roku system settings and confirm what it detects for audio support?

**Comment by tydog98** [comment]
> A lot of this depends on what the Roku detects. Could you go in to your Roku system settings and confirm what it detects for audio support?

Roku says it detects Dolby Audio - TrueHD and DTS-HD Master Audio. When I play movies on Netflix/Amazon the proper number of channels are used.

**Comment by tydog98** [comment]
Ok I don't know what happened or changed but it's working properly now. Sorry about that.
