### ISSUE TITLE
Roku Express 4K 3940RW cannot play 4k

### ISSUE THREAD

**Issue by TKwSni** [jellyfin-archive/jellyfin-roku-legacy#496]
**Describe the bug**
Roku Express 4k Cannot play 4k videos

It starts loading gets stuck at 33% and then says "it cannot extract the data of this object from the server" something like that.

I suppose it tries to transcode, because my server CPU fan revs up.

**Logs**
https://paste.gg/p/anonymous/04d9cd446e61494a97bcd44c5c798f38/files/af724bb262864cb8a9890bd1338c33f8/raw

**Additional context**

I'm able to play these videos in my LG 4k TV in its default web browser without any issues using jellyfin web.

I also installed the roku media player app, and it plays the videos without any issue using jellyfin dnla server.

**Comment by 1hitsong** [comment]
If you're still experiencing this issue using the latest Roku client release, please post to the troubleshooting forum. There are tons of great people help who can help dive into issues like this.

https://forum.jellyfin.org/f-troubleshooting
