### ISSUE TITLE
Library Detail View Sort Options

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#5]
The web application has several sorting and grouping options for libraries:

![image](https://user-images.githubusercontent.com/6452882/56856313-cb7a3100-6925-11e9-9031-b04ade5d9a71.png)

The emby roku app has the following choices for similar sorting/grouping:

[Library], Genres, Folder, Search

**Comment by bisby** [comment]
Some of the sorting options are available if you hit `*` on your remote. But the options are definitely not all of them.

I need to add those in, and then begin work on some sort of "genres" type groupings.

**Comment by bbalz** [comment]
> Some of the sorting options are available if you hit `*` on your remote. But the options are definitely not all of them.
> 
> I need to add those in, and then begin work on some sort of "genres" type groupings.

Should this work?  I just installed the latest cloned library and I can bring up the sorting menu but I can't change it.  It only shows then by title in ascending order.  It wouldn't let me adjust it using left/right or pressing any other button on the remote.

**Comment by neilsb** [comment]
Sorting of items in the new layout item list was added in PR #265.  Functionality to filtering and adding the "view" options is being worked on.

**Comment by asmartin** [comment]
If this would be better as a separate issue, let me know. I notice that in Live TV when using the "View" option and selecting "TV Guide" instead of the default "Channels" option, this preference is not retained after exiting the Roku app (the preference is reset back to "Channels" and you have to go in and select "TV Guide" again). As part of this enhancement, can you make this preference be saved after it is selected?

**Comment by anthonylavado** [comment]
> If this would be better as a separate issue, let me know. I notice that in Live TV when using the "View" option and selecting "TV Guide" instead of the default "Channels" option, this preference is not retained after exiting the Roku app (the preference is reset back to "Channels" and you have to go in and select "TV Guide" again). As part of this enhancement, can you make this preference be saved after it is selected?

Set your Web preferences to Guide :-)

- Open web interface to Jellyfin
- Sign in, click user icon at top right
- Choose "Home", scroll down to "Live TV"
- Change it from "Channels" to "Guide"

**Comment by asmartin** [comment]
Thank you, this worked!

**Comment by candry7731** [comment]
#596
