### ISSUE TITLE
Attempting to play a video with transcoding crashes the app

### ISSUE THREAD

**Issue by flrgh** [jellyfin-archive/jellyfin-roku-legacy#502]
**Describe the bug**
I disallowed audio/video transcoding for the user profile on my Roku to work around some issues with jellyfin transcoding files that it didn't need to. Now if I attempt to watch a video that requires transcoding, the app crashes.

...at least I'm pretty sure that's what is happening. I debugged this by sideloading the app so that I could use the debug (:8085) console. When I read through the stack trace and took a brief look at the code, it seemed like the most likely reason for the exception was that no transcoding url(s) was returned from the server. To confirm this behavior, I re-enabled transcoding for my user and the app no longer crashes (the video still fails to play, but that seems like a separate issue entirely).

**To Reproduce**
Disable transcoding for a user and attempt to watch a video that requires transcoding.

**Expected behavior**
The app should detect this condition and handle it by displaying an error (i.e. "Cannot play transcoded media file") instead of crashing.

**Logs**
```
Suspending threads...
Thread selected:  0*   pkg:/source/VideoPlayer.brs(126)        function getTranscodeReasons(url as string) as object

Current Function:
126:* function getTranscodeReasons(url as string) as object
127:
128:      regex = CreateObject("roRegex", "&TranscodeReasons=([^&]*)", "")
129:      match = regex.Match(url)
130:
Source Digest(s):
pkg: dev 1.4.9 c8e1f1d74606a58b7e2173cc1cdad955 Jellyfin

Type Mismatch. Unable to cast "Invalid" to "String". (runtime error &h18) in pkg:/source/VideoPlayer.brs(126)
Backtrace:
#4  Function gettranscodereasons(url As String) As Object
   file/line: pkg:/source/VideoPlayer.brs(128)
#3  Function addvideocontent(video As Dynamic, audio_stream_idx As Dynamic, subtitle_idx As Dynamic) As Dynamic
   file/line: pkg:/source/VideoPlayer.brs(112)
#2  Function videoplayer(id As Dynamic, audio_stream_idx As Dynamic) As Dynamic
   file/line: pkg:/source/VideoPlayer.brs(6)
#1  Function createvideoplayergroup(video_id As Dynamic, audio_stream_idx As Dynamic) As Dynamic
   file/line: pkg:/source/ShowScenes.brs(296)
#0  Function main(args As Dynamic) As Void
   file/line: pkg:/source/Main.brs(319)
Local Variables:
url              Invalid
global           Interface:ifGlobal
m                roAssociativeArray refcnt=6 count:7
regex            <uninitialized>
match            <uninitialized>
Threads:
ID    Location                                Source Code
 0*   pkg:/source/VideoPlayer.brs(126)        function getTranscodeReasons(url as string) as object
  *selected
```

**Additional context**

I'm not sure it's relevant (though I still haven't learned enough to know _why_ this file needs to be transcoded for the Roku), but here's some of the `ffprobe` output for the file I'm trying to play:

```
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 01:39:45.27, start: 0.000000, bitrate: 13150 kb/s
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS-eng         : 11613487
      DURATION-eng    : 01:39:45.271000000
      NUMBER_OF_FRAMES-eng: 143503
      NUMBER_OF_BYTES-eng: 8688733963
      DURATION        : 01:39:45.270000000
    Stream #0:1(eng): Subtitle: subrip (default)
    Metadata:
      BPS-eng         : 88
      DURATION-eng    : 01:39:20.858000000
      NUMBER_OF_FRAMES-eng: 1720
      NUMBER_OF_BYTES-eng: 65621
      DURATION        : 01:39:38.319000000
    Stream #0:2(eng): Audio: truehd, 48000 Hz, 5.1(side), s32 (24 bit) (default)
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 1468321
      DURATION-eng    : 01:39:45.273000000
      NUMBER_OF_FRAMES-eng: 7182326
      NUMBER_OF_BYTES-eng: 1098537996
      DURATION        : 01:39:45.272000000
```

**Comment by neilsb** [comment]
Yup - this checks out.  We don't receive any indication from the server why no transcode information was sent, so we can't let the user exactly why it can't be played, but should certainly catch the condition and give them an error message.

As for your media, do you have device that is capable of handling 5.1 Audio (either directly or via passthrough) and are the audio setting on the Roku set to DD+ or DTS (rather the Stereo)?

**Comment by flrgh** [comment]
@neilsb 👋 hi, thanks for chiming in

> do you have device that is capable of handling 5.1 Audio (either directly or via passthrough)

Yup! My signal path is Roku -> [Receiver](https://www.denon.com/en-us/product/av-receivers/avr-s510bt) -> TV.

> are the audio setting on the Roku set to DD+ or DTS (rather the Stereo)?

Roku settings:

* `Settings -> Audio -> Streaming audio format`: "Auto"
* `Settings -> Audio -> Digital output format`: "Passthrough" (tried "Auto" and had the same result)

Other details:

| name | value |
|-|-|
| roku model | 4800x |
| roku software version | 10.5.0 build 4201-C2 |
| jellyfin server version | 10.7.7 |
