### ISSUE TITLE
Roku App Does Not Reflect Home Screen Settings From Synology Web Client

### ISSUE THREAD

**Issue by BrickHardmeat** [jellyfin-archive/jellyfin-roku-legacy#503]
**Describe the bug**
When I access the Web client for the Synology version of Jellyfin and edit the profile to change the Home Screen sections, it always forces a "Next Up" row in between sections even though one is never set.   If I subsequently change the settings and add something like a "Continue Watching" section, the "Next Up" is always retained and then the home screen layout seems to "lock" and doesn't change whatever I do.

**To Reproduce**
First of all I access the web client on my PC using Opera.   When it loads, I click on the profile picture on the top right to get to "Settings" and then I click "Home".

I set my Home Screen sections to "My Media" and "Latest Media" as you can see here:

https://i.ibb.co/N9CWghH/Untitled.jpg

But this is what is reflected on the Roku app, even though "Next Up" is not set.

https://i.ibb.co/Hnmp1WP/IMG-0826.jpg

There is _no_ option to turn it off in the profile settings either.   I've also recently tried to access the Home Screen settings again and I just get the spinning circle in the middle of the screen constantly with no opportunity to actually edit anything at all now.

**Expected behavior**
I expect to see a row containing my media with the various libraries I have added.   Then I expect to see selected rows containing the latest media that has been added into my library.

**Additional context**
I'm running the latest stable version of Jellyfin, 10.7.7-4, obtained from the Synocommunity.

https://synocommunity.com/package/jellyfin

**Logs**
Attached Here:
[logs.txt](https://github.com/jellyfin/jellyfin-roku/files/7645371/logs.txt)

**Comment by Fyb3roptik** [comment]
https://github.com/jellyfin/jellyfin-roku/pull/553
