### ISSUE TITLE
Static Analysis/Channel Behavior Analysis

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#507]
Here's the latest report. The ones listed with "Error" will prevent publishing until they are resolved. "Warning" can be ignored for now.

## Static Analysis Test

 Number | Message | Severity | Category | Certification requirements
-- | -- | -- | -- | --
1 | All authenticated channels must use the RFI (getUserData) API call to pull in a user's email address during the sign-up or sign-in flow. | Error | ChannelStore |  1.11;2.1;2.9;
2 | Voice keyboards are required for entering email addresses and PIN codes. | Warning | Uncategorized | 4.12

## Channel Behavior Analysis

Number  | Test Title                       | Status | Severity | Category     | Requirements
--|----------------------------------|--------|----------|--------------|-------------
1 | Channel Launch Performance       | Fail   | Error    | Performance  | 3.2
2 | Channel Deep Linking Basic       | Error  | Error    | Deep Linking | 5.1
3 | Channel Content Play Performance | Error  | Error    | Performance  | 3.6

**Comment by anthonylavado** [comment]
Link to Certification Requirements: https://developer.roku.com/en-ca/docs/developer-program/certification/certification.md

Channel Launch Performance is a weird one here. They use a script (which can be tested with a home device using [Roku Remote](http://devtools.web.roku.com/RokuRemote/)) that should be simply launching the channel, but yet, it freezes.

The script is as follows:
```
params:
  rasp_version: 1
  default_keypress_wait: 2
  channel_name: Jellyfin
  channel_id: dev
steps:
  - launch: Jellyfin
  - pause: 30
```

I know we're supposed to only fire `AppLaunchComplete` when the main content is loaded, but I don't know if we'll need to cheat this one by calling it right at the start.

---

The Deep Linking/Content Play failures are also a mystery, but also not. They're trying to fire it almost right away on the device, but it's not logged in yet, so it can't get to the content! When I test it locally using Roku Remote, if the channel is logged in, it does launch the animated movie test title that we set up as an example. S

The channel is being provided a script with which to auto login, but they must not be running it first or something. This would also lead to why the performance test is failing, even though we set the right beacons of a dialog being loaded at the start.

---

Regarding the `getUserData` requirement, that may have been an error on my part. I'm running more tests to see.

**Comment by anthonylavado** [comment]
So `getUserData` was triggered by me choosing the "account required to access some or all features" option in the Channel Store Info. If I disable that, then the Static Analysis seems to pass, with just an "info" item about the locales available, and no errors or warnings. This appeared even in the previous results, but I don't normally put the Info items in my reports.

The issues with the Channel Behaviour Analysis remain. If I turn off the "account required" function, then it doesn't even try to run a script to auto login, it just tries to fire off the launch (which never succeeds because it still never logs in), and the deep link/playback (which then also never succeeds because it is not logged in).

---

I suppose we could fudge this all by:
1. Firing off `appLaunchComplete` right at the top, which doesn't line up with their requirements, but oh well
2. Somehow hard code some credentials or a token or something for the main demo server to playback the sample video file

---

**EDIT:** I think I got in. I'll still send some questions to Roku on this

**Comment by cewert** [comment]
Closing this since it seems you got it working. Please reopen if there's still something to fix.

**Comment by anthonylavado** [comment]
Re-opening because we'll need to pass the Channel Behaviour Analysis if we want to get rid of the message that says "CABLE OR SATELLITE SUBSCRIPTION REQUIRED".

I've let it go for this current release, but we should try to fix it for the next. I'll have to experiment with the "account required" settings.

**Comment by cewert** [comment]
Closing for now since [our app](https://channelstore.roku.com/details/cc5e559d08d9ec87c5f30dcebdeebc12/jellyfin) doesn't currently have the "CABLE OR SATELLITE SUBSCRIPTION REQUIRED" message. I think it's been gone ever since our app was restored back from it's beta status a while back. Hopefully it stays that way 🤞
