### ISSUE TITLE
No Subtitle Menu on 1.4.10

### ISSUE THREAD

**Issue by ethaldeman** [jellyfin-archive/jellyfin-roku-legacy#508]
**Describe the bug**
When watching media on the roku jellyfin app, I used to be able to press down on he arrows keys and pull up a menu to change the subtitles. On 1.4.10, pressing the down arrows does nothing. This makes it impossible to enable subtitles if they are off by default, remove them if they are on by default, or change the subtitle language. 

**To Reproduce**
1. Connect to a Linux x64 10.7.7 based Jellyin server with the 1.4.10 roku app
2. Start watching some form of media
3. Press down on the arrow keys to pull up the subtitle menu.
4. Subtitle menu does not appear. 

**Additional context**
I can confirm this bug occurs on 1.4.10 of the roku app, but does not occur on another roku device of mine running 1.4.9. This problem also does not occur on the roku beta app which is 1.4.9.

**Comment by billomega42** [comment]
1.4.10 roku app
Roku Software version 10.5.0 build 4210-CE
Jelly Windows x64 10.7.7
Can confirm problem as well. (also using the TV menus to enable subtitles, noticed them dropping out of sync on build 10; checking same file on 1.4 build 9 the subs work properly)

**Comment by neilsb** [comment]
Confirmed as an issue due to us now having introduced the Scenemanager.
