### ISSUE TITLE
Can't log in as user with no password set

### ISSUE THREAD

**Issue by fabianvf** [jellyfin-archive/jellyfin-roku-legacy#51]
**Describe the bug**

I have multiple users configured on my system, with a `guest` user that has passwordless access. I cannot log in as this user from the Roku app, as I am prompted for a password and leaving it blank doesn't work. 

**To Reproduce**

1. Through the Jellyfin web interface configure multiple users, and leave one with no password (so anyone can log in as that user)
1. Open the Jellyfin-roku app
1. Select Server
1. When prompted for a user, type in the name of the passwordless user you set up earlier
1. attempt to connect (leaving the password field blank)

**Expected behavior**

I log in successfully and see my media.
**Logs**

**Screenshots**

**Additional context**

**Comment by cghouly** [comment]
I'm working on recreating this issue. 
Wanted to make sure I was following the instructions to reproduce correctly:

**Reproduction steps taken**
1. I have 3 users currently configured, go to the Jellyfin web interface and add a new user (tested with `tmp` and `guest` as usernames). All user settings are kept as default in user profile.
2. Open the Jellyfin-roku app
3. Enter Server URL and Port then Submit
4. Enter Username (`tmp` and `guest` tested separately)
5. Skip password field, select Submit

**Behavior Seen During Tests**
Once I hit Submit at the User screen the app takes me to the Library successfully. Both users are able to navigate the app and play media.

Let me know if I am missing a step or user/server configuration to replicate this issue.

**Additional Info**
Running Jellyfin 10.3.6 on docker. Tested with and without LDAP plugin installed.

**Comment by fabianvf** [comment]
Interesting, I'm away from my home this week so unfortunately can't try to reproduce it right now, but I'll try re-installing the latest of everything, feel free to close this issue for now and I can re-open it if I see it again.

**Comment by bisby** [comment]
Glancing through the Roku side code, we don't have any specific "password can't be empty" check. The bit that does the authentication[0] does always put a `Pw=` param onto the query. If the server prefers getting no param rather than an empty `Pw` we can change that. But it would be nice to verify that it is necessary.

0: https://github.com/jellyfin/jellyfin-roku/blob/master/source/api/userauth.brs#L5

**Comment by cghouly** [comment]
I ran a quick and dirty test for this. I added a password of ```tmp``` for the tmp user and also used the guest user with no password for testing. 

**Code**

GlobalsTest.brs file:
```
'@TestSuite [GLT] Globals Tests

'@Setup
function GLT_setup() as void

end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests the ability to use the globals getter/setter
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test Global Getter and Setter
'@Params["tmp", "tmp"]
'@Params["guest", ""]
function GLT__get_token(user as String, password as String)
  url = "Users/AuthenticateByName?format=json"
  req = APIRequest(url)

  if password = "" then
    json = postJson(req, "Username=" + user)
    print "Password " + password
  else
    json = postJson(req, "Username=" + user + "&Pw=" + password)
    print "Password " + password
  end if

  print json
end function
```
Run ```make test```

**Output**

```
------ Running dev 'Jellyfin' main ------
Starting test using test scene with name TestsSceneTestsScene
#########################################################################
#TEST START : ###UNDEFINED_TEST_ID###
Loading test config from default location : pkg:/source/tests/testconfig.json
Password tmp
<Component: roAssociativeArray> =
{
    AccessToken: "d7d13e1a37234202938cd0e73b163e4a"
    ServerId: "452d05499ee347e09375cba3f3b867a9"
    SessionInfo: <Component: roAssociativeArray>
    User: <Component: roAssociativeArray>
}
Password 
invalid
Password tmp
<Component: roAssociativeArray> =
{
    AccessToken: "d7d13e1a37234202938cd0e73b163e4a"
    ServerId: "452d05499ee347e09375cba3f3b867a9"
    SessionInfo: <Component: roAssociativeArray>
    User: <Component: roAssociativeArray>
}
Password 
invalid

[START TEST REPORT]

[GLT] Globals Tests (out/staging/source/tests/specs/GlobalsTests.brs(1))
 |-tests the ability to use the globals getter/setter
 | |--Global Getter and Setter : 
 |   |--["tmp","tmp"] : ........................................................Success (464ms)
 |   |--["guest",""] : .........................................................Success (83ms)
 |
[GLT] Globals Tests (tests/source/specs/GlobalsTests.brs(1))
 |-tests the ability to use the globals getter/setter
 | |--Global Getter and Setter : 
 |   |--["tmp","tmp"] : ........................................................Success (321ms)
 |   |--["guest",""] : .........................................................Success (64ms)
 |


[END TEST REPORT]
```

**Logs**
Here are logs of the tmp user followed by an error from the guest user attempted log in:

```
[2019-07-23 05:22:50.726 +00:00] [INF] Authentication request for "tmp" "has succeeded".
[2019-07-23 05:22:50.727 +00:00] [INF] Reissuing access token: d7d13e1a37234202938cd0e73b163e4a
[2019-07-23 05:22:50.793 +00:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

I know it's an awful test, but it does look as though the server requires the ```Pw=``` param.

**Comment by fabianvf** [comment]
I updated everything to the latest release and this issue is gone!

**Comment by anthonylavado** [comment]
A user on the forums is having this issue:
https://forum.jellyfin.org/t/error-acces-jellyfin-roku/603/3?u=anthonylavado

Anything I can help investigate?

**Comment by bisby** [comment]
I know that auth has changed since the Emby days.

Currently the only way we attempt to get an auth token is through a single endpoint in a single format:

`url = "Users/AuthenticateByName?format=json"`

`json = postJson(req, "Username=" + user + "&Pw=" + password)` (postJson here means post data, return json)

The entire auth flow probably needs a bit of rework. But if that endpoint or data format is wrong for users with no password, it can be updated.

**Comment by anthonylavado** [comment]
Hrm... This is the code for that endpoint here:

https://github.com/jellyfin/jellyfin/blob/e87d7cfaf3ce2432e9a1da9901b96d5a683a7e00/MediaBrowser.Api/UserService.cs#L393-L398

So I'm not sure if things are different for an empty password.

**Edit:** So I think you need to send an empty value

**Comment by anthonylavado** [comment]
@bisby A note from @sparky8251 in Riot says you need to send a blank value (e.g. `""`) for this to work.

**Comment by cghouly** [comment]
I ran some tests sending Pw="" when the password is blank, and my user with no password failed to log in. Setting the code back to sending Pw= it will log in.

**Comment by fabianvf** [comment]
One thing I have seen, if the jellyfin server is down you can still get to this screen, and no matter what you input you'll get the `authentication failed` message.

**Comment by bisby** [comment]
Indeed. "Server is available" and "Authentication" could definitely stand to be separated.

**Comment by ghost** [comment]
I can't replicate this bug either, logging in without a password is successful for me.

**Comment by martylavender** [comment]
I am able to login without a password

Latest official jellyfin docker image
Fresh build of RokuTV channel
