### ISSUE TITLE
Jellyfin Roku app does not remember "Live TV" view/sort selections

### ISSUE THREAD

**Issue by numericOverflow** [jellyfin-archive/jellyfin-roku-legacy#510]
**Describe the bug**
When leaving the "Live TV" screen, the selected view/sort method is lost and reverts to the default

**To Reproduce**

1. Go into 'Live TV'
2. Click '*' button to bring up options menu
3. Scroll over to 'View' and down to 'Guide' then hit enter
4. Hit 'Back" button to apply new view
5. Exit one level back to the main menu and then re-select 'Live TV'
6. View returns to the default 'Channels' listing, despite just setting it to 'Guide'
7. Same behavior happens if you exit the app completely, upon return views/sorts are gone.

**Expected behavior**
View/Sort user selections should persist and remain until changed. This is the default behavior on almost all other apps.  Additionally, it 

**Logs**
N/A

**Screenshots**

https://user-images.githubusercontent.com/3429424/146695845-3c6dafd0-9131-43cc-b731-800c34219556.mp4

**Additional context**
This is a very annoying bug.  Having to adjust the view every time is tedious and makes certain users refuse to use Jellyfin :(

**Setup**
Jellyfin & Jellyfin Beta (latest)
Jellyfin server on Winx64 (latest)
HDHomeRun EXTEND (HDTC-2US)

**Comment by neilsb** [comment]
Roku User Preferences is something being looked at right now, which should allow users to set defaults for screens and sort order, etc.

Just on your example video, the default view for Live TV is taken from the Web User preferences.  You can set this on the website through user profile -> Home -> Live TV -> Default Screen.

**Comment by candry7731** [comment]
This should be fixed. @numericOverflow can you verify that your selected view is remembered?

**Comment by neilsb** [comment]
View sort orders are being saved now.
