### ISSUE TITLE
Since books are NOT supported, could we remove books?

### ISSUE THREAD

**Issue by kamanwu** [jellyfin-archive/jellyfin-roku-legacy#525]
I start to add "Books" into my library.  It looks good in browser and on my iPad.

But on my Roku TV, it looks so weird.  please see this image.  https://i.imgur.com/VFu4GE3.jpg

I understand nobody will read book on TV.  So do not support books on Ruku client does make sense.

Could we remove books?  For now, it's so ugly.

**Comment by jimdogx** [comment]
I also connect to a server that has Books.  Didn't think it bothered anyone else, but I agree that we should remove it.  It's easy to add back in if we add support for books (but also agree that might not make sense on a TV).

**Comment by kamanwu** [comment]
@jimdogx  I know this issue has been closed, but I still see books in "continue watching", and I do not know how to remove it.  There is no "continue watching" section on web client.  Please see this images.  https://imgur.com/1B2VCRx  Could this be fixed as well.  Thanks.

**Comment by jimdogx** [comment]
Good call.  I never "started" any books on Jellyfin, therefore I never had any in "Continue Watching" (only in my library).  @neilsb what's the protocol here?  Re-open this Issue to fix what was missed?  Or open a new issue?

**Comment by neilsb** [comment]
No hard and fast rule, but may as well create a new one and link it to this one. Makes change logs for the next release slightly easier.
