### ISSUE TITLE
Can't add standard player to Roku, only Beta

### ISSUE THREAD

**Issue by Codex-** [jellyfin-archive/jellyfin-roku-legacy#527]
**Describe the bug**

When attempting to install Jellyfin on my Roku I am not able to, as the option it greyed out:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/8297838/154001876-90cf3024-e05a-4702-a8c7-9fd236f4b146.png">

However, installing the beta was not an issue.

Is this an issue with the permissions on the published app or similar?

**Expected behavior**

Button to not be greyed

**Screenshots**

<img width="420" alt="image" src="https://user-images.githubusercontent.com/8297838/154001789-7e9a9289-5b5f-4da2-98e3-85579decf758.png">

**Additional context**

Brand new Roku express 4k

**Comment by neilsb** [comment]
Can you check what OS version is on it (Settings -> System Update) and if it's less than 10.5.0 can you perform a check for updates?

AFAIK the OS version is the only thing that would prevent installation.

**Comment by Codex-** [comment]
Latest version of the OS, it force updated as a part of the setup process.

I'm not going to worry about it, new to roku but too many issues with what I want to do so selling it lol.

I also found no-audio when trying to use the jellyfin beta, works fine when chromecasting though. I got the roku as a chromecast replacement but it doesn't support a lot of things I want to cast so my bad for not doing enough research.

Closing this issue because I won't be able to test anything else.

**Comment by neilsb** [comment]
No problem.  Roku Beta is a release or 2 behind now, as Roku are terminating their beta program on the 23rd of Feb, so we're no longer updating the beta.

Audio issue has since been resolved on the store release I believe.

**Comment by Codex-** [comment]
I ended up giving this a test to see if I could reproduce it. Wiped the device and reinstalled It / set it up, could install it the second time. No OS update though, not sure what changed. 

And to no-one's surprise, the audio issue I saw with beta is not present with the current store version 😅
