### ISSUE TITLE
Support Quick Connect on the Roku app?

### ISSUE THREAD

**Issue by mcronce** [jellyfin-archive/jellyfin-roku-legacy#528]
I didn't find a UI element for it in the stable or beta app, but wanted to make sure I'm not missing something before creating a feature request

**Comment by neilsb** [comment]
Quick connect is not supported on the Roku Client currently.

**Comment by mcronce** [comment]
@neilsb thanks!  Do you prefer to treat this issue as a feature request or have me open a new one?

**Comment by jimdogx** [comment]
I'm looking in to this one.

**Comment by mslinn** [comment]
Quick Connect is still not supported on the Roku Client, right?

**Comment by crobibero** [comment]
It has been supported for about 2 years now.

**Comment by mslinn** [comment]
I am just getting to know Jellyfin. Please check out https://www.mslinn.com/blog/2024/07/30/jellyfin.html

As I stumble forward, my articles morph into reality (and beyond!) as I, personally, experience the topics that I write about.

Any feedback, suggestions, corrections, oversights, comments, etc. would all be welcome; either here on 1-on-1 somehow.
