### ISSUE TITLE
Unable to see Music or Photo folders

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#530]
When opening Music or Photo folders I get "This CollectionFolder contains no items" error. This is only happening on Roku Express device. Using dekstop browser works. Using iOS works. Live TV works and Home Movies works.

**Comment by neilsb** [comment]
The Roku app doesn't yet support Music (See #124).

Initial photo support has recently been added (See #523) and will be in the next release.
