### ISSUE TITLE
Roku app - Cant select different movie versions

### ISSUE THREAD

**Issue by Fractal-Eyes** [jellyfin-archive/jellyfin-roku-legacy#531]
I am on the newest Roku channel app and I have no options to change the movie version, it defaults to the 4k version of the file. From the web I can see 2 versions 4k and 1080 and it lets me choose which one I want to play. The only options it gives me on the roku app is to adjust the audio channel.

**Comment by jimdogx** [comment]
I'm looking at resolving this issue.
