### ISSUE TITLE
TVListDetails, MovieListDetails, attempt to use non-integer index

### ISSUE THREAD

**Issue by whiteowl3** [jellyfin-archive/jellyfin-roku-legacy#537]
**Describe the bug**
In some situations (which seem to have to do with the presence/absence of proper metadata), TVListDetails and MovieListDetails fail to load and attempt to select an invalid non-integer in building the playbackinfo url.

**To Reproduce**
1. Make a library with a strm files.
2. Build and sideload main
3. Attempt to browse to the detail page of one of these strm episodes or movies.
4. See error. Details hang indefinitely, telnet shows error. jf-roku has to be restarted to continue.

**Expected behavior**
We should like to see the details please.

**Logs**
I rolled back to release before copying them, sorry.  I will reproduce it if you ask me to.

**Additional context**
My server is rigged with that silly pr that makes strms probe "properly", but I don't think this is at fault.  jf-roku latest release works as expected.

**Comment by neilsb** [comment]
Do you see this on media items which are not strm files?

Do strm files play properly for you on the current store version of the Roku Client?

**Comment by whiteowl3** [comment]
No they do not play on the stock player, logic needs to be added which uses MediaSources[0].Path.  I just switched my build over to make it work, I mention because I don't think it's an implicit strm problem, I think it is actually occurring because all providers fail to generate audio/subtitle index values. jf-roku just needs to handle the case of audio index and subtitle index being none/nan.
I have not tested the case of a local file which cannot be probed (if you have any tricks for making a test video which breaks the providers, that could be useful), my thinking is that sanitizing the indices as integers is probably justifiable per se.

**Comment by whiteowl3** [comment]
Worth mentioning, probably, that the release does not have this issue.  Only the dev build has this error currently.
