### ISSUE TITLE
Error loading content after any transcoding restart

### ISSUE THREAD

**Issue by kaysond** [jellyfin-archive/jellyfin-roku-legacy#539]
**Describe the bug**
If I execute any action that requires the transcode to restart (I think), I get an error loading content and have to restart the video. Examples include rewinding or turning on/off subtitles.

**To Reproduce**

1. Start a video that requires transcoding
2. Rewind, or enable/disable subtitles

**Expected behavior**
Video continues as intented

**Logs**
No log errors on the server side. Haven't had a chance to put the roku in dev mode and check those logs.

I don't have any of these issues watching the videos on the browser.

**Comment by 1hitsong** [comment]
Please test again using the latest server and Roku client releases. There have been several key updates to transcode functionality since March.

If you still experience this issue, please open a new issue and we'll investigate.
