### ISSUE TITLE
Occasional crash on startup

### ISSUE THREAD

**Issue by TwitchBronBron** [jellyfin-archive/jellyfin-roku-legacy#544]
**Describe the bug**
Sometimes the app crashes on startup. I've seen this happen in the production version of the app, as well as when it's sideloaded. While debugging a different issue today, the crash happened. Here's the error:
![image](https://user-images.githubusercontent.com/2544493/160591825-a592efe8-3f11-473c-9448-26a9b8e5d015.png)

I'm not sure _why_ the `updateUser` method is being called in this context. The call stack shows that it's the only function in the call stack, so it's probably being triggered by an observer somewhere. 
![image](https://user-images.githubusercontent.com/2544493/160591993-6c5cd16f-c12e-4f1c-b474-72e9908cf71e.png)

**Comment by jimdogx** [comment]
Just a quick glance, it looks like the first thing the app does (Main.brs) is set "currentUser".  But if the overhang isn't available yet (e.g. timing issue?) then you'd get a crash.  Might be as simple as reversing these two lines in Main.brs (so that _CreateHomeGroup_ comes first):

```
   sceneManager.currentUser = m.user.Name
    group = CreateHomeGroup()
```

I can try this upcoming weekend, but since you are able to reproduce it, it might be worth giving it a shot and seeing if the crash goes away.

**Comment by TwitchBronBron** [comment]
I tried like 100 times to reproduce it, and couldn't get it to happen again. It seems to only happen periodically.

**Comment by jimdogx** [comment]
You are not crazy.  I got this twice this morning.  Still investigating.

**Comment by neilsb** [comment]
This is also odd like #560, and I agree it sounds like some  timing thing.  The overhang defined in the Scene XML so I would have assumed it should be created well before that was called.

I don't see any harm in having some additional checks there, just in case.

` if m.overhang <> invalid then m.overhang.currentUser = m.top.currentUser`

**Comment by jimdogx** [comment]
Funny, I've had this in my local build for a week... just waiting to see the print statement (to prove that at least it would catch it and not crash).  Never could reproduce it LOL

![Screen Shot 2022-04-22 at 12 59 33 PM](https://user-images.githubusercontent.com/18198517/164777609-766be073-bd60-4729-aa5c-afa1ee7383fa.png)

**Comment by neilsb** [comment]
Likewise. Had it for a while trying to see if the name in the overhang is still set, but keep forgetting to look. Certainly seems to have resolved those crashes for me.
