### ISSUE TITLE
When resuming playback of a video, subtitles don't work.

### ISSUE THREAD

**Issue by wyattoday** [jellyfin-archive/jellyfin-roku-legacy#547]
**Describe the bug**

When starting a video with subtitles, they work as expected.

When pausing that video, going back to the video later and resuming from that same spot, subtitles no longer work. You can get them to work by, instead of using the "Resume from X:X" option, choose the "Start from beginning" and fast forwarding to the spot you were in the video.

**To Reproduce**

See above.

**Expected behavior**

Subtitles should work when resuming a video.

**Logs**

N/A.

**Screenshots**

N/A

**Comment by jimdogx** [comment]
I'm looking in to this one.

**Comment by 1hitsong** [comment]
I can not recreate this issue using latest server and roku client versions. Closing for now, please open a new ticket and ref this on if issue remains.
