### ISSUE TITLE
Cannot display Thai Language

### ISSUE THREAD

**Issue by FarangFlix** [jellyfin-archive/jellyfin-roku-legacy#551]
My Roku Jellyfin app will not display media descriptions using the Thai Language as seen in the photo attached.
The server is English, the interface is in English.  I just have a "Thai TV" and "Thai Movies" folder that won't display properly.
I also use Plex server/client that handles Thai letters fine.
Any suggestions?
Thanks.
![IMG_20220403_174218](https://user-images.githubusercontent.com/102903993/161425117-836c117d-c40a-4ec8-b981-9966d588794f.jpg)

**Comment by neilsb** [comment]
See #285 and #514

Closing as duplicate of those. When resolved, as long as appropriate font file is used, should be displayed correctly

**Comment by FarangFlix** [comment]
I saw that but there was no resolution on it even tho' several people has asked.
