### ISSUE TITLE
Remove books in "continue watching" section.

### ISSUE THREAD

**Issue by kamanwu** [jellyfin-archive/jellyfin-roku-legacy#558]
This is related to https://github.com/jellyfin/jellyfin-roku/issues/525.

Books sections has been removed, but still can see books in "continue watching" section.

Please see this images. https://imgur.com/1B2VCRx , Could this be fixed as well? Thanks.

**Comment by jimdogx** [comment]
PR submitted.

**Comment by jimdogx** [comment]
This will get fixed with the new Home Screen (#553)
