### ISSUE TITLE
Missing music and playlists

### ISSUE THREAD

**Issue by macdabby** [jellyfin-archive/jellyfin-roku-legacy#565]
**Describe the bug**
I am connected to my server but when j look in music or playlists there is a message "this collectionfolder contains no items" or "this uservuew contains no items" respectively.

**To Reproduce**
1. Open app
2. Connect to server
3. Select music
4. Go back
5. Select playlists

**Expected behavior**
I should see the same music and artists and playlists that i see on Android.

**Comment by neilsb** [comment]
Both these features are still to be done. There are already issues open for both of them if you wish to subscribe to them for updates. #124 #108
