### ISSUE TITLE
Deep red color/tint on Roku Streaming Stick 4K

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin-archive/jellyfin-roku-legacy#569]
I've been using Jellyfin for a while now and haven't really had a color issue. I recently installed Jellyfin on a family member's Roku Streaming Stick 4K and it has a deep red color/tint to it, similar to that discussed in [this reddit post](https://www.reddit.com/r/jellyfin/comments/syd0fm/deep_red_color_on_jellyfin_channel_of_roku/). The color on all the other channels (apps) such as Netflix and HBO look great. It's just Jellyfin. Has anyone else experienced this / are people aware of this? Thanks!

**Comment by neilsb** [comment]
When you say you hadn't really had a color issue before, do you mean that now you're looking at it that it is present on your other Roku device  as well (maybe not as severe) or is it only one Roku device that is affected?

Is it noticeable on all media played from that particular Roku device, or is it only certain media?  If it's only certain, can you check if  the media is transcoding (easiest way is going to the server Dashboard while media is playing, and clicking on the information icon for the Roku device)

Are you able to play the same media via any other Roku client (e.g. Plex, Emby, Direct, etc), and if so is the red color still present?

Is the red tint visible in User Interface when navigating media, or only when something is playing?

**Comment by AArnott** [comment]
For me, I only have a Roku Streaming Stick 4K. There is a deep red tint in the Jellyfin channel only, and only for _one_ series of a TV show I ripped from DVDs (Dr. Quinn). These same video files look great (i.e. no red tint) on computers with the Jellyfin Media Player. And all my other video files from other TV series or movies that I've ripped have no red tint to them on the Roku device. I tried multiple TVs with the Roku, and the red tint happens the same on any TV.
So this only repros on Roku+Dr.Quinn. Very strange.

Any idea why the Roku Jellyfin channel would uniquely apply a red tint, to only one ripped DVD series, where that same series looks good on a computer?

**Comment by nothing2obvi** [comment]
> When you say you hadn't really had a color issue before, do you mean that now you're looking at it that it is present on your other Roku device as well (maybe not as severe) or is it only one Roku device that is affected?
> 
> Is it noticeable on all media played from that particular Roku device, or is it only certain media? If it's only certain, can you check if the media is transcoding (easiest way is going to the server Dashboard while media is playing, and clicking on the information icon for the Roku device)
> 
> Are you able to play the same media via any other Roku client (e.g. Plex, Emby, Direct, etc), and if so is the red color still present?
> 
> Is the red tint visible in User Interface when navigating media, or only when something is playing?

1.)  When you say you hadn't really had a color issue before, do you mean that now you're looking at it that it is present on your other Roku device as well (maybe not as severe) or is it only one Roku device that is affected?

As far as Roku devices go, this is the only Roku I have. And it has this red tint issue. Jellyfin clients on all my other devices do not have this red tint.

2.) Is it noticeable on all media played from that particular Roku device, or is it only certain media?

It is noticeable on all media played from this Roku device.

3.) Are you able to play the same media via any other Roku client (e.g. Plex, Emby, Direct, etc), and if so is the red color still present?

I have not tried this. Although, again, as far as the Roku device goes, watching Netflix or HBO on their respective apps exhibits no red tint issue.

4.) Is the red tint visible in User Interface when navigating media, or only when something is playing?

The red tint is only visible when something is playing. The User Interface looks great.

**Comment by AArnott** [comment]
I noticed this on Avengers as well as Dr. Quinn, so I did some more digging. By using Handbrake to encode as H.264 instead of H.265, the deep red disappeared. H.265 is just fine for most disks, but for those with the deep red, I'll re-encode as H.264 to workaround this bizarre problem.

**Comment by BrianB-22** [comment]
Anyone know of any updates on this issue?  I also have this "red tint"  issue with Roku 4K devices and Jellyfin video playback.   Only with the 4K Roku units other Roku's are fine.    Also have this "red tint" using Roku's own media player and the same videos.  Causing me to think this is more of a Roku issue then Jellyfin.  

Most movies have a very bad "red tint" to the image particularly with skin tones.  Odd thing is it's not all my backed up DVD movies but most.   I'm archiving them with H264, and MKV containers.   Not sure if it makes a difference, but in movies with *correct coloring* inspecting the video info under the "Video color information" section I have these additional parameters - "Color Transfer", "Color Matrix Coefficients", "Color Primaries".  For the "red tint" videos they lack these parameters and just have "Color Range", "Horizontal chroma siting", and "Vertical chroma siting".    

Would this make a difference?  And not sure why some include this data and others don't.  I'm backing them up all in the same manner.

**Comment by attzonko** [comment]
This appears to be an issue with the Roku 4K support for x265 HEVC. I don't believe it can be fixed on the client side.

**Comment by 1hitsong** [comment]
We've recently pushed some updates for HEVC suppport. Please retest this using the latest Roku client and adjusting the HEVC playback settings.

**Comment by AArnott** [comment]
@1hitsong That's great news. How do we get the latest Roku client on our existing 4K stream sticks? Does it self-update or do we need to do something? And what HEVC playback settings need to be adjusted?

**Comment by TaterSalad333** [comment]
> We've recently pushed some updates for HEVC suppport. Please retest this using the latest Roku client and adjusting the HEVC playback settings.

Echoing @AArnott question. How to update and what settings?

**Comment by nothing2obvi** [comment]
After upgrading to the latest Jellyfin for Roku Client (I believe 1.6.4), this doesn’t appear to be an issue anymore. I will close this issue.

**Comment by AArnott** [comment]
I was going to ask how do you upgrade the Jellyfin for Roku client (or even see the current version), but this morning my Jellyfin app on Roku just popped a release notes display, and though it didn't mention this bug, a spot check on some shows that had the problem before appear to not have it any more. So, yay!

**Comment by cewert** [comment]
Thank you guys for reporting back!

@AArnott For future reference, you can check the channel version from the home screen by pressing the star(*) key while hovering the channel.

**Comment by hankster112** [comment]
This issue also occurs on the Jellyfin app on LG webOS. It may also occur on other clients/devices but I honestly can't tell (watched the same content on Jellyfin Media Player on Debian and the Jellyfin app on Android, and it's really hard to tell, but it definitely happens on Jellyfin for webOS). Trying to watch HEVC video results in a red tint on many of the lighter colors. This is the first time I've seen this happen when playing back HEVC content. The other media info for HEVC content that plays fine seems to be missing the color space and pixel format this has. Media info is below.

```
Title: 4K HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 150
Resolution: 3840x2160
Aspect ratio: 16:9
Interlaced: No
Framerate: 25
Bitrate: 4185 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt2020nc
Pixel format: yuv420p10le
Ref frames: 1
```

**Comment by AArnott** [comment]
It turns out this is still a problem. I still frequently see red tint on H.265 encoded videos, but only when played through the Roku.

**Comment by berke0bayraktar** [comment]
This issue also exists on the vp9 codec
