### ISSUE TITLE
Selecting a Collection item without access from another Library view

### ISSUE THREAD

**Issue by LePips** [jellyfin-archive/jellyfin-roku-legacy#574]
**Describe the bug**
When a collection item is selected while viewing contents of a library, a crash occurs.

**To Reproduce**

1. Have a library ("Movies" for example) and "Collections" library enabled with a collection of movies created ("Star Wars Collection" for example)
2. Create a user with access to "Movies" but not "Collections"
3. View "Movies" will show library contents as well as Collection items, like "Star Wars Collection"
4. Select "Star Wars Collection"
5. Observe crash as access is denied

**Expected behavior**
Unknown. Ideas:
- Collection items should not be shown in other libraries (filter by item type)
- Show "access denied" view or other visual indicator

**Comment by neilsb** [comment]
The way the API calls are done currently, the response code is not kept, so it's not straightforward right now to tell the reason for the failed call.  This needs re-worked, but in the meantime #577 will check that a valid response was received before trying to parse the response.

If the response was invalid, the screen will show the same message as an empty collection "This Boxset contains not items" which is at least not a crash.  Would no doubt raise questions about why there are no items.   This seems to a be similar approach to web currently.

**Comment by jimdogx** [comment]
Funny, while I was working on #478 the server went down for maintenance and the client crashed while trying to load episodes.  It crashed in the exact same spot you just applied your fix.  So this may fix more than one type of crash 😄
