### ISSUE TITLE
Parity Webapp Search

### ISSUE THREAD

**Issue by bisby** [jellyfin-archive/jellyfin-roku-legacy#58]
**Is your feature request related to a problem? Please describe.**

The webapp fires off like 10 searches at a time for search instead of 1 mega search.

**Describe the solution you'd like**

We should break search queries up.

**Describe alternatives you've considered**

**Additional context**

Making API requests more similar to webapp means it should be easier to decide which endpoints to use.

**Comment by anthonylavado** [comment]
I feel like this is ok for now - searching seems to work well enough for both TV Shows, TV Show names, and Movies. The only video type left would be TV shows, but that's probably best served in a new ticket.
