### ISSUE TITLE
Voice search

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#587]
**Describe the feature you'd like**

I'm a new user, with a new Roku box. On setting up the box, it taught me to use the voice search, which sounds far preferable to using an on-screen keyboard or scrolling down pages and pages through my collection.

I was then disappointed to find that the Jellyfin app doesn't seem to support it: if I attempt a choice search, it's interpreting my speech correctly but I'm told "no results from Jellyfin".

Is this feature possible? Planned? In the works? Present but not working for me?

**Comment by candry7731** [comment]
@tremby thanks for the feature request. We are currently working on a new search page and one that DOES support voice search! 

There is no timeliness on when this will be implemented but we are currently working on it. 

Thanks

**Comment by tremby** [comment]
>
> That's excellent news; thank you!

Hopefully you wouldn't need to get to the search page before it works? I'm
hoping to just hold the voice button on the remote from any screen (maybe
just a Jellyfin screen).

**Comment by neilsb** [comment]
> Hopefully you wouldn't need to get to the search page before it works? I'm hoping to just hold the voice button on the remote from any screen (maybe just a Jellyfin screen).

Unfortunately you would need to go to the search page first.  When you press the voice button from within an app, unless you're on a voice keyboard (or playing back media) then it uses the Roku inbuild media search.   In order for Channels to appear in this list, they need to provide a way for Roku to retrieve the media that they have available.   This is done by the Roku servers, and each channel has a single source of data for Roku.

So while this if fine for Netflix, Disney etc, since each Jellyfin server has a different set of media on it, it's not something that we can do.

**Comment by tremby** [comment]
Oh wow, that's a shame. I wonder if they're aware that that model is a
limitation. Maybe we could open a feature request with them, if nobody
already has.

I wonder if it could be worked around. What if someone maintained a proxy
server which Jellyfin users could opt in to, which knows how to access each
opted-in user's Jellyfin server? I guess this wouldn't work if user
identity is not available in the query that gets made by Roku, or if Roku
caches results and shares them between all users.

**Comment by anthonylavado** [comment]
It's the same model that Google follows, except Roku lets anyone join (after passing a review/validation test, where Google is invite only).

It doesn't pass on any user data at all, it just searches and matches what Channels have the content ID marked as available in the user's region. The feed is also cached on the Roku side, updating approx. every 24 hours.

Specifications are here: https://developer.roku.com/en-ca/docs/developer-program/discovery/search/implementing-search.md

As far as a central/proxy server goes, we try to reduce the number of services we run to help make sure things are private and secure.

**Comment by candry7731** [comment]
We could add a voice observe field that is hidden on the library pages that will run the loaditemstask2 and filter results, So if they are in a library you could easily "Search/Filter" by the voice command....

**Comment by tremby** [comment]
@anthonylavado
> It doesn't pass on any user data at all, it just searches and matches what Channels have the content ID marked as available in the user's region. The feed is also cached on the Roku side, updating approx. every 24 hours.
> 
> Specifications are here: https://developer.roku.com/en-ca/docs/developer-program/discovery/search/implementing-search.md
> 
> As far as a central/proxy server goes, we try to reduce the number of services we run to help make sure things are private and secure.

I see. Yeah, unfortunately with their model a proxy like I was imagining wouldn't help anyway. You'd need that identity information otherwise everyone sees everyone's results, and so I suppose the only option there would be for each user to publishing their own fork of the channel and search feed. Does not sound good.

@candry7731
> We could add a voice observe field that is hidden on the library pages that will run the loaditemstask2 and filter results, So if they are in a library you could easily "Search/Filter" by the voice command....

That sounds great, if I'm understanding right. That'd mean pressing the voice button anywhere in the Jellyfin channel (other than playback) would trigger an in-channel search? That'd be a whole lot better than "no results from Jellyfin" and some useless results from other channels.

**Comment by neilsb** [comment]
> That'd mean pressing the voice button anywhere in the Jellyfin channel (other than playback) would trigger an in-channel search?

That's not quite how the PR has been implemented currently, but given the work @candry7731 has done, I don't think that would be difficult to implement.

Currently if a user is viewing a collection (on the Media Grid page) and they use the voice search, it filters that collection to only show matching items.  So effectively it filters that grid by the search term.  It doesn't do a server wide search.  

And using the voice elsewhere in the app (not in a collection) still hits the current Roku search.

**Comment by tremby** [comment]
I guess I'm not familiar yet with the names of the different pages. If you're dug into a particular category like movies, filtering that category definitely makes sense; that sounds great. If you're on the front page (is that what the "media grid" is?), a search over the whole Jellyfin server would be ideal, I think.
