### ISSUE TITLE
Status of the Roku app

### ISSUE THREAD

**Issue by TwitchBronBron** [jellyfin-archive/jellyfin-roku-legacy#59]
Hey, I just discovered Jellyfin yesterday, and it's looking really great! However, we exclusively use Roku devices in our house...and the Roku app is quite lacking. I'm a programmer, and have some experience with Roku development. (I maintain the [vscode-brightscript-language](https://marketplace.visualstudio.com/items?itemName=celsoaf.brightscript)).  I'd love to pitch in and help with the Roku app...but before I started hacking away at it, I wanted to make sure you didn't have a ton of commits sitting locally that weren't pushed?

**Comment by anthonylavado** [comment]
Tagging @bisby. I believe they said they were learning as they went along though.

**Comment by bisby** [comment]
No local commits waiting. It was definitely a learning project and would love some Roku experience. We use mostly Roku devices in my house as well, which is why "something" was better than nothing, so I completely understand.

**Comment by abudden** [comment]
I can't offer anything in the way of useful Roku development help, but it would be great to see this.  I migrated from Plex to Emby when Plex stopped working with a Roku application update.  Emby seems okay generally, but the Roku app usually crashes at least once during any video I watch.  It'd be great to see a fully open source alternative that I could at least try to help fix issues with if I came across them.

I know this comment doesn't add much; I just wanted to make it clear that all of your efforts are really appreciated!

**Comment by TwitchBronBron** [comment]
@bisby sounds good. I'll start messing around and see what I can add to the mix. I definitely appreciate how much work you've done thus far, so thanks!

**Comment by thornbill** [comment]
@TwitchBronBron if you haven’t already, feel free to join our chat on Matrix. We have various channels there some that are specifically for development discussion. You can find the details at https://jellyfin.github.io/socialcontact.html
