### ISSUE TITLE
Roku no longer appearing in "play on" list on other apps (eg Android)

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#590]
**Describe the bug**

This was working for the first day or two I was using jellyfin-roku, but now for the last couple of days Roku is no longer appearing in the "play on" menu of other apps, for example Roku for Android.

**To Reproduce**
1. Open the Jellyfin channel on Roku 
2. Open Jellyfin on Android (signed in as the same user)
3. On Android, click the "play on" button to get the dropdown menu
4. Roku is not listed

**Expected behavior**
The jellyfin-roku instance appears in the menu.

**Logs**
(Please point me to a guide to collecting logs, if there might be something useful I can find.)

**Screenshots**

**Additional context**
I've tried restarting the Android app, and also rebooting the Roku and reopening the Jellyfin channel. I've tried signing out and back in again.

I'm not sure if it's related but when logging out and back in again I noticed that it offers one user, "user B", which is not my primary user. If I choose that one it seems to immediately log me in (even though I've never given jellyfin-roku the password for user B) but in the top right of the screen I still see my "user A" username. I've no idea what's going on there. In that state I still didn't see Roku in the the "play on" menu. I then signed out and manually entered user A's password again, still no luck.

**Comment by neilsb** [comment]
Are you certain this was working, as the Roku client doesn't currently support remote play?  There is an issue (#42) that covers this.

**Comment by tremby** [comment]
Oh... Now you've got me second guessing myself. I could have sworn, but it could be my mind playing tricks on me. It could be that I still had jellyfin-mpv-shim running on the pi connected to the same TV and I assumed it was Roku since I'd just installed this channel.

If it's not implemented yet it's not implemented yet! Sorry for the noise.

**Comment by neilsb** [comment]
Not a problem at all. It's on the list. We'll get there eventually 🙂
