### ISSUE TITLE
Add support for per-user "Parental Controls"

### ISSUE THREAD

**Issue by candry7731** [jellyfin-archive/jellyfin-roku-legacy#592]
**Describe the feature you'd like**
Need to exclude items in the libraires and in the search results

**Additional context**
It seems like the roku player does not have any login to respect the "Parental Content" section of the web client. We will need to write some login to exclude items based on users settings.

**Comment by cewert** [comment]
These settings are set up server side by using the web client -> server dashboard -> users -> select a user -> "Parental Control" tab at top
