### ISSUE TITLE
[Issue]: Flickering images on any selection. 

### ISSUE THREAD

**Issue by eyedoc3188** [jellyfin-archive/jellyfin-roku-legacy#598]
### Please describe your bug

Just what I said about. I've got video I took of the issue on reddit here: https://old.reddit.com/r/jellyfin/comments/ujw70b/jellyfin_flickering_badly_help/. 

Video here if you hate reddit: https://imgur.com/a/xNkZOKY

Any help? (I'm a newb for sure. But fairly computer savvy). Hit me up on reddit (I check it more often) or here. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jimdogx** [comment]
I am able to reproduce this and have a working theory of the cause.  More to come.

**Comment by zzzb123** [comment]
for what it's worth, I am still experiencing this on 1.4.14 (roku is a tcl TV)

**Comment by cewert** [comment]
@zzzb123 What resolution is the roku app using? This was a know bug in the past for people using 720p instead of 1080p for the roku UI. It should have been fixed but I'm betting it popped up again

**Comment by zzzb123** [comment]
its running 4k, and it stops flickering after a while usually, though with some images missing.

edit:  it usually starts flickering again if I interact with the UI

**Comment by jimdogx** [comment]
@zzzb123 Is this still an issue for you?  It appears others are also experience this again: https://github.com/jellyfin/jellyfin-roku/issues/863

**Comment by zzzb123** [comment]
Never stopped being an issue.  Unlike what the new issue implies about it being a movies screen only issue, this has been happening to me on every screen.  Given it's a 4k TV I doubt the posters are too large (though possible), I feel it looks more like some kind of image cache eviction related issue, though I have not actually looked at the code to see if that conclusion makes sense.

**Comment by eyedoc3188** [comment]
Yeap, I actually stopped using jellyfin on Mt NAS and instead use it on my
primary PC and direct jellyfin to the network shares
