### ISSUE TITLE
Pagination doesn't work (random sort order)

### ISSUE THREAD

**Issue by fabianvf** [jellyfin-archive/jellyfin-roku-legacy#61]
**Describe the bug**

I have a few hundred items in my jellyfin library, and when I try to browse through them (by hitting next page), the list gets scrambled. Generally the first result on the second page will be the same as it was on the first page, and the rest of the results are in a totally random order (afaict), with plenty of duplicates from the first page. If I then go back to the first page, it's also in a totally random order.

**To Reproduce**

1. Have enough media items that the results are paginated (I have 3 pages)
2. Click on the folder that has the aforementioned media items
3. Scroll down to the next page button
4. Click the next page button
5. See a random list of movies in no particular order

**Expected behavior**

Ordered list of items, allowing me to browse my whole collection

**Logs**

**Screenshots**

**Additional context**

**Comment by bisby** [comment]
Is this happening in the latest master branch?

Not a duplicate of https://github.com/jellyfin/jellyfin-roku/issues/56 ?

Some code was abstracted and a few things were missed migrating old code into the newer model. But as far as I could tell it was all resolved.

**Comment by fabianvf** [comment]
I'll take another look, I thought I was on latest but it's definitely possible I just messed up the deploy

**Comment by fabianvf** [comment]
My bad, this is total PEBKAC, I had changed the password for rokudev without updating my deploy script, so I *thought* I was up to date but I was just running on a very old build.
