### ISSUE TITLE
Add support for more file types

### ISSUE THREAD

**Issue by onlytahmidthings** [jellyfin-archive/jellyfin-roku-legacy#611]
I try to play many video and jelly fin does not support them so add them please so that we can enjoy

**Comment by neilsb** [comment]
Is this on the Jellyfin Roku channel you are having problems?

Could you please provide more information:

 - What file types are not supported?
 - What version of the server are you running?
 - Is transcoding enabled on the server?
 - Do the files play correctly via the Jellyfin Web site?

**Comment by neilsb** [comment]
Closing due to lack of information and response.
