### ISSUE TITLE
Checkmarks on watched episodes aren't centred properly

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#614]
**Describe the bug**
I'm seeing checkmarks not centered within their blue circles.

**To Reproduce**
1. View a season's episode list with some watched episodes

**Expected behavior**
Checkmark symbol is centred within its circle.

**Screenshots**
![PXL_20220528_041515501](https://user-images.githubusercontent.com/199635/170809573-ea81ba04-27ee-4b4f-b1be-ea6ea4d4298f.jpg)

**Additional context**
You'll also see one is bigger than the others; that's reported as #615.
You'll also see the aspect ratio is off but I suspect this is connected to #603.

**Comment by anthonylavado** [comment]
This is actually a variant of #312, believe it or not. Since you've reminded us of it, we'll see about taking action on it.

**Comment by tremby** [comment]
Dupe
