### ISSUE TITLE
Some "watched" checkmarks are bigger than others

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#615]
**Describe the bug**
I'm seeing some "watched" checkmarks display much larger than others.

I wonder if it's to do with the resolution of the thumbnail. The lower thumbnail in my photo looks to be much lower resolution, and has a much bigger checkmark which also looks to be lower resolution than the other checkmarks.

**To Reproduce**
1. Go to a season's episode list
2. Look through episodes, pay attention to the size of the checkmarks

**Expected behavior**
Consistent sizing

**Screenshots**
![PXL_20220528_041515501](https://user-images.githubusercontent.com/199635/170809682-6f4ed607-5e2a-4721-9cd4-688fba18ce32.jpg)

**Additional context**

You'll see also that the checkmarks aren't centred; that's reported as #614.
You'll see also that the aspect ratio of the images and checkmarks are off, which I suspect is related to #603.
I'm using the current stable release.

**Comment by 1hitsong** [comment]
This was an issue on the server side. We don't generate the checks within the Roku app. I believe this is now resolved.
