### ISSUE TITLE
"Refresh" episode list when reappearing on screen

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#616]
**Describe the bug**
I noticed and reproduced a few times that after starting an unwatched episode from the episode list of a season, and letting playback complete, the checkmark does not appear.

**To Reproduce**

1. Go to the episode list page of a season of a show
2. Find an unwatched episode
3. Play it, allow it to finish
4. Now that you're back at the season page, see that the checkmark has not appeared
5. Press back to return to the show page
6. Click to enter that season again
7. Scroll to the episode you just watched
8. See that it now has the "watched" checkmark

**Expected behavior**
"Watched" checkmark appears immediately after watching

**Logs**

**Screenshots**

**Additional context**

Current stable release

**Comment by cewert** [comment]
No one has attempted to implement "refreshing" the episode list view when it reappears on screen. Removing bug tag
