### ISSUE TITLE
Move Alpha Menu to left side of screen

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#626]
I think the new alpha menu is pretty sweet and can see myself using it a lot.
I propose we move it from the right side of the screen to the left. That way it can be accessed in 1 button click vs the 6 it takes now.

**Describe the solution you'd like**
Move alpha box to left side of screen

**Comment by candry7731** [comment]
I think this make sense... I can make the update once everyone weighs in.

**Comment by jimdogx** [comment]
Closed via #636
