### ISSUE TITLE
Last selected poster stays highlighted when Alpha Menu in focus

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#627]
**Describe the bug**
I was messing with the new alpha menu and lost where my selector was. Maybe bug isn't the right label? but this doesn't seem intended.

When popping over to the alpha menu from a poster, the poster stays "focused" - it doesn't shrink back down. Then if the user hits left to go back on the poster, the only visual change is the background color and text of whatever letter you had highlighted changing.

**To Reproduce**

1. Go to a video or tv show library
2. hit right 6 times
3. observe how the last poster selected stays "focused"
4. hit left once
5. observe

**Expected behavior**
last poster highlighted shrinks back down

**Additional context**
latest dev

**Comment by neilsb** [comment]
Should you always return to the previously selected item when pressing left and leaving the alphapicker, or should it depend on where you are on the picker?

i.e. 
 - \# - N --> Go back to top row right most item
 - O - Z --> Go back to bottom row right most item

**Comment by cewert** [comment]
Yea that's a great point. I guess that was a benefit of the poster staying big - at least you knew where your cursor would rejoin the itemgrid. It would be more intuitive if it was dynamic based on where you were in the picker like you suggested.

**Comment by candry7731** [comment]
#636 Should fix this.

**Comment by jimdogx** [comment]
Closed via #636
