### ISSUE TITLE
Items that don't have remote metadata cause a crash

### ISSUE THREAD

**Issue by dkanada** [jellyfin-archive/jellyfin-roku-legacy#63]
The item details page will crash when trying to load any empty metadata fields, which can often be the case when someone doesn't enable remote providers. The exact issue I ran into is the [community rating](https://github.com/jellyfin/jellyfin-roku/blob/f78e72fe2e626715c84d1b9be873d53b575ce039/components/movies/details.brs#L24) but I'm guessing it would be an issue for all of them.

**Comment by lpukatch** [comment]
I ran into this same problem and "fixed" it by checking if the community rating field was valid in the group description page. I'm not sure how to check validity in brightscript outside of IF statements but I might dig into this when I have time. At the very least checking each element is valid before assigning it to the display fields would save a lot of headache
