### ISSUE TITLE
'dPad left' and 'dPad right' should respect user's preferences for skip length in Jellyfin

### ISSUE THREAD

**Issue by kpfleming** [jellyfin-archive/jellyfin-roku-legacy#631]
**Describe the feature you'd like**
When the 'dPad left' (skip backward) and 'dPad right' (skip forward) buttons on the Roku remote are pressed during playback, the skip length should be the configured length from the user's preferences in the Jellyfin server. The 'skip backward' length should probably also be used for the 'instant replay/skip-back' button.

**Comment by jimdogx** [comment]
Investigating...

**Comment by 1hitsong** [comment]
Sorry, but Roku does not provide a method for us to change the skip length It's hard coded into the video player.
