### ISSUE TITLE
v1.4 build 13 shows as build 12

### ISSUE THREAD

**Issue by wynterca** [jellyfin-archive/jellyfin-roku-legacy#635]
**Describe the bug**
The new version is showing as v1.4 build 12 on my Roku TV and Streaming Stick.  I believe it is the new version as it has the new settings menu.

**To Reproduce**
Update the app from the Roku menu and then press * on the app and it shows version v1.4 build 12

**Expected behavior**
It should show v1.4 build 13 after update.

**Comment by cewert** [comment]
You are correct, we forgot to bump the version before release. Thank you for letting us know
