### ISSUE TITLE
On menu screens, "replay" button should send you to the start of the list

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#637]
**Is your feature request related to a problem? Please describe.**

It's frustrating to get to the start of lists. When tapping left left left, the number showing your current index and the total fades out, and only comes back when I stop moving. If I want to go to the beginning I need to tap tap tap, wait, tap tap tap, wait, tap tap tap, wait, oops I've overshot.

**Describe the solution you'd like**

- Don't fade out the position indicator, if possible
- Make the "replay" button skip straight to the beginning

**Describe alternatives you've considered**

Can't think of others, except the status quo.

**Additional context**

**Comment by candry7731** [comment]
The item count updated when an item gains focus, if you are scrolling fast the roku doesnt gain focus on the item... Not sure what we can update on this but will test out some options.
I think using the replay button makes sense. Let me see what I can work out.

When the new voice search comes out the replay button will be used to clear/reset the voice and alpha picker.

**Comment by candry7731** [comment]
@tremby let me know what you think.

**Comment by tremby** [comment]
I'm afraid I'm travelling and so have no Roku to test with at the moment.

Thanks for getting to this though!

I had a quick look at the code, and I was surprised a config option was deemed necessary. It looks like maybe the two possible actions, which I take it from the comments were "instant" vs "slow animation", were both suboptimal? Or was it more a matter of allowing users susceptible to motion sickness to reduce motion?

**Comment by candry7731** [comment]
I think giving user the ability to customize is nice however, users do not need to change or enable this to work...

**Comment by jimdogx** [comment]
@tremby I approved / merged @candry7731 's "Jump to 1st item in folder".  It works out of the box but gives the user the ability to pick between animated or "immediate".  Which I think is a nice touch (giving the user options).

When you have some time / back home / etc, let us know if this update to the replay button satisfies your need enough to close this issue.

**Comment by jimdogx** [comment]
Even though @tremby hasn't replied yet, I just realized while using the client, that the replay button feature merged doesn't address his issue.  The issue he is having is on the Home Screen and not within subitems.

**Comment by tremby** [comment]
I'm still away; I won't be home again for a couple of weeks still.

**Comment by candry7731** [comment]
@jimdogx #593 will have the "replay" button functionality for the home screen rows which should be what @tremby is requesting.

On the home screen scroll through the row then hit the "replay" button to go back to the first item in the row.

**Comment by jimdogx** [comment]
@candry7731 Sorry, didn't realize that was part of the voice search PR.  I added the functionality to #671 and it's already been merged to master.
