### ISSUE TITLE
ROKU has a problem watching some videos with new JF (MPEG4 vs H264)

### ISSUE THREAD

**Issue by mbramwel** [jellyfin-archive/jellyfin-roku-legacy#651]
`ROKU 4K Stick running 1.4 Build 12  (but was recently updated to the hidden build 13 -- no improvement to playback)

Watching some older TV series

Some videos will not play.  
JF Beta2 was ok, JF Beta3 introduced the problem.  
JF final 18.0 release still has the problem

A popup screen states:
"Error During Playback"
"An error was encountered while playing the item"

Any videos that have this will fail:
Video: 480p MPEG4 SDR Audio: MP3 Stereo

Any videos with this will play ok instantly:
Video: 480p H264 SDR Audio: MP3 Stereo

BTW:  Firestick and AndroidTV both play the same videos without issue. The ROKU will work again if I revert back to JF Beta2.
`

**Comment by cskaryd** [comment]
Also seeing this.  Video plays fine through the web interface, but not on Roku. Same error as above.

Jellyfin versions (CentOS):
jellyfin-server-10.8.0-1.el7.x86_64
jellyfin-web-10.8.0-1.el7.noarch

ffmpeg versions
ffprobe version N-61656-gfbd22504c4-static
ffmpeg version N-61656-gfbd22504c4-static

Mediainfo:
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 141 MiB
Duration                                 : 20 min 51 s
Overall bit rate                         : 943 kb/s
Writing library                          : VirtualDub build 13130/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 20 min 51 s
Bit rate                                 : 900 kb/s
Width                                    : 480 pixels
Height                                   : 352 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.178
Stream size                              : 134 MiB (95%)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 2
Format profile                           : Layer 3
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 20 min 51 s
Bit rate mode                            : Constant
Bit rate                                 : 32.0 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 16.0 kHz
Compression mode                         : Lossy
Stream size                              : 4.78 MiB (3%)
Alignment                                : Split across interleaves
Interleave, duration                     : 36  ms (1.08 video frame)
Interleave, preload duration             : 444  ms

**Comment by matthewpritchett** [comment]
I’m seeing the same error on some HEVC videos:


Video
Title: 1080p HEVC SDR
Codec: HEVC
Profile: Main
Level: 120
Resolution: 1440x1080
Aspect ratio: 4:3
Interlaced: No
Framerate: 23.976025
Bitrate: 2736 kbps
Bit depth: 8 bit
Video range: SDR
Pixel format: yuv420p
Ref frames: 1


Audio
Title: English - AAC - Stereo - Default
Language: eng
Codec: AAC
Profile: HE-AAC
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

**Comment by mbramwel** [comment]
18.0.1 was pushed out last night.   No change, the ROKU is still unable to play lots of stuff.  If I revert the JF server to beta-2, all is ok.  If I try Android or Firestick-MAX-4k all is ok.  Only the ROKU no longer works correctly.

**Comment by cewert** [comment]
Fixed by #699
