### ISSUE TITLE
After selecting series, app force closes on seasons page after 1 second

### ISSUE THREAD

**Issue by jmvbrown** [jellyfin-archive/jellyfin-roku-legacy#674]
Roku App Version: Version 1.4, build 12
Jellyfin Server Version: 10.8.1
Series affected: Survivor South Africa

**Comment by whiteowl3** [comment]
@jmvbrown please consider adding minimal details to this such as roku app version, jellyfin server version, etc...

**Comment by jmvbrown** [comment]
okay, I updated with more info. Sorry about that!

**Comment by 1hitsong** [comment]
I'm unable to recreate this issue. @jmvbrown Is this still occurring?

**Comment by jmvbrown** [comment]
I no longer get this issue, you can close this issue!
