### ISSUE TITLE
Testing framework not working

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#68]
**Describe the bug**
app crashes when running "make test"

**Logs**
`------ Running dev 'Jellyfin' main ------
Starting test using test scene with name TestsSceneTestsScene
#########################################################################
#TEST START : ###UNDEFINED_TEST_ID###
Loading test config from default location : pkg:/source/tests/testconfig.json
 ERROR! RBSFM_getTestSuitesForProject is not found! That looks like you didn't run the preprocessor as part of your test process. Please refer to the docs.`

**Comment by cewert** [comment]
The readme says to npm install rooibos-preprocessor but that package has been [renamed](https://github.com/georgejecook/rooibos-cli) to rooibos-cli.

I uninstalled rooibos-preprocessor and install rooibos-cli thinking that would fix my error but no luck.

I'll fix the readme then see if I can figure it out

**Comment by nijave** [comment]
> 
> 
> The readme says to npm install rooibos-preprocessor but that package has been [renamed](https://github.com/georgejecook/rooibos-cli) to rooibos-cli.
> 
> I uninstalled rooibos-preprocessor and install rooibos-cli thinking that would fix my error but no luck.
> 
> I'll fix the readme then see if I can figure it out

When I tried it seems `rooibos-cli` isn't backwards compatible with `roobios-preprocessor`. I think there are a couplw major version upgrades since the version this is trying to use. I didn't know enough about how it worked to try to figure out the new syntax

**Comment by anthonylavado** [comment]
Will move over to a new testing ticket.
