### ISSUE TITLE
Resume dialog interrupts next episode functionality

### ISSUE THREAD

**Issue by whiteowl3** [jellyfin-archive/jellyfin-roku-legacy#680]
**Describe the bug**

**To Reproduce**

1. Watch at least your resume percentage of a show that is not first in a series
2. Watch the previous episode completely with play next episode enabled
3. Observe that the resume modal dialog is awaiting input, next episode will not play without intervention

**Expected behavior**
"Play next episode" should always play the next episode from the beginning without user intervention.

**Comment by candry7731** [comment]
Question: if the next episode has been started previously do you want the popup to give you the option to start from the beginning or should the next episode just always start from the beginning and auto play with out any buttons needing to be pressed?

**Comment by neilsb** [comment]
Fixed by #783
