### ISSUE TITLE
remux DoVi MKV to MP4

### ISSUE THREAD

**Issue by Terebi42** [jellyfin-archive/jellyfin-roku-legacy#685]
**Describe the feature you'd like**
The TCL Roku TVs (and possibly Roku Boxes?) support Dolby vision, but only in MP4 containers. 

If Jellyfin would remux the mkv to mk4 and preserve the DoVi, it would dramatically increase compatibility for playback. 

This is apparently already done in the Safari client, see https://imgur.com/a/MbvAgjy

**Additional context**
I have test files available that work in TCL Roku (mp4 trigger DoVi) on plex or jellyfin 

and I have files that come across purple in PLEX, but fail to render at all in Jellyfin (mkv)

I can provide release names privately if needed.

**Comment by Terebi42** [comment]
m2ts container might also be an ok target, that may have less limitations than mp4

**Comment by whiteowl3** [comment]
ive done some preliminary work on supporting different HDR levels to facilitate a discussion on how HDR support should be implemented. #686 in its current state this pr at least appears to report the correct video level support, and to transcode or not transcode for the correct reason, but testing of this on other setups would help, as well as discussing the actual structure of the implementation.

**Comment by Terebi42** [comment]
> but testing of this on other setups would help



I'm happy to test, but am a .net dev, so have no idea how to build or deploy the jellyfin client to my roku

ed : ah, the devguide doesn't look too bad. Ill pull down the code and test once the PR gets merged

**Comment by whiteowl3** [comment]
a device profile of safari on ios12 remuxing an mkv for "ContainerNotSupported":
https://pastebin.com/raw/BFjXuFUB

**Comment by tiagogaspar8** [comment]
This, please, it would allow us to have our libraries in nice juicy mkv, but not only for ruku, this applies to almost all platforms

**Comment by whiteowl3** [comment]
from chat:
zackoid
—
it's common for DV to only be supported in mp4 containers. so if you can accurately detect the presence of DV there wouldn't be any harm in remuxing whenever it is present. i don't think a standard remux translates all the metadata correctly so that is probably something that can't be handled on the roku end alone, but i'm not certain about that.

**Comment by Terebi42** [comment]
re "standard remux", this tool does the work for offline transcoding. Not sure if/how this could be done from inside jellyfin, but they are both ultimately shelling out to ffmpeg?

https://github.com/gacopl/dvmkv2mp4
