### ISSUE TITLE
[1.4.12] "No route to host" When trying to connect on Roku TV or Roku Express

### ISSUE THREAD

**Issue by Drakmyth** [jellyfin-archive/jellyfin-roku-legacy#687]
**Describe the bug**
Most times when attempting to open the Jellyfin app on either of my Sharp Roku TV or Roku Express I am directed to the server select screen. Entering my local server address (http://myserver:8096) nearly always results in the following error:
```
Error: [-7] Failed to connect to myserver port 8096 after 2299 ms: No route to host
```
The delay is usually around 2200-3000 ms. Once in a great while, which I am unable to reliably reproduce, it will let me through to the credentials prompt. Attempting to watch a show when I am able to get through either does nothing (I can navigate around on the screen, but clicking "OK" on anything does nothing), crashes the app, ~or causes a dialog saying "An error was encountered while playing this item". In this latter case, clicking OK on the dialog will cause the popup to close and immediately reopen~ *Update: This seems to be due to the recent Roku transcoding issues, and likely isn't related to the above error.*

**To Reproduce**
1. Open Jellyfin app
2. Enter server address
3. Click 'Submit'

**Expected behavior**
Jellyfin connects to the specified server and logs in successfully. 

**Logs**
The Jellyfin server does not show any activity in the logs unless/until I am able to access the credentials prompt. If login is successful, I see the following:
```
[2022-07-08 02:08:10.615 +00:00] [INF] [8] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "<user>" has succeeded.
[2022-07-08 02:08:10.616 +00:00] [INF] [8] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "<user>": 5/0
[2022-07-08 02:08:10.618 +00:00] [INF] [8] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user <hash>
[2022-07-08 02:08:10.753 +00:00] [WRN] [8] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://myserver:8096/Users/AuthenticateByName?format=json" to "172.17.0.1" in 0:00:00.5659182 with Status Code 200
```

**Additional context**
I am able to connect to my Jellyfin server without issue from a web browser on my desktop, a web browser on mobile, as well as from the Jellyfin android app and FinAmp. It is only from the two Roku's that I am unable to connect. I theorize this has been happening since the 1.4.12 update but cannot confirm that. I know 1.4.11 was working, then I didn't access the app for a few months. Upon trying to connect I've had the above behavior and noticed that the app had updated to 1.4.12 in the meantime but am unsure if the update is what caused the behavior to start.

I attempted deleting and reinstalling the channel but am experiencing the same behavior.

My Jellyfin server is running on a Synology NAS via the official jellyfin/jellyfin Docker image. I was running server 10.7.7 when this behavior started. Updating to 10.8.1 seems to have had no impact.

**Comment by Drakmyth** [comment]
For anyone finding this in the future, with the awesome help of @neilsb we managed to figure out the issue. My DS920+ had a bonded network connection. For some reason, this was causing the issue. Breaking that bond seems to have resolved all networking issues between the server and the Roku. I don't know why no other devices were adversely impacted by the configuration, but I'm now able to connect with no issue.

**Comment by eclipse1482** [comment]
I have the same issue on my roku trying to connect to my Windows 10 server.

How did you break the bonded network connection?

**Comment by joesixpack** [comment]
Having same issue and there is no bonded network connection on the NAS,

**Comment by Drakmyth** [comment]
> I have the same issue on my roku trying to connect to my Windows 10 server.
> 
> How did you break the bonded network connection?

@mathys-lab From the Synology desktop go to `Control Panel > Network > Network Interface`. You should see the bond in the interface list. Simply click on it and hit `Delete`.
