### ISSUE TITLE
"Continue Watching" posters on home screen are missing progess bar

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#691]
**Describe the bug**
The "continue watching" posters should show a blue bar at the bottom indicating where the user stopped playing the video previously

**To Reproduce**

1. Debug latest master
2. observe continue watching posters on home screen

**Expected behavior**

**Logs**
N/A

**Screenshots**
What they look like on latest master:
![PXL_20220711_021326337 MP](https://user-images.githubusercontent.com/16514652/178176196-d29a58f4-35ec-4dfd-b5c6-2cbd8efbd62f.jpg)

**Additional context**
What they should look like (taken from web client)
![jellyfin-progress-bar](https://user-images.githubusercontent.com/16514652/178176119-edba3b2d-4717-418a-9b02-9e9f848b22be.PNG)

**Comment by Fyb3roptik** [comment]
I will fix this in my home settings PR if thats ok

**Comment by Fyb3roptik** [comment]
Fixed in https://github.com/jellyfin/jellyfin-roku/pull/721
