### ISSUE TITLE
Focused Media Bounding Box Outside of Scope

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#7]
The white box showing the focused media stretches beyond the scene.

![image](https://user-images.githubusercontent.com/6452882/56857162-519f7300-6938-11e9-920e-7aa6eaaeb6d9.png)

**Comment by cewert** [comment]
Confirmed this still exists on the TV show detail page

**Comment by cewert** [comment]
Scratch that, not confirmed. I was testing on a TV set to "full" instead of "native". This problem seems to be fixed when testing on my normal setup.
