### ISSUE TITLE
Images made from image script look weird

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#71]
**Describe the bug**
Images made from image script are off for me

**To Reproduce**
delete current images if necessary
run make_images.sh
look at quality of images

**Expected behavior**
identical to upstream

**Screenshots**
![Screenshot from 2019-10-05 01-04-57](https://user-images.githubusercontent.com/16514652/66250147-323d1b00-e70c-11e9-978d-2a8be94842fe.png)

**Additional context**
I'm on ubuntu 18.04
Noticed during testing while I was adding image script to makefile

**Comment by anthonylavado** [comment]
This is caused by a weird SVG interpreter in Imagemagick. I forget what it’s called, but I know if you build IM with the other one (whatever it is), then this doesn’t happen.

**Comment by bisby** [comment]
Ubuntu has a lot of out of date packages. I also had issues with macOS. archlinux the images generate just fine.
![channel-poster_fhd](https://user-images.githubusercontent.com/619700/66250260-f4d58f00-e705-11e9-8b9d-7d66e4d7447d.png) (just ran this right now, for example).

**Comment by anthonylavado** [comment]
@bisby I’m primarily on macOS and all the packages I tried had the same issue. I couldn’t wrap my head around adding a custom build parameter with brew, so I gave up. I’ll leave it to you fine folks :-)

**Comment by cewert** [comment]
Should we include a set of good images in the repo?

Updating the images manually when necessary sounds a lot easier than hunting down this bug and documenting it for every OS affected.

**Comment by anthonylavado** [comment]
I’ll would say that’s probably easier (as we are getting a few reports about it).

@bisby any thoughts?

**Comment by cewert** [comment]
Right now its one more thing for devs to do before being able to contribute and for users to do before being able to test.

Plus, if we really care about our branding, we shouldn't have users using our app with crappy pictures. Might give the wrong impression of Jellyfin as a whole.

When we get to the point where we start deploying the app to roku we could consider using the image script as part of an automated deploy.

**Comment by bisby** [comment]
There is already a set of good images in the repo.
