### ISSUE TITLE
Add support for Jellyfin.Xtreme plugin

### ISSUE THREAD

**Issue by jmvbrown** [jellyfin-archive/jellyfin-roku-legacy#711]
With the Jellyfin.Xtreme plugin installed, clicking on the Xtreme Live TV library, then clicking a section, then clicking on a channel causes Jellyfin to crash.

**Comment by cewert** [comment]
Changing this to a feature request since we've never supported the Jellyfin.Xtreme plugin

**Comment by 1hitsong** [comment]
3rd party plugins aren't supported in official clients.
