### ISSUE TITLE
Opus audio files cannot be played on Roku Express

### ISSUE THREAD

**Issue by asgardius** [jellyfin-archive/jellyfin-roku-legacy#727]
**Describe the bug**
When attempt to play audio files encoded in Opus, these audio files cannot be played

**To Reproduce**
1. Go to Music Library
2. Select an album with songs encoded in Opus
3. Select Play album option
4. Client will attempt to play every track without success

**Expected behavior**
Every track from this album will be transcoded from Opus to AAC

**Logs**
Here is ffmpeg -i output from one of tested files
[ogg @ 0x560a6911e700] 1 bytes of comment header remain
Input #0, ogg, from '05 - Dawn of the Cosmos.opus':
  Duration: 00:03:13.23, start: 0.000000, bitrate: 99 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ALBUM           : Arena ~ Electronic Music
      GENRE           : Electronic
      TITLE           : Dawn of the Cosmos
      ARTIST          : Art Of Escapism
      album_artist    : Art Of Escapism
      DATE            : 2017
      track           : 5
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 290x290 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)

App log

------ Running dev 'Jellyfin' main ------
Get server details
08-02 13:09:49.743 [beacon.signal] |AppDialogInitiate ---------> TimeBase(2637 ms)
invalid         invalid         invalid
SetServerScreen onKeyEvent      OK              true
SetServerScreen onKeyEvent      OK              false
SetServerScreen onKeyEvent      down            true
SetServerScreen onKeyEvent      down            false
roSGNodeEvent   <Component: roSGNodeEvent>
08-02 13:10:44.679 [beacon.signal] |AppDialogComplete ---------> Duration(54936 ms)
08-02 13:10:44.699 [beacon.signal] |AppDialogInitiate ---------> TimeBase(57593 ms)
08-02 13:11:07.712 [beacon.signal] |AppDialogComplete ---------> Duration(23013 ms)
Unhandled roDeviceInfoEvent:
<Component: roAssociativeArray> =
{
    Mode: "Instant replay"
    Mute: false
}
08-02 13:11:09.480 [beacon.signal] |AppLaunchComplete ---------> Pending Render Pass
08-02 13:11:09.538 [beacon.signal] |AppLaunchComplete ---------> Duration(82431 ms), DialogTime(77949 ms)

BrightScript Micro Debugger.
Enter any BrightScript statement, debug commands, or HELP.

Suspending threads...
Thread selected:  0*   pkg:/source/Main.brs(348)               if node.retryWithTranscoding

Current Function:
340:                  end if
341:              end if
342:          else if isNodeEvent(msg, "state")
343:              node = msg.getRoSGNode()
344:              if node.state = "finished"
345:                  node.control = "stop"
346:  
347:                  ' If node allows retrying using Transcode Url, give that shot
348:*                 if node.retryWithTranscoding
349:                      retryVideo = CreateVideoPlayerGroup(node.Id, invalid, node.audioIndex, true, false)
350:                      m.global.sceneManager.callFunc("popScene")
351:                      if retryVideo <> invalid
352:                          m.global.sceneManager.callFunc("pushScene", retryVideo)
Source Digest(s): 
pkg: dev 1.5.0 35f9076bbe9cae7da1af40000aa98d10 Jellyfin

Type Mismatch. "Invalid" is used in IF-clause. (runtime error &h18) in pkg:/source/Main.brs(348)
Backtrace:
#0  Function main(args As Dynamic) As Void
   file/line: pkg:/source/Main.brs(348)
Local Variables:
args             roAssociativeArray refcnt=2 count:4
global           Interface:ifGlobal
m                roAssociativeArray refcnt=2 count:11
playstatetask    roSGNode:PlaystateTask refcnt=1
scenemanager     roSGNode:SceneManager refcnt=1
group            roSGNode:NowPlaying refcnt=1
input            roInput refcnt=1
video            <uninitialized>
dialog           <uninitialized>
msg              roSGNodeEvent refcnt=1
reportingnode    <uninitialized>
itemnode         <uninitialized>
selecteditem     roSGNode:MusicArtistData refcnt=1
video_id         <uninitialized>
node             roSGNode:NowPlaying refcnt=1
ptr              roArray refcnt=1 count:2
series           <uninitialized>
albums           roSGNode:MusicArtistDetails refcnt=1
selectedindex    <uninitialized>
screencontent    roSGNode:MusicAlbumDetails refcnt=1
query            <uninitialized>
options          <uninitialized>
results          <uninitialized>
btn              <uninitialized>
audio_stream_idx <uninitialized>
mediasourceid    <uninitialized>
movie            <uninitialized>
button           <uninitialized>
panel            <uninitialized>
trackselected    <uninitialized>
retryvideo       <uninitialized>
event            roAssociativeArray refcnt=1 count:2
currenttime      <uninitialized>
info             <uninitialized>
rooibos__init    <uninitialized>
Threads:
ID    Location                                Source Code
 0*   pkg:/source/Main.brs(348)               if node.retryWithTranscoding
  *selected

**Screenshots**

Here is a sample using a Creative Commons licensed album

https://user-images.githubusercontent.com/43385234/182276151-19d10a45-7a96-4c82-a447-e5afdf3a31d9.mp4

**Additional context**

Tested devices: Roku Express 3930mx, and Roku Express+ 3710rw
Roku software version: 11.0.0.4193 on both devices
Client version: 1.5.0
Server version: 10.8.1 on Yunohost 11

**Comment by drolex2** [comment]
I experience the same problem on a TCL Roku TV. It is able to direct stream a movie that is HEVC+Opus, so I expect it should be able to direct stream Opus music. I would prefer that it does not transcode.

**Comment by 1hitsong** [comment]
@asgardius I downloaded a sample Opus file. Using Roku client version 1.6.2, which will be released within the next week or so, it played without issue. 

Once 1.6.2 is released, please try it again and if it doesn't work for you, please open a ticket and I'll investigate.
