### ISSUE TITLE
Roku Express 4k+ Stuttering

### ISSUE THREAD

**Issue by Sector14** [jellyfin-archive/jellyfin-roku-legacy#733]
**Describe the bug**
Playback of BluRay is choppy on Roku Express 4k but fine on a Surface Pro via web client (both on same wifi network).

**To Reproduce**
Play a BlurRay, for example, Enders Game (1080p, original disk, not re-encoded) on the Roku. Server reports direct play is in use. However at 11:20 into the movie when the camera is flying across the mountain range, there's a lot of stuttering. The stutter exists all the time (I see it in horizontal pans on Avatar as well), but is particularly apparent at this time stamp.

**Expected behavior**
Smooth playback. 

**Additional context**
I'm assuming this is to do with bandwidth (I don't see any buffering reports), although the Roku is connected via 5GHz and should be able to cope with 40-60mbps? Unless the device itself is choking on high bitrates? The surface (also on 5GHz wifi) doesn't directly support the audio codec, so will play back via a transcode however has no issue with the high bitrate.

Is there any way to force the Roku jellyfin client/server to transcode in order to test at a lower bitrate/resolution/different codecs to try to narrow down what the issue may be. 

At first I thought this was due to playback at 60Hz of a 24Hz movie, however I've since changed the Roku to switch refresh rate so it now successfully plays back at 24Hz, but the juddering remains. 

I don't yet have the ethernet adapter to properly eliminate wifi as the problem, but I'd like to know if anyone else has played back this BluRay, as a direct rip with no encoding so original codecs/bitrates etc

Edit: Monitoring wifi router stats, I'm not convinced this is a bandwidth issue. I'm starting to think it's just too high a bitrate for the Roku to deal with. If that's the case, are there any options to force a transcode to lower or the possibility of a future version to include streaming quality settings like the web client?

Edit2: https://developer.roku.com/en-gb/docs/specs/media/streaming-specifications.md this suggests h264 is limited to 10mbps decoding (seems rather low), could that explain the stutters if direct play is sending closer to 40mbit?

**Comment by Sector14** [comment]
I've installed Emby server and the Emby roku app to run a quick test. With Ender's game streaming at the default it uses 40mbit and also suffers from the stuttering. However, changing the client setting to 1080p @ 10mbps which the above link suggests is the max for the roku, and the stuttering is gone.

So it looks like the solution for Jellyfin will require the client to allow you to configure the resolution/bitrate. Also it might be useful if it provided an option to force a transcode to h265 if possible which would allow up to 40mbps.

I guess I won't be replacing my existing HTPC with a roku anytime soon for original bluray viewing. Still, if the client can be updated to allow quality selection, 10mbps would do the job for now.

**Comment by jimdogx** [comment]
This is an enhancement (hopefully not too far out in the future) requested here: #541 

Closing this so it can be tracked in one place 👍
