### ISSUE TITLE
App crashes upon opening on a roku streaming stick+

### ISSUE THREAD

**Issue by Antibodyarmy** [jellyfin-archive/jellyfin-roku-legacy#742]
I cannot get the jellyfin app to open on my roku streaming stick+ I've reset the roku stick, deleted the app switched roku accounts and it still wont open completely. When opening the jellyfin logo will pop up and then the  app will close.  roku 3810r streaming stick+ . This is the first time I'm using the jellyfin app on my roku stick.

**Comment by Antibodyarmy** [comment]
It suddenly started working after opening the app a bunch of times.

**Comment by neilsb** [comment]
Just going to close this for now, since we've not had any other reports of issues, and this just started working.  If you experience it again, just let us know and we can try and do some investigating.
