### ISSUE TITLE
Invalid time code and video length on most videos

### ISSUE THREAD

**Issue by triclops200** [jellyfin-archive/jellyfin-roku-legacy#743]
**Describe the bug**
When I try to watch almost any video, I get 0:00 out of 0:00 as my timecode. It plays back normally and when I start an episode to resume at a specific time, it does correctly start there, but I'm unable to skip forward or back, except to the beginning of the file. It's really frustrating if an episode craps out 20 minutes in and it offers to resume at 10 minutes.

**To Reproduce**

1. Play almost any video
2. Notice that the end time is apparently 0:00
3. Note that attempting to seek does nothing.

**Expected behavior**

The time code advancing and an end time equal to the length of the file

**Logs**

I'm not sure how to get these

**Screenshots**

![20220819_153809](https://user-images.githubusercontent.com/343522/185694728-0b15fc82-8aaa-4b64-b024-e20362541969.jpg) image of the 0:00 out of 0:00

**Additional context**

**Comment by brightscripters** [comment]
Trying with the demo server on jellyfin.org, using the build available on the Channel Store.
Not seeing this issue on Streambar, nor on the Streaming Stick.
Guidance for reproducing this issue would be great.

**Comment by alanazar** [comment]
I've faced this exact issue before and it came down to the client device not being able to play the filetype or codec.
Check the filetype and codec used, then check your transcoding settings.
Ideally it should be in a format that your client device supports to reduce workload on the server, but if it doesn't then the server should transcode it on the fly.
Hope that helps

If confirmed, I'd mark this as resolved as it's not a bug but a client device limitation.
