### ISSUE TITLE
TrueHD audio not playing and alternate audio track not selectable

### ISSUE THREAD

**Issue by tydog98** [jellyfin-archive/jellyfin-roku-legacy#744]
**Describe the bug**
When trying to play an episode with TrueHD audio the video will play but there will be no sound. Also when trying to change the audio track while this happens it simply says it's playing the "Default" track, despite there being many other tracks.

**Expected behavior**
Sound should play and audio track should be able to be changed

**Comment by 1hitsong** [comment]
@tydog98 Is this still an issue using the latest release?

**Comment by tydog98** [comment]
I unfortunately no longer use the Roku client so I cannot confirm, sorry.

**Comment by 1hitsong** [comment]
> I unfortunately no longer use the Roku client so I cannot confirm, sorry.

No worries. Have a good one.
