### ISSUE TITLE
Listenbrainz and Webhook plugins don't work with Roku client, however web interface works fine.

### ISSUE THREAD

**Issue by gbcox** [jellyfin-archive/jellyfin-roku-legacy#762]
**Describe the bug**
When using Roku app to play music, music plays but related Jellyfin plugins do not work.  Nothing is being reported to Webhook and nothing is being reported to the Listenbrainz scrobbler.  If I play music using the web interface, both plugins work fine.  When using Roku it is as if nothing is happening.

**Comment by neilsb** [comment]
Currently the Jellyfin Roku App is only reporting playback to the server for Video items.   The Music playback needs to report playback to the server in a similar way to `ReportPlayback()` in `JFVideo.brs`.

**Comment by 1hitsong** [comment]
Added to roadmap discussion post.
