### ISSUE TITLE
Search Issues

### ISSUE THREAD

**Issue by neilsb** [jellyfin-archive/jellyfin-roku-legacy#779]
A few (minor) issue with the Search functionality just merged in

## Not working in Folder View
If Folder View is enabled (Dashboard -> Libraries -> Display -> Display a folder view to show plain media folders) the search does not work in the folder view.  The content reloads and the title changes to show it is filtered by the entered text - but the items do not filter to the entered term.

## TV Series Name incorrectly displayed
In the search screen (accessed from options menu) the TV Series name can be incorrectly left behind when a search is changed.

![image](https://user-images.githubusercontent.com/5013482/188395443-f8a8d37e-f503-4c03-8903-dff8773c1052.png)

To reproduce:

- From Search Screen, perform a search that matches an Episode title only, so that the top row of the search results is "Episodes"
- Clear the search using the bin button (or press backspace to clear the search)
- Enter text that matches a non-TV episode (e.g. Movie, Series, etc)
- See the Episode Series remain visible, behind the top row

## Navigation for Single Items in a row
In the search screen (accessed from options menu) trying to navigate from a results row with only a single item back to the keypad may not work.

To reproduce:

- From Search Screen, perform a search.  In order to see this bug, the search results will need to return multiple types, at least one of which must have more than 1 item, and at least one of which must have a single item.
- If you press right to enter the search results and navigate to a row with multiple matching results and scroll right to at least the second item.
- Then use the up/down buttons to navigate to the row with only a single item
- From here, you are unable to navigate back to the search panel on the left of the screen.  Only options are to hit _back_ (to return to home screen) or use up/down to navigate to a row with multiple results, at which point you can navigate left to get to the search panel.
 
## Cancelling Episode Resume causes application crash
From the Search Screen, when selecting an Episode from the search results and getting the "Resume" prompt - if you press back to abort playback and return to search results, the app crashes

- Ensure you have at least one TV Episode in progress and appears on the "Continue Watching" home screen
- Enter the Search Screen from the Option Menu
- Search for the in progress episode and select it form the results
- When the resume dialog appears, press back
- The application crashes

**Comment by neilsb** [comment]
Found another issue.  Added "Cancelling Episode Resume causes application crash" section above.

**Comment by candry7731** [comment]
Cancelling Episode Resume causes application crash - It seems Like there is an invalid group being pushed onto the stack when the "Resume Episode Dialog" appears. Not sure where its coming from.... Any clues would be most helpful

![image](https://user-images.githubusercontent.com/83685828/190295395-66158838-85d7-4cdb-b3db-8b3ad9de84eb.png)

**Comment by candry7731** [comment]
ok, I need help on the other issues.... I am calling currFocusColumn however when you have a row with one item and you move to it, the item takes the column index of the item you were currently on.... Which seems like a roku bug to me. I would assume that when you move to the single item row that index would be 0....

**Comment by candry7731** [comment]
@neilsb, Have you had a chance to look into this? Are we all good?

**Comment by neilsb** [comment]
@candry7731 Sorry for the delay.  I've had a look, and I don't think that you need to look at `currFocusColumn` at all.  If the user is not at the very left of the row, the row will capture and handle the `left` key event and it won't bubble up to the `SearchResult`.

You should just be able to remove that whole section of the if on line ~51 of `SearchResult.brs` and make it:

`    if key = "left" and m.searchSelect.isinFocusChain()`

**Comment by 1hitsong** [comment]
@neilsb @candry7731 Are we good to close this issue since #852 is now merged?
