### ISSUE TITLE
Make the rows on Library view screen not wrap to a second row

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#78]
**Is your feature request related to a problem? Please describe.**
If you have 6 or more libraries the 6th library wraps down below the first taking up valuable screen real estate 

**Describe the solution you'd like**
Have the rowList scroll right and left past the edge of the screen with the "1 of 6" above it on the right

**Describe alternatives you've considered**
I don't think there are alternatives?

**Additional context**
Doing this would be a good first step towards having other rows below the library list. "continue watching" "next up" etc. and give us a "template" of code to build those new rows with

**Comment by bisby** [comment]
This is how the search page is set up... And the library is the only thing on the home because i modeled it after my own setup, in which there is nothing on my home screen but the libraries

It's possible we could also get user preferences from the API. Unless we decide we want to have it potentially different.

**Comment by cewert** [comment]
Nice so we could use the code from the search page? I only used it once to test it and I only had one row with one result. I'll have to check it out

Yea I think we'd have to get user preferences to know which order to place the rows in for Latest TV, Latest Movies etc.

I totally get why you developed the app to match your local and you did a great job. I have 3 Rokus so that's why I'm trying to work on this app. I use Continue watching, Next up, Latest TV, Latest Movies 98% of the time I use the emby app so I guess we're opposites haha.  My goal is to get this app to a place where I can ditch emby and I thought this would be a good first step unless you think there'd be a better way to implement it? I was just trying to copy the layout of emby. I really enjoy the look and layout of the emby roku app

**Comment by bisby** [comment]
It at least has some sample code that might not be worth re-using, but has the "1 of 6" concept in it.

And we may want to track separate user preferences. @anthonylavado do we have preference for re-using webapp settings in the roku app, or are we assuming that a drastically different UI paradigm warrants separate settings.

**Comment by anthonylavado** [comment]
@bisby Different interface, different preferences. It should have its own setting separate from the web interface.

**Comment by cewert** [comment]
@bisby Awesome I'll check it out.

Are you guys wanting to track **all** of the settings separately? There's a lot. To make sure we're on the same page here's all the settings I'm referring to:

![Screenshot_2019-10-08 Jellyfin](https://user-images.githubusercontent.com/16514652/66368541-a1ae4700-e966-11e9-8baa-7684eb3d3f5b.png)

Can we at least agree that we should use the web clients settings as default? Otherwise setting up the roku app would be a chore having to fill out that list of config options on first launch. I mean we have to make some assumptions right?

**Comment by cewert** [comment]
The roku client already uses "Library Order", "Library Folders", and "Collections" from the web client user settings. Perhaps these settings are baked into the API output?

**Comment by dkanada** [comment]
Lots of the user settings on web are only stored locally on the device if I recall, but I'm not sure which ones. Also the UX on that page is a nightmare and I've been meaning to improve it for ages.

**Comment by anthonylavado** [comment]
Well, I’m not entirely sure what the interface looks like, or what a standard/reference Roku interface looks like.

What do other popular apps do in this area?

**Comment by joshuaboniface** [comment]
I think if we're already grabbing half the config from the API, grabbing more is a good idea to avoid initial setup work.
