### ISSUE TITLE
Music Videos

### ISSUE THREAD

**Issue by SmoochySix4** [jellyfin-archive/jellyfin-roku-legacy#787]
Setting up a music video share on Jellyfin server works. The web interface shows the videos. The Roku app, however, does not show any entries in the Music Video section, and gives an error of not being supported.

**Comment by candry7731** [comment]
What file format is the music video? Do you have all music video in a separate folder?

We should be able to support this pretty easily.... how would you want to see the videos? in a grid layout like movies or in a list layout like tv show episodes? 

![image](https://user-images.githubusercontent.com/83685828/190241568-0173e3c9-4e18-433e-9e68-08b3e4e229b8.png)

**Comment by SmoochySix4** [comment]
All files are in the same format. Here is the ffprobe output of one of those files. I, personally, prefer list format. But, I am sure the grid layout would be useful for some.

```Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\music\Hozier - Take Me To Church - 1080P.mp4':                                Metadata:                                                                                                                 major_brand     : isom                                                                                                  minor_version   : 512                                                                                                   compatible_brands: isomiso2avc1mp41                                                                                     title           : Take Me To Church                                                                                     artist          : Hozier                                                                                                date            : 20140325                                                                                              encoder         : Lavf59.30.100                                                                                       Duration: 00:04:16.14, start: 0.000000, bitrate: 2010 kb/s                                                              Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 1875 kb/s, 23.98 fps, 23.98 tbr, 90k tbn (default)                                                                  Metadata:                                                                                                                 handler_name    : VideoHandler                                                                                          vendor_id       : [0][0][0][0]                                                                                      Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)                    Metadata:                                                                                                                 handler_name    : SoundHandler                                                                                          vendor_id       : [0][0][0][0]```

**Comment by candry7731** [comment]
Can you send me a screen shot of what it looks like on your web interface?
