### ISSUE TITLE
Move search box

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#79]
**Is your feature request related to a problem? Please describe.**
Once we have multiple rows on the home screen "My libraries", "continue watching", "next up" etc. the search box would prevent us from scrolling the screen down to view more rows.

Same logic as #78 - pave the way for future rows on the home screen

**Describe the solution you'd like**
There are only two solutions I think

1. Move the search link into a row on the main screen. The best spots IMO would be:

-  At the top above the media libraries row (in a small font to not take up much space) 

- At the bottom (similar to emby) and could be as big and fancy looking as we want.

1. Move the search function into the Options menu.

I think I lean towards the option menu but I don't think of search as being an "option" so I worry it would be poor UX. Second choice being top row above media libraries. When using emby it's super annoying having to hit the down arrow like 6 or 7 times to see the search link and when I search for something it's almost always a movie I had in mind before I opened the app.

What do you guys think?

**Comment by dkanada** [comment]
In situations like these I check what the platform standard is and follow that method. My personal opinion is that a search button that leads to a separate page sounds best, similar to the web client.

**Comment by bisby** [comment]
I also checked with my wife, and checked the Netflix app, which has search in the left sidebar.
