### ISSUE TITLE
Provide the ability to select the audio language for an entire series instead of episode by episode

### ISSUE THREAD

**Issue by Kunfury-blep** [jellyfin-archive/jellyfin-roku-legacy#806]
**Is your feature request related to a problem? Please describe.**
Currently when you are playing a series that has multiple audio tracks (sub/dub), there is no way to change the default audio track that is used and you have to change it for each episode. This is made even worse by the fact that there doesn't seem to be a way to go directly to the episode from the box on the home screen, instead requiring you to load the video, play a minute or so of it, exit out, select the video again so that you can finally see the options, then hit "Go To Episode" and from there you can finally change the audio track.

**Describe the solution you'd like**
The perfect solution would be to allow users to simply set a default audio track on the series as a whole that would be applied to every episode in the series.

**Describe alternatives you've considered**
An alternative would be to allow the '*' button on the Roku remote to bring up the option menu to allow the user to go immediately to episode details instead of requiring them to load into the episode and back out first.

**Comment by jpw4dev** [comment]
Another option, in addition to the solution/alternative, is to at least follow the user profile settings for User > Playback > "Preferred audio language" and User > Playback > "Play default audio track regardless of language"

If a preferred audio language is selected and "Play default audio track regardless of language" is unchecked, then all playback for the user should attempt to use the preferred audio language by default.
