### ISSUE TITLE
Screensaver follows short pattern

### ISSUE THREAD

**Issue by pforpond** [jellyfin-archive/jellyfin-roku-legacy#831]
When listening to music the screensaver will kick in after a while. It is the album art of the playing track bouncing around the screen similar to the DVD logo. Unfortunately unlike the DVD logo it follows a very obvious pattern and bounces off the bottom left corner of the screen ever minute or so. Maybe make it more random? I feel like corner hits should be a rare treat not an often occurrence.

**Comment by 1hitsong** [comment]
We try to maximize our user's happiness.

https://media.giphy.com/media/VkpMw5kkpOQHVL4LQB/giphy.gif
