### ISSUE TITLE
Can't work on a Hisense 65U6GR TV!

### ISSUE THREAD

**Issue by bhtools** [jellyfin-archive/jellyfin-roku-legacy#836]
**Describe the bug**
My Tv is Hisense 65U6GR which is a roku TV
I have install Jellyfin server in my nas,  and it works well. i can use it from web and iphone.
I install jellyfin app from roku store, but i can not use it.
The app doesn't work, it crashes as soon as he enters the screen。
I don't know why?
i try to install emby,it works well.

**Comment by jimdogx** [comment]
Could you launch the Roku app again and follow these instructions to copy / paste a log file of the crash here?

https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#bugcrash-reports

**Comment by bhtools** [comment]
> Could you launch the Roku app again and follow these instructions to copy / paste a log file of the crash here?
> 
> https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#bugcrash-reports

Thanks ，Bro。
I update my TV's system rom.  remove jellyfin app and reinstall jellyfin app.

now ,it works.  I don't know why,  maybe because of the TV system.

But now ,there is another question.

I don't have any Chinese characters on my TV, so now the introduction to the movie is all square symbols. I've set up the new Chinese font on my jellyfin server, and it looks great on the web and mobile. I would like to know if I want to display Chinese movie introductions, does my TV have to have Chinese character bank? Because when I was playing the movie, the Chinese subtitles were great, because of course I used the spare character library.


https://ibb.co/VNH3MCT
https://ibb.co/MhRz75W
https://ibb.co/FhgZG3W

**Comment by jimdogx** [comment]
This is an ongoing issue.  See:

https://github.com/jellyfin/jellyfin-roku/issues/285
and
https://github.com/jellyfin/jellyfin-roku/issues/514

I'm going to close this issue for now since the app is now launching on your TV.  I'd recommend keeping an eye on those two issues above.
