### ISSUE TITLE
v1.6.0 fails to install on Roku Ultra model 4670X

### ISSUE THREAD

**Issue by roostercactus** [jellyfin-archive/jellyfin-roku-legacy#839]
**Describe the bug**
v1.6.0 fails to install on Roku Ultra model 4670X

**To Reproduce**
1. download v1.6.0 from github.com (or git pull from local git repo)
2. make dev
3. make install
4. See error below from telnet session

`11-05 21:35:31.272 [beacon.signal] |AppLaunchInitiate ---------> TimeBase(0 ms)
11-05 21:35:31.272 [beacon.signal] |AppCompileInitiate --------> TimeBase(0 ms)
Note: Translation file loaded: pkg:/locale/en_US/translations.ts: 182 items.
11-05 21:35:31.277 [scrpt.cmpl] Compiling 'Jellyfin', id 'dev'
11-05 21:35:31.289 [scrpt.load.mkup] Loading markup dev 'Jellyfin'
11-05 21:35:31.297 [scrpt.unload.mkup] Unloading markup dev 'Jellyfin'
11-05 21:35:31.338 [scrpt.parse.mkup.time] Parsed markup dev 'Jellyfin' in 48 milliseconds

------ Compiling dev 'Jellyfin' ------

=================================================================
Found 1 compile error
--- Error loading file. (compile error &hb9) in pkg:/source/roku_modules/api/api.brs
*** ERROR compiling LoadItemsTask2:

=================================================================
An error occurred while attempting to compile the application's components:
-------> Compilation Failed.
LoadItemsTask2`

**Expected behavior**

Expected it to install normally

**Logs**

See telnet log above

**Screenshots**

N/A

**Additional context**

I tried on release source code zip v1.6.0 from github.com and also from local git repo (git pull; make dev; make install) from both the stable and unstable branches.  

v1.5.0 installs okay.

Roku Ultra 4670X
software 11.5.0 build 4235-46

**Comment by jimdogx** [comment]
I believe you are missing the "npm install" command:

https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#clone-the-github-repo

**Comment by roostercactus** [comment]
Hi, yes...sorry.  I should have reviewed the page again with the new version.  It works fine now (after installing node).
