### ISSUE TITLE
Slow netowrking can lock up Roku

### ISSUE THREAD

**Issue by minecraftchest1** [jellyfin-archive/jellyfin-roku-legacy#842]
**Describe the bug**

When attempting to exit the app when one or more requests is waiting for a response, such as because of a networking issue, the Roku locks up, requiring a reboot to make the device function again. This is just a guess based off behavior with this and other apps.

**To Reproduce**

1. Connect Roku to a network with slow and/or unreliable networking. Ensure other apps such as Prime Video or Vudo are slow to load.
2. Open your home server in the Jellyfin Roku app, and browse a collection with a large number of items. Open and Close one or more items in quick succession. The items should be slow to load if they open at all. 
3. Attempt to open the home page. The Roku should become unresponsive.

**Expected behavior**

The Roku should remain at least partially responsive, allowing the app to close.

**Logs**

Was unable to get logs at this time, the family wanted to watch something and not wait around.

**Screenshots**

Jellyfin-Roku version: 1.5.0

**Additional context**

**Comment by jimdogx** [comment]
I'm confused.  Are you saying the Roku itself is slow?  Or are you saying that the Jellyfin app is slow while other apps are responsive?  From your description, it sounds like *all* apps are slow (not just Jellyfin).  If that is the case, we don't have control over how responsive the Roku itself is.

**Comment by minecraftchest1** [comment]
> I'm confused. Are you saying the Roku itself is slow? Or are you saying that the Jellyfin app is slow while other apps are responsive? From your description, it sounds like _all_ apps are slow (not just Jellyfin). If that is the case, we don't have control over how responsive the Roku itself is.

Yes. The entire Roku itself is being unresponsive. Without looking at the code, it feels like the request is being made synchronously, or being awaited in the primary thread.

**Comment by jimdogx** [comment]
If the entire Roku is being unresponsive (including Prime Video, Vudo, etc), then that is a Roku issue (not Jellyfin) and you might have better luck creating a thread here:

https://community.roku.com/t5/Solving-playback-issues/bd-p/audio-video
