### ISSUE TITLE
Music: cannot play *.ape files

### ISSUE THREAD

**Issue by kamanwu** [jellyfin-archive/jellyfin-roku-legacy#845]
Use the latest version 1.6.  Cannot play ape files.  Is this a easy fix?  Thanks.

Audio
Title: APE - Stereo
Codec: APE
Codec tag: APE 
Layout: stereo
Channels: 2 ch
Bitrate: 877 kbps
Sample rate: 44100 Hz
Bit depth: 16 bit
Default: No
Forced: No
External: No

**Comment by jimdogx** [comment]
I don't believe Roku supports the APE codec:

https://developer.roku.com/docs/specs/media/streaming-specifications.md

**Comment by kamanwu** [comment]
I see.   Since the client does NOT support the codec, the server should do the transcoding, right?
For now, when I hit the *.ape file, it did nothing.

**Comment by kamanwu** [comment]
Here is the info when I play the ape file on my iPhone:

Transcoding
The media is being converted into a format that is compatible with the device that is playing the media.


384 Kbps TS AAC


Reason for transcoding:
The container is not supported
The video codec is not supported
The audio codec is not supported

**Comment by neilsb** [comment]
Yes, the same should happen with Roku too.

**Comment by jimdogx** [comment]
Wouldn't this be a server issue (server not transcoding)?

Or are we mistaking telling the server we support APE?

**Comment by neilsb** [comment]
If it works for android, I suspect it's more likely a problem with the Device Profile we send the server.

**Comment by kamanwu** [comment]
I use iPhone app: Jellyfin Mobile.

**Comment by jimdogx** [comment]
Investigating and roping @1hitsong in to all of this as well 😄

**Comment by 1hitsong** [comment]
I've never heard of such a file. I'll see if I can find/create a sample file and look into it.

**Comment by kamanwu** [comment]
Here is the example ape file:
https://example-files.online-convert.com/audio/ape/example.ape

**Comment by 1hitsong** [comment]
Thanks @kamanwu . I've figured it out and have the sample file playing through JF on my Roku. I'll need to make further adjustments to make it more generalized, but it's working 👍
