### ISSUE TITLE
Selecting a collection from the main movie list page causes crash

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#85]
**To Reproduce**
install TMDb Box Sets plugin? Select a movie library. select a collection

**Expected behavior**
Either the collection should be filtered out and the individual movies displayed or selecting the collection takes you to the collection detail page with the list of movies inside.

**Logs**
```brightscript
 else if data.type = "BoxSet"
    tmp = CreateObject("roSGNode", "CollectionData")
    tmp.image = PosterImage(data.id)
    tmp.json = item
    return tmp
```

`Use of uninitialized variable. (runtime error &he9) in pkg:/source/api/Items.brs (Line: tmp.json = item)`

**Additional context**
This bug may only exist because I'm using "TMDb Box Sets" plugin. I assume without the plugin the collection wouldn't show up at all in the movie list.

**Comment by jcdick1** [comment]
It may be related to this whenever the Collections library is accessed:

```
=================================================================
Warning occurred while setting a field of an RoSGNode
-- Tried to set nonexistent field "overview" of a "CollectionData" node
   at line 6 of file pkg:/components/data/collection.brs
=================================================================
```

This comes up in the client logs for each Collection entry in the library.

**Comment by cewert** [comment]
At some point this bug was fixed. The individual movies are now shown in the main movie list.
