### ISSUE TITLE
Streaming information popup could be incorrect

### ISSUE THREAD

**Issue by jimdogx** [jellyfin-archive/jellyfin-roku-legacy#858]
**Description**
Streaming information popup assumes the video is always the first mediaSource / mediaStream:

VideoPlayer.brs
```
stream = m.playbackInfo.mediaSources[0].MediaStreams[0]
```

**Expected behavior**
Streaming information should make sure it's showing information for the currently playing stream.

**Screenshots**
See conversation / screenshot here: https://github.com/jellyfin/jellyfin-roku/pull/856

**Comment by jimdogx** [comment]
@1hitsong this PR is to fix the "transcoding / streaming information" popup (that you actually noticed 😄 ).  #856 only fixes the information on the video details page (not the popup).  I created this PR so we wouldn't forget to fix it later on.

**Comment by 1hitsong** [comment]
I believe this was fixed when we transitioned to the new global video player. Closing.
