### ISSUE TITLE
Missing File From Source Code

### ISSUE THREAD

**Issue by medeus661974** [jellyfin-archive/jellyfin-roku-legacy#876]
Why  do you put incomplete  code ?
Where  is this  file 
 <script type="text/brightscript" uri="pkg:/source/roku_modules/api/api.brs" />
Stupid retarded
![bandicam 2022-12-10 02-05-01-286](https://user-images.githubusercontent.com/85520718/206814369-d10cecfb-eefd-40a1-8c8d-e686a78d8e0a.jpg)

**Comment by neilsb** [comment]
That file is auto generated from via ropm. 

If you do a "npm install" in the source directory after checkout it should install all the required modules and put that missing file in the correct location.

**Comment by 1hitsong** [comment]
Next time read the dev guide first.

![image](https://user-images.githubusercontent.com/3330318/206823501-9044aa1d-0efb-49f1-b893-cc464e2d76ad.png)
