### ISSUE TITLE
Make Sort By Release Date Default for Movie Collections

### ISSUE THREAD

**Issue by lakerssuperman** [jellyfin-archive/jellyfin-roku-legacy#895]
Issue:  Currently, movie collections default to sort by name in the Roku app with the ability to manually change the sort order of a collection to other views including sort by release date.

Enhancement:  Make 'release date' the default sort order for collections.

Rationale: Sort by Release Date is the default behavior when viewing collections in a web browser and feels more logical for a series of movies as one would expect to start with the first in the series and iterate forward (see screenshot).

![Bond Collection Web View](https://user-images.githubusercontent.com/18699905/207746958-73e2d1a8-2bbc-49be-bd25-3bd9b134c666.png)

**Comment by candry7731** [comment]
It doesn't look there is a sort order now in roku, correct?

**Comment by lakerssuperman** [comment]
> It doesn't look there is a sort order now in roku, correct?

The default sort order on Roku is by name A-Z ordering. So in my James Bond Collection example in default name sort order the first movie is Casino Royale.  There are manually selectable sort options in the Roku app including release date, which I've manually switched all of my collections to.

**Comment by cewert** [comment]
I believe this was fixed by #1442. Would you mind testing this again on unstable when you get a chance?

**Comment by lakerssuperman** [comment]
Sorry, I've been running unstable and the sort order is correct now for collections. Default sort order is now by release date. Awesome work.  Thank you!
