### ISSUE TITLE
Grid layout reduced to 1.5 rows

### ISSUE THREAD

**Issue by dennisdupont** [jellyfin-archive/jellyfin-roku-legacy#899]
**Software Versions**
Jellyfin Server Version: 10.7.5
Roku Client Version: 1.6 build 2

**Describe the bug**
The view of videos after selecting a media folder used to show a grid with rows and columns filling the screen.  In this version there is only a row and a half and a large mostly blank space above (it has just the title and duration).

**How To Reproduce**

1. Go to a media folder
2. Scroll 

**Expected behavior**
Old layout 

![20221215_184952 (002)](https://user-images.githubusercontent.com/8162159/207997291-b800010b-2a74-4456-9c95-c51fe51bf7fd.jpg)

**Connection Information**
Is server local or remote?  Local

Is server connection http or https?  http

**Comment by Security-Chief-Odo** [comment]
Also experiencing this with the recent update. It's atrocious. Only showing one row and part of another one, instead of the full screen listing as previously. 

Software Versions
Version: 10.8.7
Operating System: Linux
Jellyfin Roku App: v1.6 build 2

Serving Locally over https

**Comment by 1hitsong** [comment]
I updated the view for Movie libraries so it looks like this if all meta data is filled in: https://social.linux.pizza/@tgpo/109535689733075646

I'm working on a 2nd view that will have the old grid view. It'll likely be in the next release then users can choose between them.

**Comment by dennisdupont** [comment]
I am not familiar with the release process but I assume closing this doesn't mean the fix is available via Roku.  Will this just roll out silently someday?  Any ETA on that?

**Comment by dennisdupont** [comment]
BTW - I should have also said a big THANK YOU for getting this done quickly and for all the work you do maintaining a fantastic product.

**Comment by 1hitsong** [comment]
> I am not familiar with the release process but I assume closing this doesn't mean the fix is available via Roku. 

Correct. It means the fix has been merged into the upcoming release branch.

> Will this just roll out silently someday? Any ETA on that?

No ETA. Roku won't reopen submissions until next week, but we're going to release these bug fixes ASAP.
