### ISSUE TITLE
Posters don't refresh when an image is changed on the server

### ISSUE THREAD

**Issue by jimdogx** [jellyfin-archive/jellyfin-roku-legacy#900]
**Software Versions**
Jellyfin Server Version: Any
Roku Client Version: 1.6.2

**Describe the bug**
PR #605  removed the Tag parameter as it was thought it was causing a flickering issue.  Turns out the Tag parameter is needed in order for caching to work correctly.  To fix we should revert changes from PR #605 

**How To Reproduce**
Update a movie poster on the server.  Notice the Roku client does not update.

**Expected behavior**
Movie poster should update on the client.

**Additional context**
[Reddit report](https://www.reddit.com/r/jellyfin/comments/zmx5dy/regarding_jellyfin_on_roku/)

**Comment by 1hitsong** [comment]
I just tested this and it now works as expected. It appears our rollback of the tag param fixed this.
