### ISSUE TITLE
Client crashes when viewing 'Genres' in a TV library

### ISSUE THREAD

**Issue by antiops** [jellyfin-archive/jellyfin-roku-legacy#902]
**Software Versions**
Jellyfin Server Version: 10.8.4
Roku Client Version: 1.6 build 2

**Describe the bug**
> This is a bug happening to a friend, I don't know much about Roku devices so I can provide better info if needed

When trying to view the 'Genres' area in a library the client crashes after a couple seconds.

**How To Reproduce**

1. Go to TV section
2. Click `*` (Asterisk button) on the remote
3. Go to 'View' -> 'Genres'
4. Bug occurs (Crash)

**Expected behavior**
Expected behaviour is for the client to display a page with a list of shows sorted by genre

**Logs**

**Screenshots**
https://user-images.githubusercontent.com/22041463/208196414-12e2ca7a-540e-4cee-859d-259487c7c96e.mp4

**Connection Information**
Connection is remote using http (`remote_ip:port`)

**Additional context**
The genres section loads as expected, and quickly, on the web and mobile clients. The specific library that was tried in the video was a TV library with 3500 shows.

My friend had to reinstall the app afterwards because it just kept crashing.

**Comment by candry7731** [comment]
Do you have any genre metadata on your tv shows? 

You can go to the metadata manager and click a folder then item to see if it has any data. 

![image](https://user-images.githubusercontent.com/83685828/208200280-95210c5f-d1dc-4d0a-befb-4d6722e8fe7a.png)

**Comment by Security-Chief-Odo** [comment]
Having this same issue on Jellyfin. Where/how do you access metadata manager from the admin web dashboard as in your screenshot?
