### ISSUE TITLE
1.6.2 Stuttering on SOME HEVC but not ALL HEVC

### ISSUE THREAD

**Issue by JPKribs** [jellyfin-archive/jellyfin-roku-legacy#903]
**Software Versions**
Jellyfin Server Version: 10.8.8
Roku Client Version: 1.6.2
Roku Version: Roku Streaming Stick 4K (3820R)

**Describe the bug**
Starting in 1.6.2, some HEVC files will try to play without transcoding now but the file will stutter. Stutter occurs every second. Audio plays without issue. This only impacts some HEVC files. Please see below:

Example Stutter:

Video
Type: mp4
Title: 1080p HEVC SDR
Codec: HEVC
Codec tag: hev1
Profile: Main 10
Level: 120
Resolution: 1920x1036
Aspect ratio: 1.85:1
Interlaced: No
Framerate: 23.976215
Bitrate: 2000 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Eng - AAC - 5.1 - Default
Language: eng
Codec: AAC
Codec tag: mp4a
Profile: LC
Layout: 5.1
Channels: 6 ch
Bitrate: 224 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Example No Stutter:

Video
Type: mp4
Title: 1080p HEVC SDR
Codec: HEVC
Codec tag: hev1
Profile: Main 10
Level: 120
Resolution: 1920x818
Aspect ratio: 2.35:1
Interlaced: No
Framerate: 23.976025
Bitrate: 1999 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Eng - AAC - 5.1 - Default
Language: eng
Codec: AAC
Codec tag: mp4a
Profile: LC
Layout: 5.1
Channels: 6 ch
Bitrate: 224 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

I’m not sure what could be the cause as they seem similar but all the movies encoding in the first way are getting this stuttering issue. No other devices get this issue and DLNA on Roku gets this same issue as well. 

**How To Reproduce**

1. Start a stream on Jellyfin-Roku 1.6.2 containing an HEVC encoded file (I could even provide it if needed.)

**Expected behavior**
Video format should either work without stutter or transcode to a compatible version.

**Logs**
These files don’t show as transcodes but do produce “DIRECTSTREAM” logs. Below, I believe, is the important part but please let me know if the full file would help:

usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -fflags +genpts  -i file:"/media/remote/movies/500 Days of Summer (2009)/(500) Days of Summer (2009) [Bluray-1080p].mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/transcode/946f843666d2cd6b5d49ed6d8d13cdf5%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/transcode/946f843666d2cd6b5d49ed6d8d13cdf5.m3u8"

ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/media/remote/movies/500 Days of Summer (2009)/(500) Days of Summer (2009) [Bluray-1080p].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2020-04-09T03:26:10.000000Z
    title           : 500.Days.of.Summer.2009.1080p.BluRay.x265
    encoder         : Lavf58.20.100
    comment         : 500.Days.of.Summer.2009.1080p.BluRay.x265
  Duration: 01:35:04.62, start: 0.000000, bitrate: 2227 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1920x800 [SAR 1:1 DAR 12:5], 1996 kb/s, 23.98 fps, 23.98 tbr, 1200k tbn (default)
    Metadata:
      creation_time   : 2020-04-09T03:26:10.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2020-04-09T03:26:10.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, hls, to '/transcode/946f843666d2cd6b5d49ed6d8d13cdf5.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv), 1920x800 [SAR 1:1 DAR 12:5], q=2-31, 1996 kb/s, 23.98 fps, 23.98 tbr, 90k tbn (default)
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 384 kb/s (default)
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
frame=    3 fps=0.0 q=-1.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x555a57298000] Opening '/transcode/946f843666d2cd6b5d49ed6d8d13cdf50.ts' for writing

**Connection Information**
Is server local or remote? 

- Issue occurs for both

Is server connection http or https? 

- Issue occurs for both

**Additional context**
Since the 1.6.2 changes, HEVC can work without transcoding. I would guess this is related and maybe my encode is close enough to think it doesn’t need a transcode but different enough to break it.

On Roku, I have tried changing the Playback settings. All enabled and all disabled. No changes to the Playback stuttering.

**Comment by TheBetelgeuze** [comment]
This is an old issue that has returned with the fix that allowed direct play of x265 files implemented in the latest Roku update. Previously it was transcoding all x265 content which masked the underlying issue with Roku. The last post in the linked report below has mitigation steps but it requires changes to all affected files. It would be nice to be able to force transcoding on the affected files. See issue #449 

https://github.com/jellyfin/jellyfin-roku/issues/449

**Comment by JPKribs** [comment]
Gotcha! I’ll close this out since this is on the Roku side. I’ll resubmit as a FR for “Force x265 transcoding” setting as a workaround. It’d be nicer if Roku resolved this from their end but it looks like this has been going on for some time.

Thanks for the response and the link to the issue!
