### ISSUE TITLE
Question: how do I get a crash log

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#917]
I tried to follow the instructions at https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#bugcrash-reports but I think it might be incomplete.

I can connect via telnet to the Roku device but then what? I get nothing on my terminal. Is there some command I need to issue over the telnet connection?

Do I need to have installed a development version? I was hoping to be able to find logs for the current stable version, to figure out why a particular file is causing a crash during playback.

**Comment by 1hitsong** [comment]
No, those instructions are complete I'm afraid. It just so happens that the Roku logs are next to useless.

The absolute best way to diagnose these issues is to run a dev branch from VSCode using debug and cause the error. It will throw the error in VSCode terminal complete with error details, line number, etc.

It's not an eloquent method to debug, but it does work.
