### ISSUE TITLE
Subtitle styling

### ISSUE THREAD

**Issue by nathanWilson81** [jellyfin-archive/jellyfin-roku-legacy#932]
**Is your feature request related to a problem? Please describe.**
Being able to style the srt subtitles. Currently I get the white text on black background where the background is filled and looks like old school CC. 

**Describe the solution you'd like**
Would like to be able to style like on the android tv app where there is no background 

**Describe alternatives you've considered**

**Additional context**

**Comment by 1hitsong** [comment]
@nathanWilson81 Isn't this already possible? 

Change the styles in `Roku Settings / Accessibility / Captions Style`. Are your subtitle styles in Jellyfin not following your set styles?

**Comment by 1hitsong** [comment]
I played around with different settings and got these.

![image](https://user-images.githubusercontent.com/3330318/210107657-91e75bac-7ae5-43f7-883d-2e8f895dcc5b.png)
![image](https://user-images.githubusercontent.com/3330318/210107672-153342d5-d646-4522-a46b-3502e7d3d079.png)

**Comment by nathanWilson81** [comment]
@1hitsong I didn't realize that this was defined by Roku globals. It's working how I would like. Most other Roku apps have had overrides inside them. My bad. Closing this issue
