### ISSUE TITLE
Any plans to update the UI?

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin-archive/jellyfin-roku-legacy#940]
**Describe the feature you'd like**

I love the Roku app, it's made a huge difference in my watching experience. But i would love to have some UI enhancments. Is there a plan to add posters to the home menu rather then thumbnails? And backgrounds using the backdrop images from content. Really just making it closer to Jellyfin Media Player and Jellyfin WebUI. Also is there plans to add support to the Skin Manager Plugin for additional Themeing?

**Comment by 1hitsong** [comment]
We've made UI updates here and there as we've expanded functionality. Our primary focus at the moment is getting the functionality that exists in other clients into the Roku client. 

We're always open to new ideas and feature requests, such as the ones you mentioned, but our core goal at the moment is the feature gap.

> Also is there plans to add support to the Skin Manager Plugin for additional Themeing?

1. No. Those themes are CSS based and are not compatible with Roku.
