### ISSUE TITLE
Make Next Episode countdown length variable

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#942]
Make the Next Episode countdown length a user setting.

I suggest allowing the value to be 5 - 60 seconds long.

**Comment by jimdogx** [comment]
Can we also add a setting to turn that feature off?  Or can we do 0 - 60 and if 0 then it's Off?  There is currently no way to hide the button (unless I'm missing something).

**Comment by 1hitsong** [comment]
I say we make a toggle switch to enable/disable.

**Comment by candry7731** [comment]
you guys working on this or do you want me to submit a pr?

**Comment by 1hitsong** [comment]
I'm not. I'm 100% on playlist right now.

**Comment by deanaba** [comment]
On music videos, short form media, the pop-up really takes the viewer out of the moment. It'd be great if you could toggle this feature on/off.

**Comment by candry7731** [comment]
- @candry7731 Assigning myself to this issue to work on next.

**Comment by cewert** [comment]
Fixed by #1013
