### ISSUE TITLE
Crashing While Scrolling...

### ISSUE THREAD

**Issue by darknight-tonight** [jellyfin-archive/jellyfin-roku-legacy#947]
**Software Versions**
Jellyfin Server Version: 10.8.8 on Linux x86 Ubuntu Server VM
Roku Client Version: 1.6.2 on Roku Express 4K+ (2022 model)

**Describe the bug**
The Jellyfin app crashes, exits, and returns to the Roku's main menu

**How To Reproduce**
Note: for some reason, it seems to occur more often when the selection is not the leftmost (i.e. pick Season 3 or Show 3)
1. Choose a show
2. Pick a season
3. Press the Down or Up button repeatedly
4. The app crashes

**Expected behavior**
It is expected that the scrolling with continue albeit delayed

**Logs**
[log.txt](https://github.com/jellyfin/jellyfin-roku/files/10366818/log.txt)
//Let me know if you need more than this...

**Connection Information**
The server is Local
The server is http

**Additional context**
With the standard client (from the Roku store), the app crashes to the main menu. With a dev install, the app still crashes, but hangs indefinitely

**Comment by 1hitsong** [comment]
How many episodes are in the season? We fixed a bug when there are 27+ episodes.

Ref: https://github.com/jellyfin/jellyfin-roku/pull/912

This bug fix will be in the upcoming release.

**Comment by darknight-tonight** [comment]
Yep, that seems to be it. (No issue on 20 episodes, but shows up on 30)
Glad to hear it's taken care of; looking forward to the next release!
