### ISSUE TITLE
Show Info While Playing

### ISSUE THREAD

**Issue by darknight-tonight** [jellyfin-archive/jellyfin-roku-legacy#948]
**Is your feature request related to a problem? Please describe.**
I like to look at the show description while watching my archived shows to get an idea of the plot in case I didn't pay attention. Otherwise, I have to exit the show, read the description, then return back

**Describe the solution you'd like**
When pressing the OK button, the show could go to a mini player in the top-right quadrant, with the description underneath and the Season art to the left

**Describe alternatives you've considered**
1. The description and info show up when paused
2. Transparent info over the full-size video stream

**Additional context**
![image](https://user-images.githubusercontent.com/115961230/211163448-05f06be7-62a8-45fd-8138-4b436b671835.png)
//This is the Spectrum TV UI, but I think the current stream (top-right) should be larger and take up about 25% of the screen

**Comment by candry7731** [comment]
We are working on nav buttons in the video player to show info about the episode or movie.

![image](https://user-images.githubusercontent.com/83685828/213898063-d648443d-86b9-4f53-a406-d1a9495b4b76.png)

**Comment by darknight-tonight** [comment]
Very nice! Thanks :)
