### ISSUE TITLE
App Freezes when starting an Episode

### ISSUE THREAD

**Issue by pearlyturbine** [jellyfin-archive/jellyfin-roku-legacy#949]
**Software Versions**
Jellyfin Server Version: 10.8.8
Roku Client Version: Latest git

**Describe the bug**
The Roku Jellyfin Dev app freezes when trying to open an episode of a show.

**How To Reproduce**
1. Open Jellyfin Dev
2. Choose an episode of a show
3. Try playing it by pressing select on the remote
4. Bug occurs - App Freezes

**Expected behavior**
Start playing the episode

**Logs**
Type Mismatch. Operator "/" can't be applied to "Invalid" and "Float". (runtime error &h18) in pkg:/source/VideoPlayer.brs(49)

**Connection Information**
Server is on local network

Connected to server via HTTP

**Additional context**
When I remove the problematic line of code it fixes the issue, but breaks RunTimeTicks and in turn makes the 'Next Episode' button appear the whole time, throughout the entire episode.

When the app freezes notable variables are:

video.runTime = 0
meta.json.RunTimeTicks has no value

**Comment by jimdogx** [comment]
I'm not able to reproduce this.  I tried with server 10.8.8 and the latest unstable branch.

Are you sure your dev client is sync'd with unstable?

In theory we could add some defensive code around RunTimeTicks being invalid, however, if it is invalid, my understanding is other parts of the client will break.  So if this is indeed the case, I'm wondering if there is a setup issue (why does the content not have RunTimeTicks)?

**Comment by pearlyturbine** [comment]
> I'm not able to reproduce this. I tried with server 10.8.8 and the latest unstable branch.
> 
> Are you sure your dev client is sync'd with unstable?
> 
> In theory we could add some defensive code around RunTimeTicks being invalid, however, if it is invalid, my understanding is other parts of the client will break. So if this is indeed the case, I'm wondering if there is a setup issue (why does the content not have RunTimeTicks)?

I don't know why this is happening for me only it seems, Jellyfin web, Findroid, Finamp all work on other devices and the Next episode button also works.

Also could you please explain what 'dev client sync'd with unstable means'.

Thanks

**Comment by jimdogx** [comment]
Unstable is the git branch where all the latest and greatest code lives.

Just wanted to make sure you had done a "git fetch", "git pull" on the unstable branch.

I know that for me at least, because I have a fork of Jellyfin, I have to make sure I sync my fork with the main project before doing a fetch/pull (and sometimes I forget 😄 )

**Comment by pearlyturbine** [comment]
> Unstable is the git branch where all the latest and greatest code lives.
> 
> Just wanted to make sure you had done a "git fetch", "git pull" on the unstable branch.
> 
> I know that for me at least, because I have a fork of Jellyfin, I have to make sure I sync my fork with the main project before doing a fetch/pull (and sometimes I forget 😄 )

I think I was just using the main branch because I just ran `git clone https://github.com/jellyfin/jellyfin-roku`.

I will retry with the unstable branch to see how that goes.

EDIT: I've just seen unstable is the default, but I will try again anyway and sync it although I think mine was pretty up to date because I only cloned it a few days ago.

**Comment by pearlyturbine** [comment]
Extra Info: This doesn't seem to happen on all media, even on the media it does happen on - it is tempermental and sometimes works.

The shows I'm having trouble with are:

The Sarah Jane Adventures, Doctor Who, Torchwood

Some of these episodes I obtained using get-iplayer which is a tool that downloads stuff from iplayer and tags it correctly. I think this might be something to with it.

This may have been fixed in 1.6.3 so I will test it soon. 

Thanks Jellyfin Roku team for your brilliant work!

**Comment by 1hitsong** [comment]
> This may have been fixed in 1.6.3 so I will test it soon.

If you're still experiencing this issue using the latest Roku client release, please post to the troubleshooting forum. There are tons of great people help who can help dive into issues like this.

https://forum.jellyfin.org/f-troubleshooting
