### ISSUE TITLE
Make compatible app for older roku devices / older brightscript versions?

### ISSUE THREAD

**Issue by Andersama** [jellyfin-archive/jellyfin-roku-legacy#953]
**Is your feature request related to a problem? Please describe.**
Have been trying to install or build the plugin for an old roku xs I found back home with no luck. Was hoping to get it working so that I could use it in place of one of the family laptops.

**Additional context**
I'm noticing when trying to build the plugin during the "compile" stage there appear to be a lot of syntax errors surrounding a couple of things namely:

```
some_variable?.some_other_variable
```

Normally these appear in conditional statements and potentially wrapped with `isValid()`. I'm assuming this is some shorthand for comparing against `invalid` so I've been replacing large segments of code with chains of and statements.

Then there appears to be an issue with try catch statements. My overall suspicion is I'm somehow working with an older version of brightscript which doesn't have these features.

There also appear to be issues with throw statements.

After removing a pretty lengthy list of syntax errors and try catch blocks (I'll have to cross my fingers the try catch blocks don't trigger) I now have errors complaining about `Extends type does not exist: "StandardDialog"` and `Extends type does not exist: "StandardMessageDialog"` and I've no clue what I'm meant to do to fix those so I'm stuck.

Currently have the old roku xs in development mode, have been trying to debug the app through vscode. Note: roku's not physically near me so if I'm supposed to see anything I've no idea what is happening. I'm just working off of the debug output.

**Comment by jimdogx** [comment]
Unfortunately, the Roku XS has been discontinued by Roku and is no longer receiving updates.

https://developer.roku.com/docs/specs/hardware.md#legacy-models

Someone would have to fork and maintain a completely separate build for older devices as there is just too much that has moved on and relies on the latest Roku O.S.

**Comment by Andersama** [comment]
I sort've figured, thanks for the feedback.
