### ISSUE TITLE
MP4 plays on web and iOS client but fails on Roku using DirectPlay

### ISSUE THREAD

**Issue by Bubbgump209** [jellyfin-archive/jellyfin-roku-legacy#965]
**Software Versions**
Jellyfin Server Version: 10.8.8 
Roku Client Version: 1.6.2

**Describe the bug**
Certain MP4s fail to play on Roku while they play fine on the web and iOS client.

**How To Reproduce**
Play an MP4 on Roku - see mediainfo output for specifics

**Expected behavior**
The MP4 plays be it Direct Play or transcoded

**Logs**
Jellyfin:
`[2023-01-16 18:21:08.047 -05:00] [INF] User policy for "Kids". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-01-16 18:21:08.047 -05:00] [INF] RemoteClientBitrateLimit: 6000000, RemoteIp: "1.2.3.4", IsInLocalNetwork: False
[2023-01-16 18:21:08.047 -05:00] [INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/downloader/Kids/TV/Garfield and Friends/Season 1/Garfield and Friends - S01E10E11E12 - SDTV.mp4", AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/758b69af-a7d7-4068-afe4-ab91913feb06/stream.mov?MediaSourceId=758b69afa7d74068afe4ab91913feb06&Static=true&VideoCodec=mpeg4&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=5f7336acfe93a1cae16939a5e0cc903b"
[2023-01-16 18:21:10.515 -05:00] [INF] Playback stopped reported by app "Jellyfin Roku" "1.6.2" playing "Banana Nose". Stopped at "0" ms
`

mediainfo

`General
Complete name                            : Garfield and Friends - S01E10E11E12 - SDTV.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 237 MiB
Duration                                 : 23 min 52 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 387 kb/s
Cover                                    : Yes
Imbed                                    : Lando18

Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings                          : BVOP
Format settings, BVOP                    : Yes
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : mp4v-20
Duration                                 : 23 min 52 s
Bit rate mode                            : Constant
Bit rate                                 : 1 187 kb/s
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Variable
Frame rate                               : 23.976 (23976/1000) FPS
Minimum frame rate                       : 23.810 FPS
Maximum frame rate                       : 24.390 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.161
Stream size                              : 203 MiB (86%)
Title                                    : Main
Writing library                          : XviD 1.2.1 (UTC 2008-12-04)
Language                                 : English

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 23 min 52 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 32.8 MiB (14%)
Title                                    : Main
Language                                 : English
Default                                  : Yes
Alternate group                          : 1`

**Screenshots**

**Connection Information**
Remote server set to max of 6mbps for remote clients.

Is server connection http or https? HTTPS

**More info***
When the files do play successfully on web and iOS, they are transcoded.

**Comment by sevenrats** [comment]
have you tried changing the "direct play mp4" setting?

**Comment by Bubbgump209** [comment]
By golly that worked. I didn't know that setting existed. Thanks
