### ISSUE TITLE
Use back-button to unset alphanumeric filter in movie grid

### ISSUE THREAD

**Issue by Zerva5** [jellyfin-archive/jellyfin-roku-legacy#967]
**Is your feature request related to a problem? Please describe.**
No way to unset alphanumeric filter in movie view besides exiting the movie grid and re-entering.

**Describe the solution you'd like**
Use the back button!

**Describe alternatives you've considered**
Could go back and hit "OK" on the one you already selected, however might make user think they can select multiple letters to filter with. "Back" seems the most intuitive.

I'm going to try and implement this.

**Comment by jimdogx** [comment]
This feature is implemented by using the instant replay button.
