### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by johnmmcgee** [jellyfin-archive/jellyfin-roku-legacy#980]
It would be nice to have an option to log into another saved server profile, so that you could share servers like in plex.

**Comment by johnmmcgee** [comment]
Ideas:

Set a default profile(server), which loads on start.
Have option to switch servers from the option menu.

**Comment by jimdogx** [comment]
Is this not working for you or is this request for something different than what is currently implemented?

You can currently switch between servers exactly as you've mentioned.  So I might be missing something.

**Comment by johnmmcgee** [comment]
Seems to only list local servers.  Is it possible to save servers you have previously visited and entered manually, along with credentials?

**Comment by jimdogx** [comment]
> Seems to only list local servers. Is it possible to save servers you have previously visited and entered manually, along with credentials?

Yes.  By default it will scan for local servers.  However, once you enter a remote server it should stay in the list.  Don't forget to keep "Save Credentials" checked.

I currently have one local server and two remote servers that I jump between.

If this isn't working for you let me know.  Otherwise I'll close this issue.

**Comment by sevenrats** [comment]
this is probably a request for Plex's SSO-leveraged sharing feature, where you can share your library with other plex users by entering their email or username, and then they get notified that theyve been invited.  Jellyfin is not a product, it does not have a service running on the internet, and so we cannot (and probably would not) replicate that feature.  This would require Jellyfin to act as a data processor and there is no indication that the team is interested in that.

**Comment by johnmmcgee** [comment]
> this is probably a request for Plex's SSO-leveraged sharing feature, where you can share your library with other plex users by entering their email or username, and then they get notified that theyve been invited. Jellyfin is not a product, it does not have a service running on the internet, and so we cannot (and probably would not) replicate that feature. This would require Jellyfin to act as a data processor and there is no indication that the team is interested in that.

In correct.  The way @jimdogx explained it works as I had expected.  I just wasn’t aware it would save a history and auth information of previously visited remote servers.

**Comment by jimdogx** [comment]
> The way @jimdogx explained it works as I had expected. I just wasn’t aware it would save a history and auth information  of previously visited remote servers.

If there are no objections, then I will close this issue.
