### ISSUE TITLE
WAV files playing slowed down

### ISSUE THREAD

**Issue by dacioromero** [jellyfin-archive/jellyfin-roku-legacy#993]
**Software Versions**
Jellyfin Server Version: 10.8.9
Roku Client Version: 1.6 build 3

**Describe the bug**

Playing any WAV file from Wolfgang Amodeus Phoenix on my Roku TV is in maybe at an 8th's speed. The files were downloaded from http://atozmedia.com/soundcard.

**How To Reproduce**

1. Load WAV file of Phoenix's 1901 (24 bit 96 kHz PCM) into your library
2. Open Jellyfin on a TCL 50S435 Roku TV
3. Play 1901
4. 1901 plays back at an 8th's speed

**Expected behavior**

The music should play at a normal rate.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/12436128/215359124-e4a09aec-cf38-4c57-9404-4c9d676e71b1.png)
![PXL_20230129_142932361](https://user-images.githubusercontent.com/12436128/215359382-1b7ea29c-b3a7-4612-9612-6b78d082feab.jpg)

**Connection Information**
Is server local or remote?  local

Is server connection http or https? http

**Additional context**

#124

**Comment by 1hitsong** [comment]
@dacioromero I'm unable to download the example off that site as it requires purchase. 

Can you try some of the 24 bit files from here and let me know if any have the same issue: https://www.lessloss.com/high-resolution-audiophile-recordings-c-68.html?zenid=066aiihl47iv9h6hpeg5siuue4

**Comment by dacioromero** [comment]
I figured that could be an issue. Except one here plays slowed down: https://www.lessloss.com/steinway-sons-grand-piano-recording-p-202.html

**Comment by 1hitsong** [comment]
Which track title plays incorrectly? 1, 2, or 3?

**Comment by dacioromero** [comment]
It was 1, "Mephisto Waltz Excerpt #1"

**Comment by dacioromero** [comment]
I noticed that the media player UI changed for videos so I tested playing a WAV file again. It seems to be playing properly now!
